### ISSUE TITLE
Bundle Identifier on iOS changed with every login

### ISSUE THREAD

**Issue by SaraChicaD** [auth0/react-native-auth0#102]
So this is the issue, when I set up the callback URL per the instructions for Android on RN, no problem, on iOS, however, I can't get the authorization to work unless I add an ADDITIONAL word to what would be the bundle identifier. Example:

`{COM.COMPANY.APPNAME}` is what I put in but to get the authorization to work I have to change it to: `{COM.COMPANY.APPNAME.COMPANY}`

I'm not sure why this is. The bundle identifier is set everywhere the same, and when I *don't* add the _additional_ `company` tag at the end, I get an auth0 error message that the callback URL is not an allowed:

![screen shot 2017-10-11 at 11 41 54 pm](https://user-images.githubusercontent.com/6945122/31479591-d8175fae-aedd-11e7-8ef8-6bbfe9cdf00a.png)
 
Any help on this would be much appreciated!!!

**Comment by cocojoe** [comment]
Hi @SaraChicaD 

The Android and iOS callbacks are different, the name required comes down to how it's been setup. I would suggest having another read of https://auth0.com/docs/quickstart/native/react-native

If you feel there is anything that could be clearer it would be great if you can feedback on it to help everyone.

Thanks

**Comment by SaraChicaD** [comment]
hey @cocojoe i do have some suggestions, shall I just do a PR here on the README? Thanks!

**Comment by cocojoe** [comment]
Please do @SaraChicaD Thx
