### ISSUE TITLE
Error: Missing NativeModule. Please make sure you run `react-native link react-native-auth0

### ISSUE THREAD

**Issue by DanSchick** [auth0/react-native-auth0#105]
This comes up when I call a react-native-auth0 function from my Expo app

This is the function I call:

```
onLogin() {
    auth0.webAuth
      .authorize({
        scope: 'openid profile',
        audience: 'https://' + credentials.domain + '/userinfo'
      })
      .then(credentials => {
        Alert.alert(
          'Success',
          'AccessToken: ' + credentials.accessToken,
          [{ text: 'OK', onPress: () => console.log('OK Pressed') }],
          { cancelable: false }
        );
        this.setState({ accessToken: credentials.accessToken });
      })
      .catch(error => console.log(error));
  }
```

When I run react-native link react-native-auth0 this is what the console says:

C:\Users\schic\device-mgr>react-native link react-native-auth0
Scanning folders for symlinks in C:\Users\schic\device-mgr\node_modules (31ms)

It doesn't say anything else.

Version information:

npm 3.10.10
react-native-cli: 2.0.1
react-native: 0.48.4
react-native-auth0@1.2.1

Would appreciate any help at all

**Comment by cocojoe** [comment]
@DanSchick  I have not tried with Expo. However, I believe they do not support the standard `react-native link`.  You can read more about it in this issue https://github.com/expo/expo/issues/56
It talks about using `ExponentKit` to facilitate this.

Be great if you can report back. Thanks

**Comment by DanSchick** [comment]
Thanks for your response, it seems obvious in retrospect

I don't think I'm going to use ExpoKit, so I ended up using the built in Expo class featured here:

https://github.com/expo/auth0-example/blob/master/main.js

**Comment by cocojoe** [comment]
Thanks, not actually seen that before.

**Comment by SamiChab** [comment]
I have this issue without using Expo

react-native: "0.49.3"
"react-native-auth0": "^1.2.1"

**Comment by cocojoe** [comment]
@SamiChab The alternative solution in the Expo is provided in the sample above https://github.com/expo/auth0-example

In Expo if you want to link native modules you need to look into ExponentKit

**Comment by bubuzzz** [comment]
I still use react native and after using `react-native link`, everything works fine on IOS, but not on Android. I have been hitting my head to the wall for nearly 1 week for this. After that, I download the login example of React Native of Auth0 again and check every single file to see the difference and see that you HAVE TO put the `new A0Auth0Package()`, into the MainApplication.java in order to make it work. This is so tricky !!!!

**Comment by cocojoe** [comment]
@bubuzzz please can you create a new issue for this and tell me the steps you took.
Also what version of RN are you using? I'm wondering if anything has changed in RN. Thx

**Comment by tannerhallman** [comment]
@bubuzzz solution worked for me.

**Comment by cjrorvik** [comment]
I'm trying to implement Auth0 to my React Native app. Everything works fine on iOS but on Android I get the same as this issue. When I try to add A0Auth0Package to my MainApplication.java, I get an `error: package com.auth0.react does not exist`. How did you guys manage to get this to work for Android?

**Comment by tannerhallman** [comment]
@cjrorvik did you add:

`dependencies { compile project(':react-native-auth0') ...}` in your app's `build.gradle`?

**Comment by aditodkar** [comment]
@tannerhallman I am getting following error see screenshot:

 ![screenshot_5](https://user-images.githubusercontent.com/16613832/45348045-32332000-b5cb-11e8-98a7-8aca87262b55.png)

build.gradle:

![screenshot_7](https://user-images.githubusercontent.com/16613832/45348365-0fedd200-b5cc-11e8-970c-780b66dc952e.png)

Error after modifying build.gradle:

![screenshot_6](https://user-images.githubusercontent.com/16613832/45348405-2dbb3700-b5cc-11e8-8fc2-d8f4a90f9273.png)

**Comment by mcclen** [comment]
This problem seems to recur with the current release. @tannerhallman's solution seems to be the forgotten and/or misapplied item.

**Comment by AnanasPie** [comment]
Still happening in iOS.
I got the following error: "Error. Missing NativeModule. Please make sure you run 'react-native link react-native-auth0".

RN: 0.60.4
react-native-auth0: 1.5.0

**Comment by madebyew** [comment]
The following commands resolved this issues for me.
`$ cd ios && pod install && cd .. `

**Comment by rasmusrim** [comment]
If you use Expo, you should use their API instead: https://reactnativemaster.com/react-native-geolocation-example/

**Comment by shahriar0247** [comment]
im getting this in web, whaat to do
