### ISSUE TITLE
Scope not recognized when calling passwordRealm

### ISSUE THREAD

**Issue by Looveh** [auth0/react-native-auth0#110]
When calling

```js
auth.passwordRealm({
  email: "example@example.com",
  password: "some-password",
  realm: "my-realm",
  scope: "openid"
});
```

I get a response containing a different scope than the one provided (and inspecting the JWT token confirms that it is different than provided within the token too):

```js
{
  accessToken: "<some-access-token>",
  expiresIn: 86400,
  idToken: "<some-id-token>",
  scope: "openid profile email address phone",
  tokenType: "Bearer",
}
```

This is obviously a problem since I'm not able to control the information passed from the client to consumers of the token.

**Comment by cocojoe** [comment]
With the password-grant all scopes will be included if you only specify "openid", if you specify say "openid email" then it will only use those scopes.

**Comment by Looveh** [comment]
All right, thanks!

Out of curiosity, is this by design of Auth0 or this lib in particular?

**Comment by cocojoe** [comment]
This is applied on the Auth0 server-side. Thanks
