### ISSUE TITLE
Confusion over nonce parameter in webAuth.authorize

### ISSUE THREAD

**Issue by blakew** [auth0/react-native-auth0#111]
2 things-

1. Looked through the code, looks like the nonce parameter gets thrown out since it's not an accepted parameter of auth.authorizeUrl

2. Isn't having an nonce redundant when there's a state parameter that is used? I thought the nonce was sent via the state, so why are there 2 parameters for the same thing (one of which appears to be doing nothing)?

What are users supposed to be doing with this parameter?

**Comment by cocojoe** [comment]
A bit more info on [state](https://auth0.com/docs/protocols/oauth2/oauth-state)
If you were using a different response Type say `id_token` then you would add the `nonce` param to help mitigate id_token replay attacks. However, this library uses PKCE and this is not needed.
