### ISSUE TITLE
Clarification on usage with non Auth0 servers

### ISSUE THREAD

**Issue by Meligy** [auth0/react-native-auth0#112]
Hello,
I understand that this library is meant to be used with Auth0 service (Auth0 servers and accounts), which is awesome.

However, is it also possible to use against any other OpenID server?
(Or does it have any assumptions etc specific to Auth0?)

Thanks a lot.

**Comment by cocojoe** [comment]
@Meligy I think most likely it will be easier to look for a generic OAuth library, rather than hacking this one as you will be left with an unsupported library.
Off the top of my head, the dndpoints are of course specific and the callback format is also fixed.
