### ISSUE TITLE
Native login

### ISSUE THREAD

**Issue by risto1913** [auth0/react-native-auth0#116]
Are you planning a native login solution for SSO?

The feel of the login as is is now is a bit disappointing.

**Comment by harrisrobin** [comment]
I have the exact same feedback as @risto1913. I was planning on using auth0 on my next project but because of this I am looking at accountkit by facebook since they offer that.

**Comment by cocojoe** [comment]
@risto1913 Can you walk me through what you are trying to achieve and where it falls short for you. 

@harrisrobin same question 😄

**Comment by harrisrobin** [comment]
@cocojoe 

I think the biggest issue is more aesthetic than it is about trying to achieve something. I have a client that does not want to be redirected to a browser and uses other apps to demonstrate this where they keep you in the native environment. I think it would be great if auth0 supported both options in this package. 

Hope this answers the question!

**Comment by cocojoe** [comment]
@harrisrobin There is an embedded example that allows for a more native interface, I suggest you have a look at this.  https://github.com/auth0-samples/auth0-react-native-sample/tree/Embedded/

OAuth authentication will happen in a web flow, use any Google App certainly in iOS, you will go through a webflow to authenticate and this is the industry standard.

**Comment by harrisrobin** [comment]
@cocojoe thanks ill take a look.

In my case, it was SMS passwordless login which a lot of apps do not take you via a web flow for. I understand your point!

Thank you :)

**Comment by risto1913** [comment]
Sory for the late reply.

The thing is, I would like to se native facebook and google buttons for the login.
A login experience that dosn't need a webvew for the authentication.

Personally I think it sould result in a mutch nicer experience.

I agree with @harrisrobin, its also an issue of aesthetic but also the "feel".

So to wrap up my "issue" its a matter of getting that native feel with facebook google and thows login methods that you have created with email and password login.

**Comment by joaom182** [comment]
I have the same feel, the user don't want re-enter their Facebook credentials on browser, he already logged in Facebook App.

**Comment by SaraChicaD** [comment]
Have there been any updates to making this feature available? As in being able to use the FB app on the phone to authenticate versus asking the user to enter their information in a webview via Auth0?

**Comment by FullstackJack** [comment]
Yeah, just look at Firebase Auth, it's dead easy to just call signInWithEmailAndPassword() from your native text inputs and there are packages already developed for Flutter and React Native. Auth0 really is against the grain.
