### ISSUE TITLE
No clear support for Firebase addon

### ISSUE THREAD

**Issue by Benjamin-Dewey** [auth0/react-native-auth0#117]
What is the recommended way for tenants created later than 8 June 2017 to implement the Firebase addon? The usage section of the Firebase addon guide says

> You can have Auth0 issue a Firebase token through the Delegation endpoint. This endpoint allows you to exchange a token for a new one.

and it directs me [here](https://auth0.com/docs/api/authentication#delegation) to use the Delegation endpoint but it says

> With the latest Auth0 authentication pipeline, this endpoint should not be used to exchange an ID token issued to one client for a new one issued to a different client, or to use a refresh token for a fresh ID token. For more information refer to Introducing OIDC Conformant Authentication > Delegation.
> 
> This feature is disabled by default for new tenants as of 8 June 2017. Please see Client Grant Types for more information.

Is there still a way to hookup auth0 with Firebase?

**Comment by cocojoe** [comment]
@Benjamin-Dewey There is not an alternative today for OIDC.  However, there are plans for functionality in Q1 2018.

**Comment by akhanukov** [comment]
Has this functionality been released yet @cocojoe ? Is it this info: Silent Authentication and https://auth0.com/docs/quickstart/spa/vanillajs/05-token-renewal? Or is there newer libraries and methods? Thanks!

**Comment by cocojoe** [comment]
@akhanukov not yet, Silent Authentication is not related to the delegation endpoint and Firebase.
