### ISSUE TITLE
disallowed user_agent on android

### ISSUE THREAD

**Issue by cultofmetatron** [auth0/react-native-auth0#118]
Got the oauth flow working but on android, google oauth does not work.

Works fine with facebook login and both google and facebook oauth work on ios.

<img width="486" alt="screen shot 2017-12-19 at 5 54 27 pm" src="https://user-images.githubusercontent.com/5964/34182800-c4ffb5a4-e4e5-11e7-9158-2ac1c222197c.png">

**Comment by cocojoe** [comment]
Indeed Google will not allow WebViews.  Typically in real use the user will have Chrome as their default browser.  WebView Browser tester is your default browser?
