### ISSUE TITLE
JSON response not correct (RFC)

### ISSUE THREAD

**Issue by GituBojan** [auth0/react-native-auth0#122]
Hey,

I have used the auth0.auth.passwordRealm() function to get an accessToken from the Auth0 API and I receive a response in form of a JSON string. Unfortunately it seems that the JSON string is not formatted correctly from the Auth0 side. The quotes are missing for the keys.

Auth0 response
```
{
accessToken : " ...."
idToken .: " .... "
..
}
```

instead of
```
{
"accessToken" : "....."
"idToken" : "...."
...
}
```

Thank you for your help.

**Comment by cocojoe** [comment]
Not sure what you mean, there is no issue in the Auth0 Server response, if it wasn't valid JSON that would be a big problem 😄 Perhaps this is just how it looks when logged in console?
