### ISSUE TITLE
How to disable zoom-in

### ISSUE THREAD

**Issue by yuyaohshimo** [auth0/react-native-auth0#123]
When I focus input element, the screen zooms-in. How do I disable zoom?

Screenshot:

![simulator_screen_shot_jan_18__2018_21_43_22](https://user-images.githubusercontent.com/3455528/35136535-02fa59fc-fc99-11e7-87f6-25e422f826b2.png)

I found `scalesPageToFit` makes disable zoom in the [doc](https://facebook.github.io/react-native/docs/webview.html#scalespagetofit).

**Comment by cjrorvik** [comment]
Same here

**Comment by cocojoe** [comment]
Did `scalesPageToFit` help?

**Comment by adamivancza** [comment]
I managed to fix this by editing the HTML code of login page (https://manage.auth0.com/#/login_page). Edit the original viewport meta to this one: 

```<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />```
