### ISSUE TITLE
react-native-auth0 WebAuth popup 

### ISSUE THREAD

**Issue by pragadeesh0106** [auth0/react-native-auth0#124]
```
auth0
            .webAuth
            .authorize({ 
              scope: 'openid profile offline_access', 
              audience: 'https://' + Config.auth0Domain+ '/api/v2/'
              })
            .then(function (credentials) {
                console.log(credentials);
            })
            .catch(error =>
                console.log("error", error)
            );
```

when this function is called the webauth is opened outside the app . So when i go check my otp and click recent tabs in my phone my app remains there but the auth0 webauth popup is missing .

If anyone knows how to solve the issue kindly help...

**Comment by cocojoe** [comment]
@pragadeesh0106 please can you tell us the steps to re-create, I presume you are using MFA.
It is expected behaviour that Web Auth is launched via your default system browser, most often Chrome.

**Comment by pragadeesh0106** [comment]
web view opening in the browser is not a issue .

The auth0 page opens in a chrome web view and when i go check my otp  in my messenger and come back to enter otp im not able to reopen that webview it closese automatically.

**Comment by scottbrassfield** [comment]
We are seeing this issue as well. When using webAuth with Passwordless authentication, the user is required to navigate out of the default system browser to retrieve the code from the entered email. Upon navigating back, the browser window where the code is meant to be entered has closed, and the authentication process cannot be completed.

**Comment by cocojoe** [comment]
Thanks, I'll have a run through this.

**Comment by msalokangas** [comment]
@cocojoe in our case, we tracked the problem to be related to Chrome Custom Tabs being used in Android. Right now our workaround will be to disable Custom Tabs.

**Comment by pragadeesh0106** [comment]
@cocojoe what is the workaround to disable custom tabs does anyone know it ??

**Comment by lbalmaceda** [comment]
@pragadeesh0106 I guess in [this](https://github.com/auth0/react-native-auth0/blob/master/android/src/main/java/com/auth0/react/A0Auth0Module.java#L56) method skip the "CustomTabsIntent" code and just start a new Intent with Action VIEW and the URL as URI, like it's done when the activity is null.

**Comment by msalokangas** [comment]
@pragadeesh0106 @lbalmaceda yes, that's what we are doing. so we forked the library and removed the CustomTabsIntent part.

**Comment by pragadeesh0106** [comment]
I didn't get you can u explain clearly what to do and i am calling the auth0 from react native so should i do the changes  in react native or the node modules of the react native auth0

**Comment by msalokangas** [comment]
@pragadeesh0106 you would fork react-native-auth0 library and edit your own fork. and then reference the fork from your package.json

**Comment by pragadeesh0106** [comment]
After forking what is the change to be done i didn't get that part.

**Comment by lbalmaceda** [comment]
This is a workaround while we seek for a formal solution. You have to fork the repo and replace:

```java
        if (activity != null) {
            CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder();
            CustomTabsIntent customTabsIntent = builder.build();
            customTabsIntent.intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            customTabsIntent.intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            customTabsIntent.launchUrl(activity, Uri.parse(url));
        } else {
            final Intent intent = new Intent(Intent.ACTION_VIEW);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            intent.setData(Uri.parse(url));
            getReactApplicationContext().startActivity(intent);
        }
```

with

```java
            final Intent intent = new Intent(Intent.ACTION_VIEW);
            intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
            intent.setData(Uri.parse(url));
            getReactApplicationContext().startActivity(intent);
```

then just build and reference the library locally

**Comment by pragadeesh0106** [comment]
intent.addFlags(Intent. FLAG_ACTIVITY_NEW_TASK);

Above flag needs to be added and the it worked fine thank you.

Is there any way to open it within the app instead of a browser.

**Comment by lbalmaceda** [comment]
The only way would be through Custom Tabs as they open "in a separate activity" within your app. Use of the `WebView` component is blocked for OAuth requests.

**Comment by pragadeesh0106** [comment]
So your saying it is not possible.

**Comment by cocojoe** [comment]
@pragadeesh0106 While technically it's possible to launch a WebView, this would be a pointless practice as OAuth authentication is not permitted using WebView.  

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by pragadeesh0106** [comment]
OK got it

**Comment by msalokangas** [comment]
@pragadeesh0106 @cocojoe @lbalmaceda This issue should not be closed, there is no real fix for it yet

**Comment by cocojoe** [comment]
Agreed

**Comment by lbalmaceda** [comment]
@msalokangas @pragadeesh0106 I've proposed changes on #126. Feel free to try it and leave some feedback before we merge it.
