### ISSUE TITLE
Multiple audiences in webAuth authorize?

### ISSUE THREAD

**Issue by VilleMiekkoja** [auth0/react-native-auth0#125]
Is it possible to define multiple audiences in the webAuth authorize method? According to the api documentation, the field is marked as string, and it looks like you can't: http://auth0.github.io/react-native-auth0/WebAuth.html#.authorize

Also, I tried to specify other audience there than 'mydomain + /userinfo', but the method seems to reject in this case. Browser is opened, but user will be immediately redirected back to the application login page. Platform is Android.

I want to specify other than the 'mydomain + /userinfo' so that I will receive a jwt token back, that can then be used in authorizing my own API calls. According to Auth0, you should use the access_token for this purpose, and not the id_token: https://auth0.com/docs/api-auth/why-use-access-tokens-to-secure-apis

EDIT: Found solution to the second problem: I can now specify other audience than the 'mydomain + /userinfo'. What this required was that in the auth0 dashboard you need to create a new API from the API section. There you will define it's identifier, that you can then use in the webAuth authorize method.

**Comment by lbalmaceda** [comment]
The authentication API doesn't support requesting multiple audiences yet. Adding a "userinfo audience" is only required if you're not using APIs and you need to access the user profile. Like you said, if you instead create a new API in the dashboard and request that "identifier" as audience, the token would still be a JWT.
