### ISSUE TITLE
My app closes on opening the auth0 in browser 

### ISSUE THREAD

**Issue by pragadeesh0106** [auth0/react-native-auth0#127]
auth0
            .webAuth
            .authorize({ 
              scope: 'openid profile offline_access', 
              audience: 'https://' + Config.auth0Domain+ '/api/v2/'
              })
            .then(function (credentials) {
                console.log(credentials);
            })
            .catch(error =>
                console.log("error", error)
            );

After successfull login from browser it return to my app but not where i left instead it is restarting the app so what happens is the login page opens again.

After login it should go to the then function but it calls the auth0 function once again .

This happens only in android version 4.0

**Comment by cocojoe** [comment]
Please provide a video or animated gif, also please check your react native logs.  Thx

**Comment by pragadeesh0106** [comment]
Once auth0 opens my app becomes dead. 

So after authentication it opens my app again which lead to pop up of browser

**Comment by cocojoe** [comment]
React Native - Supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0.

**Comment by lbalmaceda** [comment]
Please provide more details. 
- Have you followed the set up steps from the readme? (activity's launchMode, intent-filter, etc)
- Is this related in anyway to #124? 
- Is this happening only with a particular browser app?

**Comment by cocojoe** [comment]
Inactivity
