### ISSUE TITLE
Android: Unable to enter email code when resuming application from launcher

### ISSUE THREAD

**Issue by seanpatrickcatlin** [auth0/react-native-auth0#132]
### Issue
When using react-native-auth0 on Android to authenticate against an auth0 client using a passwordless email code a user is unable to enter their email code when resuming the application from the launcher or launching it from a home screen shortcut.

### Steps to reproduce
 1. Download the auth0 sample app from `https://auth0.com/docs/quickstart/native/react-native` (my sample app was in a file named `00-login.zip`)
 1. Open a terminal window and `cd` to the `00-login.zip` location
 1. `unzip 00-login`
 1. `cd 00-login`
 1. `npm install`
 1. `react-native run-android`
 1. Click on the "Log In" button
 1. Enter email address and press "submit"
 1. Notice that auth0 lock is now requesting a code
 1. Press the Android `HOME` button
 1. Open email application on device to get the code
 1. Press the Android `HOME` button
 1. Open the application launcher
 1. Tap on the `Auth0Sample` app 

### Expected Behavior
I am shown the `Enter a code` custom tab

### Actual Behavior
I am shown the original page with the `Log In` button

### Example
![auth0-example](https://user-images.githubusercontent.com/1840890/36041842-d108d01c-0d97-11e8-8631-d4f1a1448467.gif)

**Comment by cocojoe** [comment]
Thanks for the gif, please can you retest in a real browser such as Chrome or Firefox.

**Comment by lbalmaceda** [comment]
Thanks for all the details 🎉 . Does this still happens if you open the app from the "recents apps" instead of clicking the app icon in the drawer?

**Comment by seanpatrickcatlin** [comment]
RE: `Thanks for the gif, please can you retest in a real browser such as Chrome or Firefox.`
 * Testing with Chrome, Firefox, and Firefox Focus all show the same behavior on multiple devices, I will attach some gifs to this post shortly

RE: `Does this still happens if you open the app from the "recents apps" instead of clicking the app icon in the drawer?`
 * This does not happen when resuming the application from the "recent apps".  This does happen when:
   1. Tapping the app icon from the "Android Launcher" / app drawere
   1. Tapping the app icon from a shortcut added to the "home screen"

**Comment by lbalmaceda** [comment]
I can confirm that this happens just as described above. Though it was not introduced in the latest PR https://github.com/auth0/react-native-auth0/pull/126 so this requires a bit more research on our side.

**Comment by lbalmaceda** [comment]
@seanpatrickcatlin if this is still happening, can you please confirm if you are or not using `react native navigation` library along with this one?

**Comment by seanpatrickcatlin** [comment]
I will check if this still happens within the next day or 2.

This bug report specifically references that this happens with the sample project provided by auth0, so `react native navigation` was not used.
