### ISSUE TITLE
iOS 11: Unable to use magic link for authentication

### ISSUE THREAD

**Issue by seanpatrickcatlin** [auth0/react-native-auth0#133]
### Issue
When using react-native-auth0 for passwordless magic link authentication in an application running on an iOS device with iOS 11.  The issue is not seen on iOS 10.x, iOS 9.x, or Android devices.

#### Auth0 Setup
 1. Configure the "Hosted Page" login to use the the "Passwordless" template.
 1. Add `passwordlessMethod: "link",` to the object that is the 3rd parameter of the `Auth0LockPasswordless` constructor

#### Application
 1. Download the auth0 sample app from `https://auth0.com/docs/quickstart/native/react-native` (my sample app was in a file named `00-login.zip`)
 1. Open a terminal window and `cd` to the `00-login.zip` location
 1. `unzip 00-login`
 1. `cd 00-login`
 1. `npm install`
 1. ~~`react-native run-android`~~
 1. **edit** Open xcodeproj file
 1. **edit** Run application on an iOS 11 device (iPhone X was used in this test)
 1. Click on the "Log In" button
 1. Enter email address and press "submit"
 1. Open the iOS Mail app
 1. Open the email with the magic link
 1. Tap on the link

### Expected Behavior
In iOS 9.x and iOS 10.x I would see a dialog `Open this page in "Auth0Sample"?` and then the app would open and I would be authenticated.

<img width="383" alt="screen shot 2018-02-13 at 1 33 41 pm" src="https://user-images.githubusercontent.com/1840890/36167086-a069997c-10c2-11e8-843e-6a204ba0098e.png">

<img width="380" alt="screen shot 2018-02-13 at 1 35 19 pm" src="https://user-images.githubusercontent.com/1840890/36167137-d2526608-10c2-11e8-9eb5-1607dc459ecf.png">

<img width="388" alt="screen shot 2018-02-13 at 1 35 34 pm" src="https://user-images.githubusercontent.com/1840890/36167144-d60be77e-10c2-11e8-8568-845a22013a75.png">

### Actual Behavior
Safari opens to a page that says `Oops!, something went wrong`

![screen shot 2018-02-13 at 1 30 31 pm](https://user-images.githubusercontent.com/1840890/36166935-1ca414fa-10c2-11e8-9d8a-ac127d9b2b31.png)

**Comment by lbalmaceda** [comment]
What do the logs say in your auth0 dashboard when this error page is shown?

**Comment by seanpatrickcatlin** [comment]
Here is what I see

<img width="846" alt="screen shot 2018-02-13 at 4 39 17 pm" src="https://user-images.githubusercontent.com/1840890/36175170-937a45d0-10dc-11e8-9a5c-33cbf5c6a75f.png">

Both of the failed logins have the same summary:

<img width="884" alt="screen shot 2018-02-13 at 4 39 47 pm" src="https://user-images.githubusercontent.com/1840890/36175179-9be8e1d6-10dc-11e8-913c-a2c30afc0d55.png">

Let me know if I should DM you full logs with client ids and such.

I could be completely wrong but overall this feels like iOS 11 is behaving as expected because in iOS 11 each safari instance is sandboxed, so the data in the SFSafariViewController is not accessible to the main Safari instance that is loaded when tapping on a link in an email.  I assume that is why the Auth0.swift project added iOS 11 support via the SFAuthenticationSession API in https://github.com/auth0/Auth0.swift/pull/154

**Comment by lbalmaceda** [comment]
Aghh! Those logs are not helpful at all. Passwordless works by sending a code via email or sms. Even when using the `link` alternative, the code is present as a param. When you click the link, your app should capture this and open itself to continue the authentication. This means that your app must keep the previous state (email or phone of the user who started the authentication). For some reason it seems that safari is not allowing your app to open once the URL is hit. Please, share here the URL as seen in the "oops!" error page and verify that your app is configured to capture it (scheme, domain, path, etc). I don't really know if this issue has anything to do with the one you linked above. I'd wait for @cocojoe to help me on this one.

**Comment by seanpatrickcatlin** [comment]
The url was
`https://alfalfabit.auth0.com/passwordless/verify_redirect?scope=openid%20profile&response_type=token&redirect_uri=auth0.samples.auth0samplesc%3A%2F%2Falfalfabit.auth0.com%2Fios%2Fauth0.samples.Auth0Samplesc%2Fcallback&_intstate=true&_csrf=deprecated&audience=https%3A%2F%2Falfalfabit.auth0.com%2Fuserinfo&client_id=5MjmktL_PvjA6WENihoksIx4X-ISrGKO&code_challenge_method=S256&state=gOuQQg5Odqj5VA8Dn0CszYUOPJbOTxyM&code_challenge=4pbkVr6RGMqI_MJzpBqgKfrOH6D08lnHzcMF9V4XsEk&auth_0_client=eyJuYW1lIjoicmVhY3QtbmF0aXZlLWF1dGgwIiwidmVyc2lvbiI6IjEuMi4yIn0%3D&protocol=oauth2&verification_code=531037&connection=email&email=catlin.sean%40gmail.com`

The same app works without issue on iOS 9, iOS 10, and Android, so I assume everything is set up correctly.

**Comment by cocojoe** [comment]
Hi @seanpatrickcatlin I'm surprised this works at all. I'm sure this didn't used to work, regardless of iOS version. I would generally recommend using the code method vs magic link. As I've found it easy to break magic link on device if a user accidentally clicks `open in web` instead of `open in app` and then it remembers this setting.  Also had issues with it not opening from other mail apps etc

I'll need to set aside some time to test this flow in general now.  Thanks

**Comment by cocojoe** [comment]
So having tried this it seems like an iOS 11 ** security feature** I tried opening up the initial WebAuth in SFAuthenticationSession to see if it helped. However, the magiclink will just be opened by a WebView or SafariViewController and nothing is shared. 

I can only recommend not to use magic link as I don't see a solution for iOS 11.
