### ISSUE TITLE
Is it possible to use social logins without hosted login page?

### ISSUE THREAD

**Issue by jeaye** [auth0/react-native-auth0#134]
This was brought up in the a few older tickets (#17, #28, #39), but I'd some up-to-date info on it. Assuming I'm not using a hosted login page, can I still get Google and Facebook logins? If so, will you please provide the necessary documentation? If not, will you please tell me when this will be available?

**Comment by lbalmaceda** [comment]
As of today what you can do is call the hosted login page passing a `connection` query parameter, e.g. `facebook`. As long as the connection name exists and it's enabled for that client in your dashboard, you should be redirected to this provider's login page and skip the hosted Lock. You still need to handle the callback redirection and the code exchange. Does that work for you?

**Comment by jeaye** [comment]
Thanks for the quick reply.

@lbalmaceda So I'd need a hosted Lock page, which is never used directly, authentication code for first party Auth0 username/pass login, *and* authentication code for social login which opens up the web auth with a query param, causing a redirect to the third party. Is that all correct?

**Comment by lbalmaceda** [comment]
If you say you need a usr/pwd connection login then you can call this [login method](https://github.com/auth0/react-native-auth0/blob/master/auth/index.js#L118) provided you have a login UI in your app and the "Password" grant [enabled](https://auth0.com/docs/api-auth/tutorials/password-grant) for your client. Note that the method is meant for database connections only. I prefer using the HLP as it's [safer](https://auth0.com/docs/hosted-pages/login#why-use-the-hosted-login-page) for your users. You can always customize the look and feel or even use your own UI along with auth0.js library by editing the script of the login page [here](https://manage.auth0.com/#/login_page).

**Comment by jeaye** [comment]
@lbalmaceda I'm currently on react-native-lock, using password, Google, and Facebook logins. I need to move away from it because we now have a need for a completely custom UI.

I'd be fine using the HLP, and I've seen that last page on customizing it, but there is a very tiny amount exposed in that JS `theme` object for customization and I would not only need to customize the primary color and logo, but also the layout, wording, etc. From what I've seen, the HLP doesn't offer that kind of customization, right?

**Comment by cocojoe** [comment]
@jeaye You might find this sample of interest.  
https://github.com/auth0-samples/auth0-react-native-sample/tree/Embedded/01-Custom-Form

**Comment by jeaye** [comment]
@cocojoe Yes, I do! Thank you so much.
