### ISSUE TITLE
Facebook prompt consent Error

### ISSUE THREAD

**Issue by rf1804** [auth0/react-native-auth0#137]
**Whenever i decline some permission in facebook like email when it asks for permissions during login it gives an error**

![screenshot_20180310-103654](https://user-images.githubusercontent.com/35443934/37238596-e17b725a-244f-11e8-9f4f-953617b678a7.jpg)

**and when i use prompt: 'consent'
it gives a reprompt screen but clicking on cancel or accept both just display unauthorized and does not close the browser(If i've clicked on accept on prompt screen it shows unauthorised but when i close webview it shows up the email recieved)**

![screenshot_20180310-104556](https://user-images.githubusercontent.com/35443934/37238649-e51e872a-2450-11e8-8ad1-c7d18e280705.jpg)
![screenshot_20180310-104611](https://user-images.githubusercontent.com/35443934/37238652-eb4f63d0-2450-11e8-9610-8ac80c214afe.jpg)

**Comment by cocojoe** [comment]
How are you requesting additional FB permissions? 
When you say `decline` can you show how you are declining, a video/gif be good thanks so we can see the flow from start/finish.

**Comment by cocojoe** [comment]
No information provided.
