### ISSUE TITLE
social login and also auth0 login with username and password

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [auth0/react-native-auth0#138]
Now, this is a library available for auth0 login in react native. We are going to use it. But we can't find any option so that we can set social login(with only **Facebook** and **LinkedIn**).
Can anyone find any solution to **login with social as well as auth0(using username and password)**?
It's so urgent to find a solution.

**Comment by lbalmaceda** [comment]
Use [WebAuth](https://github.com/auth0/react-native-auth0#webauth). Any connection enabled for that client in your dashboard will show up there. There's a quickstart in the auth0 site as well describing how to achieve this.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@lbalmaceda  so what would be the value of **scope** in **WebAuth**?

**Comment by lbalmaceda** [comment]
That would depend on what you want to do with the tokens later.. Read more about it [here](https://auth0.com/docs/scopes/current) and don't hesitate to make this kind of questions on http://support.auth0.com or http://community.auth0.com

**Comment by MSSPL-PiyaleeMaiti** [comment]
@lbalmaceda  thanks for your response.  We use **WebAuth** for social and normal login. Now can you tell me how can we get the value of **location** from social login? We can't get location field from social login response.

**Comment by lbalmaceda** [comment]
@MSSPL-PiyaleeMaiti Please, use the links provided above to ask questions about the platform or if you need guidance. This space is for `react-native-auth0` bugs and issues only.

**Comment by MSSPL-PiyaleeMaiti** [comment]
Ok, thnks
