### ISSUE TITLE
Execution failed for task ':react-native-auth0:processReleaseResources'

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [auth0/react-native-auth0#139]
I am using react-native-auth0.
And when I build the app after following all the installation process then its show below issue:
**Execution failed for task ':react-native-auth0:processReleaseResources'**
![screenshot from 2018-03-16 12-39-43](https://user-images.githubusercontent.com/20696057/37508126-bb04cfbe-2917-11e8-85e6-ba63888e123b.png)

**Comment by MSSPL-PiyaleeMaiti** [comment]
Solve this issue by running below command 
`sudo apt-get install lib32z1`

and after that 
`cd android && ./gradlew clean`

then do anyone of below:
```
react-native run-android
react-native run-ios
```

**Comment by lbalmaceda** [comment]
Before that, have you run `link`?

```
react-native link react-native-auth0
```

**Comment by MSSPL-PiyaleeMaiti** [comment]
Yes, sure. First need install then link after that below steps.

**Comment by lbalmaceda** [comment]
Alright. Thanks for the heads up 👍
