### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by digitalhobo** [auth0/react-native-auth0#150]
Hi As reported by a customer, they get an error when he tries to login and get redirected to the app on android. The redirect is correct as it works for many other users. Just this one case. Do you have any idea what it could be. 
![mazda3 3mzbm64661m159993 joerg lewerenz telta de 2](https://user-images.githubusercontent.com/4119085/39126522-f5838e92-4702-11e8-8b46-89683c89e72a.jpg)

Many Thanks

**Comment by lbalmaceda** [comment]
the browser error says `unknown_url_scheme`, but that one looks just fine. It's either the browser app used not allowing to launch external intents or that your mobile app is not registered to handle that callback url.

**Comment by digitalhobo** [comment]
Thanks for the quick feedback.
Is their a way to tell the user that the browser app used does not allow launching external intents.
Thanks again.

**Comment by lbalmaceda** [comment]
If you're asking if there's a way to tell if the user's browser app is not working or if it's something else, then the answer is yes: Trial and error 😆. Ask which browser app is he using and try to reproduce it locally on your side. AFAIK Firefox is one of the browser apps that doesn't open automatically an app registered with that intent-filter. Instead, it displays a button next to the address bar that the user must manually click to open the app in question.

**Comment by digitalhobo** [comment]
Thanks for the feedback. Is their a way to force the user to use chrome.

**Comment by lbalmaceda** [comment]
Sure. Just [change the Intent](https://github.com/auth0/react-native-auth0/blob/master/android/src/main/java/com/auth0/react/A0Auth0Module.java#L60) set up to use a specific package, such as the chrome one. Note that if the app is not installed the launch will fail with an uncaught exception. Leaving the intent in a generic way will prevent such error. Remember also, if a user has chosen a default browser you should respect their decision and not force any other browser. By using the CustomTabs builder the service will try to find the best browser match to open the link in a custom tab.

**Comment by digitalhobo** [comment]
Thanks. Im wondering, maybe it would be better to handle the error in the browser, for example rather than showing the what you see in the attached image, we show a prompt to the user that the browser is not compatible.

Thanks again for your help.

**Comment by lbalmaceda** [comment]
Unfortunately, the error you see is part of the browser app and not part of any auth0 web page. You can't customize that.. It's shown since the browser can't find an app in the device that can handle that redirect.
