### ISSUE TITLE
add option to customize nav bar on iOS

### ISSUE THREAD

**Issue by initech-asynchrony** [auth0/react-native-auth0#151]
on iOS, when the auth webview opens, it appears to be using `SFSafariViewController` [under the hood](https://github.com/auth0/react-native-auth0/blob/31c838d213a9206dc8b4031d103c75b1498db832/ios/A0Auth0.m#L50). From what I am reading, [Apple discourages/prevents UI customization on this webview](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller). Our team would like to be able to remove the Safari button from the navigation bar at the bottom of the webview, but it looks like the best way to do that is to abandon `SFSafariViewController` altogether. `WKWebView` seems like the preferred alternative webview if UI/UX customization is needed.

**Comment by cocojoe** [comment]
In the world of OAuth, WebViews were deprecated quite a long time ago. See: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

If you want to customise the UI, you can look at the [Hosted Login Page](https://manage.auth0.com/#/login_page)

Thanks

**Comment by initech-asynchrony** [comment]
thank for you the information about WebViews. perhaps that is not the way to go.

to be clear, we are using a hosted login page currently. the UI that we wish to customize is _not_ the UI of the hosted login page. we already customized that. the UI that we wish to customize is the bottom nav bar of the outer view on iOS (which seems to be a SFSafariViewController) which _contains_ the hosted login page. we don't want the 'open in safari' button displayed in the nav bar.

![nav-bar](https://user-images.githubusercontent.com/33063676/39638905-55019fc0-4f8d-11e8-9fc8-3929334a1946.png)

would a [custom login form](https://github.com/auth0-samples/auth0-react-native-sample/tree/Embedded/01-Custom-Form) be the way to go?

**Comment by cocojoe** [comment]
I understand, this is not something Apple gives you much control over. 
This is all standard behaviour for WebAuth flow in iOS and not something that's come up as a concern before.
