### ISSUE TITLE
Passwordless without webAuth

### ISSUE THREAD

**Issue by nenti** [auth0/react-native-auth0#154]
Dear auth0 team, I would like to implement passwordless request out of my react-native ui and don't want to use webauth. Is there a workaround to implement own UI and not break native app experience with this react-native library?

Is it possible to use auth0.js for react native application to use the passwordless request?

**Comment by luisrudge** [comment]
That's not specific to this project. As of now, our backend only supports doing Passwordless authentication via a web browser, so you won't find any other native or backend SDK that support that scenario. Calling `oauth/token` might work for now, but it's not a supported scenario and has a few limitations because it doesn't create a session at Auth0's servers, so there's no SSO support etc.

**Comment by luisrudge** [comment]
Just to add more context: we're aware of the limitations and we know it's not the idea solution for everyone. We have plans to offer this in the future, but there is no ETA as of now.

**Comment by Alexander-0x80** [comment]
This is very disappointing indeed.

**Comment by bartolkaruza** [comment]
You can implement the first step in the Passwordless flow by making a post request based on the user provided email: https://auth0.com/docs/api-auth/passwordless

Also the webAuth of the JS SDK provides a method to implement this called [`passwordLessStart`](https://auth0.github.io/auth0.js/global.html#passwordlessStart) which is easy to port. @luisrudge are you open for a PR to port this to react-native-auth0?

**Comment by bartolkaruza** [comment]
Well here it is anyway :)
https://github.com/auth0/react-native-auth0/pull/189

**Comment by bmovement** [comment]
> This is one thing that put me off really bad, I'm walking away from Auth0 just because I'll have open a browser window and that I have no control on the token expiry, 2 hours force user to login?!.
> 
> For anyone why tries the approach proposed by @nenti they don't let you do that anymore, you will run into the error `Passwordless authentication is not allowed on this endpoint.`

@santthosh Did you find a different provider you'd recommend?

**Comment by estsauver** [comment]
Just thought I'd chime in: We operate in the field in subsaharan Africa. We currently use digits which has a version that works quite well natively. We'd love to migrate to Auth0 but this is blocking the final step of the migration, opening up chrome in the phones we typically are working with puts meaningful memory pressure on the device.

**Comment by kodayashi** [comment]
I'm surprised this isn't supported by Auth0. Authentication should be seamless for users and opening up web views disturbs the user experience. The branding options for the hosted views are weak as well (link to logo and two colors).

I see this was supported in the past but is now disabled. Is there not a plan to add support for this later?

**Comment by luisrudge** [comment]
There is a plan, but no ETA yet.

Luís
________________________________
De: Drew Horn <notifications@github.com>
Enviado: Tuesday, May 14, 2019 12:27:05 AM
Para: auth0/react-native-auth0
Cc: Luís Rudge; Mention
Assunto: Re: [auth0/react-native-auth0] Passwordless without webAuth (#154)


I'm surprised this isn't supported by Auth0. Authentication should be seamless for users and opening up web views disturbs the user experience. The branding options for the hosted views are weak as well (link to logo and two colors).

I see this was supported in the past but is now disabled. Is there not a plan to add support for this later?

**Comment by mikebucks** [comment]
This would be super useful. Any update @luisrudge?

**Comment by luisrudge** [comment]
Not yet :(

**Comment by mtt87** [comment]
I've added this guide and would like to get feedback on the approach 😄 
https://community.auth0.com/t/passwordless-with-react-native-and-auth0/34056
