### ISSUE TITLE
Error unknown error

### ISSUE THREAD

**Issue by joefazz** [auth0/react-native-auth0#155]
If you have a rule set up on Auth0 that only certain domains are allowed to access and then create the account from the Auth0 management section and try to login with that account while the rule doesn't include that domain then it will give this incredibly vague error while looking like it succeeded.

Whitelisting the domain fixes the issue.

**Comment by cocojoe** [comment]
Glad you sorted it.

**Comment by marcfielding1** [comment]
Sorry to bump this I thought it might be useful for anyone else, if you have a rule that bugs out for ANY reason you'll get this error, for instance, I was appending metadata to the accessToken, now that was fine for users that had the metadata, but for users that didn't the metadata was undefined so I ended up doing:

function (user, context, callback) {
  if(context.clientId === 'XXXXXXXXXXXX'){ // clientId from the applications console where users always have the meta data.
    const namespace = 'https://id.mydomain.com';
    context.accessToken[namespace + 'Id'] = user.app_metadata.shopId;
    callback(null, user, context);
  } else {
    callback(null, user, context); 
  }
}
