### ISSUE TITLE
After linking "react-native link react-native-auth0" the dev options (cmd+r and cmd+d) stopped working

### ISSUE THREAD

**Issue by festiveox** [auth0/react-native-auth0#157]
Does this happen to anyone else? After linking the native module in react-native-auth0 my dev environment stopped working. I can confirm that this is the issue because I remade a new native project with "react-native init" installed everything, but I didn't linked it and the library wasn't working, of course, but the dev options were. As soon as I linked and relaunched the dev options stopped working.

I'm on a mac with High Sierra.

**Comment by cocojoe** [comment]
The act of linking is a RN behaviour, it would seem unlikely our lib itself could affect the dev options.  Sounds more like a RN issue.
