### ISSUE TITLE
missing parameter "connection" in webAuth.authorize

### ISSUE THREAD

**Issue by linchen2chris** [auth0/react-native-auth0#159]
I check  documentation of [Auth0.js,](https://auth0.com/docs/libraries/auth0js/v9) if we wanna social login he connection parameter will need to be specified:
![image](https://user-images.githubusercontent.com/3970087/41191348-9e4c49e6-6c20-11e8-82ac-aa820542748b.png)

But in react-native-auth0 webAuth stop me to pass "connection", how can I social login in react-native-auth0?
#160

**Comment by linchen2chris** [comment]
#160

**Comment by lbalmaceda** [comment]
That's [how the Universal Login Page works](https://auth0.com/docs/hosted-pages/login#how-does-universal-login-work). Besides that `connection` value it also accepts [any OIDC parameter](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest). I'll leave a review on the PR you submitted and I'll close this one. Thanks

**Comment by linchen2chris** [comment]
Thanks so much @lbalmaceda for your reply.
