### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by hojberg** [auth0/react-native-auth0#16]
It seems that it's been a few months since any work was done here.
Could we consider the beta final then and do a proper release ? :D:D

**Comment by hzalaz** [comment]
We were planning a big api change before releasing a stable version 1 but our priorities shifted and we delayed it. In the coming weeks we will go back to a stable v1

**Comment by hojberg** [comment]
@hzalaz thanks - let me know if you could use some extra hands pushing it over the finish line
