### ISSUE TITLE
question on using pkce

### ISSUE THREAD

**Issue by john-pondr** [auth0/react-native-auth0#161]
The auth0 docs demonstrate a pkce flow. Is this supported in react-native-auth0? I cannot get the api to return a code object using react-native.

**Comment by lbalmaceda** [comment]
Whenever you use [Web Auth](https://github.com/auth0/react-native-auth0#webauth) you're already using the PKCE flow. The code exchange happens in the background after the browser is closed, and you're either handled an error or a pair of tokens.
