### ISSUE TITLE
Style of the iOs and Android login screen?

### ISSUE THREAD

**Issue by Darren-Ivey** [auth0/react-native-auth0#162]
Is there a way to edit the style and/or title of the iOS and Android login screen? 

For my login screens I'd like to change the colours and ideally provide a more specific title. I know the styling can be done for lock screens by passing through an options object with preferences, is there anything similar for react-native-auth0? 

Thanks

**Comment by cocojoe** [comment]
The screen you see is the Hosted Login Page, you should take a look there.
https://manage.auth0.com/#/login_page
https://auth0.com/docs/libraries/lock/v11/ui-customization
