### ISSUE TITLE
Is this library affected by the legacy Lock API deprecation?

### ISSUE THREAD

**Issue by grifotv** [auth0/react-native-auth0#163]
https://auth0.com/docs/migrations/guides/legacy-lock-api-deprecation

**Comment by engvik** [comment]
I tried to turn off the Legacy Lock API, and I was still able to log out and log in, retrieve and change user data, so I think it's not affected.

But it would be nice with an official answer.

**Comment by cocojoe** [comment]
No, this library doesn't use the Legacy API 👍

**Comment by grifotv** [comment]
Thanks @engvik @cocojoe

Here's an official answer https://twitter.com/Auth0Community/status/1017417274439995393
