### ISSUE TITLE
Access denied in PasswordRealm login

### ISSUE THREAD

**Issue by EmptyCrown** [auth0/react-native-auth0#164]
I'm trying to implement username/password login on React Native + Expo, with the following code.

```
const auth0 = new Auth0({ domain: 'camelot.auth0.com', clientId: 'XXX' });

auth0
    .auth
    .passwordRealm({username, password, realm: "Username-Password-Authentication"})
    .then(console.log)
    .catch(console.error);
```

The username and password are correct, since I'm not getting the `username/password incorrect` error, but instead, I always get `Access Denied`. Does anyone know what this is happening?

I've enabled password grants in my application, which is indeed `Native`.

**Comment by cocojoe** [comment]
Do the Auth0 Dashboard logs give you anymore information?
You don't have any custom rules running?

**Comment by EmptyCrown** [comment]
I don't believe so. How do I check for custom rules?

My dashboard just shows the logins that have been happening. However, each time, my app return Access Denied.

**Comment by cocojoe** [comment]
Expo is not officially supported, I would suggest going through our [QuickStart](https://auth0.com/docs/quickstart/native/react-native) and ensuring you can get that working first.
