### ISSUE TITLE
[Warning] React-Native warning about requiresMainQueueSetup

### ISSUE THREAD

**Issue by taboulot** [auth0/react-native-auth0#168]
When I launch my application, React-Native show me this  warning message on my simulator.

<img width="298" alt="screen shot 2018-07-20 at 16 58 06" src="https://user-images.githubusercontent.com/9041221/43264876-897c1e1a-90e7-11e8-9194-d42b7e1609f6.png">

It let me thinking that it will maybe have a problem with the implementation of a method called requiresMainQueueSetup.

What does it really mean ? 
Is there any risk for my application for the future if I upgrade my react-native version ?
If yes, did auth0 plan to handle this ? 

Thanks for your answers !

**Comment by festiveox** [comment]
Any news/resolution on this?

**Comment by cocojoe** [comment]
How do you make this warning appear?
What are the steps to reproduce?
What version of RN?

**Comment by cocojoe** [comment]
No follow up.
