### ISSUE TITLE
Linking adds POD to tvOSTests

### ISSUE THREAD

**Issue by mlaug** [auth0/react-native-auth0#169]
Calling `react-native link react-native-auth0` results in an entry in the `Podfile` for tvOSTests. This causes the running app to complain about missing native dependencies.

Steps to reproduce

`react-native init test`
`npm install react-native-auth0 --save`
`cd ios`
`pod init`
`cd ..`
`react-native link react-native-auth0`

results in

```
target 'test-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'A0Auth0', :path => '../node_modules/react-native-auth0'

  end
```

expectd result is the line `pod 'A0Auth0', :path => '../node_modules/react-native-auth0'` to be the target `test`

**Comment by cocojoe** [comment]
Inactive.
