### ISSUE TITLE
Social login?

### ISSUE THREAD

**Issue by dronsfield** [auth0/react-native-auth0#17]
Does this library support social login?

When I try this:
`.login("<EMAIL>", "<PASSWORD>", "facebook")`

I get this error:
`Error: specified strategy does not support requested operation (facebook)`

I need to use Auth0 for social login with a custom login UI.

**Comment by hzalaz** [comment]
@dronsfield that method is for database and AD connections. For social connections you need to enter the user credentials in the social provider login page and this involves showing that page in a browser. We are going to add  this feature to this library soon.

**Comment by dronsfield** [comment]
@hzalaz Thanks. I was hoping to use Auth0 as a quick solution for a client project, do you think this feature will be ready in the next couple of months?

**Comment by hzalaz** [comment]
@dronsfield we aim to start working on this  sometime in Feb so I'd say March

**Comment by dronsfield** [comment]
@hzalaz cool, thanks for your help

**Comment by dronsfield** [comment]
hey @hzalaz, has there been any progress with this?

**Comment by mtt87** [comment]
I have to implement this for Facebook and Google social login, but with a custom UI I can't use Lock for React-Native at the moment 😭

**Comment by mcclowes** [comment]
Could really do with this

**Comment by mackenziemance** [comment]
any updates on this ?
