### ISSUE TITLE
possibility to run with launchMode:singleTop?

### ISSUE THREAD

**Issue by lean** [auth0/react-native-auth0#170]
Is there any way to run with `launchMode:singleTop`? I tryied and I noticed that I can not get the response credentials in the app. I need to set it for compatibility with another library

**Comment by lbalmaceda** [comment]
I guess it depends on how you handle the state in your activity. The intent call should be received either on the `OnCreate` (first launch) or the `onNewIntent` (following launches) methods of your activity. I remember trying this on the past but we ended up using the `singleTask` launch mode, don't remember now why. I think it was related to the Custom Tabs.

**Comment by lbalmaceda** [comment]
Thinking this further, using single top would mean that the activity you use to authenticate will have more than one instance in the activities' stack. That's not an scenario you want to have as it will generate your user issues when they press back. See the diagram below. This was taken from https://medium.com/@iammert/android-launchmode-visualized-8843fc833dbe 
![image](https://user-images.githubusercontent.com/3900123/43738103-e6cdb5be-9999-11e8-8a44-de67c26e6583.png)

**Comment by marcoschicote** [comment]
Hi @lbalmaceda 
I'm experiencing a similar problem to lean's. I'm using the [react-native-firebase](https://rnfirebase.io/docs/v4.3.x/notifications/android) library with Notifications which requires the `launchMode` to be `singleTop`. 
Other libraries like [react-native-fcm](https://github.com/evollu/react-native-fcm) also require singleTop. Do you have any recommendations for this scenario?

Thanks in advance.
Marcos

**Comment by lbalmaceda** [comment]
@marcoschicote The advantage we have by using singleTask is that we can wipe all the activity stack above the one we are launching now, useful when we open a custom tab activity and we want to remove it once the authentication is performed, for example. A workaround could be declaring a new singleTask activity without any layout to perform all the authentication steps (launch browser and parse result). We do something similar on the android library.

i.e.
```
your activity -> this authentication activity -> browser 
browser redirection -> authentication activity, performs exchange -> finishes and passes the result back -> your activity
```

**Comment by chiaberry** [comment]
@lbalmaceda @marcoschicote How would one go about declaring a new singleTask activity? Do I just add one in the androidmanifest, and if so, how do I specify the activity is for auth0 and not OneSignal for example. Thanks!

**Comment by lbalmaceda** [comment]
👋We're not going to change the android launchMode (currently `singletask`) as that would affect how the authentication is received on the activity. If this still an issue for you?

**Comment by xeroxoid** [comment]
Hi @lbalmaceda this is still an issue, yes. The problem is that other libraries i.e. OneSignal (for push notifications) as well as Firebase use `singleTop` for the `MainActivity` (and they claim they can not change their implementation to support `singleTask` as seen on this issue: https://github.com/OneSignal/react-native-onesignal/issues/565).

Is there any workaround to use `singleTop` with auth0?

Can you describe implementation wise what the suggested solution (in your comment here: https://github.com/auth0/react-native-auth0/issues/170#issuecomment-411084815) would look like?

**Comment by lbalmaceda** [comment]
@xeroxoid ReactNative Linking requires the `launchMode` of the activity in which you will receive the result to be `singleTask`. So the easiest thing I can come up with now is to _use different activities_ for OneSignal and Auth0. That way you can have one with `singleTop` and the other with `singleTask`.

**Comment by xeroxoid** [comment]
@lbalmaceda you're right thanks, but we can't seem to find an example on how to use multiple activities with react-native as well as how data will be passed from the OneSignalActivity to the MainActivity.

I understand that this is out of the scope of auth0's team but we are trying a find a solution that seems to be affecting multiple users of multiple libraries.

I posted a new comment here to hopefully get some input from OneSignal's team too: https://github.com/OneSignal/react-native-onesignal/issues/565#issuecomment-553565655
