### ISSUE TITLE
"User cancelled Auth" message on Android with React Native Navigation  V2

### ISSUE THREAD

**Issue by reinvanimschoot** [auth0/react-native-auth0#171]
Hi guys

I've been having some troubles getting Auth0 to work in a new project that also features React Native Navigation V2. Whenever I try to use WebAuth, the browser popup opens and then disappears and I am left with the following error:

<img width="411" alt="screen shot 2018-08-08 at 15 42 11" src="https://user-images.githubusercontent.com/35171567/43840732-a7fc357a-9b21-11e8-8f6d-d9e13fe1af5b.png">

I noticed some other issues around this topic but none of them have really fixed the problem it seems, and they are from last year.

Is there anyone that could help me set this up correctly?

Kind regards!

**Comment by lbalmaceda** [comment]
@reinvanimschoot That's the behavior you get when the user closes the browser manually and goes back to your application. If it wasn't intended, then it looks like a configuration error on your android application. Have you followed the [android steps](https://github.com/auth0/react-native-auth0/tree/a5e6c8bb2452ea2f2b8f8f47b0aa1fa8c8fb98a1#android) described in the readme?

**Comment by reinvanimschoot** [comment]
I followed the config guide yep. Could it be a problem with an incorrect callback?

**Comment by lbalmaceda** [comment]
Ah sorry. I just read the first comment again.. When you use `React Native Navigation` this library can't receive the callback as the result it's being swallowed by them.

Original issue: https://github.com/auth0/react-native-auth0/issues/83#issuecomment-375450057
