### ISSUE TITLE
Fail to run on iOS

### ISSUE THREAD

**Issue by nthegedus** [auth0/react-native-auth0#172]
Hi, 

I'm trying to integrate react-native-auth0 on my app.

I've followed whole steps, and I was getting this error message:

> Please make sure you run `react-native link react-native-auth0`

Then I realized that `react-native link react-native-auth0` didn't work as expected. So I linked manually.

Now I'm getting this other error, and I have no idea how to fix it

> ...
> ** BUILD FAILED **
> 
> The following build commands failed:
>         CompileC /Users/.../ios/build/Build/Intermediates.noindex/A0Auth0.build/Release-iphonesimulator/A0Auth0.build/Objects-normal/x86_64/A0Auth0.o A0Auth0.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> 
> Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Dev.Debug-iphonesimulator/DEV.Equals.app/Info.plist
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

Does anyone have any ideia about what is wrong?

this is my environment:
> react-native-cli: 2.0.1
> react-native: 0.55.4

Thanks

**Comment by kiljee** [comment]
Hi @hegedus,
I found solution in this [PR](https://github.com/auth0/react-native-auth0/pull/136/files),
need to add .dependency "React" in 0Auth0.podspec.

**Comment by winseyli** [comment]
Thanks @kiljee for your solution. I had the same issue today.
