### ISSUE TITLE
Style iOS webview

### ISSUE THREAD

**Issue by cjrorvik** [auth0/react-native-auth0#178]
![img_c57dfda0abd3-1](https://user-images.githubusercontent.com/1122305/46211866-e7d4d180-c334-11e8-9af9-4d9488ea5029.jpeg)

Is it possible to style the iOS Lock top and bottom bar. Ideally I would like to remove the bottom bar, and make the top bar look more like our app navigation bar?

**Comment by luisrudge** [comment]
Can you clarify what you mean by top and bottom bar?

**Comment by cjrorvik** [comment]
I am thinking about the top and bottom bar of the Safari Secure web view.. Like changing color of the top bar where it says 'Ferdig' and where the refresh icon is.

**Comment by cocojoe** [comment]
@cjrorvik While I agree it might be nice, this is not something exposed to the developer by Apple.  Authentication uses the recommended flow of [SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession)

This will be updated at some point to use [ASWebAuthenticationSession] which is pretty much a name change. (https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)
