### ISSUE TITLE
Release needed in regards to iOS deployment target update

### ISSUE THREAD

**Issue by RaphCayou** [auth0/react-native-auth0#179]
With the latest commit updating the iOS deployment target (commit 7390389bc51720c2c1cb5c5845d370ce348ec922), would it be possible to create a new stable release in order to use it from yarn easily? 

I am getting this error when building my app to deploy on iOS 12: 
>warning: The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.0. (in target 'A0Auth0')  

Thank you

**Comment by cocojoe** [comment]
Agreed, it's on my list of tasks today.
