### ISSUE TITLE
How to get a refresh token for social login

### ISSUE THREAD

**Issue by mhopey** [auth0/react-native-auth0#183]
I am able to get a refresh token using passwordRealm and including offline_access in my scope. However I'm unable to get the refresh token for social login using the /authorize endpoint. I've also included offline_access but I am not receiving the refresh token. Any help would be appreciated.

**Comment by lbalmaceda** [comment]
There are a number of things that could lead to that behavior. e.g. the API you are requesting the audience for doesn't have the "offline access" enabled in their settings, or the associated application doesn't have the offline_access grant enabled. 

Can you please check if the refresh token is coming in the request's response, and being ignored by the SDK?
