### ISSUE TITLE
Only One Safari Can be Visible.

### ISSUE THREAD

**Issue by marcfielding1** [auth0/react-native-auth0#193]
I hope you don't mind I've skipped template simply because this directly refers to a specific error message.

Because I was having a idiot moment I accidentally messed up copying my BundleIdentifier to the URL's section of info.plist, when running my react native app I ended up with this error message

[Link to Auth0 code](https://github.com/auth0/react-native-auth0/blob/e49d57e98adbc9f40c8d99b065f04de678142d31/ios/A0Auth0.m#L56)

This gives "Only One Safari Can be Visible."  error in the debugger and took me quite a long while to track down the source of issue which was the CFBundleURLTypes section of my info.plist.

I would love to put up a PR for it but I'm a JS guy and don't understand native code that well. Would it be an idea to perhaps make that error a little clearer?

**Comment by cocojoe** [comment]
It would be best to use the template as it helps give a lot of information to help review any issue. 

Could you clarify the issue please, it sounds like you misconfigured the application and it didn't work?

**Comment by marcfielding1** [comment]
Hey Cocojoe, yes so it's entirely my fault, it's fixed now I simply had to make sure the CFBundleURLTypes was correct - my point is that the error message "Only One Safari can be visible" is a bit vague for the user in terms of tracking down the problem, my question was really is there any way to improve that error message - again I'm not a swift expert so I thought I'd ask.

**Comment by cocojoe** [comment]
Agree, it's not the most obvious and I don't think it would be exclusive to this mistake as I can imagine other scenarios that could throw this. So don't think there is much we should do. However, appreciate your input on improving the experience 👍

**Comment by marcfielding1** [comment]
No worries, by the way, Auth0 has saved us a ton of time with our identity solution - great work!
