### ISSUE TITLE
Can react-native-auth0 be used for whitelabel Guardian app?

### ISSUE THREAD

**Issue by jimcullenaus** [auth0/react-native-auth0#198]
Related to [this issue](https://github.com/auth0/auth0-guardian.js/issues/35) in the auth0-guardian.js repo, can the react-native-auth0 library be used in order to build a custom application that supports receiving push notifications for use in MFA login requests?

**Comment by jimcullenaus** [comment]
What you describe is not our use case. We want to use our app to receive push notifications for 2FA from our desktop site.

**Comment by cocojoe** [comment]
Indeed, I wanted to highlight the typical use case this library was designed to solve. I understand your request. However, this library can not facilitate that for you. You will most likely need to go native.
