### ISSUE TITLE
Authentication API userInfo causes Unexpected token

### ISSUE THREAD

**Issue by calclavia** [auth0/react-native-auth0#2]
React Native v0.27

Error message:

```
Unexpected token U in JSON at position 0
SyntaxError: Unexpected token U in JSON at position 0
```

Replicate by doing:

```
      lock
              .authenticationAPI()
              .userInfo(token.idToken)
              .then(response => console.log(response))
              .catch((err) => console.log(err))
```

**Comment by crbrasfield** [comment]
Also experiencing
`SyntaxError: Unexpected token U in JSON at position 0`

**Comment by hzalaz** [comment]
@calclavia @crbrasfield I have this working on my end with the same steps, also the error seems to be a malformed JSON returned in the request to `/tokenInfo` so I need you guys to paste the response or more details on how to reproduce it (A working sample maybe)

**Comment by pranny** [comment]
From what it looks like, this is because the API is unauthorized. I too get this error and found the API calls are returning `Unauthorized` response.

**Comment by lhrolim** [comment]
I´m also having the same issue using RN 0.39.0 and 
React-native-lock 0.4.0.

Excuse my ignorance. I´m kinda unfamiliar with React-native environment. @hzalaz  but any hints on how to gather the response since it´s not logged on chrome´s network tab? I Tried to use a Fiddler proxy (running on windows here) but no luck either.

**Comment by lhrolim** [comment]
After reading my previous answer I realize that the issue was that I was sending the idtoken instead of the accesstoken.

Nonetheless, you´d better improve your exception handling for these kind of 401 scenarios.
