### ISSUE TITLE
a warning when we use the newest react-native-auto

### ISSUE THREAD

**Issue by pengcao1** [auth0/react-native-auth0#202]
### Description

Description of the bug or feature request and why it's a problem. Consider including:

- a gradle build warning thought by gradle build tools
- the warning message like this 
- Configuration `compile` is obsolete and has been replaced with `implementation`. It will be removed at the end of 2018

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version
 - v1.3.1
- React Native version
 - N/A
- iOS Setup
 - N/A
- Android Setup
 - a normal build steps

### Reproduction
implementation the `v1.3.1` to your project and build the android package

**Comment by Walaa106** [comment]
I have the same warning  `WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
Please fix!!

**Comment by leemcmullen** [comment]
This is because of the dependencies element in `build.gradle` for this package. 

For a temporary fix, you can edit the file directly within your `node_modules` (i.e. `android/build.gradle`) and replace `compile` with `implementation` (or `api`) within the `dependencies` element. That should get rid of the warning for the time being.

**Comment by lbalmaceda** [comment]
>>> Configuration compile is obsolete and has been replaced with implementation. It will be removed at the end of 2018

This warning will keep appearing until we can bump the gradle version to a newer one. But that is tied to the react-native version this project was made for. And today that minimum is too old. We definitely need to migrate it to 0.60.x so we can support android X dependencies as well. Keep an eye on https://github.com/auth0/react-native-auth0/issues/221 for this.
