### ISSUE TITLE
React/RCTDefines.h file not found

### ISSUE THREAD

**Issue by paulmichalak** [auth0/react-native-auth0#207]
After the recent release (1.4.0) I'm getting a build error on iOS claiming `'React/RCTDefines.h' file not found` after doing a pod install. I noticed this: https://github.com/auth0/react-native-auth0/pull/192/files in the last PR and when I put it back locally (and run pod install) it seems to build again. It seems this causes issues in older versions of react native. Is the only solution to update RN or is there a way to make this backwards compatible?

**Comment by eliasturbay** [comment]
I have the exact same problem.... Anyone around to provide some clarification in order to solve it?
Thanks in advance!

**Comment by cocojoe** [comment]
The pod install is not a method we officially support here, although people do use it. However, to clarify @paulmichalak the fix for you was to roll back the podfile?

Although that PR was in response to this issue:
https://github.com/auth0/react-native-auth0/issues/191

**Comment by eliasturbay** [comment]
Yes @cocojoe. I can confirm that adding this line back to the podspec file solves the issue:
https://github.com/auth0/react-native-auth0/pull/192/files#diff-b783818a710ff92753f417048ea8213dL17

In a side note, it's kind of confusing what you said that you aren't officially supporting `pod install`, because the only thing that cmd `react-native link react-native-auth0` is doing is adding this line to the `Podfile`:
```
    pod 'A0Auth0', :path => '../node_modules/react-native-auth0'
```

I can open a PR today to address this issue if you want

**Comment by cocojoe** [comment]
Thanks for the clarification, PRs are always welcome 👍

**Comment by paulmichalak** [comment]
@cocojoe Sorry for the late response. Basically, as far as I can tell, the fix for issue https://github.com/auth0/react-native-auth0/issues/191 fixes newer versions of react native but breaks older ones. Just curious if anyone has suggestions for backward compatibility. Updating react native projects is still quite painful so I'm trying to defer for at least a little while longer.

**Comment by PizzaBrandon** [comment]
I'm having the same problem on a brand-new React Native project running 1.4.0 of this package and RN 0.59.1, so this doesn't actually fix newer versions either. When I revert to version 1.3.1, the build succeeds.

**Comment by cocojoe** [comment]
Thanks for feedback @PizzaBrandon bit of a mixed bag here. I'll need to try this myself.

**Comment by reinvanimschoot** [comment]
Is there any update on this? I started out with a fresh RN project a couple of days ago and wanted to integrate Auth0 when I stumbled upon this error.

**Comment by cocojoe** [comment]
I had a play with this, using the follow versions:

```
react-native-cli: 2.0.1
react-native: 0.59.3
Xcode 10.1
react-native-auth0: 1.4.0
```

I followed this guide as I wanted to understand pod usage: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html (Swift Project)

I ran into `RCTBridgeModule.h missing`, looked at various "solutions". However, simply adding the `s.dependency "React"` back into `node_modules/react-native-auth0A0Auth0.podspec` fixed this for me. I believe the original concern was unwarranted as if you check the `ios/Podfile.lock` it uses the latest react pulled in by your project.

**Comment by joenas** [comment]
FYI what worked for me (for iOS, haven't tried Android yet) was to:
-  **remove** ` pod 'A0Auth0', :path => '../node_modules/react-native-auth0'` from `Podfile`
- add `node_modules/react-native-auth0/ios/A0Auth0.xcodeproj` to `Libraries` in Xcode
- manually link `libA0Auth0.a` in _Build Phases_

Using

      Xcode: 10.1
      react-native: 0.57.8
      react-native-cli: 2.0.1
      react-native-auth0: 1.4.0

**Comment by paulmichalak** [comment]
@cocojoe, any timeline in mind for putting it back?

**Comment by XEmAX32** [comment]
Hi, I have the same issue but I can find  `s.dependency "React"` at the end of A0Auth0.podspec, any solution?

**Comment by peterholcomb** [comment]
Having this issue currently on 2.1.0 on a new react native project

**Comment by igorlimansky** [comment]
Having this issue on 2.4.0, any possible fix?
@peterholcomb did you figure it out by chance?

**Comment by lr-mjaouen** [comment]
`pod 'A0Auth0', :path => '../node_modules/react-native-auth0/ios'` worked for me
