### ISSUE TITLE
Problem trying to compile my application in iOS

### ISSUE THREAD

**Issue by pbarrenechea** [auth0/react-native-auth0#210]
### Description
Hi team,

I was playing around with react-native and tried to make it work with Auth0. I faced an issue at the time of running my application on iOS.
After executing the command:
`react-native run-ios` I'm facing the following issue:

```
unknown receiver 'ASWebAuthenticationSession'; did you mean 'SFAuthenticationSession'?
        self.authenticationSession = [[ASWebAuthenticationSession alloc]
```
I've tried to build the project on xcode, to find more details and I found the following:

```
Unknown receiver 'ASWebAuthenticationSession'; 
```
on the following code:
```
if (@available(iOS 12.0, *)) {
        self.authenticationSession = [[ASWebAuthenticationSession alloc] ...
```
the other branches of the if seems to be using `SFAuthenticationSession` instead. 

### Environment

Please provide the following:

- React Native Auth0 version: 1.4.0
- React Native version: ^0.55.0
- iOS Setup

**Comment by cocojoe** [comment]
Can you complete the ENV info please? What version of Xcode are you using? Thanks

**Comment by pbarrenechea** [comment]
Xcode: Version 9.4.1 (9F2000)

**Comment by pbarrenechea** [comment]
Btw, thanks for your quick response!

**Comment by cocojoe** [comment]
You need to use Xcode 10, not sure why Xcode 9 can't skip this code tbh However, you do need 10 and Apple would also say you should be using 10 😄

**Comment by pbarrenechea** [comment]
Thank you so much. I was able to run the build successfully with Xcode 10. 🍺
