### ISSUE TITLE
Meet Facebook Platform Policy - Native Login required

### ISSUE THREAD

**Issue by waterdoo** [auth0/react-native-auth0#211]
### Description

Facebook updated its policies, and all native apps must use native login.
[Facebook's requirement](https://developers.facebook.com/policy#7-2-photo)

### Prerequisites

* [YES] Did you check the documentation? [https://auth0.com/docs/quickstart/native/react-native/00-login]
* [YES] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [YES] Are you reporting this to the correct repository?
* [NO] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version: 1.2.2
- React Native version: 0.51.0

**Comment by nenti** [comment]
Is this library still supported by auth0?

**Comment by cocojoe** [comment]
We are aware of this and actively working towards a solution, previously I was unable to communicate on this. However, I can share the following:

We are aware that developers who are creating native applications using Auth0's Facebook social connector to authenticate users are experiencing app rejections from Facebook based on the recent changes to Facebook’s native application [login policy](https://developers.facebook.com/policy#login). 

This recent policy change from Facebook impacts all identity as a service (IDaaS) providers, and we are currently exploring solutions. We will provide an update as soon as we are able and you can also stay in touch with us on [Auth0 community](https://community.auth0.com/) on this topic.

**Comment by VilleMiekkoja** [comment]
Any news on this? I have an app in production and they will disable facebook login for it because it goes through the browser. Any idea what could I do about this? @cocojoe
