### ISSUE TITLE
Is there any way to work around 'disable javascript' issue in browser incase of webAuth

### ISSUE THREAD

**Issue by jariwalabhavesh** [auth0/react-native-auth0#212]
### Description

When we try to login user using ```auth0.webAuth.authorize(authConfig)``` it will launch browser instance which will show login page. In case javascript is disable in user browser then login page is not loading. Is there any work around it. If we enable javascript from browser then it login page start working.

### Prerequisites

* [X] Did you check the documentation? [Add a link]
* [X] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [X] Are you reporting this to the correct repository?
* [X] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version : 1.3.1
- React Native version: 0.55.1

### Reproduction

Reproduction only require to disable javascript in chrome browser in case of android. And then try toi login from app.
**Step to disable javascript in android:**

1. Open chrom browser.
2. Click on three dots on right top side, It will open menu.
3. Click on **Setting** from menu.
4. Click on **Site settings**
5. You should find **Javascript** option. Please disable it. and test app again.

**Step to disable javascript in IOS**
1. Go to iphone **settings**
2. Find out **safari** in list and click on it.
3. After that you should able to see option for safari, please goto bottom and click on **Advanced**
4. Under that you should able to find **Javascript** option. Disable it and test app again

**Comment by lbalmaceda** [comment]
Yes, that is **expected**. 

If you're using the Classic Hosted Login Page, the browser must have javascript enabled for it to work. You might want to try the new look and feel, which is server-side rendered and thus, doesn't require javascript enabled in the browser. Take a look at the docs here https://auth0.com/docs/universal-login#choosing-an-experience. Note that it's missing some features yet as explained [here](https://auth0.com/docs/universal-login/new-experience-limitations)

**Comment by jariwalabhavesh** [comment]
@lbalmaceda: Thanks for informtion
