### ISSUE TITLE
iOS: AppDelegate application:openURL:sourceApplication:annotation: deprecated (RN 0.59.4)

### ISSUE THREAD

**Issue by sseppola** [auth0/react-native-auth0#219]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please user the [Auth0 Community](https://community.auth0.com/).

### Description
Similar to the issue: https://github.com/facebook/react-native-fbsdk/issues/525

your docs use an outdated AppDelegate openURL method when using RN 0.59.4:
<img width="915" alt="Screen Shot 2019-05-14 at 11 39 35" src="https://user-images.githubusercontent.com/4065840/57688202-2d80a900-763d-11e9-8728-12ff9b006ec1.png">

In particular, notice the use of `sourceApplication` and `annotation` instead of `options`.
Docs: [application:openURL:sourceApplication:annotation:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application?language=objc)
Docs: [application:openURL:options:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application?language=objc)

For us that meant links back to the application from Auth0 broke on login.

### Environment

Please provide the following:

- React Native Auth0 version: 0.59.4
- React Native version: 16.8.3
- iOS Setup: iOS 12.1.4
- Android Setup

**Comment by lbalmaceda** [comment]
@cocojoe please evaluate

**Comment by cocojoe** [comment]
Sorry @sseppola never saw this first time around. Are you still having an issue and if so what is your use case and steps to recreate. Thanks

**Comment by sseppola** [comment]
I'm not having this problem, I solved it and described the fix. The point was your docs are outdated and telling people to use `annotation` and `sourceApplication` in the openURL method instead of `options`.

Looks like I copied the wrong link to the docs, see https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623073-application?language=objc

**Comment by Widcket** [comment]
@sseppola thanks for raising this.
