### ISSUE TITLE
Unknown error is not unknown

### ISSUE THREAD

**Issue by steffenagger** [auth0/react-native-auth0#220]
## Intro:
Hello, we're using passwordless email login flow in a RN-app we're developing.
I'm currently handling auth errors, and I'm fairly certain I ran in to a bug. It's been a bug for awhile (see closed PR: https://github.com/auth0/react-native-auth0/pull/141)...

I'll try to elaborate a bit more than the above PR.

If a user is blocked through Auth0's back-office, and tries to authenticate, this error is thrown:

```json
{
  "name": "a0.response.invalid",
  "message": "unknown error",
  "json": {
    "error": "unauthorized",
    "error_description": "user is blocked",
    "state": "..."
  },
  "status": 0
}
```

Notice that `err.message` is `"unknown error"`, and `err.name` is `"a0.response.invalid"`, both default/fallback values in `Auth0Error`. But from the metadata we can clearly see that the user is in fact `"unauthorized"` with the reason: `"user is blocked"`.

I think (and apparently I'm not the only one) this is caused by using `Auth0Error` [here](https://github.com/auth0/react-native-auth0/blob/master/webauth/index.js#L78) instead of `AuthError`.

In general I'm unsure why `Auth0Error` extracts `name` & `description` from `response.json`, and not `error` & `error_description`. I guess there are responses/url-redirects which describes an error-state with `name` & `description`?

### Versions used
react-native: 0.57.8
react-native-auth0: 1.4.2

**Comment by cocojoe** [comment]
@lbalmaceda can you evaluate please.

**Comment by lbalmaceda** [comment]
@steffenagger Thanks for the report. I've assigned myself and will check it sometime next week.

**Comment by lbalmaceda** [comment]
@steffenagger Sorry for the delay.

Thought about this. Actually is not clear to me in what scenarios the backend would respond with `error`  or `error_description`. The diff on the closed PR is the safest way on changing that now without breaking anyone, assuming that `error` worked for some scenarios in the past. If I can confirm this never worked I don't mind removing that whole IF and just using a `AuthError` instance when `error_description` is present in the query (vs checking for `error`).

In some other clients SDK we use as message of the exception either `error` or `error_description` or a _default_ one if none of the previous was present. That would also make sense. I don't know why this SDK has 2 different error classes with that subtle difference. I'll come back next week to manually test some basic scenarios and propose a PR or re-open that one.
