### ISSUE TITLE
Can it work on Expo? 

### ISSUE THREAD

**Issue by vonwao** [auth0/react-native-auth0#222]
I'm wondering why this has to be configured with Android and iOS native code?  What does authentication have to do with native code?  Can it be implemented entirely in RN with Expo?  Thanks for any info.

**Comment by cocojoe** [comment]
Expo only works with pure JS.  Native code is used so we can implement the recommended guidance required to support each native platform in a secure manner. 
So we currently can't support Expo.

**Comment by Lucas-Geitner** [comment]
@vonwao this is an exemple of Oauth0 with Expo : https://github.com/expo/auth0-example

I will try it, if it's not succesfull, i will be force to eject !
Let me know how you did it ;)

**Comment by RipTheJacker** [comment]
I don't see why it wouldn't work with https://docs.expo.io/versions/v37.0.0/sdk/auth-session/ but it does not.

**Comment by aliahsan07** [comment]
So this doesn't work on expo? Wish I knew earlier

**Comment by DomVinyard** [comment]
Yes, me also. Does anybody have a recommended approach for Expo+social login?

**Comment by bearcub3** [comment]
I don't understand why Auth0 is not compatible with Expo as it is widely used between many JS developers, specifically for React Native. :-(

**Comment by bombillazo** [comment]
Can we re-open given there is a PR for a solution in the works to make this compatible with Expo and this seems to be the original issue?
