### ISSUE TITLE
"error":"invalid_grant", "error_description":"Wrong email or password."

### ISSUE THREAD

**Issue by LaVielle** [auth0/react-native-auth0#224]
### Description

I am getting error reports that some **iOS** users are having problems creating account:

```JSON
{
"name":"invalid_grant",
"message":"Wrong email or password.",
"json":{"error":"invalid_grant","error_description":"Wrong email or password."},
"status":403,
"line":459,
"column":482,
"sourceURL":"/var/containers/Bundle/Application/073C3ED9-26DB-4346-BC24-796BA48BA869/pkup.app/main.jsbundle"
}
```

Our UI prevents users from inputing invalid email addresses or passwords that don't match security criteria, so "Wrong email or password" doesn't seem possible.

I cannot reproduce the issue but I see on my reports that several users experience this ever day.

So really I'm trying to understand what this error means so I have a better idea of how to find the root cause, cause I'm pretty clueless now...

I have found similar looking issues on the community forum, but unanswered:
https://community.auth0.com/t/login-fails-part-2/6109
https://community.auth0.com/t/oauth-token-responds-with-error-invalid-grant-error-description-invalid-username-or-password-for-azure-ad/15411

### Prerequisites

* [x] Did you check the documentation?
https://auth0.com/docs/api-auth/grant/password#realm-support
https://auth0.com/docs/api-auth/tutorials/password-grant#realm-support
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [ ] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version **1.3.0**
- React Native version **0.59.9**
- iOS Setup ✅
- Android Setup ✅

### Reproduction

I have not been able to reproduce this error

**Comment by lbalmaceda** [comment]
@LaVielle I'll close this one as it's not an SDK issue. You mentioned _you are_ validating them but have you considered that maybe your users are calling the API on their own, outside of your app? e.g. via a curl/postman script. Is that a possibility in your case? Or even that the error is in fact true and they are mistyping the email or password, leading to an invalid combination of credentials? How often you get these errors?

**Comment by LaVielle** [comment]
@lbalmaceda It was indeed a user error, but mostly a developer error :/

We were trimming and lower casing the email given by the user and passing that to `createUser`.
The auth0 user was then created, and we would log in the user with `passwordReal`. However, we were passing the raw email input (no trim, no lower case) for the login. So some users were probably typing a space at the end of their email and then the match would not work... Definitely a developer error.

```JavaScript
// Create new user
await auth0.auth.createUser({
  email: email.trim().toLowerCase(),
  password,
  connection: 'Username-Password-Authentication',
  metadata,
})

// Login new user
const token = await auth0.auth.passwordRealm({
  username: email,
  password,
  audience: 'colugo',
  scope: 'openid offline_access',
  realm: 'Username-Password-Authentication',
})
```
