### ISSUE TITLE
'App' wants to use 'app.com' to Sign In

### ISSUE THREAD

**Issue by yvocilon** [auth0/react-native-auth0#226]
![Screenshot 2019-07-11 at 16 19 51](https://user-images.githubusercontent.com/38035825/61058702-09043b80-a3f8-11e9-9adc-f9c03ec0b3d7.png)

I've been getting the above message since upgrading to 1.4.2. I'm getting the messaging when using `auth0.webAuth.authorize` and `auth0.webAuth.clearSession`. 

Is it possible to disable this message or is there an explanation. I've been searching for quite a while but have not been able to find it. Or is this iOS specific and does it have nothing to do with this package? Our current app is running on a rather old version and the message does not show up there. 

Thank you!

**Comment by lbalmaceda** [comment]
I found that as frustrating as you but it's not because of this package. That's iOS specific and cannot be customized nor disabled, AFAIK. Is something introduced in iOS10 and iOS11, but not present on iOS9 (that's why you don't see it on older devices)

**Comment by yvocilon** [comment]
Ah okay. I upgraded our react-native-auth0 from 1.2.2 to 1.4.2 and did not have this issue with 1.2.2. Tested it on the same device.

**Comment by wincod75** [comment]
@lbalmaceda Do you know if it's possible to change the "App Name" key that this alert points to? I have rebranded my app, changing the display name, but keeping the identifier. So it might be confusing if "AppName 1" wants to use Auth0, when everything is branded "AppName 2"

#258
