### ISSUE TITLE
Not working after upgrade to React Native 0.60.x

### ISSUE THREAD

**Issue by bneigher** [auth0/react-native-auth0#230]
### Description
I seem to be running into a runtime issue with the functionality of react-native-auth0 after upgrading from RN 0.59.9 to RN 0.60.3.  
This seems to only have an effect on the simulator.

Seems that there is an issue with handling the responses made after HTTP requests are made by this sdk. To be clear - I can see the requests being sent with the correct parameters, but the response preview doesn't show any data in chrome debugger, the promise resolves successfully, but there is an error:
`AuthError: unknown error`

After adding some debugging to the src, it looks like the http requests don't contain a json property?

![image](https://user-images.githubusercontent.com/4627728/61504710-379e8b00-a991-11e9-99e0-f7aed7895e3e.png)

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [-] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version
> 1.5.0
- React Native version
> 0.60.3
- iOS Setup
> *Simulator, iPhoneX*
- Android Setup
> Not tested yet (androidx support?)

### Reproduction
```
export const loginWithUserPass = async (username, password) => {
  console.log("loginWithUserPass");
  try {
    const res = await auth0instance.auth.passwordRealm({
      scope: "openid offline_access profile email",
      audience: Config.AUTH0_AUDIENCE,
      device: DeviceInfo.getUniqueID(),
      realm: Config.AUTH0_REALM,
      username,
      password
    });
    console.log("res", res);
    return res;
  } catch (err) {
    console.log(err);
  }
};
```

Again - this only affects the simulator apparently.
Anyone else seeing this?

**Comment by bneigher** [comment]
Seems that this code is throwing, and then the error is being muted.  The request is failing here:
https://github.com/auth0/react-native-auth0/blob/master/networking/index.js#L79-L88

With the error at .toJSON on the response:
`SyntaxError: Unexpected token o in JSON at position 1`

Has `fetch` changed lately or something?

**Comment by bneigher** [comment]
AH!  Looks like there is a new issue in react-native:
https://github.com/facebook/react-native/issues/25701
Looks like this solution works, perhaps it should be added to the auth0 source?
Adding `global.Blob = null` anywhere in your code fixes the problem

**Comment by lbalmaceda** [comment]
@bneigher it seems like a bug on the latests react-native version. What if you move to a previous patch? e.g. 0.6.0, 0.6.1 or 0.6.2. Is the issue still happening?

**Comment by bneigher** [comment]
Yep thats what I found.  Downgrading works, but I'm cool with the fix referenced in my comment above

**Comment by lbalmaceda** [comment]
👍I don't think we should be changing that from the SDK side. I don't even know if adding that today would break older React Native versions.. And since this SDK doesn't specify a react-native version, I think it's best to delegate that decision to the users. Probably the next RN patch fixes it.
Cheers
