### ISSUE TITLE
Apple Rejection for using this component

### ISSUE THREAD

**Issue by victoriafrench** [auth0/react-native-auth0#235]
Apple has rejected our app for using the safari method of authentication used in this library. Please advise.

## Guideline 4.0 - Design

We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

### Next Steps

To resolve this issue, please revise your app to enable users to sign in or register for an account in the app.

We recommend implementing the Safari View Controller API to display web content within your app. The Safari View Controller allows the display of a URL and inspection of the certificate from an embedded browser in an app so that customers can verify the webpage URL and SSL certificate to confirm they are entering their sign in credentials into a legitimate page.

### Resources

For additional information on the Safari View Controller API, please review the What's New in Safari webpage.

**Comment by Ingibjorg** [comment]
@victoriafrench I'm curious as to why you closed this issue. What was your solution?
