### ISSUE TITLE
RefreshToken not returned after auth0.auth.refreshToken()

### ISSUE THREAD

**Issue by hokasan** [auth0/react-native-auth0#236]
### Description

When I call refreshToken with a valid refreshToken I get this response:
```json
accessToken: "eyJ0eXAiOiJKV1Qi...6genf9y-zw"
expiresIn: 86400
idToken: "eyJ0eXAiOiJKV1QiLC...tS8dSQ"
scope: "openid profile email read:current_user update:current_user_metadata offline_access"
tokenType: "Bearer"
```

Should I not get my refreshToken in the response or am I suppose to store that between calls to refreshToken()?

### Prerequisites

* [x] Did you check the documentation? [Add a link]
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository?
* [x] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version 1.4.2
- React Native version 0.60.5

### Reproduction

Call `auth0.auth.refreshToken()`

**Comment by Ghost-in-a-Jar** [comment]
I was running into this issue as well and have been meaning to post something. While debugging I found that the refresh token was being returned in the hash (#) part of the url, while this react-native-auth0 lib is parsing for them from the query (?) in the url. I made this hackish change to get my project working: https://github.com/Ghost-in-a-Jar/react-native-auth0/pull/1/files
