### ISSUE TITLE
How can I get 'refresh token' in React Native?

### ISSUE THREAD

**Issue by a-jumping425** [auth0/react-native-auth0#245]
Hi,

Now I am trying to get 'refresh token' in React Native.
I've checked this document.
https://auth0.com/docs/tokens/refresh-token/current
It seems I can get 'refresh token' via only browser, not SDK. Is it right?
Please let me know.

Thank you.

**Comment by joshcanhelp** [comment]
@a-jumping425 - I'm not sure I'm totally clear on your question here but I'll take a stab at it. 

Refresh tokens need to be obtained and stored securely so they should never be obtained through the browser or stored in the browser. Native applications (like a React Native application) can obtain and store them securely. Requesting a refresh token is done by adding `offline_access` to the `scope` parameter [used when logging in](https://github.com/auth0/react-native-auth0#log-in). Once you have it stored, it can be used [like so](https://github.com/auth0/react-native-auth0#getting-new-access-token-with-refresh-token).

**Comment by borisKnox** [comment]
@a-jumping425 there? This is knox. Can we discuss about auth token in React Native?
I am very interested in your post.

**Comment by bunea** [comment]
@joshcanhelp I have the same problem. I can open a new issue if necessary.

It seems that auth0 is not returning the refresh token when using webauth. I followed the instructions in this repo's readme to the letter.

I call the sdk like so:
```js
        const auth0 = new Auth0({
            domain: 'mydomain',
            clientId: 'myclientid,
        });
        auth0.webAuth
            .authorize({
                scope: 'openid email offline_access',
                audience: 'guest_members_api',
            })
            .then(c => {
                console.log(c);
            })
            .catch(e => console.log(e));
```

and I get this logged as the response:

```json
{
  "accessToken": "...",
  "expiresIn": 86400,
  "idToken": "...",
  "scope": "openid email",
  "tokenType": "Bearer"
}
```

There's no refresh token there, and the `offline_access` scope disappeared.

**Comment by DarioVaccaro** [comment]
@bunea I was having the same issue, enabling this setting in the API on the Auth0 Dashboard fixed it.

https://github.com/auth0/react-native-auth0/issues/279#issuecomment-586506570

As well as setting the `Rotating Token Behavior` under the `Application Tokens` in my Application Settings

**Comment by BailyTroyer** [comment]
Just adding to @DarioVaccaro's response with a supplemental screenshot for anyone that runs into this issue.

Under Application Settings, the following toggle fixed it so `refreshToken(...)` returns a `refreshToken` in the response object. 

<img width="1144" alt="Screen Shot 2021-04-20 at 9 17 26 PM" src="https://user-images.githubusercontent.com/22754190/115482951-d66ab200-a21d-11eb-9798-1f3e58748809.png">

**Comment by sambeetsahu** [comment]
I have done that in the auth0 dashboard but still not able to get the refresh token 
auth0.webAuth
      .authorize({
        audience: config.API_BASE_URL,
        connection: connection,
        scope: 'openid profile email offline_access',
      })

**Comment by sambeetsahu** [comment]
> Just adding to @DarioVaccaro's response with a supplemental screenshot for anyone that runs into this issue.
> 
> Under Application Settings, the following toggle fixed it so `refreshToken(...)` returns a `refreshToken` in the response object.
> 
> <img alt="Screen Shot 2021-04-20 at 9 17 26 PM" width="1144" src="https://user-images.githubusercontent.com/22754190/115482951-d66ab200-a21d-11eb-9798-1f3e58748809.png">

can i get a working example in a git public repo … where i will change the credentials for auth0 and test if refresh token coming or not
