### ISSUE TITLE
Android user called the auth

### ISSUE THREAD

**Issue by heatherSnepenger** [auth0/react-native-auth0#247]
Hi all,

I know there's a few issues listed similar to this one, but they seemed to be closed out without a resolution.

My auth is working as expect on iOS, but when I run on Android, I get the following response:

`{error_description:` "User cancelled the Auth", error: `"a0.session.user_cancelled"}`

I am using react-navigation, but I need to...is there a way to combine both libraries?

**Comment by joshcanhelp** [comment]
Hi @heatherSnepenger. I see two similar issues in this repo, #120 and #83. I see a few possible solutions in those threads. Have you tried any of the fixes there? I'm not sure if we've got a better answer than what's been posted already, unfortunately.

**Comment by Girres** [comment]
I had a similar problem with Android.  How I fixed it?

1. I had checked https://github.com/renrizzolo/auth0-react-native-sample/blob/master/00-Login/android/app/build.gradle and I realize that one line in my android/app/build.grade was missing, so I've placed - implementation project(':react-native-auth0') - inside dependencies group, like this:

`
dependencies {
    implementation project(':react-native-auth0')
    implementation project(':react-native-screens')
    implementation project(':react-native-reanimated')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}
`

2. I validated permission in the AndroidManifest.xml, so I realize that 2 permission must be present in there:

`
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
`

3. android:launchMode must be included as an attribute of activity, like this:

`
 ........
........
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
        ........
        ........
`

Hope it helps.

**Comment by lbalmaceda** [comment]
This SDK requires `launchMode=singleTask`. As react-native-navigation requires the same, there shouldn't be any problem with combining both libraries. It seems someone was able to make it work, as pointed out in the first issue linked by Josh above. Closing this now
