### ISSUE TITLE
Can't get JWT: a0.state.invalid: Invalid state received in redirect url 

### ISSUE THREAD

**Issue by MichaelTamm** [auth0/react-native-auth0#250]
### Description

I try to get a JWT as access token by including `responseType: 'token'` in the parameters object given as first argument to the `webAuth.authorize(...)` call. Unfortunatelly this always fails with the Error `a0.state.invalid: Invalid state received in redirect url`

### Reproduction

```
    const auth0 = new Auth0({
        domain: '...',
        clientId: '...',
    });
    ...
    const credentials = await auth0.webAuth.authorize({
        responseType: 'token',
        audience: '...',
        scope: 'openid profile email',
    });
```

### Environment

- **Version of this library used:**
react-native-auth0 2.1.0

### Analysis

The problem is, that the returned `redirectUrl` has the form "...#access_token=...&state=..."

and because the access_token and the state are behind the '#' character, the call
```
    const query = url.parse(redirectUrl, true).query
```
in src/webauth/index.js line 82 returns an empty object.

**Comment by joshcanhelp** [comment]
@MichaelTamm - Sorry for the trouble here. I'll answer this in a general sense to hopefully get you unstuck (not 100% familiar with this platform). Also, thank you for the code samples, that's very helpful 👍 

I believe the default `responseType` for this library is `code`, which is exactly what you want it to be if you're requesting access tokens. You've got your `audience` in there, which is what tells Auth0 to issue an access token for a specific API. You may also want to add to the `scope` parameter, depending on how your API is built.

So, really, all you need to do is add the `audience` and you should be getting back the token you need. Give that a try and let us know if that worked or not.

**Comment by MichaelTamm** [comment]
You are right: When I specify the `audience` I get back an JWT.

Thank you.

**Comment by hstemplewski** [comment]
Hi, I have the same problem. Should it have worked out of the box?

```ts
    const auth0Client = new Auth0({
      domain: "...",
      clientId: "...", 
    }),
```

```ts
    try {
      const response = await auth0Client.webAuth.authorize(
        {
          scope: 'offline_access',
          audience: '...', // URL from API's in manage dashboard
        },
        { ephemeralSession: true },
      );
      console.log('🚀 response', response);
    } catch (error) {
      console.log('🚀 error', error);
    }
```

```
 LOG  🚀 error [a0.state.invalid: Invalid state received in redirect url]
```
