### ISSUE TITLE
[2.1.0] TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by Bardiamist** [auth0/react-native-auth0#251]
I have error `TypeError: undefined is not a function, js engine: hermes` after update from `2.0.0` to `2.1.0`. Only on Android and only if Debug is off.

Update: release apk also crash on start.

Minimum steps to reproduce:

1. `react-native init` (I tested on version 0.61.2 and 0.61.3 version)
2. Enable Hermes (one line change, see documentation)
3. `import 'react-native-auth0';`

**Comment by joshcanhelp** [comment]
@Bardiamist - Thanks for the report here and apologies for the trouble. Can you give us a bit more to go on here? Possibly sample code that's causing the issue or a line number where that error is coming from?

**Comment by Bardiamist** [comment]
Just error on start.
![](https://i.imgur.com/TgAT0cp.png)

But I can see what error in `jssrssign/lib/jssrssign.js` (thanks Reactotron)
![](https://i.imgur.com/ZBveZL5.png)

**Comment by export-mike** [comment]
@Bardiamist I've downgraded to 2.0.0 for hermes support.

**Comment by GuillaumeAmat** [comment]
For the record:

* `react-native-auth0@2.1.0` + Hermes = ❌
* `react-native-auth0@2.1.0` + Hermes + Debug mode = 👌

**Comment by export-mike** [comment]
hmmm @2.1.0 is not going to work either.

jsrsasign is a dependency

2.1.0
```
npm list jsrasign 
   ┬ react-native-auth0@2.1.0
  └── jsrsasign@8.0.12
```

2.0.0
```
 npm list jsrsasign
/Users/mike/projects/temp-app
└── (empty)
```

**Comment by cocojoe** [comment]
@Widcket can you take a look at this please

**Comment by Widcket** [comment]
Thanks everyone for the information. This issue is in our radar, and we’re currently evaluating options.

**Comment by ix42** [comment]
Having the same problem with 2.1.0. Only downgrading to 2.0.0 fixed it

**Comment by lbalmaceda** [comment]
@Bardiamist & all, I've put a PR that replaces jsrsasign. I've tested it and an Hermes enabled app works fine now. We'll be making a new release next week but in the meantime I'd love you have your feedback. 

You can try the branch code by installing the package this way:


```
yarn add https://github.com/auth0/react-native-auth0.git#temp-idtv-2
```

**Comment by Bardiamist** [comment]
I checked, that works for my application.

**Comment by keremcubuk** [comment]
> hmmm @2.1.0 is not going to work either.
> 
> jsrsasign is a dependency
> 
> 2.1.0
> 
> ```
> npm list jsrasign 
>    ┬ react-native-auth0@2.1.0
>   └── jsrsasign@8.0.12
> ```
> 
> 2.0.0
> 
> ```
>  npm list jsrsasign
> /Users/mike/projects/temp-app
> └── (empty)
> ```

Thanks a lot :) 
We removed jsrassign in our project and crash issue is fixed.

**Comment by Kumargaurav11998** [comment]
> That error occurs only if Hermes is enabled.
> 
> Minimum steps to reproduce:
> 
> 1. `react-native init` (I tested on version 0.61.2 and 0.61.3 version)
> 2. Enable Hermes ([one line change, see documentation](https://facebook.github.io/react-native/docs/hermes))
> 3. `import 'react-native-auth0';`
> 
> I see `jsrsasign` dependency was added in [this commit](https://github.com/auth0/react-native-auth0/commit/1bbd1dd8cd598330e104d301a34c436c69b242e4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) and this not works on Hemes.
> 
> Please fix it. Hermes is very good thing and will enabled by default in future.

where to `import 'react-native-auth0';`?

**Comment by Afaq503** [comment]
can you send vedio about this error sulation

**Comment by supersuryaansh** [comment]
Hi, the issue still persists for my application
