### ISSUE TITLE
No webview on iOS 13 / Xcode 11

### ISSUE THREAD

**Issue by Bogidon** [auth0/react-native-auth0#252]
The webview to log in through auth0 is no longer showing after migrating to iOS 13 / Xcode 11 / React Native 0.61.3. No errors being reported, simply the alert box `<Appname> Wants to Use "<login url>" to Sign In` is no longer popping up. Pod install works and I was able to build.

Anyone else seeing this?

**Comment by Bogidon** [comment]
Using app compiled with Xcode 10 on iOS 13.2 works fine. I think it's the new Xcode that's the issue

**Comment by heatherSnepenger** [comment]
I'm also seeing this on iOS 13, Xcode 11. Pod install didn't fix. I'm still looking for solution

**Comment by Bogidon** [comment]
It could have been something else I changed, but it's now working with Xcode 11.2.1

**Comment by cocojoe** [comment]
Glad you figured it out @Bogidon 

@Widcket just ran through a quick test of this following our quickstart https://auth0.com/docs/quickstart/native/react-native

There were no problems, tested with the following versions:

```
- React Native: 0.61.4
- react-native-auth0: 2.1.0
- Xcode: 11.2.1 (11B500)
- iOS: 13.2.3
```
