### ISSUE TITLE
Anyway we can hide browser which open while  auth0.webAuth.clearSession session

### ISSUE THREAD

**Issue by jariwalabhavesh** [auth0/react-native-auth0#253]
### Describe the problem you'd like to have solved

> Right now whenever you call the  auth0.webAuth.clearSession function in the app then the browser will be open for couple of seconds and close back(In ios only).

### Describe the ideal solution

> Any way we can avoid opening a browser while clearSession because while logout it looks weird that browser opens up and doesn't show something and close. I think it feels like a bad user experience. In android, it is not opening any browser while calling .clearSession method. Only opening in ios

**Comment by winseyli** [comment]
+1

**Comment by stigi** [comment]
For us the workaround was to just never clear the session, but to just clear your tokens and start new sessions with the `prompt=login` option. In our case we just wanted to clear the session so the user got the chance to start login from scratch.

**Comment by lbalmaceda** [comment]
That's following Apple guidelines, and prompt would depend on the iOS version. 
Closing as dupe of https://github.com/auth0/react-native-auth0/issues/226.
