### ISSUE TITLE
token exchange API used by Sign In With Apple is missing

### ISSUE THREAD

**Issue by linfan68** [auth0/react-native-auth0#254]
### Describe the problem you'd like to have solved

I need to add Sign In With Apple in my React Native app

### Describe the ideal solution

adding API: tokenExchange(withAppleAuthorizationCode  similar to the SWIFT client

## Alternatives and current work-arounds

call the client post function directly:

```ts
const auth: any = (auth0.auth as any)
const payload = {
  client_id: auth.clientId,
  grant_type: 'urn:ietf:params:oauth:grant-type:token-exchange',
  subject_token: credential.authorizationCode,
  subject_token_type: 'http://auth0.com/oauth/token-type/apple-authz-code',
  scope: 'openid profile offline_access',
}
const res = await auth.client.post('/oauth/token', payload)
```

**Comment by lbalmaceda** [comment]
@cocojoe @Widcket please, evaluate

**Comment by Widcket** [comment]
Hey @linfan68, thanks for raising this!

**Comment by himalayaahuja** [comment]
> ### Describe the problem you'd like to have solved
> I need to add Sign In With Apple in my React Native app
> 
> ### Describe the ideal solution
> adding API: tokenExchange(withAppleAuthorizationCode similar to the SWIFT client
> 
> ## Alternatives and current work-arounds
> call the client post function directly:
> 
> ```ts
> const auth: any = (auth0.auth as any)
> const payload = {
>   client_id: auth.clientId,
>   grant_type: 'urn:ietf:params:oauth:grant-type:token-exchange',
>   subject_token: credential.authorizationCode,
>   subject_token_type: 'http://auth0.com/oauth/token-type/apple-authz-code',
>   scope: 'openid profile offline_access',
> }
> const res = await auth.client.post('/oauth/token', payload)
> ```
> 
> ### Additional context

Is this correct and working ?
