### ISSUE TITLE
How to login as another user

### ISSUE THREAD

**Issue by ranshine** [auth0/react-native-auth0#255]
Using this plugin Azure auth login is working fine but in logout i am calling clearing session method it is opening empty browser and closing After that if i again do user interaction login it is not prompting any username field it is simply showing silent login page with previous user emailid.

**Comment by stigi** [comment]
There are two things you might be able to do:

- call `clearSession()` to properly logout
- pass `prompt=select_account` as an option in `authorize(...)`. More info here: https://community.auth0.com/t/how-to-logout-in-react-native/9046/2

**Comment by lbalmaceda** [comment]
What @stigi pointed out can help. You can also try passing the `federated` parameter to the `clearSession` call, although the behavior depends on each identity provider and is external to Auth0. See [this reference](https://github.com/auth0/react-native-auth0/blob/1bbd1dd8cd598330e104d301a34c436c69b242e4/src/webauth/index.js#L119)
