### ISSUE TITLE
How to update key on iOS

### ISSUE THREAD

**Issue by wincod75** [auth0/react-native-auth0#258]
When prompted "MyApp" Wants to use  "auth0.com" to Sign in...

How do i change "MyApp" from the Bundle Identifier to the "CFBundleDisplayName"

I have rebranded my app, thus the Display Name is different from the Bundle Identifier.

"react": "16.6.3",
"react-native": "0.59.10",
"react-native-auth0": "1.6.0"

**Comment by lbalmaceda** [comment]
This is an iOS or react-native question rather than this SDK's. I don't know the answer and will leave open for someone else to respond. But [SO](https://stackoverflow.com/questions/50448989/requirement-to-change-app-name-in-google-sign-in-alert) has some pointers.

**Comment by wincod75** [comment]
> But [SO](https://stackoverflow.com/questions/50448989/requirement-to-change-app-name-in-google-sign-in-alert) has some pointers.

Thanks @lbalmaceda, changing the $(PRODUCT_NAME) did the job.

**Comment by lbalmaceda** [comment]
Perfect! Thanks for sharing the result. Will close this now.
