### ISSUE TITLE
Un-openable Android App when using react-native-splash-screen

### ISSUE THREAD

**Issue by jack828** [auth0/react-native-auth0#259]
### Description

After adding react-native-auth0 to my application - and building a debug apk, I am unable to open the application, getting bounced to the app info screen.
This does not happen on development.

### Reproduction

Please take a look at https://github.com/jack828/TestApp - clone, install, then run `yarn showme` to build and install (over adb) the apk.
I have installed react-native-splash-screen, setup and confirmed working.
I have then added react-native-auth0, and you can see after building an app it will result in it not being openable, as in, it opens directly to the App Info dialogue.

I suspect this has something to do with the stuff this library needs adding to AndroidManifest.xml, but I am not very versed in android development! :)

### Environment

- **Version of this library used:** 2.1.0
- **Version of the platform or framework used, if applicable:** 0.61.5/0.61.4
- **Other relevant versions (language, server software, OS, browser):** OnePlus 7 Pro Android X
- **Other modules/plugins/libraries that might be involved:** react-native-splash-screen@3.2.0

Please let me know if you need anything else!

**Comment by jack828** [comment]
Update: I've been messing with the contents of `AndroidManifest.xml` and it works fine if I make this change:


```diff
         <intent-filter>
             <action android:name="android.intent.action.MAIN" />
             <category android:name="android.intent.category.LAUNCHER" />
             <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
-              <data
-                  android:host="dev-ve4qm42a.eu.auth0.com"
-                  android:pathPrefix="/android/${applicationId}/callback"
-                  android:scheme="${applicationId}" />
         </intent-filter>
       </activity>
       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
```

I assume this is just preventing the native code in this package from running, so this isn't really a fix. I'll see if I can't decipher the internals :laughing:

**Comment by lbalmaceda** [comment]
If the manifest is the issue, what we ask the dev to configure there is just the intent-filter that will capture the authentication result and change that activity's launchMode to singleTask. Maybe this last configuration is messing with it? I have no clue. Indeed that project looks abandoned. Found in some of the comments someone recommending this one, you might want to give it a try. Though we haven't tested it as well. https://github.com/zoontek/react-native-bootsplash

**Comment by VilleMiekkoja** [comment]
@lbalmaceda Hi, have you had the time to test auth0 with the bootsplash? I'm having issues with it on Android emulator: https://github.com/zoontek/react-native-bootsplash/discussions/530
