### ISSUE TITLE
getUser Bad HTTP authentication header format

### ISSUE THREAD

**Issue by jt-singularity** [auth0/react-native-auth0#260]
### Description
I am trying to make a call to getUser, based on the example provided, and am getting the following error returned to me:
"Bad Request: Bad HTTP authentication header format"
### Reproduction
- I am successfully logging in and receiving an accessToken in the following format: xxxx_xxxxxx-xxxxxxxxxxxxxxxx-xxx where the x's are alphanumeric characters.
- I am successfully making a call to getUserInfo using the accessToken from above and receive an object with email, emailVerified, name, nickname, picture, sub, and updatedAt. I am assuming sub is the user id and it has the following format: auth0|xxxxxxxxxxxxxxxxxxxxxxxx again where x's are alphanumeric characters.
- I am then using the accessToken and sub in the below code as token and userId respectively and have confirmed these variables are defined with the proper values:
```
export const getUser = (token, userId) => {
  auth0
    .users(token)
    .getUser({ id: userId })
    .then(console.log)
    .catch(console.error)
}
```
- This is where I am getting the bad request error.

### Environment

> Please provide the following:
Here are the dependencies from my package.json:
```
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-auth0": "^2.1.0",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-screens": "^2.0.0-alpha.16",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3"
```
Thanks in advance for your help and let me know what other information you might need.

**Comment by lbalmaceda** [comment]
The token is passed to the `Client` class [here](https://github.com/auth0/react-native-auth0/blob/fd890dd750cec6757832c5610ab747d1e401fe3b/src/networking/index.js#L24). You don't need to prepend anything (i.e. "bearer "), so if you were passing it as received it should be fine. 

However `auth0.users()` is calling the Auth0 Management API. Tokens calling this API must have the correct audience set, which is `https://YOUR_DOMAIN/api/v2/` (including the trailing slash). Of course, depending on the endpoint you'd like to consume, you'd also need that token to have the correct `scope` value. Check the [docs](https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id) for more information.

I'm curious, what details are you looking to obtain on this call that is not included on the userinfo response? You might find useful the "remarks" section on the [userinfo docs](https://auth0.com/docs/api/authentication#get-user-info).

**Comment by jt-singularity** [comment]
Thanks for the reply.

Can you please explain what you mean by audience set and scope values? I don't see either of these terms in the react-native-auth0 documentation.

I can certainly make calls directly to the API but I was hoping to use the react-native-auth0 library to wrap these calls. From what I can tell I am using the library correctly so please correct me if I am doing something wrong.

I was hoping to either get help using auth0.users.getUser if I am currently using it incorrectly or point out a bug. If I am supposed to make calls to the API for full user info I am confused about the purpose of users library feature.

**Comment by lbalmaceda** [comment]
@jt-singularity Sorry about the confusion and please let me start over. Is there any specific claim or property that you require or are expecting to see on that profile payload, that you weren't able to obtain with the `/userinfo` call? 

As of today, the contents of the ID Token received upon authentication should match the `/userinfo` response, provided the right OpenID connect scopes are being requested. Read about the valid OIDC scopes [here](https://auth0.com/docs/scopes/current/oidc-scopes). If you happen to need anything other than that, then those claims should be manually set to the ID token by using a [Rule](https://auth0.com/docs/rules#what-can-i-use-rules-for-). Custom claims like those inside the `user_metadata` property fall into this category.

**Comment by jt-singularity** [comment]
Thanks again for the reply but I still feel like we are having two separate conversations.

I have one primary question: does auth0.users.getUser work?

If the answer is yes then please help me understand what I am doing wrong because it is not working for me.

If the answer is no then there is a bug that should be addressed.

So far you seem to be directing me away from using auth0.users.getUser which I find confusing as it is a feature of this library. Does this mean that auth0.users.patchUser should also not be used?

**Comment by lbalmaceda** [comment]
@jt-singularity 
> does auth0.users.getUser work?

Yes. But, as pointed out on my first comment, in order to use it you must call the endpoint with a token that has the right **Audience** and **Scope** granted.


See how I add `read:current_user` which is a special scope that allows me to consume only the user profile for the user that is being signed on. And note how the audience value specifies that the token should be used to call the management v2 API. (Replace `lbalmaceda` with your tenant/account name.)

```js
 auth0.webAuth
            .authorize({
                scope: 'openid profile email read:current_user',
                audience: 'https://lbalmaceda.auth0.com/api/v2/'
            })
```

You can see that the access token received in the response was indeed granted those values. Use this site to check that https://jwt.io/.

![image](https://user-images.githubusercontent.com/3900123/71910046-ed33e500-314f-11ea-8b27-25c53d50c571.png)


Then take that access token, and the user id associated with that same token, and use it to call the management API.

```js
const myUserId = "sub value token from ID token or /userinfo call";
auth0.users(accessToken)
            .getUser({ id: myUserId })
```

>So far you seem to be directing me away from using auth0.users.getUser which I find confusing as it is a feature of this library.


I'm not moving you away from using this "Users client". But calling /userinfo or decoding the ID token sounds like a simpler approach, IMO.

**Comment by jt-singularity** [comment]
I just tried this out and it is working! Your example was very helpful, thanks. I think other users would benefit from this example if it was in the docs. Thanks again.

**Comment by lbalmaceda** [comment]
I'm glad it worked! The `current_user` scopes were removed from the Management API docs, I don't know why but I can check with the docs team. But one of the probable reasons this is not documented on this repo's readme is because as of today, it is much simpler to retrieve the user profile inside the ID token or calling `/userinfo` as explained above.
