### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by joaom182** [auth0/react-native-auth0#261]
### Description

I'm trying to perform passwordRealm authentication, by this way:

```
const auth0 = new Auth0({
  domain: AUTH0_DOMAIN,
  clientId: AUTH0_CLIENT_ID
});

let credentials = await auth0.auth
    .passwordRealm({
      username,
      password,
      realm: 'Username-Password-Authentication',
      scope: 'openid profile',
      audience: 'https://xxx-api.mydomain.com'
    });
```

My `AUTH0_CLIENT_ID` is a application of type `Native`, and has all the Allowed Callback URL's configured and Allowed Logout URL's.

And i get the with success the response with the credentials (id_token, access_token, refresh_token).

But when i call my API, with Authorization header `Bearer ID_TOKEN`, the server side returns 401.

My server side is a NodeJS application with Hapi Server, and i'm protecting my API with auth-strategies.

Example of server side auth strategy registration:
```
server
    .auth
    .strategy('auth0-extranet', 'jwt', {
      complete: true,
      key: jwksRsa.hapiJwt2Key({
        cache: true,
        rateLimit: true,
        jwksRequestsPerMinute: 5,
        jwksUri: `https://mydomain.auth0.com/.well-known/jwks.json`
      }),
      verifyOptions: {
        audience: 'https://xxx-api.mydomain.com',
        issuer: 'https://mydomain.auth0.com/',
        algorithms: ['RS256']
      },
      validateFunc: function (decodedToken, request, callback) {
         callback(null, true, decodedToken)
      }
    })
```

Why the auth step is returning a token, and the server side is rejecting the token?

### Environment

react-native-auth0: 1.6.0
react-native: 0.58.5
iOS 12.1

**Comment by lbalmaceda** [comment]
@joaom182 👋 ID tokens are to be consumed on the client-side (your iOS device in this case) and never leave it. If you plan to call an API you should use an access token instead. That said, any token validation issues that occur on the server-side are not the responsibility of this library. If the issue persists once you change the token you send on the header, please open an issue on the repo of the corresponding server-side middleware library you're using for authentication.

**Comment by joaom182** [comment]
@lbalmaceda Thanks for the explaining! The source of problem is because password realm auth, returns opaque access_token (that cannot be used to call API's, only for /userinfo endpoint), so i mistakenly used a id_token to try call API.
