### ISSUE TITLE
clearSession propmts security consent

### ISSUE THREAD

**Issue by OrangeChickens** [auth0/react-native-auth0#263]
### Description

Using clearsession to log out in React native but it prompts security consent. "xxx wants to use xxx to sign in".
Auth0 version: v.1.6.0.
Is there a way to remove it the consent?

**Comment by lbalmaceda** [comment]
@OrangeChickens 👋 That is expected and depends on the iOS version your app runs in. There are many issues already closed you can check, like https://github.com/auth0/react-native-auth0/issues/226.
