### ISSUE TITLE
[Android] API 'variant.getJavaCompile()' is obsolete

### ISSUE THREAD

**Issue by yohannpoli** [auth0/react-native-auth0#264]
### Description

Building app with Android Studio result in: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.

### Prerequisites

- [x] Did you check the documentation? [Add a link]
- [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
- [x] Are you reporting this to the correct repository?
- [ ] Are there any related or duplicate Issues or PRs for this issue?

### Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.57 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 21, 22, 23, 24, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

### Reproduction

Start from a fresh install, add the last version of react-native-auth0 (build with Android Studio while Invalidate cahes / Restart).

Error details is:

```
INFO: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: react-native-auth0
```

"javaCompile" is call in build.gradle line 109

```java
android.libraryVariants.all { variant ->
  def name = variant.name.capitalize()
  task "jar${name}"(type: Jar, dependsOn: variant.javaCompile) {
    from variant.javaCompile.destinationDir
  }
}
```

**Comment by lbalmaceda** [comment]
@yohannpoli I'm aware of this as it has also been a warning for many other android libraries throughout the year 2019.

I don't think the removal will affect any given library unless the main Gradle version used on **your** app (the one making use of these dependencies) gets bumped to the latest major where this code gets actually removed.

 I'll make a PR with the changes.
