### ISSUE TITLE
does not support custom domains

### ISSUE THREAD

**Issue by Bilal-S** [auth0/react-native-auth0#274]
The react-native authentication does not seem to support Auth0 custom domains.
Custom domains are used by many clients to authenticate users.

#### Description 

To support Auth0 Custom Domains the `audience` and `domain` elements need to be provided individually during authentication to auth0.

The `Options` will have to expand and add `audience` and carry through:

```
 export interface Options {
    domain: string;
    audience: string;
    clientId: string;
}
```

The audience should default to domain when not provided but should use the given audience when provided.

The changes will have to follow through to `passwordRealm` and other places that make an audience determination.

More information here:

https://auth0.com/docs/custom-domains/additional-configuration

and some caveats here:

https://community.auth0.com/t/unable-to-authorized-with-the-custom-domain/10020

**Comment by Widcket** [comment]
@lbalmaceda please evaluate

**Comment by lbalmaceda** [comment]
@Bilal-S An audience can be specified when authenticating via web auth, as seen [here](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L47). What method are you trying to call?

**Comment by Bilal-S** [comment]
@lancelaird thanks for the feedback.
We will review this week and will post back here.

**Comment by Bilal-S** [comment]
We were not able to get it working where we logged in to the custom domain successfully. We specified different values for audience and domain but the token generated was incorrect (always using the standard auth0 domain).
We decided to use a workaround solution so we can exchange data between app and mobile web page.
Thanks for your assistance.
We can close this ticket.

**Comment by Andriiklymiuk** [comment]
hi, seems that we have same issue.
What was a workaround @Bilal-S that you refer to?
Thanks in advance
