### ISSUE TITLE
Multiple authentication sources without Lock.

### ISSUE THREAD

**Issue by BrunoQuaresma** [auth0/react-native-auth0#28]
Hi, I can not found a doc about implement multiple auth sources like Facebook using the react-native or js lib. It is possible?

**Comment by dronsfield** [comment]
I asked the same thing a few months ago ( #17 ) and was told social login would be available as a feature around March, but it hasn't happened yet. I'm not optimistic about it ever happening tbh, there haven't been any new commits to master since last August.

**Comment by BrunoQuaresma** [comment]
😢

**Comment by hzalaz** [comment]
It will be in the last release
