### ISSUE TITLE
App Rejected By Apple due to Apple Sign In UI on Universal Login

### ISSUE THREAD

**Issue by Ingibjorg** [auth0/react-native-auth0#281]
### Description

Our React Native app that uses the `react-native-auth0` library with _Universal Login_ got rejected by Apple because the UI of the Apple Sign In button doesn’t meet their requirements. I expect the auth0 library to adhere to the Apple Sign In guidelines so my app is not rejected.

We used a customized version of the Universal Login page that was configured in the Auth0 dashboard and uses the default social authentication buttons. Please see screen shot:

I took a look at Auth0’s “new” universal login page and that one doesn’t follow Apple’s requirements on how the Sign In With Apple button either. See https://developer.apple.com/documentation/signinwithapplejs/incorporating_sign_in_with_apple_into_other_platforms and the attached screen shot

Please tell me how to proceed here. I tried customizing the button with your interface and wanted to replace it with an icon form Apple for the button but I’m unable to do so. Button: https://appleid.cdn-apple.com/appleid/button?height=44&width=300&border_radius=24&scale=4

**Rejection:**
> **Guideline 4.0 - Design**
> We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect:
> Your app uses Sign in with Apple as a login option but does not use Sign in with Apple button design, branding and/or user interface elements appropriately as described in the Sign in With Apple Human Interface Guidelines.
> **Next Steps**
> To resolve this issue, please revise your app to address all instances of this type of issue.
> **Resources**
> For information on improving and enhancing your app:
> - Watch the video The Ingredients of Great Apps to understand the basics of great apps.
> - Watch the video iPhone and iPad User Interface Design for practical design tips.
> - Watch iOS Development Videos to learn about programming and design tips.
> - Review the iOS Human Interface Guidelines and ensure that your app’s interface and design adhere to these guidelines.

### Reproduction

> Use react-native-auth0 with either the default universal login or the new universal login option and observer that both designs do not adhere to Apple's guidelines for the Sign In Button 

I submitted: 
![Auth0SignIn](https://user-images.githubusercontent.com/5962836/74594964-00f52580-4ff1-11ea-8bad-85cbcaac2104.png)

New universal login UI from Auth0:
![NewUniversalLogin](https://user-images.githubusercontent.com/5962836/74594969-07839d00-4ff1-11ea-9678-260b3a56179f.png)

### Environment

- **Version of this library used:**
    "react-native-auth0": "^2.3.0",
- **Other relevant versions (language, server software, OS, browser):**
    "react-native": "0.61.3",
- **Other modules/plugins/libraries that might be involved:**
Universal Login from Auth0

Linking community post for same issue: https://community.auth0.com/t/react-native-auth0-app-rejected-by-apple-due-to-apple-sign-in-ui-in-universal-login/37949

**Comment by Widcket** [comment]
Hi @Ingibjorg, we are aware of this issue and are working on a fix. I can’t provide an ETA, but will update as soon as possible.

**Comment by Ingibjorg** [comment]
I got an answer on my support ticket. The latest lock version has updated the UI to follow Apple’s guidelines. I just had to use v11.22.1 in my customized universal login page like so:
<script src="https://cdn.auth0.com/js/lock/11.22.1/lock.min.js"></script>
I will submit to Apple again and mark this as solved if there are no issues.

**Comment by Johnsgaard** [comment]
I am having this issue now. Using the new universal login and its getting rejected over and over again. Is there any way around this without having to create a custom login with Classic? @Widcket @Ingibjorg

**Comment by cocojoe** [comment]
@Johnsgaard there shouldn't be an issue with new universal login, can you reach out to our support team please who can help further with this. If you have feedback from Apple please include the details. Thanks

https://support.auth0.com/

**Comment by cocojoe** [comment]
I see you opened #310 as well, which does include more detail. I will raise internally. However, if you can raise a support ticket that would help. Thanks
