### ISSUE TITLE
Dynamic tenant URLs on Android 

### ISSUE THREAD

**Issue by 3rfan** [auth0/react-native-auth0#282]
### Description
This is more of a question than a bug/feature request. However, I would consider this an issue related to this library. 

As described in the Readme you have to specify the auth0 tenant domain in the `AndroidManifest.xml` like:

```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data
        android:host="YOUR_AUTH0_DOMAIN"
        android:pathPrefix="/android/${applicationId}/callback"
        android:scheme="${applicationId}" />
</intent-filter>
```

We are building a multi-tenant mobile app. Since each of our tenants have a different URL we need a way to dynamically change the value of `YOUR_AUTH0_DOMAIN`. According to the  [Android documentation](https://developer.android.com/guide/topics/manifest/data-element) it is possible to use wildcards inside `android:host` such as `*.mydomain.com`. I did't try this yet but it should work if all my tenants would use different subdomains under the same top-level-domain. This might be an ok solution for production environments but that would also mean that I have to pay for every other environment (dev and staging) to use the custom domain feature on auth0.

So my question is, if it is possible to build a multi tenant app on Android with this package?

### Prerequisites

- [x] Did you check the documentation? [Add a link]
- [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
- [x] Are you reporting this to the correct repository?
- [ ] Are there any related or duplicate Issues or PRs for this issue?

### Environment

Please provide the following:

- React Native Auth0 version
2.1.1
- React Native version
0.60.5

**Comment by lbalmaceda** [comment]
I haven't tried this but it should be possible. If you're targetting later Android versions you could use "Android App Links" and whitelist the domain so that it gets verified on install-time and the redirect happens smoothy. 

However, if you need or want to use a custom scheme, for the Android SDK we recently added a way to [customize the redirect URL](https://github.com/auth0/Auth0.Android/pull/268). If your intent-filter configuration does not work for you, feel free to reach out and we will evaluate adding that feature as well here.

**Comment by 3rfan** [comment]
Sorry, I don't have a lot of experience with Android development. I am not sure if the linked PR is related to my issue. Just want to make sure that we are not talking past each other. I am looking for a way to dynamically change the value of the `host` attribute. Afaik I can use wildcards inside the `host` value to handle URLs such as:
- foo.mydomain.com
- bar.mydomain.com
by writing: 
```
android:host="*.mydomain.com"
```
However, this would only work if I pay for every tenant to enable the custom domain feature. This would become pretty expensive if I also would do that for every environment (dev, staging, prod). Ideally I would like to have a custom domain (foo.mydomain.com) for my production environment which I can handle by using a wildcard as described above but use the free auth0 domain (e.g. `foo-develop.auth0.com`) for dev and staging.

What I didn't try yet is to just add another intent-filter with `*.auth0.com` and see if that works.

**Comment by lbalmaceda** [comment]
Yes, that's what I understood from your first comment as well 👍 

Regarding intent-filters, you can add as many as you want in the manifest, but you could also use wildcards in one as you mentioned to cover all your subdomains. What you need to understand from intent-filters is that they behave like "listeners" attached to a specific activity, and if a match occurs it will open up that activity. 

In your scenario you are looking to match all your subdomains so that they all open the same activity and you are able to handle the authentication. As long as they all make use of the same auth0 domain and client ID, the authentication will complete correctly. 

The PR that I linked shows what IMO is the same scenario but for the android native SDK. This user required us to open up the library to allow customizing the callback URL since the default one was tied to the auth0 domain and was auto-generated by the SDK. This SDK does the same, so if you run into the same situation and you'd need to customize it, we will have to make that change. I'll wait for you to confirm you're on that situation to move on 👍

**Comment by 3rfan** [comment]
Thank you for the elaborate answer. Since I don't want to create extra work for you I will try to use 2 intent-filters first and respond to you after I know if that is working or not.

> As long as they all make use of the same auth0 domain and client ID, the authentication will complete correctly.
I don't understand this part. The auth0 domain and client ID in our app is changing based on the tenant the user selects before trying to authenticate. Afaik just the domain should be an issue since it is also defined on the native side (in the AndroidManifest file). However the client ID is only used on the JS side and therefore changing it shouldn't be an issue, or am I wrong about that?

I have one more question. Do you think using intent-filters this way will become an issue:
```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data
        android:host="*.mydomain.com"
        android:pathPrefix="/android/${applicationId}/callback"
        android:scheme="${applicationId}" />
</intent-filter>
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data
        android:host="*.auth0.com"
        android:pathPrefix="/android/${applicationId}/callback"
        android:scheme="${applicationId}" />
</intent-filter>
```
One concern I have is that the intent-filter with `*.auth0.com` as host value will also be triggered when another app on the user's device is using the auth0 domain.

**Comment by lbalmaceda** [comment]
> The auth0 domain and client ID in our app is changing based on the tenant the user selects before trying to authenticate. Afaik just the domain should be an issue since it is also defined on the native side (in the AndroidManifest file). However the client ID is only used on the JS side and therefore changing it shouldn't be an issue, or am I wrong about that?

Sorry for poorly explaining it. That's correct, the client ID and domain are the only values that you will dynamically change, but the domain is the only one that needs to be "whitelisted" in the manifest using the intent-filter approach of your choosing (described on previous comments). Ignore that thing that I said and you quoted 👍.

> One concern I have is that the intent-filter with *.auth0.com as host value will also be triggered when another app on the user's device is using the auth0 domain.

The intent-filters you wrote above are correct. Your concern might be right only if the scheme and pathPrefix also match at least one intent-filter of the rest of the apps on the device. But given that this callback URL contains the application id (package name), I doubt that will happen as those are unique.

**Comment by 3rfan** [comment]
Oh, that makes sense. Thank you so much for your help and time. I will try this approach and close this issue if everything works as expected.

**Comment by 3rfan** [comment]
Everything works as expected now. Thank you again @lbalmaceda :)
Here is relevant part of my AndroidManifest.xml in case someone has the same use case:

```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustPan"
        android:launchMode="singleTask">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
            android:host="*.auth0.com"
            android:pathPrefix="/android/${applicationId}/callback"
            android:scheme="${applicationId}" />
    </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
            android:host="*.eu.auth0.com"
            android:pathPrefix="/android/${applicationId}/callback"
            android:scheme="${applicationId}" />
    </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
            android:host="*.tenant.example.com"
            android:pathPrefix="/android/${applicationId}/callback"
            android:scheme="${applicationId}" />
    </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
            android:host="app.example.com"
            android:pathPattern="/.*"
            android:scheme="https" />
    </intent-filter>
</activity>
```
