### ISSUE TITLE
Custom UI Login - App name missing on native Apple Sign In View

### ISSUE THREAD

**Issue by Ingibjorg** [auth0/react-native-auth0#286]
### Description
I've implemented a custom UI Login screen that uses auth0 to login to my app via different social platforms. When I log in with Apple by specifying the social connection like so

```javascript
auth0.webAuth.authorize({ 
  scope: 'openid profile email offline_access', 
  connection: 'apple',
  audience: '<myAuth0Audience>'
})
```

the app name shows up as "null" in the Apple Sign In dialogue (see screen shot):

![IMG_6888](https://user-images.githubusercontent.com/5962836/76256630-809b9c00-620d-11ea-916d-1b60cf2ca599.jpg)

I would expect the Apple Sign In dialogue to display the app name correctly and not say "null".

### Reproduction
1. Set up the auth0 React Native sample project https://github.com/auth0-samples/auth0-react-native-sample
2. Change the code for login to specify apple as a connection like so:
```javascript
auth0.webAuth.authorize({
  scope: 'openid profile email',
  connection: 'apple',
})
```
3. Run the app and try logging in with Apple
4. Observe that the message displays "null" as the app name and says: "Do you want to sign in to null with your Apple ID ""?" 

Note that I tested Auth0's Swift sample to verify my settings with Apple (https://github.com/auth0-samples/auth0-ios-swift-siwa-samples/tree/master/00-Login) and that one works as expected. The message says "Do you want to sign in to signinwithapple with your Apple ID "<myAppleId>"?"  So in that case, the sign in dialogue uses the Xcode project name.

### Environment

- **Version of this library used:** 2.3.0
- **Version of the platform or framework used, if applicable:** react-native v0.61.2
- **Other relevant versions (language, server software, OS, browser):** iOS

**Comment by Widcket** [comment]
Hi @Ingibjorg, thanks for the report. [We're aware](https://github.com/auth0/Lock.swift/issues/588) of this issue. This something on Apple's side, and we've brought it up with them. 
Will close this one for now, as there's nothing we can do. Please refer to the linked issue for updates.

**Comment by Ingibjorg** [comment]
Ok, @Widcket do you know if Apple will reject apps submitted like this to the AppStore?

**Comment by Widcket** [comment]
No, AFAIK.

**Comment by Ingibjorg** [comment]
Thank you!
