### ISSUE TITLE
Close the In-app Browser during Deep linking routing

### ISSUE THREAD

**Issue by lhuria94** [auth0/react-native-auth0#288]
We would like to understand if there is a possibility to close the in-app browser when we get redirected to the internal route via Universal deep linking.

Example Scenario
- Open App, Try to login (In-app browser opens)
- Go to your Email or anywhere you can get the link
- Click on the link, redirect to internal route
- The app keeps "In-app browser" open while the app in the background redirect to internal route

Anyway to close it programmatically when we like?

**Comment by lbalmaceda** [comment]
For Android we're using the Custom Tabs plugin. If a Custom Tabs compatible browser is installed, the tab is launched within the app context, and when redirects back it will be closed and not kept in the history. This is not the same case when no compatible browser is found and the URL needs to be opened on an "external" browser app. The SDK doesn't have control over external apps, and they don't expose an API for us to close it. Nothing you can do here other than recommend installing a compatible browser, like Chrome, Opera, Firefox, etc 👍 

I don't know for iOS, @Widcket can you fill that one, please?

**Comment by Widcket** [comment]
Hi @lhuria94, the plugin uses `ASWebAuthenticationSession` on iOS 12+ and `SFAuthenticationSession` on older versions of iOS. Both expose a public `cancel()` method that will dismiss the browser, but the plugin doesn't expose it.

**Comment by Widcket** [comment]
@lbalmaceda is there a way to manually dismiss a Custom Tab before the redirect?

**Comment by lbalmaceda** [comment]
> @lbalmaceda is there a way to programmatically dismiss a Custom Tab before the redirect?

If the activity that launched the CT is closed, it should close the CT as well. There's no public API for telling the CT to close programmatically.

**Comment by Widcket** [comment]
@lhuria94 currently there's no way to programmatically dismiss the in-app browser before the redirect.
