### ISSUE TITLE
Possibility of disabling login prompt

### ISSUE THREAD

**Issue by lhuria94** [auth0/react-native-auth0#289]
Thanks for the great library. It supports a ton of options and very useful.

I just wanted to check in if there is a possibility of disabling login prompt in all cases and take us directly to in-app browser when clicked which shows auth0 login page, as I understand it's not something Auth0 enforces but on the ios side.

![dea3fdaf61120e45f51028a205df8f1c jpg  640×1135 ](https://user-images.githubusercontent.com/10358379/77824479-fddd7100-7128-11ea-89c2-6e53e1cf5038.png)

**Comment by Widcket** [comment]
Hi @lhuria94, it's in our backlog. We plan on supporting `prefersEphemeralWebBrowserSession` on iOS 13+ with a fallback to `SFSafariViewController` on older versions of iOS. Keep in mind that disabling the popup will disable SSO.
