### ISSUE TITLE
logging out completely

### ISSUE THREAD

**Issue by sheprdinc** [auth0/react-native-auth0#29]
I'm using facebook login with Auth0... logging out works fine, except it's not a true log out... it's a partial log out where only the local session is removed from AsyncStorage, however, facebook continues to remember the user, which makes it impossible for a different facebook user to login on the same device, unless you ask your user to delete the app and re-install, which is not an acceptable thing to ask users to do, especially at scale. Is there a way to make the app not remember/store any facebook info, so that new users can login?

**Comment by luisrudge** [comment]
Are you sure you're using this library for that? This library doesn't support Facebook login.
