### ISSUE TITLE
Cannot pass user_metadata to auth.CreateUser()

### ISSUE THREAD

**Issue by kevinranks** [auth0/react-native-auth0#291]
### Description

I am trying to include `user_metadata` with the `createUser` method but it's not working. 

Referring to: https://github.com/auth0/react-native-auth0/blob/master/src/auth/index.js#L486

If I pass an object I receive the error: `invalid user_metadata.consentGiven type (only strings are allowed)`

If I pass a string I receive the error: `"invalid user_metadata type (expected object)"`.

### Reproduction

```
auth0.auth
  .createUser({
    email: 'info@auth0.com',
    username: 'username',
    password: 'password',
    connection: 'myconnection',
    metadata: {
        consentGiven: true
    }
  })
  .then(console.log)
  .catch(console.error);
```

OR

```
auth0.auth
  .createUser({
    email: 'info@auth0.com',
    username: 'username',
    password: 'password',
    connection: 'myconnection',
    metadata: JSON.stringify({
        consentGiven: true
    })
  })
  .then(console.log)
  .catch(console.error);
```

### Environment
- **Version of this library used:** 2.3.0
- **Version of the platform or framework used, if applicable:** React Native 0.61.5

**Comment by Widcket** [comment]
Hi @kevinranks, thanks for reaching out. The **values** must be strings, as per the [endpoint documentation](https://auth0.com/docs/api/authentication#signup):
> property values must be strings of no more than 500 characters.

So in your example that would be:
```javascript
auth0.auth
  .createUser({
    email: 'info@auth0.com',
    username: 'username',
    password: 'password',
    connection: 'myconnection',
    metadata: {
        consentGiven: 'true'
    }
  })
  .then(console.log)
  .catch(console.error);
```
