### ISSUE TITLE
Getting signin popup during logout

### ISSUE THREAD

**Issue by lhuria94** [auth0/react-native-auth0#294]
Hi, 

We are getting this popup during logout from the mobile app.
Our code is:
```
auth0.webAuth
      .clearSession({})
      .then(success => {
        Alert.alert('Logged out!');
        setAccessToken(null);
      })
      .catch(error => {
        console.log('Log out cancelled', error);
      });
```

Is there any way to avoid this situation?

**Comment by Widcket** [comment]
Hi @lhuria94, can you share a screenshot of the popup?

**Comment by mountainfirefly** [comment]
I am having the same issue, here is the screenshot @Widcket
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-17 at 15 15 46](https://user-images.githubusercontent.com/11595211/79556275-79926400-80be-11ea-8cbc-dae99f2934bf.png)

**Comment by mountainfirefly** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-17 at 15 15 46](https://user-images.githubusercontent.com/11595211/79556663-04735e80-80bf-11ea-8f38-f34dbb91686d.png)
I am having the same issue, here is the screenshot. @Widcket

**Comment by Widcket** [comment]
@mountainfirefly thanks for the screenshot. Support for disabling SSO (and thus avoiding that popup) is already in our backlog.

**Comment by lhuria94** [comment]
@Widcket But we need the SSO as well, even if we have the popup its the message which does not make sense for the. A signed in user has to sign in to logout.

**Comment by Widcket** [comment]
@lhuria94 both popup and message are displayed by `ASWebAuthenticationSession`, and unfortunately we do not have control over it. However if you'd like to force the user to login again, you can add the `prompt: "login"` param to the login call.

**Comment by pavelpashkovsky** [comment]
v2.3.1 still getting this popup. Is there any solution to avoid it except rolling back to old versions?

**Comment by paulosborne** [comment]
@Widcket 

> @lhuria94 both popup and message are displayed by `ASWebAuthenticationSession`, and unfortunately we do not have control over it. However if you'd like to force the user to login again, you can add the `prompt: "login"` param to the login call.

Is there a way to at least configure the message to say "sign-out" instead of "sign-in"?

**Comment by lhuria94** [comment]
Thanks @Widcket 

Add the `prompt: login` worked for me. But I see later it can come back to us in case of SSO functionality since we are not clearing the session and making the user to force login again. 

Showing "sign-out" would really help us here.

**Comment by paulosborne** [comment]
@Widcket 

Are you able to provide any clue how far down the backlog this is?

**Comment by Widcket** [comment]
Hi @paulosborne, unfortunately it's not possible to modify the popup message in any way. Last week we've implemented the ephemeral session option [for Auth0.swift](https://github.com/auth0/Auth0.swift/pull/388), but I can't provide an ETA for this SDK.

**Comment by paulosborne** [comment]
> Hi @paulosborne, unfortunately it's not possible to modify the popup message in any way. Last week we've implemented the ephemeral session option [for Auth0.swift](https://github.com/auth0/Auth0.swift/pull/388), but I can't provide an ETA for this SDK.

Thanks for the reply @Widcket 

Will ephemeral sessions remove the sign-out prompt the user when they are logging out?

**Comment by Widcket** [comment]
@paulosborne yes, and for the log in prompt as well. The behavior you get on iOS 13+ is similar to using `prompt: "login"` but without SSO, because it won't place a cookie in the system browser's shared cookie jar. Like using a browser in incognito mode.

**Comment by paulosborne** [comment]
> @paulosborne yes, and for the log in prompt as well.

Excellent :)

**Comment by Widcket** [comment]
@paulosborne the changes are up on the branch `feature/ephemeral-session-support`. Can you please try them out? You'll need to pass the `ephemeralSession` option, like this:
```js
        auth0.webAuth
            .authorize({
                scope: 'openid profile email'
            }, {
                ephemeralSession: true
            })
```

**Comment by paulosborne** [comment]
> @paulosborne the changes are up on the branch `feature/ephemeral-session-support`. Can you please try them out? You'll need to pass the `ephemeralSession` option, like this:
> 
> ```js
>         auth0.webAuth
>             .authorize({
>                 scope: 'openid profile email'
>             }, {
>                 ephemeralSession: true
>             })
> ```

@Widcket I checked out the branch and gave it a try and the login prompt no longer appeared - nice work. It does still appears on logout but i'm assuming this branch is a work-in-progress?

Looks like SSO has been disabled successfully as I was required to re-validate my google account every time I logged in.

Thanks again :)

**Comment by Widcket** [comment]
@paulosborne the thing is, you don't really need it for logout. There's no cookie to clear, so to perform 'logout' just remove the tokens from your app.

**Comment by paulosborne** [comment]
@Widcket 

Good to know, thanks for your help 😊

**Comment by blarzHernandez** [comment]
It worked if  we set both properties: prompt and ephemeralSession as following
```
auth0.webAuth.authorize(
      {
        scope: 'openid email profile',
        prompt: 'login',
      },
      { ephemeralSession: true }
    );
```

**Comment by aprilmintacpineda** [comment]
how come `prompt` is not included in https://auth0.github.io/react-native-auth0/WebAuth.html#.authorize

**Comment by ShepSims** [comment]
on versions above 2.16 ephemeral session no longer prevents the sign in popup.  Does anyone have solutions for getting rid of the popup on 3.1 or later?

**Comment by whiterabbitj** [comment]
this has been year and its still an issue it's ridiculous...
