### ISSUE TITLE
Overheat issue during auth0 login 

### ISSUE THREAD

**Issue by lhuria94** [auth0/react-native-auth0#297]
We are using this module and sample boilerplate (https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login) for auth0 login.

When we click on login, it opens an in-app browser with an auth0 login. If we keep it idle say 6-8 mins, it starts to overheat the phone.

Wanted to check if its anywhere related to this library or in general?

We ran the profiling using Detox Instruments/Xcode and CPU usage is 100% when left open.
<img width="1227" alt="IDMSLOGININTEGRATION" src="https://user-images.githubusercontent.com/10358379/80564685-24364b00-8a0c-11ea-8204-270540d7697d.png">

**Comment by Widcket** [comment]
Hi @lhuria94, thanks for the report. I ran the sample app on an iPhone 11 Pro, opened the browser window and left it there for 7 minutes. Got the following readings on Instruments:

<img width="1239" alt="Screen Shot 2020-04-30 at 23 58 50" src="https://user-images.githubusercontent.com/5055789/80778812-0407a880-8b40-11ea-82fb-60027ea6968f.png">

Doesn't seem to be related to the SDK.

**Comment by lhuria94** [comment]
Thanks, that helps. We will check whats the problem on our side.
