### ISSUE TITLE
New Universal Login Window cutoff in React Native on IPad

### ISSUE THREAD

**Issue by michaelbramwell** [auth0/react-native-auth0#298]
### Description

We are using react-native-auth0 lib 2.1.0 on React Native 0.61.4 and when launching the auth0 New Universal Login window on the IPad the login window is cutoff (tested on both my new 7th gen IPad and client’s older gen iPad Pro as used in the screenshot below).

There seems to be no way to control the window height via react-native-auth0 lib. Is there anyway to prevent this from being cutoff? Reverting to the classic auth0 login window is not an option as far as our client is concerned.

Note - Konrad from community team suggested I post this issue here https://community.auth0.com/t/new-universal-login-window-cutoff-in-react-native-on-ipad/40687 

### Reproduction

- 7 Gen iPad and iPad Pro

![bfcdc5ba17df256d67ad5d8d8e8b3daad7bc0d28](https://user-images.githubusercontent.com/1246485/80429398-916bb280-891e-11ea-8e8d-ef653fa1698c.jpeg)

### Environment

> Please provide the following:

- **Version of this library used: 2.1.0**
- **Version of the platform or framework used, if applicable: React Native 0.61.4**
- **Other relevant versions (language, server software, OS, browser): Auth0 New Universal Login**
- **Other modules/plugins/libraries that might be involved: N/A**

**Comment by Widcket** [comment]
Hi @michaelbramwell, the window is managed by [AuthenticationServices](https://developer.apple.com/documentation/authenticationservices), the underlying iOS API used by the SDK. Unfortunately it does not expose any way to control its presentation.
