### ISSUE TITLE
Is this library maintained or should we explore other options?

### ISSUE THREAD

**Issue by brobiden** [auth0/react-native-auth0#30]
@hzalaz Is this library being maintained and will pull requests be accepted in appropriate timeframes? Looking for a auth0 solution for react-native and trying to decide if we should create our own internal framework or contribute to this.

Things that are missing that we would add:

* Social
* Forgot Password

Additionally we would like add more features as they become available in our app.

**Comment by hzalaz** [comment]
It was not a high priority but we'll put more effort now that we finished our priority items.
