### ISSUE TITLE
Calling `webAuth.authorize` too quickly after resuming the app makes the returned Promise never resolve

### ISSUE THREAD

**Issue by 3rfan** [auth0/react-native-auth0#301]
### Description

My code is calling `webAuth.authorize` when a user comes into the app through a deeplink. On Android everything works as intended. However, on iOS the `webAuth.authorize` call never resolves and the confirmation alert never shows. 
I figured out that this happens because the `resolve` function in `NativeModules.A0Auth0.showUrl` in `agent.js` isn't called.

Delaying the call of `webAuth.authorize` by using a `setTimeout` of >500ms fixes the issue. After further investigation I have also discovered that this always happens when calling the function shorty after resuming the app (it does't happen when opening the app from a closed state). 

Calling `webAuth.authorize` by pressing a button works as intended.

### Environment
Happens 1/10 times in dev and 10/10 in production

- **Version of this library used:**
2.3.0
- **Version of the platform or framework used, if applicable:** 
react-native 0.60.5
- **Other relevant versions (language, server software, OS, browser):**
iPhone 8, iOS 13
- **Other modules/plugins/libraries that might be involved:**
react-navigation

**Comment by Widcket** [comment]
Hi @3rfan, when the deeplink url is handled the iOS app is not yet on the foreground. Setting a timeout just gives it time to finish loading. Instead you can use [AppState](https://reactnative.dev/docs/appstate) to detect when the app transitions to the foreground and call `webAuth.authorize`.

**Comment by mansnilssonQred** [comment]
@Widcket Would you say that using `AppState.currentState === 'active'` should be enough to make sure we can call `webAuth.authorize` and avoid the issue reported in this ticket?

I'm trying this now, and I'm unable to get this to work when opening the app (i.e. the app is not in the background). It seems that `AppState.currentState` is reported as `'active'` before it has "finished loading". I'm considering trying to find something else which indicates that the app is ready to use `webAuth.authorize`, but I'm not sure what that should be..

**Comment by Widcket** [comment]
Hi @mansnilssonQred,

According to `AppState`'s [documentation](https://reactnative.dev/docs/appstate), `active` means that the app is in the foreground:

<img width="824" alt="Screenshot 2023-02-12 at 19 11 14" src="https://user-images.githubusercontent.com/5055789/218340410-27c04874-9f94-4f42-95e1-2a17884bf0a9.png">

So you'd have to subscribe to `AppState` changes to find out when it becomes `active`:

<img width="516" alt="Screenshot 2023-02-12 at 19 11 44" src="https://user-images.githubusercontent.com/5055789/218340468-1f86899d-d908-49bb-830c-2174b5be5ab3.png">
