### ISSUE TITLE
How i can validate user after login

### ISSUE THREAD

**Issue by laxman-ram-iconnect** [auth0/react-native-auth0#304]
I am building an application and using this lib for authentication.
How could I make user silent_login once he signUp/loggedIn?

and how can I validate the user token session in react-native if it is valid or not so that I can send him for relogin?

**Comment by Widcket** [comment]
Hi @laxman-ram-iconnect, you can use a Refresh Token to get a new Access Token.

```js
auth0.auth
  .refreshToken({refreshToken: 'the user refresh_token'})
  .then(console.log) // new credentials object with a new Access Token
  .catch(console.error);
```

To get a Refresh Token, you need to use the `offline_access` scope on login. Like this:

```js
auth0.webAuth
  .authorize({scope: 'openid email profile offline_access'})
  .then(credentials => console.log(credentials))
  .catch(error => console.log(error));
```

The credentials object will contain a Refresh Token in addition to the Access Token. You need to store that Refresh Token somewhere safe, like the Keychain (in iOS), so you can retrieve it later when you want to use it to get a new Access Token.

That object will also contain a `expires_in` key with a TTL value that you can use to know when your Access Token is no longer good and you need to get a new one.

If in your app you're only using the ID Token and not the Access Token, then you can use the `exp`  claim contained in the ID Token for the same purpose. Note that the TTL of the Access Token (`expires_in`) !== expiration of the ID Token (`exp` claim).

Hope that answers your questions. If you have any further inquiries, please comment.
