### ISSUE TITLE
Support .useLegacyAuthentication

### ISSUE THREAD

**Issue by conorcussell** [auth0/react-native-auth0#306]
### Describe the problem you'd like to have solved

When authenticating a popup is displayed saying "APP wants to use DOMAIN to sign in" which the user must accept. This is confusing for our users because we have a single Auth0 domain but many apps with different names, as a result the user may not recognise the url we are authenticating them on as being related to the app they are using.

![Frame 1](https://user-images.githubusercontent.com/4960622/82543887-2774b080-9b4c-11ea-8b12-411a2fd35ffc.jpg)

This can be avoided in iOS when using the native Swift SDK because it provides the option to [`.useLegacyAuthentication`](https://github.com/auth0/Auth0.swift/blob/7f1e0a5113519a5aff56bb844729c85b6b743b82/Auth0/MobileWebAuth.swift#L64) which uses `SFSafariViewController` instead of `SFAuthenticationSessionn` and does not display the popup.

### Describe the ideal solution

The option `.useLegacyAuthentication` is available in `react-native-auth0` to prevent showing the popup when authenticating with Auth0

**Comment by Widcket** [comment]
Hi @conorcussell, this is in progress right now. Check out https://github.com/auth0/react-native-auth0/pull/305
