### ISSUE TITLE
response is not defined

### ISSUE THREAD

**Issue by viniciusmoret** [auth0/react-native-auth0#31]
I'm getting this error(1st image below), but when it returns, shows a message saying that response is not defined(2nd image below)

![image](https://cloud.githubusercontent.com/assets/25463445/25918813/1d7e8acc-35a3-11e7-9b6e-32096f263034.png)

![image](https://cloud.githubusercontent.com/assets/25463445/25918833/3138fe80-35a3-11e7-962c-d7d31029ae83.png)

**Comment by hzalaz** [comment]
Fixed and will be in latest version
