### ISSUE TITLE
iOS App rejected "Sign in with Apple" button not styled correctly

### ISSUE THREAD

**Issue by Johnsgaard** [auth0/react-native-auth0#310]
### Description

My app was rejected by the Apple store based on the button styling / design of the Auth0 buttons in the Universal login.

My app at the time of rejection was using the Classic with v 11.24.1 lock.js package & It was also rejected using the New Universal universal login form.

Here is the message from Apple:

```
Guideline 4.0 - Design
We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect:

Your app uses Sign in with Apple as a login option but does not use Sign in with Apple button design, branding and/or user interface elements appropriately as described in the Sign in With Apple Human Interface Guidelines 1.
Next Steps

To resolve this issue, please revise your app to address all instances of this type of issue.
```

Link given in the apple review:
https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/

### Reproduction

This is using a default setup of react-native-auth0 through `Expo`. I have added no customization other than the logo and branding colours (when you choose a universal login)

> - Screenshots
![IMG_7573](https://user-images.githubusercontent.com/11530155/83477873-922dc200-a451-11ea-908d-629e84d1dad3.jpg)

<img width="805" alt="Screen Shot 2020-06-01 at 9 51 05 PM" src="https://user-images.githubusercontent.com/11530155/83478076-2730bb00-a452-11ea-8d55-508008070302.png">

### Environment

- **Version of this library used:**
Classic Login with 11.24.1
New Universal login

- **Version of the platform or framework used, if applicable:**
Expo SDK: "36.0.0",
- **Other relevant versions (language, server software, OS, browser):**
React Native

**Comment by aaguiarz** [comment]
Hi @Johnsgaard 

One customer had a similar experience, and they pointed the Apple reviewer to this link https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/, specifically the "White with Outline" and "Creating a Custom Sign in with Apple Button", and they got it approved. The button complies with those rules.

Please let us know how that goes.

Thanks!

**Comment by Johnsgaard** [comment]
@aaguiarz @cocojoe 
I just got off the phone with Apple review and they have mentioned that the reason the rejection is happening is because of the grey border around the buttons. They say the app will not be accepted unless the grey border is changed too black.

**Comment by Johnsgaard** [comment]
<img width="1099" alt="Screen Shot 2020-06-03 at 7 50 34 AM" src="https://user-images.githubusercontent.com/11530155/83644839-f4c8b000-a56e-11ea-8619-1ca73991ad8a.png">

**Comment by Widcket** [comment]
Closing as the customer got their app approved, as per https://github.com/auth0/lock/issues/1877/
