### ISSUE TITLE
when is the next release (sorry)

### ISSUE THREAD

**Issue by conorcussell** [auth0/react-native-auth0#312]
Sorry to make an issue about this but we're relying on this https://github.com/auth0/react-native-auth0/pull/305 to be released in order to start hiding that popup in our app, when is the next release scheduled for?

**Comment by lbalmaceda** [comment]
@conorcussell I'm having some trouble bumping the dependencies before making this next release (#313). If this doesn't get shipped today it will ship the next week.

**Comment by conorcussell** [comment]
Brilliant, thanks!

**Comment by lbalmaceda** [comment]
@conorcussell 2.4.0 was just published
