### ISSUE TITLE
Mobile SSO with SAML clients

### ISSUE THREAD

**Issue by lhuria94** [auth0/react-native-auth0#319]
Hi, We are trying the following flow with mobile app idp login:

1. User opens the mobile application (React native)
2. Click on “Login to continue”
3. Auth0 Custom Template loads on the page with just one option i.e Email/User ID and a button called “Next”.
4. After User enters email e.g. abc@domain.com
5. Keep configuration in mobile app i.e domain to connection name linking
6. Use a existing SAML connection
7. Based on the email domain entered, we add a logic on auth0 template to redirect to particular connection URL: https://abc.auth0.com/authorize?client_id=client_id&response_type=token&connection=<connection_name>&redirect_uri=com.something
8. This will take the user to client idp login page in the same “In-app-browser”

What we need is:

9. After entering credentials on client-idp, it will redirect back to the mobile app closing the window automatically since we have the app callback in redirect_uri. 
Is there any way to make the user login?

**Comment by lbalmaceda** [comment]
👋 I've followed the steps 1-8 to what I think it's a regular authentication flow, with SSO on top of that provided by the custom page script you're using. What I don't understand is what's the problem you're facing in step 9. You seem to be receiving a callback in your application after the user has logged in into the IDP.

Can you clarify what is your expectation? and what parameters you receive in that callback?

**Comment by lbalmaceda** [comment]
@lhuria94 are you still having this issue?

**Comment by lhuria94** [comment]
Really sorry for the late response. It works fine now.
