### ISSUE TITLE
I can't set a scope when I'm using Password Grant `passwordRealm`

### ISSUE THREAD

**Issue by gabrielperales** [auth0/react-native-auth0#327]
### Description

I'm trying to update my user metadata, and in order to do that I need to login with the scope `update:current_user_metadata` but when I login with that scope it's not being set.

### Reproduction

```javascript
        const response = await auth0.auth.passwordRealm({
          username: email,
          password,
					realm: 'Username-Password-Authentication',
					scope : 'update:current_user_metadata openid',
        })
        console.log(response.scope) // outputs "openid profile email address phone"
```

### Environment

- **Version of this library used:** 2.5.0
- **Version of the platform or framework used, if applicable:** React Native 0.61.5

**Comment by gabrielperales** [comment]
Ok, I have tried to change the scope using this rule:

```
function (user, context, callback) {
    // change scope
  context.accessToken.scope = ['openid', 'profile', 'email', 'address', 'phone', 'update:current_user_metadata'];
  
  callback(null, user, context);
}
```

And it seems to work, but when I try to update the user metadata it returns an error: `Bad HTTP authentication header format`. 

This is the code I'm using to update my user:

```
        const response = await auth0
          .users(accessToken)
          .patchUser({
						id: user.sub,
						metadata: {
							name: 'Gabriel'
						}
					})
```

**Comment by lbalmaceda** [comment]
You shouldn't need to use any Auth0 rule to grant scopes. The issue is that the *current_user scopes belong to the Auth0 Management API and the access token you've requested does not have that audience. The audience value basically tells where the token should be used in. 

Try the snippet you shared originally but adding the `audience` for the API. It should be `https://YOUR_DOMAIN/api/v2/` (replacing your domain). 

Do read the limitations of using these scopes. Although this article says SPA, they also apply to a Native app. https://auth0.com/docs/tokens/management-api-access-tokens/get-management-api-tokens-for-single-page-applications

**Comment by gabrielperales** [comment]
It didn't work. 

When I created the auth0 instance I was already setting the domain:

```
const auth0 = new Auth0({
  domain: auth0Domain,
  clientId: auth0ClientId,
})
```

So this is my code after making the changes your suggest:

```
        const response = await auth0.auth.passwordRealm({
          username: email,
          password,
					realm: 'Username-Password-Authentication',
					scope : 'openid update:current_user_metadata',
					audience: `${auth0Domain}/api/v2`
        }
```

And when I try to login I'm getting this error message: `invalid audience specified for password grant exchange`.

**Comment by lbalmaceda** [comment]
@gabriel-miranda your code is missing the trailing slash. It should be `https://YOUR_DOMAIN/api/v2/` (replacing your domain).
I'd console log that value just in case to check the template replacement is outputting the right domain.

**Comment by gabrielperales** [comment]
@lbalmaceda I would have said I did it and it was not working either... but I just tried again and it worked.

Thank you very much :)
