### ISSUE TITLE
Refresh Token Rotation

### ISSUE THREAD

**Issue by heysailor** [auth0/react-native-auth0#328]
### Describe the problem you'd like to have solved

Thanks for [Refresh Token Rotation](https://auth0.com/docs/tokens/concepts/refresh-token-rotation) - it would be great to see it automatically handled in this library as in the React library.

### Describe the ideal solution

Ideally, once the user is authorised, this library would maintain access token validity with silent refresh token rotation.

## Alternatives and current work-arounds

An alternative would be to make the [Auth0 React library](https://auth0.com/docs/libraries/auth0-react) truly React universal by adding support for other localstorage-similar solutions including React Native's AsyncStorage.

**Comment by lbalmaceda** [comment]
It's a good feature addition, but I'm not sure what's the best way to securely store the tokens locally on this framework. 

Once that's decided, the solution would take into account the `expires_in` value received in the credentials exchange response, which belongs to the access token, and the decoded ID token's `exp` claim, analogous but for the ID token, and consider both values to determine when the first token expires. The next time the developer wants to retrieve these tokens, the clock will be checked and it would refresh the tokens if one of them has expired; updating the refresh token value if it has changed (due to refresh token rotation).

**Comment by heysailor** [comment]
The React Native docs [have a great discussion of storing secret info here](https://reactnative.dev/docs/security) - see the Secure Storage section about using the iOS Keychain and android services to store tokens.

In particular, they reference the npm module [react-native-sensitive-info](https://github.com/mCodex/react-native-sensitive-info).

The main gotcha, including with that module, appears to be that on Android data is stored unencrypted by default. [This branch](https://github.com/mCodex/react-native-sensitive-info/tree/keystore), also referred to by the RN docs, uses the Android Keystore instead, as an encrypted alternative solution.

**Comment by lbalmaceda** [comment]
@heysailor Thanks for the links and apologies for the delayed response. We would like to have a common helper class that works for both iOS and Android platforms in a similar and secure way, but we are limited by the requirements constraint.

Encrypted Shared Preferences is relatively new to Android. The version of the dependency that lowers the minimum Android API version required to 21 [has been on alpha for some months now](https://developer.android.com/jetpack/androidx/releases/security#version_110_2). For context, this SDK [requires Android API version 16](https://github.com/auth0/react-native-auth0/blob/master/android/build.gradle#L24) and above. 

In general, I trust simple Shared Preferences with mode "private" (I think that's React Native's async storage), as Android and its Unix user permissions system would take care of limiting access to your app's private files from other apps. The encryption of data before saving it (what the Encrypted Shared Preferences do) is a good addition to make it harder _but not impossible_ for an attacker to access that private data. 

To be clear, having root access is out of consideration here, as nothing can save your data in that scenario. e.g. with root, you could pull out the keys used to encrypt the data from the KeyStore and decrypt them from the Encrypted Shared Preferences.
