### ISSUE TITLE
Android: putting the app on background and tapping app's launch icon closes authentication webview

### ISSUE THREAD

**Issue by AlejandroCamposPhinx** [auth0/react-native-auth0#336]
### Description

On android: 
 1. Calling client.webAuth.authorize pops a webview/embedded browser.
 2. Putting the app on background and refocusing it keeps the webview/embedded browser open with same state.
 3. Putting the app on background and tapping the app's icon will bring the app from background but will cancel the webview/embedded browser. <- This is the issue 

This issue is highly critical as it means that users that go to their authenticator app to grab a TOTP code, will lose their current authentication progress if they tap on the app's launch icon.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.

1. Create a new app via create-react-app.
2. Install react-native-auth0 and do the setup on the readme.
3. Add a button that on press creates an auth0 client and calls webAuth.authorize
```
import Auth0 from 'react-native-auth0';

const auth0 = new Auth0({
  domain: 'AUTH0_DOMAIN',
  clientId: 'AUTH0_CLIENTID',
});

export const webLogin = () => {
  auth0.webAuth
    .authorize({
      scope: 'openid email profile',
    })
    .then((credentials) => console.log({credentials}))
    .catch((error) => console.log({error}));
};
```
4. Put the app on background and then focus it back, check that the webview stays correctly.
5. Put the app on background and then press the app's launch icon, you'll see that the webview will cancel and will throw the "user canceled" error.

### Environment

> Please provide the following:

- **Version of this library used:**
   - react-native-auth0 2.5.3 and also on 2.6.0
- **Version of the platform or framework used, if applicable:**
   - React native 0.63.2
- **Other relevant versions (language, server software, OS, browser):**
 Reproducible on Android 10
- **Other modules/plugins/libraries that might be involved:**
 I've been able to reproduce it in a barebones RN app.

**Comment by nlindroos** [comment]
To bypass this issue, a potential solution is to use
```xml
<activity
  android:launchMode="singleTop"
```
in _AndroidManifest.xml_. This might cause some other unwanted effects so be sure to test the app thoroughly.

**Comment by AlejandroCamposPhinx** [comment]
The solution we went with was creating a new launcher activity that solely launches React Native's activity. We then also had to compensate for different intents (App Store/Install manager/App Icon) causing different launcher behaviours.
