### ISSUE TITLE
Malformed Access Token received in response to loginWithSMS()

### ISSUE THREAD

**Issue by odedmagger** [auth0/react-native-auth0#349]
### Describe the problem

When logging in with the Passwordless SMS flow, the call to `auth::loginWithSMS()` returns a response that contains a Malformed access token.

The response seems to be a legal JSON with the expected fields (accessToken, idToken, expiresIn, etc).

**The accessToken is not a legal JWT**, but rather a string that's 32 characters longs, composed of lowercase letters, uppercase letters and a dash. Base64-decoding this string yields a 'gibberish' text.

Note #1: The idToken field's value is a legal JWT.

Note #2: Looking at the user on the user's page in Auth0 dashboard, the log in action seemed to have succeeded.

_Note #3: this also reproduces with the Passwordless Email code flow, when calling `auth::loginWithEmail()`. This report focuses on SMS for simplicity._

### What was the expected behavior?
The accessToken field of the response to a successful call to auth::loginWithSMS() should be a BASE64-encoded, well-formed JWT token.

### Reproduction

Pre
The set up is a React Native project, ran in an iOS 11.0 simulator.
The SMS Passwordless connection is configured to use Twilio.

- Step 1 - On our app, the user navigates to a log in page
- Step 2 - Call auth::passwordlessWithSMS() with a Twilio-verified, Israeli phone number.
- Step 3 - receive an SMS from Twilio with the 6-digits access code.
- Step 4 - call auth::loginWithSMS() , passing the phoneNumber from step 2 as well as the code received in step 3.

```
import Auth0, { LoginWithSMSParams, PasswordRealmResponse } from "react-native-auth0";

class AuthServiceModule {
  auth0 = new Auth0({
    domain: AUTH0_CONFIGS.domain,
    clientId: AUTH0_CONFIGS.clientId,
  });
  async loginWithSMS(params: LoginWithSMSParams) {
    const loginResponse = await this.auth0.auth.loginWithSMS(params);
    console.log(loginResponse.accessToken);
  }
// ...
}
```

### Environment

- **Version of this library used:** react-native-auth0 2.6.0
- **Any other relevant information you think would be useful:** Using Twilio as SMS gateway.

**Comment by odedmagger** [comment]
The access token was an opaque token; The fact that Passwordless login may return an opaque access token if audience is undefined was well-hidden in the documentation; Perhaps worthwhile to explicitly document this fact.

**Comment by thedarkcder** [comment]
https://github.com/auth0/react-native-auth0/blob/defc6f945c1fd6ba929eb583588ba5d3c43c775d/src/auth/__tests__/index.spec.js

for anybody who comes across this issue - please find the solution to adding the audience
