### ISSUE TITLE
Allow additional parameters for `createUser`

### ISSUE THREAD

**Issue by wyang36** [auth0/react-native-auth0#352]
### Describe the problem you'd like to have solved

We have a custom scripts that runs when a new account is created, and it requires `first_name` and `last_name`. However the `createUser` method currently only accepts `email`, `password`, `connection`, and `username`. I can make it a separate call directly to `/dbconnections/signup` endpoint but it's messy.

### Describe the ideal solution

Add the following (optional) parameter to the `createUser` method:
- `given_name`
- `family_name`
- `name`
- `nickname`
- `picture`

## Alternatives and current work-arounds

Direct call to `/dbconnections/signup` with the complete payload.

**Comment by lbalmaceda** [comment]
To me, this is a valid request. @wyang36 are you able to provide a PR with tests? The change should be located in these lines https://github.com/auth0/react-native-auth0/blob/master/src/auth/index.js#L481-L486

**Comment by DenisDov** [comment]
How about passing this fields in metadata?

**Comment by lbalmaceda** [comment]
@DenisDov yes that's a good suggestion. When these properties are not supported by the endpoint, they should go in the `user_metadata` object property. We already support passing that to the sign-up endpoint, see [this line](https://github.com/auth0/react-native-auth0/blob/master/src/auth/index.js#L486). As requested here, `first_name` and `last_name` are not directly supported by the sign-up endpoint, but there are variants of them that comply with the OIDC spec: `given_name` and `family_name` which can be sent in the request.

@wyang36 To clarify, what I said before is that we would accept a PR that adds support for the [remaining properties](https://auth0.com/docs/api/authentication#signup).
![image](https://user-images.githubusercontent.com/3900123/112827226-56be4d00-908e-11eb-9396-5f74fa82bb4d.png). 


Let me know if you're interested in contributing, I'm happy to guide you.

**Comment by ZentPeople** [comment]
Do we have support for adding first name in signup?
