### ISSUE TITLE
Web Auth login automatic re-login after first login.

### ISSUE THREAD

**Issue by aprilmintacpineda** [auth0/react-native-auth0#354]
### Describe the problem you'd like to have solved

When the user accessed the app for the first time, what I do is I display a screen on the user with a button that says login, when the user taps on that button, I call the `webAuth.authorize` like so:

```js
const credentials = await auth0.webAuth.authorize({
  scope: 'openid profile email read:current_user offline_access',
  connection,
  audience
});
```

When the user logs in again for the second time, we don't want to display the login screen with that login button anymore, we just want to automatically log the user is. First approach that I did is to call `auth0.webAuth.authorize` automatically when the app loads, but that didn't went well as it seems to not do anything on ios, but on android that seems to work well, we still see the web page popup but it then goes down and returns the response to us.

### Describe the ideal solution

like a method to automatically re-login without needing to open the login web page.

## Alternatives and current work-arounds

Not sure.

### Additional information, if any

References:

- https://github.com/auth0/react-native-auth0#web-authentication

Tags: auto login, webAuth.authorize automatic login, auto re-login

**Comment by Widcket** [comment]
Hi @aprilmintacpineda, you need to securely store the credentials returned on first login (including the refresh token), eg using the Keychain on iOS. Then, on app launch, you need to check the validity of the credentials by their expiration date (beware that the AT expiration timestamp may be different from the ID Token expiration timestamp; in that case, consider for this purpose the closest date). If they're still valid, then the user is still logged in, and you can omit the login page. If they've expired, then you need to [use the refresh token](https://github.com/auth0/react-native-auth0#getting-new-access-token-with-refresh-token) to get new credentials. If no credentials are stored, then the user is not logged in and you can show the login page.

Please check out [Auth0.swift's CredentialsManager](https://github.com/auth0/Auth0.swift/blob/master/Auth0/CredentialsManager.swift) for an example implementation of the above logic.

Does that help?

**Comment by aprilmintacpineda** [comment]
So do I need to parse the JWT tokens on the app side?

**Comment by Widcket** [comment]
You need to parse the JWT on your app. The SDK already validates it.

**Comment by aprilmintacpineda** [comment]
Thanks, @Widcket, do you think it's okay if I simply call `auth0.auth.refreshToken({ refreshToken })` every time?

**Comment by Widcket** [comment]
You'd be rotating your refresh token unnecessarily (if you have refresh token rotation activated), and you'd be having an extra network call on every launch that could be avoided if the credentials are fresh.

**Comment by aprilmintacpineda** [comment]
So you're saying that I need to decode both idToken and accessToken and check if one of those has already expired?

**Comment by Widcket** [comment]
The AT is not necessarily a JWT, for some cases it's just an opaque string, so it's not to be decoded. The response object contains a `expiresIn` property with a timestamp. That is the AT's expiration.
Then you should decode the ID Token (which is a JWT) and check the value of the `exp` claim.
So you need to check both expiration values.

**Comment by aprilmintacpineda** [comment]
Ahh, I see thank you for the help, that makes sense 🙇🏻

**Comment by aprilmintacpineda** [comment]
@Widcket the `expiresIn` is actually the number of seconds when the token will expires, but the credentials does not include the `issuedAt`, so do I have to manually generate and store the `issuedAt`?

**Comment by Widcket** [comment]
@aprilmintacpineda the issued at should be in the ID Token as the `iat` claim.

**Comment by aprilmintacpineda** [comment]
Thanks very much @Widcket
