### ISSUE TITLE
Face ID

### ISSUE THREAD

**Issue by DenisDov** [auth0/react-native-auth0#358]
### Face Id authentication

Is it possible to authenticate users with Apple Face ID?

**Comment by Widcket** [comment]
Hi @DenisDov, Universal Login [supports](https://auth0.com/blog/auth0-releasing-sign-in-with-apple-support-for-billions-of-ios-devices/) Sign in with Apple, which lets you authenticate with FaceID.

**Comment by lbalmaceda** [comment]
Closing this, if you have further questions feel free to chime back in.

**Comment by Widcket** [comment]
@DenisDov using FaceID as a MFA factor is now available: https://auth0.com/docs/mfa/configure-webauthn-device-biometrics-for-mfa#ios
