### ISSUE TITLE
Sso confirmation pop up when logout in ios > 13

### ISSUE THREAD

**Issue by idrisssakhi** [auth0/react-native-auth0#359]
### Describe the problem you'd like to have solved

When loging out in ios with version > 13, a confirmation pop up is displayed

### Describe the ideal solution

adding ```{ephemeralSession: true}``` for clearSessionn method

**Comment by Widcket** [comment]
Hi @idrisssakhi, you [do not need](https://github.com/auth0/react-native-auth0/issues/333#issuecomment-788308422) to call `clearSession` on iOS when you're using `ephemeralSession` on the login call.
I'll be adding clear documentation about this on the Readme.

**Comment by idrisssakhi** [comment]
Thank you, solved it as specified in that post.
