### ISSUE TITLE
Auth0 authorize stuck only on the very first try

### ISSUE THREAD

**Issue by ravi-poonia** [auth0/react-native-auth0#360]
On the very first install of the app, if I call the authorize function, it just gets stuck ..no error...no response. If I restart the app and do the same thing again it starts working.

### What was the expected behavior?

The authorize function should either use the logged-in session or popup the universal login view.

### Reproduction
Install a fresh app and call the authorize function 

Note:
I'm getting this log in Xcode :
[AuthenticationSession] Error: The provided scheme is not valid. A scheme must not include any special characters, such as ":" or "/"
I don't know if it's relevant to this problem or not, it's added in both cases

### Environment

RN: 0.64
xcode : 12.4
iphone 11 (simulator)
RN-auth0 : 2.7.0

**Comment by bkusch** [comment]
the same

**Comment by Widcket** [comment]
Hi @ravi-poonia, what config parameters are you passing to the SDK?

**Comment by Widcket** [comment]
Also, which Xcode version are you using?

**Comment by Widcket** [comment]
Just tried this out. Xcode 12.5 beta and RC no longer accept an entire URL for the `ASWebAuthenticationSession` scheme. We need to update the SDK.

**Comment by altibanna** [comment]
Same for me, XCode 12.5 has now been released and i'm hitting this bug today for the first time.

Is there any workaround ?
