### ISSUE TITLE
Blank Auth0.com login page on Android below 6.0 inch screen

### ISSUE THREAD

**Issue by sathishk2030** [auth0/react-native-auth0#365]
Auth0 login page showing blank, it is happening in screen size below 6.0 inch.

Steps to reproduce: 
1. Create new react native app and integrate react-native-auth0 into the app as instruction from site or use sample app from Auth0.com
2. run android app in Screen below 6.0 inch and login takes to blank Auth0.com page.

- When we load first time in 5.0 inch devices it is working but from second time on wards it is not working(blank page)

Note: Works perfectly in above or on 6.0 inch screen.

**Comment by lbalmaceda** [comment]
I believe this might not be an issue with the SDK but with your Universal Login Page configuration. You might want to check in the dashboard if you've done any customizations to it, and turn it off to use the default, in that case, to test if that fixes it. I'll wait for your reply.

**Comment by sathishk2030** [comment]
No change done in universal login. if it is universal login issue where to report.

**Comment by lbalmaceda** [comment]
You can contact support directly via the [support center](https://support.auth0.com/). The options of contact will vary depending on the type of Auth0 subscription you have.

**Comment by sathishk2030** [comment]
issue fixed on recent update
