### ISSUE TITLE
iOS 13+ ephemeralSession for logging out

### ISSUE THREAD

**Issue by JohnKim7** [auth0/react-native-auth0#368]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-auth0@2.8.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-auth0/src/webauth/index.js b/node_modules/react-native-auth0/src/webauth/index.js
index 4519503..49d5abd 100644
--- a/node_modules/react-native-auth0/src/webauth/index.js
+++ b/node_modules/react-native-auth0/src/webauth/index.js
@@ -158,6 +158,6 @@ export default class WebAuth {
     options.returnTo = callbackUri(domain, options.customScheme);
     options.federated = options.federated || false;
     const logoutUrl = client.logoutUrl(options);
-    return agent.show(logoutUrl, false, true);
+    return agent.show(logoutUrl, options.ephemeralSession || false, true);
   }
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by Widcket** [comment]
Hi @JohnKim7, you [do not need](https://github.com/auth0/react-native-auth0/issues/333#issuecomment-788308422) to call `clearSession` on iOS when you're using `ephemeralSession` on the login call.

**Comment by Widcket** [comment]
Just added some information to the Readme.

<img width="811" alt="Screen Shot 2021-04-30 at 11 35 56" src="https://user-images.githubusercontent.com/5055789/116710610-52949080-a9a8-11eb-884b-4f2e0c856139.png">

I will close this issue, please ping if you have any questions.
