### ISSUE TITLE
oauth/token endpoint incomplete

### ISSUE THREAD

**Issue by duhseekoh** [auth0/react-native-auth0#37]
We recently created a new auth0 account that no longer supports /oauth/ro. The alternative is to use oauth/token, but that endpoint is incomplete here. It doesn't allow one to set the `username`, `password`, `grant_type`. And it should not require a `verifier`, `redirect_uri`, or `code`

**Comment by hzalaz** [comment]
Its not incomplete but used for a different purpose for our recommended approach: using hosted login page with code grant + PKCE and then using the returned code with the "incomplete" method to get the users tokens, the last version handles all this by itself https://github.com/auth0/react-native-auth0#webauth. 

Also the method to use password realm to exchange user credentials for tokens is also available
