### ISSUE TITLE
Android: crash during social login with error Network request failed

### ISSUE THREAD

**Issue by vishnuchd** [auth0/react-native-auth0#379]
### Describe the problem
We have used the guide from the react-native-auth0 git repo as well as reviewed all documentation around this on auth0 website
https://github.com/auth0/react-native-auth0. 
https://auth0.com/docs/quickstart/native/react-native?download=true#integrate-auth0-in-your-application

You can see the below screenshots to give you an idea of our work, which seems to be all correct..
INTENT FILTER (we have the stage and prod variables in there)
ALLOWED CALLBACKS
AUTH0 AUTHENTICATION ( works well for ios and yes we are using the same code for both)

ERROR
It does seem to be giving a callback code in the callback url before it crashes the app.. 

Login still works fine on traditional email and password login on the android device, only social login is having issues on android.

![image](https://user-images.githubusercontent.com/9019494/120004914-f51a5080-bff4-11eb-9dd2-f2b900cd015b.png)

we tried to debug the sdk exactly here it crashes

![image (4)](https://user-images.githubusercontent.com/9019494/120005105-24c95880-bff5-11eb-8d0a-fe4b84b4873f.png)

Manifest file
![manifest](https://user-images.githubusercontent.com/9019494/120006002-14fe4400-bff6-11eb-9baa-4427ccd7c511.jpg)

method where it is Called

![image (1)](https://user-images.githubusercontent.com/9019494/120006103-2e06f500-bff6-11eb-8cd9-d7274cc8a2f6.png)
 
![image (3)](https://user-images.githubusercontent.com/9019494/120006150-3b23e400-bff6-11eb-8505-ffbf0b031d7c.png)

### Reproduction

- we are using  
 "react-native-auth0": "^2.8.3"
- "react-native": "^0.63.3"

**Comment by Mr-Fraser** [comment]
Looks like it is failing here C:\Users\codyf\Source\refrra\refrra_react\node_modules\react-native-auth0\src\networking\index.js

**Comment by lbalmaceda** [comment]
I'm sorry you are running into this issue. Let's keep the conversation in the linked issue above as this seems to be a duplicate and so more people are involved and can loop back therefeedback. If this isn't correct, please explain further how they differ and I'll reopen it.
