### ISSUE TITLE
Integrating auth0 SSO feature with react-native

### ISSUE THREAD

**Issue by AjithKumarRaviChandran** [auth0/react-native-auth0#383]
With my react-native application currently i am using 2factor to verify and store the user details, I want to integrate an additional feature to my app which supports auth0 with SSO(Single sign on), so I want auth0 to verify the user credential(using 2factor API)  and also supports the SSO feature with my app.

**Comment by Widcket** [comment]
Hi @AjithKumarRaviChandran, apologies for the late response. Could you please explain in more detail your use case? What exactly do you want the SDK to support and why?

**Comment by Widcket** [comment]
Closing this one for now, please ping if you'd prefer to reopen.
