### ISSUE TITLE
Support custom parameters in RefreshToken call

### ISSUE THREAD

**Issue by cpave3** [auth0/react-native-auth0#385]
### Describe the problem you'd like to have solved

We have a need to provide custom parameters to both the `authorize` and `refreshToken` calls so that we can use rules to add some derived data into our JWTs. `authorize` currently supports this by just adding the extra parameters to the call, but the `refreshToken` call seems to filter them out.

### Describe the ideal solution

Ideally, I can submit a PR to either add an extra argument to the refresh token call to allow custom parameters, or skip the argument and just make that the default behaviour if it won't break anything. The main thing here is that I'd like to check if this is an acceptable solution that would be likely to get merged in. If so, I am happy to make the change.

## Alternatives and current work-arounds

If we make the call manually, with the custom parameters included in the POST body, it works as desired

**Comment by cpave3** [comment]
@lbalmaceda I've made the change and submitted the PR. Please let me know if you need anything else from my side 🙏 Thank you.

**Comment by lbalmaceda** [comment]
Merged!
