### ISSUE TITLE
Android is crashing on startup without any error logs 

### ISSUE THREAD

**Issue by jasonkv** [auth0/react-native-auth0#388]
### Describe the problem

Our  android app  now crashes  right away  (on startup ) without any error logs. 

### What was the expected behavior?
We are just trying to add this package to our react native app  by following the README instructions but it crashes on android right away without any error logs. We have it mostly working as expected for ios.

### Reproduction

We installed the package with npm and edited our `android/app/build.gradle`
By inserting this :
```
    

android {
  // more code here we already had  lives between these two lines
  defaultConfig {
        applicationId 'OUR_APP_ID_HERE'

         // more code in this section that we already had, like the applicationId above
        manifestPlaceholders = [auth0Domain: "login.ourURL.com", auth0Scheme: "${applicationId}"]
    }
}

```

If we try to remove the manifestPlaceholders line from our gradle file we get this error and the app fails to build for android:

```
> Task :app:processDebugManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

713 actionable tasks: 2 executed, 711 up-to-date
/Users/jason/ourrepo/android/app/src/debug/AndroidManifest.xml Error:
	Attribute data@host at AndroidManifest.xml requires a placeholder substitution but no value for <auth0Domain> is provided.
/Users/jason/ourrepo/android/app/src/debug/AndroidManifest.xml Error:
	Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <auth0Scheme> is provided.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

```

Misc: We also tried uninstall the package `react-native-auth0` and leaving the manifestPlaceholders line in our build.gradle and that did not crash on startup up  just as a test.

We are just running:  npx react-native run-android

Thank you

### Environment

- **Version of this library used:**
-     "react-native-auth0": { "version": "2.9.0",
- **Which framework are you using, if applicable:**
- We are on expo sdk 41 but using a bare workflow.

- **Other modules/plugins/libraries that might be involved:**
- We were using expo-auth-session before 

- **Any other relevant information you think would be useful:**

Running on OSX 11.4
Andrioid version 10, pixel 4

**Comment by jasonkv** [comment]
I believe this is because we had expo-auth-session still installed and it was conflicting in a weird way for android only. 
Now we are seeing a new error but will make a new issue if we can't figure it out:

`[TypeError: Object is not a constructor (evaluating 'new Auth0({`

**Comment by Widcket** [comment]
Hi @jasonkv I just tested the SDK on a fresh Expo bare app, and I'm not able to reproduce the last error you mentioned:

https://user-images.githubusercontent.com/5055789/124192213-4e195080-da9b-11eb-9ede-cb86aa93ec64.mov

**Comment by jasonkv** [comment]
Hi @Widcket  which error in particular?

If it's the Auth0 constructor error, that was a mistake from importing the auth0 package in the wrong way by doing import * as auth0, instead of import from

But if you mean the original error, that one was due to having both `expo-auth-session` and react-native-auth0 installed

**Comment by Widcket** [comment]
@jasonkv the Auth0 constructor error.

**Comment by jasonkv** [comment]
Ah got it @Widcket . Thanks for looking into it but yeah that was just a mistake on my end trying to do a workaround that ended up causing that error later. That's why I had removed it from my comment after but sorry you still saw that and wasted your time.
