### ISSUE TITLE
“You may have pressed the back button” error fro auth0.webAuth.authorize

### ISSUE THREAD

**Issue by gitmazzio** [auth0/react-native-auth0#389]
Hi, 
the following error popup showing on iphone (6/7) on some of our customers when they try to login via webview:

`"Oops!, something went wrong. You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn’t find your session. Try logging in again from the application and if the problem persists, please contact the administrator"`

My signIn function is the following: 

`auth0.webAuth.authorize({
      scope: 'openid profile email offline_access',
      audience: Config.API_URL_AUDIENCE,
      prompt: 'login',
    })`

Do you have any ideas for how to fix the problem?

![IMAGE 2021-07-05 18_06_34](https://user-images.githubusercontent.com/29253427/124498025-060c6d80-ddbc-11eb-80d9-0c489f7fcf8b.png)

**Comment by Widcket** [comment]
Hi @gitmazzio, is a re-render causing `authorize()` to be called twice?
Also, please fill out the details from the issue template:

```
Version of this library used: 
Which framework are you using, if applicable: 
Other modules/plugins/libraries that might be involved: 
Any other relevant information you think would be useful:
```
In the future, please fill out the template in your issue description instead of removing it.

**Comment by gitmazzio** [comment]
Hi all,

we found that it was just our client's problem. He hadn't enabled cookies on the iPhone. 
I close the issue.

**Comment by Paul171** [comment]
Hi @Widcket , may I know if it's possible to disable cookies and able to login auth0 successfully? thanks
