### ISSUE TITLE
After webview, a weird popup is being shown.

### ISSUE THREAD

**Issue by ibtisamarif831** [auth0/react-native-auth0#391]
### Describe the problem

Recently, our application has started to show the selector dialogue after the user login or logout from the webview inside the application. The two redirections to the application are shown in the picture and only one of them successfully logins or logsout the person. This was not happening before it only started appearing 5-6 days before.
![unnamed](https://user-images.githubusercontent.com/34893993/125724808-815f7e8b-5328-4a8b-9cb8-af8e285ee0b8.jpg)

### What was the expected behavior?

Not seeing the dialogue and direct redirection to the application after the webview

### Environment

- **Version of this library used:2.6.0.**
- **Which framework are you using, if applicable:React Native**
- **This happens on emulator as well as physical devicess

**Comment by KrifaYounes** [comment]
Sale issues
What happening ?
