### ISSUE TITLE
How to send app_metadata in CreateUser

### ISSUE THREAD

**Issue by LouisJS** [auth0/react-native-auth0#398]
### Describe the problem you'd like to have solved

Hi, i'm using the method `createUser` to create my user, and i need to pass some metadata.
In the auth0 documentation, it is said that there is different type of metadata available

[Metadata Auth0](https://auth0.com/docs/users/metadata#metadata-types)

Here is an example of `createUser` implementation on web app.

```
email: 'email@email.com',
password: 'Password123',
connection: env.auth0_connection,
user_metadata: {
    firstname: 'Firstname',
},
app_metadata: {
    phoneNumber: '+336123456',
},
```

However, using auth0/react-native-auth0, it is said in the [documentation](https://auth0.github.io/react-native-auth0/Auth.html#.createUser) that only one `metadata` property is available, and will correspond to `user_metadata`.

My question is : How can i pass/add some `app_metadata` to my user ?
Is there a possibility to createUser then use patch ?

**Comment by lbalmaceda** [comment]
👋  the `app_metadata` field is intended to be a **read-only** field. You can set values there when you first create the user, or by using an Auth0 Rule, or by changing it manually in the User's dashboard, or with a request to API2 with an Access Token scoped with `update:users_app_metadata`.

If you need to set a value from a public client, such as a mobile app, you should be using the `user_metadata` field instead.

**Comment by Widcket** [comment]
@LouisJS I'll close this issue as your question has been answered. Please ping if you have further questions.
