### ISSUE TITLE
Some Android devices never resolve the webAuth.authorize promise

### ISSUE THREAD

**Issue by seltar** [auth0/react-native-auth0#399]
### Describe the problem

Some Android devices don't resolve the promise when executing webAuth.authorize. 
I fill out all the information during the login flow and get to the last page where I expect the browser to close and return the connection details, but instead it just hangs until I cancel. 

### What was the expected behavior?

The browser should close when login is verified and return the tokens in the promise. 

### Reproduction

Verifiable on a Samsung A-20e, Android version 11

### Environment

This is using "BankID on mobile" via a custom OIDC using Signicat (previously Idfy). 

- Latest version of react-native-auth0 2.9.0
- React-Native 0.63.3

**Comment by Widcket** [comment]
Hi @seltar, thanks for raising this. Version 2.9.0 introduced a breaking change to the Android configuration. Have you followed the migration steps at https://github.com/auth0/react-native-auth0#android?
Se also a sample diff of the necessary changes: https://github.com/auth0-samples/auth0-react-native-sample/commit/69f79c83ceed40f44b239bbd16e79ecaa70ef70a

**Comment by seltar** [comment]
Unfortunately I've had this problem with v 1.4.2 as well, which is why I tried upgrading to v 2.9.0. 
I've tested the steps you provided and it doesn't solve our issue unfortunately.

**Comment by seltar** [comment]
The problem seems to have solved itself (no code changes) using v1.4.2, so I'm suspecting there was a bug with the provider that they managed to fix. Either way, this is solved for now.
