### ISSUE TITLE
Middleware to re-issue tokens on failed http call

### ISSUE THREAD

**Issue by ssomnoremac** [auth0/react-native-auth0#4]
Based on [this post](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/) I'm trying to implement the sliding session. Is there some middleware that exists in RN-auth0 so that it can detect a failed call (expired access token) and do a reissue of tokens (using locally stored refresh token) automatically? Seems like a good feature to have if I'm understanding this properly.

**Comment by hzalaz** [comment]
This is something we are considering once we release a stable v1
