### ISSUE TITLE
React-native-auth0. “Open with..” Duplicate after upgrade to 2.9.0

### ISSUE THREAD

**Issue by ElihuJ** [auth0/react-native-auth0#401]
Hi,
I have upgraded my react-native-auth0 from 2.6.0 to 2.9.0
Ever since the upgrade when logging in, the app request confirmation on what app to use to continue (Only on Android)

![ss](https://user-images.githubusercontent.com/30395400/130553415-abf4e43c-69d9-4f73-876e-643b9b000231.jpeg)

I have added as per the documentation manifestPlaceholders = [auth0Domain: "myDomain.auth0.com", auth0Scheme: "${applicationId}"] to my build.gradle

App is not duplicated in the phone

Any help, much appreciated

**Comment by lewie9021** [comment]
I was also experiencing this issue. The fix for me (for now) was to remove Deep Linking configuration in the AndroidManifest.xml, [leaving a single `<intent-filter>` within the MainActivity](https://github.com/facebook/react-native/blob/main/template/android/app/src/main/AndroidManifest.xml#L19).

I'm interested to find how others have fixed this issue who require Deep Linking though.

**Comment by Widcket** [comment]
Hi @ElihuJ, thanks for raising this. Did you remove [this intent filter](https://github.com/auth0-samples/auth0-react-native-sample/commit/69f79c83ceed40f44b239bbd16e79ecaa70ef70a#diff-e0de684ab7a7be0085b0bf2990b399d0a60aa2391fb50d4b73fa589b68347f4aL23), as per the migration instructions?

**Comment by ElihuJ** [comment]
Correct @lewie9021 @Widcket once I removed the extra intent it worked fine, I was guided by the documentation given in npm, [https://www.npmjs.com/package/react-native-auth0#android] and I couldn't find where it mentions about removing the extra intent, maybe I just missed it

Thanks heaps for the help!

**Comment by antila3567** [comment]
> Hi @ElihuJ, thanks for raising this. Did you remove [this intent filter](https://github.com/auth0-samples/auth0-react-native-sample/commit/69f79c83ceed40f44b239bbd16e79ecaa70ef70a#diff-e0de684ab7a7be0085b0bf2990b399d0a60aa2391fb50d4b73fa589b68347f4aL23), as per the migration instructions?

Hi. I have the same problem. I removed intent filter and it doesn't help. I open that magic link from email and I cannot get data in my Linking listener, could you help , please ?
