### ISSUE TITLE
Android Build error using RN 0.65.1 with Gradle 7.0.2

### ISSUE THREAD

**Issue by Gra55h0pper** [auth0/react-native-auth0#403]
### Problem

After upgrading React-Native and Gradle to the latest & greatest available versions `gradlew bundleRelease` throws an error:

```
Build file '.../node_modules/react-native-auth0/android/build.gradle' line: 18

A problem occurred evaluating project ':react-native-auth0'.
> Plugin with id 'maven' not found.
```

### Reproduction

Both `gradlew clean` and `gradlew bundleRelease` will throw the above error.

### Workaround

Don't know yet but I will try downgrading Gradle to a version older than 7.0.0.

### Environment

React Native 0.65.1
react-native-auth0: 2.9.0
Gradle 7.0.2

**Comment by Gra55h0pper** [comment]
### Workaround

Downgrade Gradle. 
In Android Studio go to `File->Project Structure` and select: 
- Android Gradle Plugin Version: 4.2.2 
- Gradle Version: 6.7.1

This seems to make things work again.

**Comment by bneigher** [comment]
This is breaking releases for the current version of react-native (uses gradle 7)

**Comment by hamzaz9912** [comment]
i'm having the same issue 


> I'm having the same issue and moving the below did not solve the issue: Android Gradle Plugin Version: 4.2.2 Gradle Version: 6.7.1
go to MainActivity.java and remove ...   @Override
  protected String getMainComponentName() {
    return "AwesomeProject";
  }

**Comment by schoenbl** [comment]
> i'm having the same issue 
> 
> 
> 
> 
> 
> > I'm having the same issue and moving the below did not solve the issue: Android Gradle Plugin Version: 4.2.2 Gradle Version: 6.7.1
> 
> go to MainActivity.java and remove ...   @Override
> 
>   protected String getMainComponentName() {
> 
>     return "AwesomeProject";
> 
>   }

I don't recall exactly what I did, but I think I may have uninstalled the node module, built the app, and then installed the module again. And it worked, but it maybe different issues, and/or I can't remember how I solved it.

**Comment by poovamraj** [comment]
@hamzaz9912 Which version of the SDK are you using? If it is the latest, can you confirm which Gradle line is causing the issue. We currently have a fix in master for a similar issue in Gradle 7.0. Refer #446
