### ISSUE TITLE
`webAuth.authorize` hanging on iOS

### ISSUE THREAD

**Issue by lewie9021** [auth0/react-native-auth0#407]
### Describe the problem

`webAuth.authorize` sometimes hangs on iOS (only identified on iOS but Android could also be affected). I found a related issue [here](https://github.com/auth0/react-native-auth0/issues/301) and added an `AppState` check to ensure the app was `active`. However, I'm still able to cause the flow to hang on my iPhone 12 Pro even though `AppState.currentState` is `active` immediately before calling `webAuth.authorize`.

Digging into the source code I discovered it calls [`NativeModules.A0Auth0.showUrl`](https://github.com/auth0/react-native-auth0/blob/986e5fe7cb0a7a5449c445519aafaf8b4c037da4/src/webauth/agent.js#L22) which (thankfully) calls back, but returns `null` for both `error` and `redirectURL`. It seems the `if` branches don't cover the scenario as it's lacking a final `else` condition.

### What was the expected behavior?

I'd expect to receive an `Error` instance back with maybe the code of `a0.session.user_cancelled`? I'm not entirely sure what it means to have no `redirectURL`, especially with the `closeOnLoad` flag as I'm struggling to find documentation on it.

### Reproduction

- Step 1: Call `webAuth.authorize` via a button to open the browser widget.
- Step 2: Immediately background the app by swiping from the bottom before the widget has chance to open.
- Step 3: Observe that `AppState.currentState` is still `active` and `NativeModules.A0Auth0.showUrl` calls back with `null` for both `error` and `redirectURL`. As a result, the [`Promise`](https://github.com/auth0/react-native-auth0/blob/91c08f93d37e0dd2f2c41415ebb65f4cf720f1a4/src/webauth/agent.js#L13) that wraps `Agent.prototype.show` will never settle.

### Environment

- **Version of this library used:** 2.8.2 (code referenced in this issue is from `master` and identical to this version)
- **Which framework are you using, if applicable:** React Native (0.63.4)
- **Other modules/plugins/libraries that might be involved:** N/A
- **Any other relevant information you think would be useful:** N/A

**Comment by Widcket** [comment]
Hi @lewie9021, thanks for raising this. Can you please provide a video of the issue in our [sample app](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login)?

**Comment by Widcket** [comment]
@lewie9021 looks like you're not experiencing this issue anymore. I'll close this issue then. Please let me know if you'd prefer to reopen.
