### ISSUE TITLE
Warning for deprecated method "removeEventListener()" with "react-native" "0.65.1"

### ISSUE THREAD

**Issue by ripupo88** [auth0/react-native-auth0#410]
### Describe the problem

I get this warn when use auth0.webAuth.authorize( );

` _WARN  EventEmitter.removeListener('url', ...): Method has been deprecated. Please instead use 'remove()' on the subscription returned by 'EventEmitter.addListener'._`

### What was the expected behavior?

Do not get Warnings messages.

### Reproduction

- Step 1.. Use auth0.webAuth.authorize( ); to go Auth0 and login,
- Step 2.. Login in Auth0
- Step 3.. When back to the app, get the warn message.

### Environment

- **"react-native-auth0": "^2.10.0",**
- **React Native CLI:**
- **"react": "17.0.2",**
- **"react-native": "0.65.1",**

**Comment by lbalmaceda** [comment]
Thanks for the PR. I left a review there.

**Comment by breynolds-dev** [comment]
I'm trying to get these errors resolved to clean up warnings in my project - are there any updates on this PR?

**Comment by Widcket** [comment]
Hi @breynolds-dev, please feel free to raise a new PR. Please make sure the tests pass (that's the reason the existing PR is still open).
