### ISSUE TITLE
Update from 2.9.0 to 2.10.0 breaks login with refresh token

### ISSUE THREAD

**Issue by fcandi** [auth0/react-native-auth0#413]
### Describe the problem

Without any change, after upgrading to 2.10, login with refresh token do not work andy more, while gettig the user info i get "unauthorized: invalid credentials". After downgrading again, everything works again.

### What was the expected behavior?

There should be no breaking change

### Reproduction

I get the stored refresh token and try to resume like so:

```
  auth0.auth
                .refreshToken({
                    scope: 'openid profile email userinfo offline_access',
                    audience: CONFIG.AUTH0_API_AUDIENCE,
                    refreshToken: refreshToken.password,
                }, {ephemeralSession: true})
                .then(credentials => {
```

I then take the credentials to get the user infos:

```
 auth0.auth
            .userInfo({token: credentials.accessToken})
            .then(userinfo => {
                console.log("User Info",userinfo);
```

The Userinfo is failing in 2.10                

### Environment

- **Version of this library used:**
2.10.0

- **Which framework are you using, if applicable:**
React Native 0.64.2
IOS and Android

**Comment by Widcket** [comment]
Hi @fcandi, thanks for raising this.
Are you still experiencing this issue?

**Comment by fcandi** [comment]
hi @Widcket 

the problem is not solved!

I did not find the time to try it again. Now, its urgent because I need to update to v2.10.0 because of Gradle 7 Update.

When I try to get Userinfo after Creating a session with the refresh token, I get "unauthorized: invalid credentials" since v. 2.10 (and now in 2.11). The same is still working in production with 2.9!

What could this be?

Thanks,

Andreas
