### ISSUE TITLE
Unable to choose Google account login with iOS 15

### ISSUE THREAD

**Issue by andcal** [auth0/react-native-auth0#415]
### Describe the problem

On a device with iOS 15, when I select log in with Google I cannot choose an account if I have already been logged in before. Whereas with iOS 14.5 I can make this choice: use a previous account or add a new one.

I tested on both iOS versions with the same code and app configuration.

### What was the expected behavior?

I can choose between a previously registered Google account or add a new one to log in

### Reproduction

That is the way I make the Google login
```
    await auth0.webAuth.authorize({
      connection: 'google-oauth2',
      state: `${uuidv4()},google-oauth2`,
      scope: 'openid profile email picture offline_access',
      audience: AUTH_AUDIENCE,
    });
```

### Environment

**- react-native-auth0: 2.10.0**
**- RN: 0.65.1**

**Comment by andcal** [comment]
I solve it by adding ` prompt: 'select_account',` as an `authorize` param
```
 await auth0.webAuth.authorize({
      connection: 'google-oauth2',
      state: `${uuidv4()},google-oauth2`,
      scope: 'openid profile email picture offline_access',
      audience: AUTH_AUDIENCE,
      prompt: 'select_account',
    });
```

**Comment by sujeethkanuganti** [comment]
Saved me,

await authorize({scope: 'openid profile email offline_access',prompt: 'select_account'});
