### ISSUE TITLE
Logout not working

### ISSUE THREAD

**Issue by flashman2** [auth0/react-native-auth0#416]
### Describe the problem

Unable to LogOut user with clearSession
LogIn works well, however on LogOut a popup appears saying "Safari cannot open the page because the address is invalid".
This happens on both iOS and Android. Using console.log I was able to see that LogOur URL was correct and returns some callback. But Safari just can't handle this callback and get back to the application. The callback address for LogOut is same as callback for LogIn. But there is no "code" and "state" parameters in LogOut callback URL.
So callbacks looks like this:
com.toxon://some-thing.auth0.com/ios/com.Toxon/callback - for LogOut (not working)
com.toxon://some-thing.auth0.com/ios/com.Toxon/callback?code=xxxxx&state=yyyyy - for LogIn (works)

What may cause the problem?

### What was the expected behavior?

LogOut should work without error popup 

### Reproduction

LogIn:

auth0.webAuth
      .authorize({
        scope: 'openid profile email',
        audience: 'https://some.com',
      }).then((credentials) => {});
      
LogOut:

auth0.webAuth
      .clearSession({})
      .then((res) => {})
      .catch((error) => console.log(error));
  }; 

### Environment

- **Version of this library used:**  2.9.0
- **Which framework are you using, if applicable:** React Native 0.64.1
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:** iOS 14

![ScreenRecording](https://user-images.githubusercontent.com/981169/134550220-f688f86a-4d76-4798-8c90-653213637444.gif)

**Comment by flashman2** [comment]
looks similar to this one: https://github.com/auth0/react-native-auth0/issues/321

But, if problem is CustomScheme setup, then where is documentation for this? How this works and how to add CustomScheme?

**Comment by Widcket** [comment]
Hi @flashman2, please follow the setup instructions at https://github.com/auth0/react-native-auth0#configuration. I'll close this one as it answers your question, but please let me know if you'd prefer to reopen.

**Comment by flashman2** [comment]
Hi @Widcket 

I followed instructions for set up. It does not answer for my questions. Logout is not working - looks like Auth0 return wrong callback URL. This could be related to Bundle Id. It contain uppercase symbols and auto-converted to lowercase. Or maybe it is something else... Anyway, logout is not working.

**Comment by Widcket** [comment]
@flashman2 are you able to reproduce this using the sample app at https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login?

**Comment by lucasbento** [comment]
Exact same issue here and I'm using the [`auth0-react-native-sample`](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login) app.

Can you please reopen this @Widcket?

**Comment by arunzone** [comment]
I am also facing the same issue, I logout urls are configure as recommended by documentation. @Widcket  can you please repoen this issue, we want this to get it working. We ran out of options now

**Comment by lossen** [comment]
Faced the same issue! Any updates?

**Comment by AFoaad** [comment]
Did any one managed to solve this issue?
