### ISSUE TITLE
Support Biometrics for Android and iOS

### ISSUE THREAD

**Issue by vmurillo** [auth0/react-native-auth0#417]
### Describe the problem you'd like to have solved

Modern apps allow users to log in seamlessly using biometrics

### Describe the ideal solution

Universal Log in should support this

**Comment by Widcket** [comment]
Hi @vmurillo, thanks for raising this.
Using biometrics with Universal Login is supported as an MFA factor: https://auth0.com/docs/login/mfa/fido-authentication-with-webauthn#platform-authenticators- and https://auth0.com/docs/login/mfa/fido-authentication-with-webauthn/configure-webauthn-device-biometrics-for-mfa
Note that UL-related issues are beyond the scope of this SDK, so I'll close this issue.
