### ISSUE TITLE
Can not pass the parameter screen_hint: 'signup' on webAuth.authorize method?

### ISSUE THREAD

**Issue by softshipper** [auth0/react-native-auth0#418]
Hi all,

I would like to redirect the users to SIGN UP page when they press the SIGN UP button.  
Unfortunately, I can not pass the parameter `screen_hint` to `auth0.webAuth.authorize(...)` method. Regarding the type definition of [AuthorizeParams ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-auth0/index.d.ts#L201) it does not provide the parameter `screen_hint`.  

"@types/react-native-auth0": "^2.5.9"
"react-native-auth0": "^2.10.0"

Best regards,
Softshipper

**Comment by lbalmaceda** [comment]
@softshipper 👋  we do not maintain that package. You can create a PR in that [repository](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls) and add support to this parameter. Cheers.
