### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by therunbuddy** [auth0/react-native-auth0#419]
### Describe the problem you'd like to have solved

I want to be able to start the `Sign in with Google`  authentication flow directly from my app. Screenshot of example below:
![image](https://user-images.githubusercontent.com/77796515/135122856-2a5467b0-1615-46d1-8a36-8a09a84a172c.png)

At the moment in order to start this flow you first need to open up the universal login page using `auth0.webAuth.authorize()` and then click on the `Continue with Google` button on the browser. 

### Describe the ideal solution

The ideal solution would be to have method where you can start the social login flow directly from the app. e.g. `auth0.webAuth.authorizeSocial({connection: 'google'})`. Calling this API directly from the app would open up a browser and you would go through the normal oAuth 2 flow.

**Comment by lbalmaceda** [comment]
This is already supported. You should be able to achieve this with `auth0.webAuth.authorize()` passing the correct connection name, which you can pick from the auth0 dashboard (Authentication / Social).

e.x.
```js
auth0.webAuth.authorize({
  connection: "google-oauth2",
  scope: "openid profile email"
});
```

Cheers

**Comment by therunbuddy** [comment]
Ohh amazing. Maybe a section on the readme would be useful for this feature

Walter
________________________________

**Comment by lbalmaceda** [comment]
@therunbuddy Thanks for the suggestion! We prefer not to duplicate documentation, as we find often they get outdated and not kept in sync. 

That said, we do have generated docs that are sourced from the code doc block annotations on every release. [Here](https://auth0.github.io/react-native-auth0/WebAuth.html#.authorize) you can find the specific one for the web auth authorize method. 

Cheers.

**Comment by therunbuddy** [comment]
@lbalmaceda thanks for the above suggestion. I was able to get Google Social Login working, however, the `authorize()` API does not return a `refreshToken` on successful login with Google. Is this expected? If so do you have any suggestions on how to refresh the access token without asking the user to go through the login flow again? Ideally, I want to keep the user logged in on my application.

**Comment by therunbuddy** [comment]
Nevermind I managed to get the `refreshToken` by adding `offline_access` to scope parameter
