### ISSUE TITLE
Support for multiple Auth0 tenants

### ISSUE THREAD

**Issue by ptrowan** [auth0/react-native-auth0#421]
Before version 2.9, we were able to add support for multiple tenants (for example, we have a dev tenant and a prod tenant) by simply adding multiple `<data/>` tags to the intent filter, one for each auth0 domain we use.
With the updates in version 2.9, we can only specify one Auth0 domain. We can swap between Auth0 domains between doing production builds and dev builds, but in our use case, our team needs to be able to swap between dev & prod servers at runtime (which worked with multiple data tags).

Don't know enough about Android/Gradle to know the limitations of manifestPlaceholders, but it doesn't seem like having list-type placeholders that generate tags would be possible. 
Another solution would be to have option to specify the intent filter in the user's AndroidManifest, like how it was done pre-v2.9 (not sure if there's already a way to override the react-native-auth0's AndroidManifest)

Was able to get around this by adding multiple `<data>` tags to the intent filter inside of node_modules/react-native-auth0, and add corresponding manifestPlaceholders (e.g. auth0Domain_prod and auth0Domain_dev) but obviously this is not a real solution.

**Comment by xanderdeseyn** [comment]
This is completely blocking our team from upgrading as well.

**Comment by alessioemireni** [comment]
Same problem here. We have in production an App with open Domain and now we are blocked with the v2.9.0. Before we could set the `<intent-filter>` like below:
```
<intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                <!-- host is not necessary for multi domain -->
                    android:pathPrefix="/android/com.examplecallback"
                    android:scheme="com.example" />
            </intent-filter>
```
In the actual version of the library I try to remove the `auth0Domain` in the build.gradle but the app not compile.

Could be possible to set an empty `auth0Domain` in the next release, so that we will accept a multi domain?

**Comment by Widcket** [comment]
Hi @ptrowan, thanks for raising this.
I believe https://github.com/auth0/Auth0.Android/issues/333#issuecomment-686644124 will answer your question (the Android SDK also uses manifest placeholders and this question has come up in the past).

Please let me know if that helps.

**Comment by ptrowan** [comment]
@Widcket adding an activity with `tools:node="replace"` seemed to work! thanks!!
for the sake of writing out a solution on this thread, I added this to my AndroidManifest:
```
<activity android:name="com.auth0.react.RedirectActivity"
          tools:node="replace">
    <intent-filter android:autoVerify="true"
                   tools:targetApi="m">
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data android:host="domain1.auth0.com"
              android:pathPrefix="/android/${applicationId}/callback"
              android:scheme="${auth0Scheme}" />
        <data android:host="domain2.auth0.com"
              android:pathPrefix="/android/${applicationId}/callback"
              android:scheme="${auth0Scheme}" />
    </intent-filter>
</activity>
```
(which is identical to the `<activity/>` tag in the package manifest, with the exception of explicitly defining multiple domains and adding the `tools:node="replace"`)
and remember to add `xmlns:tools="http://schemas.android.com/tools"` to the topmost `<manifest/>` tag

**Comment by fragilehm** [comment]
@ptrowan thanks for sharing the solution, so android:launchMode="singleTask" from the main activity should be removed right? And no need to add manifestPlaceholders?

**Comment by Sumit2202** [comment]
> @ptrowan thanks for sharing the solution, so android:launchMode="singleTask" from the main activity should be removed right? And no need to add manifestPlaceholders? I am having a weird issue, after I signing the web view disappears (expected) but then the application restarts.

I am also facing this exact issue in Android where after signing in, the application is restarting, how did you end up resolving it?

**Comment by kimball-j** [comment]
> > @ptrowan thanks for sharing the solution, so android:launchMode="singleTask" from the main activity should be removed right? And no need to add manifestPlaceholders? I am having a weird issue, after I signing the web view disappears (expected) but then the application restarts.
> 
> I am also facing this exact issue in Android where after signing in, the application is restarting, how did you end up resolving it?

Deleting `tools:targetApi="m"` worked for me

**Comment by jnjdev42** [comment]
Now, auth0 documentation says you have to write this in your build.gradle :

manifestPlaceholders = [auth0Domain: "domain", auth0Scheme: "${applicationId}.auth0"]

But, this is totally dumb as you can't pass multiple domains??? Any solution?

**Comment by Inlustra** [comment]
For anyone else coming across this - and a caveat here is that I haven't gotten around to testing it. 
I've created an expo plugin so you don't need to go full bare-workflow. 

Usage:  
If you have an `app.json`, change that over to an `app.config.js`

```js
const withAuth0MultiTenancy = require("./withAuth0MultiTenancy");

module.exports = {
  expo: {
    name: "YourAppName",
    slug: "your-app-slug",
    android: {
      package: "com.example.app", // Replace with your app's package name
    },
    plugins: [
      [
        withAuth0MultiTenancy,
        [
          {
            host: "host1.com",
            pathPrefix: "/android/${applicationId}/callback",
            scheme: "mysheme",
          },
          {
            host: "host2.com",
            pathPrefix: "/android/${applicationId}/callback",
            scheme: "myscheme",
          },
        ],
      ],
    ],
  },
};
```


`withAuth0MultiTenancy.js`
```js
const { withAndroidManifest } = require("@expo/config-plugins");

/**
 * Adds a custom activity with intent filters to the AndroidManifest.xml.
 * @param {object} androidManifest - The parsed AndroidManifest.xml object.
 * @param {Array} filters - Array of objects containing host, pathPrefix, and scheme.
 * @returns {object} - The modified AndroidManifest.xml object.
 */
const addCustomActivity = (androidManifest, filters) => {
  const appNode = androidManifest.manifest.application[0];

  // Define the new activity with the provided filters
  const newActivity = {
    $: {
      "android:name": "com.auth0.react.RedirectActivity",
      "android:exported": "true",
      "tools:node": "replace",
    },
    "intent-filter": [
      {
        action: [
          {
            $: {
              "android:name": "android.intent.action.VIEW",
            },
          },
        ],
        category: [
          {
            $: {
              "android:name": "android.intent.category.DEFAULT",
            },
          },
          {
            $: {
              "android:name": "android.intent.category.BROWSABLE",
            },
          },
        ],
        data: filters.map((filter) => ({
          $: {
            "android:host": filter.host,
            "android:pathPrefix": filter.pathPrefix,
            "android:scheme": filter.scheme,
          },
        })),
      },
    ],
  };

  // Initialize activities array if it doesn't exist
  if (!appNode["activity"]) {
    appNode["activity"] = [];
  }

  // Find index of existing Auth0 redirect activity
  const existingActivityIndex = appNode["activity"].findIndex(
    (activity) => activity.$?.["android:name"] === "com.auth0.react.RedirectActivity"
  );

  // Replace if exists, otherwise add
  if (existingActivityIndex !== -1) {
    appNode["activity"][existingActivityIndex] = newActivity;
  } else {
    appNode["activity"].push(newActivity);
  }

  return androidManifest;
};

/**
 * Custom Expo Config Plugin to add an Auth0 Multi-Tenant Redirect Activity.
 * @param {object} config - The Expo configuration object.
 * @param {Array} filters - Array of objects containing host, pathPrefix, and scheme.
 * @returns {object} - The modified Expo configuration object.
 */
const withAuth0MultiTenancy = (config, { filters = [] }) => {
  return withAndroidManifest(config, (config) => {
    config.modResults = addCustomActivity(config.modResults, filters);
    return config;
  });
};

module.exports = withAuth0MultiTenancy;

```

**Comment by caolong0204** [comment]
> For anyone else coming across this. I've created an expo plugin so you don't need to go full bare-workflow. You can just use `expo prebuild`
> 
> Usage: If you have an `app.json`, change that over to an `app.config.js`
> 
> const withAuth0MultiTenancy = require("./withAuth0MultiTenancy");
> 
> module.exports = {
>   expo: {
>     name: "YourAppName",
>     slug: "your-app-slug",
>     android: {
>       package: "com.example.app", // Replace with your app's package name
>     },
>     plugins: [
>       [
>         withAuth0MultiTenancy,
>         {
>           flters: [
>             {
>               host: "host1.com",
>               pathPrefix: "/android/${applicationId}/callback",
>               scheme: "mysheme",
>             },
>             {
>               host: "host2.com",
>               pathPrefix: "/android/${applicationId}/callback",
>               scheme: "myscheme",
>             },
>           ]
>         },
>       ],
>     ],
>   },
> };
> `withAuth0MultiTenancy.js`
> 
> const { withAndroidManifest } = require("@expo/config-plugins");
> 
> /**
>  * Adds a custom activity with intent filters to the AndroidManifest.xml.
>  * @param {object} androidManifest - The parsed AndroidManifest.xml object.
>  * @param {Array} filters - Array of objects containing host, pathPrefix, and scheme.
>  * @returns {object} - The modified AndroidManifest.xml object.
>  */
> const addCustomActivity = (androidManifest, filters) => {
>   const appNode = androidManifest.manifest.application[0];
> 
>   // Define the new activity with the provided filters
>   const newActivity = {
>     $: {
>       "android:name": "com.auth0.react.RedirectActivity",
>       "android:exported": "true",
>       "tools:node": "replace",
>     },
>     "intent-filter": [
>       {
>         action: [
>           {
>             $: {
>               "android:name": "android.intent.action.VIEW",
>             },
>           },
>         ],
>         category: [
>           {
>             $: {
>               "android:name": "android.intent.category.DEFAULT",
>             },
>           },
>           {
>             $: {
>               "android:name": "android.intent.category.BROWSABLE",
>             },
>           },
>         ],
>         data: filters.map((filter) => ({
>           $: {
>             "android:host": filter.host,
>             "android:pathPrefix": filter.pathPrefix,
>             "android:scheme": filter.scheme,
>           },
>         })),
>       },
>     ],
>   };
> 
>   // Initialize activities array if it doesn't exist
>   if (!appNode["activity"]) {
>     appNode["activity"] = [];
>   }
> 
>   // Find index of existing Auth0 redirect activity
>   const existingActivityIndex = appNode["activity"].findIndex(
>     (activity) => activity.$?.["android:name"] === "com.auth0.react.RedirectActivity"
>   );
> 
>   // Replace if exists, otherwise add
>   if (existingActivityIndex !== -1) {
>     appNode["activity"][existingActivityIndex] = newActivity;
>   } else {
>     appNode["activity"].push(newActivity);
>   }
> 
>   return androidManifest;
> };
> 
> /**
>  * Custom Expo Config Plugin to add an Auth0 Multi-Tenant Redirect Activity.
>  * @param {object} config - The Expo configuration object.
>  * @param {Array} filters - Array of objects containing host, pathPrefix, and scheme.
>  * @returns {object} - The modified Expo configuration object.
>  */
> const withAuth0MultiTenancy = (config, { filters = [] }) => {
>   return withAndroidManifest(config, (config) => {
>     config.modResults = addCustomActivity(config.modResults, filters);
>     return config;
>   });
> };
> 
> module.exports = withAuth0MultiTenancy;

How can I use your approach in bare RN project

**Comment by adammcarth** [comment]
@caolong0204 @jnjdev42 Supporting multiple tenants has been made possible again (in a barebones RN project) if you are able to upgrade your Auth0 SDK to Version 4. iOS requires no changes after following the setup instructions (since you no longer need to add your domain config in XCode), and you can refer to my answer here to get Android working: https://github.com/auth0/react-native-auth0/issues/747#issuecomment-2439196254
