### ISSUE TITLE
Support for react-native-windows

### ISSUE THREAD

**Issue by Deltaxel** [auth0/react-native-auth0#432]
### Describe the problem you'd like to have solved

`react-native-auth0` does not work when targeting Windows platform with `react-native-windows`.
The `authorize` method keeps failing with the following message: 
```log
Error: Missing NativeModule. React Native versions 0.60 and up perform auto-linking. Please see https://github.com/react-native-community/cli/blob/master/docs/autolinking.md.
```
Since I use react-native 0.66.0, we can assume that it is not a linking issue but the native module for windows not existing.

### Describe the ideal solution

Ideally, a native module for windows would be created. 

## Alternatives and current work-arounds

I do not know of any alternative, but one would be welcome.

**Comment by Widcket** [comment]
Hi @Deltaxel, thanks for raising this.
This is something that has come up in the past (https://github.com/auth0/react-native-auth0/issues/335). Unfortunately, we still do not have plans to support React Native on Windows with this SDK, which is focused on mobile (iOS & Android).

cc @kevlil83

**Comment by Deltaxel** [comment]
Hi @Widcket,

Thank you for your answer. I read the related posts you shared.
Although I understand the reason for the reject of the windows platform, it is for sure an issue for any project that support more than just windows. Especially when using libraries that depend on auth0. The integration gap and flow alignment represent a lot of work for each individual project with no clear alternative solution.

Since there are already users proposing pull request for windows support. Why not make windows support community based?
Or, add the windows support on JS side only and expect the project to come up with it's own native module. You could then refer to one of the PR which tried to introduce them.

What would be the issues in supporting any of those scenarios?

cc @kevlil83
