### ISSUE TITLE
Change auth0Domain at runtime on Android

### ISSUE THREAD

**Issue by zgordon02** [auth0/react-native-auth0#433]
### Describe the problem you'd like to have solved
This is an issue only in Android, iOS is fine

We have an environment selection screen when our app starts. For each environment we have a different `auth0Domain`. In iOS I have everything working great.

In iOS, we can simply pass the `auth0Domain` when the client is created. On Android, it appears that the required manifest placeholder overrides whatever is passed to the JS client. `manifestPlaceholders = [auth0Domain: "our.domain", auth0Scheme: "our.scheme"]
`

I'm not sure if I am missing something or if there is a workaround I am unaware of, but I would like to set the `auth0Domain` at runtime

### Describe the ideal solution

manifestPlaceholders are not required on android in favor of configuration passed to the JS client

**Comment by Widcket** [comment]
Hi @zgordon02, thanks for raising this.
Please refer to https://github.com/auth0/react-native-auth0/issues/421#issuecomment-964700004, as this has come up in the past.

**Comment by zgordon02** [comment]
Thanks @Widcket. Is there something in the docs I missed? If not, I would suggest highlighting this in the setup docs explaining why this behavior exists. Thanks again!
