### ISSUE TITLE
Anyway we can close the auth0.webAuth.authorize popup?

### ISSUE THREAD

**Issue by aprilmintacpineda** [auth0/react-native-auth0#435]
### Describe the problem you'd like to have solved

We need a way to programmatically close the popup that opens when we call `auth0.webAuth.authorize`, maybe something like `auth0.webAuth.close`. We do this in relation to deep linking.

### Describe the ideal solution

We can call a function like `auth0.webAuth.close` to close the popup when needed.

## Alternatives and current work-arounds

Haven't found any,

**Comment by Widcket** [comment]
Hi @aprilmintacpineda, thanks for raising this.

The SDK has no control whatsoever over that popup. It cannot be closed programmatically, and its contents cannot be changed. It's displayed (and managed) by `ASWebAthenticationSession`, the underlying Apple API used by the SDK.
See https://github.com/auth0/react-native-auth0#disable-single-sign-on-ios-13-only for more information
