### ISSUE TITLE
webAuth({ prompt: 'signup' }) doesn't work as expected

### ISSUE THREAD

**Issue by IbrahimSaberi** [auth0/react-native-auth0#437]
### Describe the problem

The `prompt` option seems to be ignored when callng `...webAuth.authorize({ prompt: 'SOME_PROMPT' })`

### What was the expected behavior?

I expected prompts as outlined [here](https://auth0.com/docs/brand-and-customize/text-customization-new-universal-login/prompt-common) to result in the proper webauth screens being pulled up. I've tried `signup`, `signup-password`, `login-password`.

### Reproduction

I'm not sure if I'm using these fields correctly or if I'm missing some other critical information; I'm currently calling `authorize` as the following:

``` typescript
export const signIn = (method: 'Google' | 'Facebook' | 'Apple' | 'Email', create?: boolean) => {
  const SOCIAL_MAP = {
    Apple: 'apple',
    Google: 'google-oauth2',
    Facebook: 'facebook'
  };

  const currentUserAndCredential: Credentials = await auth0.webAuth.authorize({
      scope: 'openid profile email offline_access',
      connection: method && method !== 'Email' ? SOCIAL_MAP[method] : undefined,
      prompt: create && method !== 'Google' ? 'signup-password' : 'login'
  });
}
```

I've also tried omitting different keys and different scopes as well to no avail. Totally considering that I'm calling this the wrong way, but I've peeked both through the source and through documentation and I'm not sure what exactly I'm doing wrong here.

I've looked at the documentation and don't see a `prompt` field there, but it IS included in the TS definitions. Is this just a carry-over from the regular JS library or is it used for other things (e.g. the one I know of is the `select_account` prompt when forcing `google-oauth2` connections to show the account selection screen).

### Environment

- **Version of this library used:** 2.10.0
- **Which framework are you using, if applicable:** RN 0.63.3
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by IbrahimSaberi** [comment]
Ok, turns out you can pass the parameter `screen_hint: 'signup'` and this will do the job, though the `screen_hint` parameter is not in the TS definition files. Is doing this not advised for some reason, or does this parameter just need to be added still? Thanks in advance!

**Comment by IbrahimSaberi** [comment]
Scratch that, just realized y'all don't currently maintain your TS definitions. I don't see this param however in the [actual jsdoc for the authorize method](https://github.com/auth0/react-native-auth0/blob/965ef8150001e940d1e26c768893e347f71d518a/src/webauth/index.js#L51), so original question still stands. Is using the `screen_hint` param ok/ safe or will this potentially cause unwanted behavior?

**Comment by Widcket** [comment]
Hi @IbrahimSaberi, thanks for raising this. This SDK allows passing arbitrary parameters that are added to the call to `/authorize`, so we don't keep a whitelist of parameters (beyond validating the required ones).
That's why you won't find `screen_hint: 'signup'` in the jsdoc, but it's totally fine to pass it.

**Comment by IbrahimSaberi** [comment]
Thanks for the clarification!

**Comment by gax97** [comment]
I am still experiencing a problem here. Even when I pass `screen_hint: 'signup'` it goes to the login page(iOS). Does anyone have a same problem?

**Comment by Widcket** [comment]
Hi @gax97, the `screen_hint: 'signup'` parameter only works for the new Universal Login Experience, not the classic experience. Are you using the new Universal Login Experience?

**Comment by gax97** [comment]
@Widcket I am not sure TBH, how can I check that?

**Comment by gax97** [comment]
You were right, it only works with Universal Login Experience. Thanks for clarifying.
