### ISSUE TITLE
How to delete user by auth0 management api

### ISSUE THREAD

**Issue by VilleMiekkoja** [auth0/react-native-auth0#454]
After users login to auth0, their information is stored on the auth0 side. Apple review will soon require that user data should be able to delete through app itself. Can we delete auth0 side user data using this library? I saw no methods indicating that in the repo so far.

**Comment by Widcket** [comment]
Hi @VilleMiekkoja, thanks for raising this.

To delete a user, you'll need to expose an endpoint in your backend that makes a request to the Management API. You can then call your endpoint from the mobile app, using the Access Token.

**Comment by Widcket** [comment]
@VilleMiekkoja, I'll close this issue as I believe the above answers your question. Please let me know if you'd prefer to reopen.
