### ISSUE TITLE
Setting auth0domain at runtime

### ISSUE THREAD

**Issue by gax97** [auth0/react-native-auth0#458]
Would it be possible to set the auth0domain at runtime? Right now it looks like this is possible only for iOS. On android, auth0domain is used in the manifest file.

This is useful for situations where you want to retrieve your auth0 config from the backend.

**Comment by poovamraj** [comment]
Hi @gax97, It should be currently possible by using `customScheme` and you can override the RedirectActivity if you don't need want to hardcode your domain. You can follow the steps in this section to achieve this -https://github.com/auth0/react-native-auth0#android

Please reopen this ticket if you have any further doubts regarding this.
