### ISSUE TITLE
No callback after webauth authentification.

### ISSUE THREAD

**Issue by alexandrzavalii** [auth0/react-native-auth0#46]
```
const auth0 = new Auth0('alexandr.auth0.com')
.webAuth('asdasdfssafasf')
.authorize({connection: 'linkedin'})
.then(credentials => console.log('credentials', credentials))
    .catch(error => console.log('ERROR', error));
```
I successfully sign in with webauth using my linkedin account, but I dont recieve any callback or tokens back.

**Comment by hzalaz** [comment]
Please check https://github.com/auth0/react-native-auth0#configuration and make sure you have configured properly also the API changed a bit when we released the stable version (info in the README).

Basically you need to make sure you linked the library with `react-native link` and configured the app linking as stated in the README so the communication between browser and app works for WebAuth
