### ISSUE TITLE
On iOS the promise returned by webauth.authorize can sometimes never complete.

### ISSUE THREAD

**Issue by marcelmeulemans** [auth0/react-native-auth0#460]
### Describe the problem

The promise returned by `webAuth.authorize()` will consistently not complete when called immediately again after pressing cancel on the iOS permission popup (i.e. "App" want to use...). The issue is related to this `if` statement:

https://github.com/auth0/react-native-auth0/blob/master/src/webauth/agent.js#L44

In reproduction situation both `redirectURL` and `closeOnLoad` are both falsy and the urlHandler will never be called so the promise being returned never completes.

### What was the expected behavior?

The promise should always resolve or reject.

### Reproduction

I can across this behaviour by automatically calling authorize again when the authorize promise rejects. Something like:

```
try {
  await webAuth.authorize();
} catch (_) {
  setTimeout(() => webAuth.authorize(), 0);
}
```
1. Call webAuth.authorize()
2. Press cancel when iOS ask permission for "App" Wants to use "auth0.com" to sign in.
3. Immediately call webAuth.authorize() again.

The returned promise from step 3 will never complete. When the timeout is increased to 1000 the problem does not manifest.

I can probably provide a reproduction scenario via the sample app if the above does not highlight the problem clearly enough.

### Environment

- **Version of this library used:**
  2.13.0
- **Which framework are you using, if applicable:**
  N/A
- **Other modules/plugins/libraries that might be involved:**
  N/A
- **Any other relevant information you think would be useful:**
  `ephemeralSession` is false

**Comment by Widcket** [comment]
Hi @marcelmeulemans, thanks for raising this.
I'm a bit busy ATM, but I'll try to take a look at this next week.

**Comment by marcelmeulemans** [comment]
Thanks @Widcket!

**Comment by sophie-li** [comment]
Thanks so much! Do we have an ETA for when will this be released? 😄

**Comment by Widcket** [comment]
@sophie-li it's out now: https://github.com/auth0/react-native-auth0/releases/tag/v2.13.1
