### ISSUE TITLE
Remember this device for 30 days auth0 not working

### ISSUE THREAD

**Issue by Slasherio** [auth0/react-native-auth0#463]
### Describe the problem
Hi. I have auth0 for my mobile application and I have enabled MFA. Everything working fine, but, if I will click on the `Remember this device for 30 days` checkbox, it is not working, and with the next login, I have to enter the security code again.

### What was the expected behavior?
In case to user clicked `Remember this device for 30 days` checkbox during login, the app should not request this user to input a security code during the next session.

### Reproduction

Video of reproducing: https://vimeo.com/688891278

```
export const login = async (): Promise<Credentials> => {
  try {
    return await auth0.webAuth.authorize(
      {
        scope:
          'openid profile email read:current_user offline_access enroll read:user read:users edit:user',
        audience: `https://${Config.AUTH0_DOMAIN}/mfa/`,
        prompt: 'login',
      },
      { ephemeralSession: true },
    );
  } catch (error) {
    throw error;
  }
};
```

- Call webAuth.authorize
- Enter login credentials
- Enter security code for MFA
- Click on `Remember this device for 30 days` checkbox
- Login
- Logout
- Call webAuth.authorize
- Enter login credentials
- Enter security code for MFA

### Environment

- **Version of this library used:**
  2.11.0
- **Which framework are you using, if applicable:**
  N/A 
- **Other modules/plugins/libraries that might be involved:**
  N/A
- **Any other relevant information you think would be useful:**
  N/A

**Comment by Widcket** [comment]
Hi @Slasherio, thanks for raising this.

I see you're using `ephemeralSession: true`. This means that the cookies will not be persisted. Since the `Remember this device for 30 days` relies on cookies to work, it will not be remembered on the next login.
