### ISSUE TITLE
Explicitly support Custom URL parameters for authorize 

### ISSUE THREAD

**Issue by bombillazo** [auth0/react-native-auth0#471]
### Describe the problem you'd like to have solved

When passing custom URL parameters to the `authorize` function, one appends them to the first parameter. this parameter has a set of "supported" parameters but also implicitly allows any additional parameter to be passed. The issue comes when using TypeScript  with the library, which doesnt support these custom parameters:
```ts
const credentials = await auth.webAuth.authorize(
  {
    scope: 'openid offline_access profile email',
    audience: 'MY_AUDIENCE',
    // @ts-ignore // @types/react-native-auth0 doesn't support custom parameters yet
    screen_hint: loginType,
    customParam: 'foo',
  },
  { ephemeralSession: true },
);
```
[TypeScript Issue](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59965)

### Describe the ideal solution

Have an additional optional parameter to explicitly pass these custom parameters as opposed to implicilty appending them in code without any mnetion of them. ([Source](https://github.com/auth0/react-native-auth0/blob/ad2af24d9e10ce76ddc1613a14eb0950a5c0baab/src/webauth/index.js#L97))

## Alternatives and current work-arounds

- Add some Typing magic to the @types repo to work around this implicit support
- Use // @ts-ignore to ignore the error

**Comment by poovamraj** [comment]
Hi @bombillazo, Thanks for raising this. Really appreciate the effort with the PR.

With respect to the ideal solution, I don't think it can be adopted directly since it will be a breaking change that will need a major release.

Analyzing your PR what we would recommend from the library end is the below snippet.

```typescript
type AuthorizeParams = { [key: string]: any } & {
    state?: string; // Random string to prevent CSRF attacks and used to discard unexpected results. By default its a cryptographically secure random.
    nonce?: string; // Random string to prevent replay attacks of id_tokens.
    audience?: string; // Identifier of Resource Server (RS) to be included as audience (aud claim) of the issued access token
    scope?: string; // Scopes requested for the issued tokens. e.g. `openid profile`
    connection?: string; // The name of the identity provider to use, e.g. "google-oauth2" or "facebook". When not set, it will display Auth0's Universal Login Page.
    language?: string;
    prompt?: string;
    max_age?: number; // The allowable elapsed time in seconds since the last time the user was authenticated (optional).
    organization?: string; // The ID of the organization to join
    invitationUrl?: string; // The invitation URL to join an organization. Takes precedence over the "organization" parameter.
}
```

Since it will be the user who will be defining the custom parameters, they will be free to define however they want. I tested the type with the following case and they work fine. This will avoid unwanted use of generics and makes the code and API look neater

```typescript
export interface ExtendedAuthorizeParams extends AuthorizeParams {
    customParam: number;
    customParam2: number;
}

auth0.webAuth.authorize({
    state: 'state',
    nonce: 'nonce',
    scope: 'openid',
    max_age: 10,
    customParam:1,
    customParam2:2
});
```

Hope this helps. Let us know if you have any other ideas to tackle this.

**Comment by bombillazo** [comment]
The @types repo PR has been merged, thanks for the feedback!
