### ISSUE TITLE
Code 400: bad request. Expecting a non-nullable value. LoginWithSMS

### ISSUE THREAD

**Issue by saadnaveed94** [auth0/react-native-auth0#473]
### Code 400: bad request. Expecting a non-nullable value. LoginWithSMS
 I am using passworldless method.
 i use auth0.auth
  .passwordlessWithSMS({
    phoneNumber: '+5491159991000',
  })
to receive the code in sms. which is successful. But when i enter the code in this method 
auth0.auth
  .loginWithSMS({
    phoneNumber: 'info@auth0.com',
    code: '123456',
  })
i get the error  Expecting a non-nullable value
### passwordless with sms (successfully getting the code)
  authO.auth
      .passwordlessWithSMS({
        phoneNumber: '+923214567954',
      })
      .then(() => {
        setStep(2)
      })
      .catch((err: any) => { console.log(err) });
      
  ### loginWithSMS (giving error)
   authO.auth
      .loginWithSMS({
        phoneNumber: '+923214567954',
        email: 'saad.naveed@techverx.com',
        code: code,
      })
      .then(console.log)
      .catch(console.error);
### Expected Behaviour is get the user token with successful response

Platform Android and ios

- react-native-auth0": "^2.13.1"**

### Screenshot
![Screenshot_1652866290](https://user-images.githubusercontent.com/43129124/169009760-777384a6-dce8-4f25-9bdb-f8da59f4fa46.png)

**Comment by poovamraj** [comment]
Hi @saadnaveed94, I checked the code and looks like you are sending the email id instead of the phone number, I saw the same issue is there in our README and updated it in this PR - https://github.com/auth0/react-native-auth0/pull/482. Hope it helps
