### ISSUE TITLE
Is it possible to auth user with Face ID ( IOS ) / Touch ID ( Android )?

### ISSUE THREAD

**Issue by alexmyshchyshyn** [auth0/react-native-auth0#476]
Hello!

Is it possible to auth user with Face ID ( IOS ) / Touch ID ( Android )?

My current implementation:
```
export const auth0Auth = async ({
  screenHint,
}: IAuth0AuthParams): Promise<Credentials> => {
  try {
    return await auth0.webAuth.authorize({
      scope:
        'openid profile email read:current_user offline_access enroll read:user read:users edit:user',
      audience: `https://${Config.AUTH0_DOMAIN}/mfa/`,
      prompt: 'login',
      /**
       * https://github.com/auth0/react-native-auth0/issues/437#issuecomment-998344788
       */
      //@ts-ignore
      screen_hint: screenHint,
    });
  } catch (error) {
    throw error;
  }
};
```

P.S I tried to enable `WebAuthn with FIDO Device Biometrics`, but it do not work :(
P.S.S We don't have custom domains. We're using default one: `sc-staging.eu.auth0.com`

**Comment by brandonedley** [comment]
Definitely need this feature as well. We use react native and want to have a more seamless experience with FaceID. Seems the swift SDK has this available already?

**Comment by poovamraj** [comment]
Hi @alexmyshchyshyn and @brandonedley, Can you confirm that the expected feature is to secure the credentials in the app using biometric authentication similar to our [iOS](https://github.com/auth0/Auth0.swift#biometric-authentication) and [Android](https://github.com/auth0/auth0.android#encryption-enforced) implementation?

**Comment by alexmyshchyshyn** [comment]
@poovamraj Hi. Yes

**Comment by brandonedley** [comment]
> Hi @alexmyshchyshyn and @brandonedley, Can you confirm that the expected feature is to secure the credentials in the app using biometric authentication similar to our [iOS](https://github.com/auth0/Auth0.swift#biometric-authentication) and [Android](https://github.com/auth0/auth0.android#encryption-enforced) implementation?

Yes confirmed. This is exactly what I need

**Comment by poovamraj** [comment]
@brandonedley @alexmyshchyshyn thanks for your feedback. We are actually planning to implement this feature and have this in our upcoming releases. We can't confirm on the timeline but we will keep you updated once this is out there. We will note this issue in the internal ticket we maintain, so we will close this for now. Please feel free to reopen it if you have anything more to add on to it.
