### ISSUE TITLE
Unable to update auth0Domain URL for android build

### ISSUE THREAD

**Issue by Mingyang-Li** [auth0/react-native-auth0#477]
### ❌ Describe the problem
Our app uses auth0 login widget to login users.

Currently, I'm unable to open `Auth0 login widget` with RN `InAppBrowser` once I clicked to login from the native app UI. Instead, I get an error like the screen attached below

This happens after checking the `auth0Domain` URL string from `manifestPlaceholders` array in  `build.gradle` is indeed correct => I somwhow, at some point, accidentally pasted 3 chinese characters into the URL string BUT I corrected it afterwards.  However my app still opens the URL with extra chinese characters at the end of it

❗❗❗ This only occurs in dev environment atm ❗❗❗

![image](https://user-images.githubusercontent.com/53138432/170628492-9d505fae-ef57-40c1-b202-ead0ac9991cc.png)

### ✅ What was the expected behavior?
I expect RN `InAppBrowser` opens the auth0 login widget using the correct URL that ends with `.auth0.com` (so that I can actually open the `Auth0 login widget` from `InAppBrowser`) rather than `auth0.com.邓子豪` ...

### 👀 Reproduction
I am unable to reproduce it on any of my coworkers machine except for mine, and this issue happens on both the android VD and well as my physical samsung device, so I suspect the problem is DEFINITELY in the android build process, not my local android environment setup

📝 Things I've tried so far to solve it:
1. Deleted `/android/.gradle` folder
2. Deleted `/android/build` folder
3. Cleaned android cache by `cd android` then `gradlew clean` as well as `gradlew cleanBuildCache` => I looked up that  `gradlew clean` and  `gradlew cleanBuildCache` are obsolete according to [this stackoverflow page](https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache), so I followed the latest methods to clean cache
4. Cleaned yarn cache by `yarn cache clean`
5. Clearned `watchman` by running `watchman watch-del-all`
6. Wiped emulator data for all VDs
7. Re-created VDs and ran the app
8. Deleted and reintalled `node_modules`
9. Cleared the browser cache for all browsers on all virtual devices that the app (seems useless becos RN uses InAppBrowser rather than browsers on your VDs)
10. Cleared the cahce for the app on my VD - I cleared both data storage PLUS the cache
11. Intentionally made `manifestPlaceholders = [auth0Domain: "our-own.auth0.com", auth0Scheme: "${applicationId}"]` to `manifestPlaceholders = [auth0Domain: "jibberish.auth0.com", auth0Scheme: "${applicationId}"]` to see if the auth0 URL changes after build, which is didn't. The VD still opens the wrong auth0 URL (the one that has extra chinese characters at the end of it - see screenshot)
12. Reinstalled our `InAppBrowser` (react-native-inappbrowser-reborn)

### Environment

NPM packages related:
1. `"react-native-auth0": "^2.13.1"`
2. `"react-native": "0.65.1"`

Android stuff:
```
buildToolsVersion = "30.0.2"
minSdkVersion = 21
compileSdkVersion = 30
targetSdkVersion = 30
ndkVersion = "20.1.5948944"
androidXAnnotation = "1.2.0"
androidXBrowser = "1.3.0"
```

**Comment by Mingyang-Li** [comment]
@poovamraj @fbartho any 2 cents on this? I saw you were discussing another issue in this repo:)

**Comment by Mingyang-Li** [comment]
@noway Any 2 cents?

**Comment by juddey** [comment]
Did you try clearing metro bundlers cache, maybe?
`yarn start --reset-cache`

**Comment by Mingyang-Li** [comment]
> yarn start --reset-cache

Yes I tried, still having the same issue on my VD
Output:
```
C:\appfolder>yarn start --reset-cache

                        #######
                   ################
                #########     #########
            #########             ##########
        #########        ######        #########      
       ##########################################     
      #####      #####################       #####    
      #####          ##############          #####    
      #####    ###       ######       ###    #####    
      #####    #######            #######    #####    
      #####    ###########    ###########    #####    
      #####    ##########################    #####    
      #####    ##########################    #####    
      #####      ######################     ######    
       ######        #############        #######     
         #########        ####       #########        
              #########          #########
                  ######### #########
                       #########


warning: the transform cache was reset.
error listen EADDRINUSE: address already in use :::8081.
Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (node:net:1330:16)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at C:\sugar-wallet-app\node_modules\metro\src\index.js:164:16
    at new Promise (<anonymous>)
    at Object.exports.runServer (C:\appfolder\node_modules\metro\src\index.js:163:10)   
    at async Object.runServer [as func] (C:\appfolder\node_modules\@react-native-community\cli\build\commands\start\runServer.js:113:26)
    at async Command.handleAction (C:\appfolder\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.
```

**Comment by juddey** [comment]
Yes, but that issue says you already have a metro bundler running on another port:
`error listen EADDRINUSE: address already in use `

**Comment by Mingyang-Li** [comment]
> Yes, but that issue says you already have a metro bundler running on another port:
> `error listen EADDRINUSE: address already in use `

Yea, I intentionally killed the server and ran that script again before your last comment, I still got the same error

**Comment by tyfrth** [comment]
Similar to what @Mingyang-Li has stated regarding other machines, just adding that I wasn't able to reproduce this in our sample app on my end either 🤔

**Comment by poovamraj** [comment]
@Mingyang-Li this seems to be because of the browser redirection. You can clear the storage (and cache) on the browser app and it should work. Please feel free to reopen this issue if the issue still persists
