### ISSUE TITLE
ITMS-90338: Non-public API usage: _SFAuthenticationErrorDomain

### ISSUE THREAD

**Issue by tony-dong** [auth0/react-native-auth0#479]
I received an email from Apple rejecting the app due to usage of a non-pubic API. This happened when I uploaded a build to the App Store.

`Dear Developer,

We identified one or more issues with a recent delivery for your app. Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public symbols in : _SFAuthenticationErrorDomain. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Best regards,

The App Store Team`

When I searched for the keyword SFAuthenticationErrorDomain, it appears to be used here:
https://github.com/auth0/react-native-auth0/blob/master/ios/A0Auth0.m

This only started happening yesterday for us, and the code hasn't changed. This must be something new that Apple has put in to place and would stop anyone uploading to the App Store using RNAuth0.

**Comment by gran33** [comment]
Same for me, found this [thread](https://developer.apple.com/forums/thread/127678?answerId=715975022#715975022), see last comments.

**Comment by tony-dong** [comment]
This appears to be an Apple issue, and as per @gran33's comment, is now resolved. So I'm closing.
