### ISSUE TITLE
I cannot set the scope to get the refreshToken with    authO.auth.loginWithSMS

### ISSUE THREAD

**Issue by FaisalSeraj-techverx** [auth0/react-native-auth0#480]
i am trying to add the refreshToken to my response when user is authenticated. I am unable to get the refreshTOken in the response because i am unable to set the scope = 'offline_access' to auth.loginWithSms
here is the code: 
     authO.auth
        .loginWithSMS({
          phoneNumber: completePhone,
          email: '',
          code: code,
          authParams: {
            scope: 'offline_access',
          },
        })

**Comment by poovamraj** [comment]
Hi @FaisalSeraj-techverx, the scope should be sent as a parameter like the following example

```javascript
auth0.auth
        .loginWithSMS({
            phoneNumber: '+11111111111111',
            code: '111111',
            scope: 'offline_access'
          })
          .then(console.log)
          .catch(console.error);
```

That should return the following result

```json
{
   "accessToken":"xxxx",
   "expiresIn":86400,
   "idToken":"yyyy",
   "refreshToken":"zzzz",
   "scope":"openid profile email address phone offline_access",
   "tokenType":"Bearer"
}
```

Hope this helps. Please feel to reopen this issue if you have more doubts
