### ISSUE TITLE
Missing NativeModule after `react-native upgrade`. `v2.13.1`

### ISSUE THREAD

**Issue by michaelbeutler** [auth0/react-native-auth0#487]
### Describe the problem

When trying to authenticate, the error `Missing NativeModule` gets thrown.

### What was the expected behavior?

When clicking any button, the user should be authenticated using webauth.

### Reproduction

- clone https://github.com/iperka/vacations-mobile
- Run `yarn install && yarn react-native upgrade`
- Upgrade `react-native-auth0` to v2.13.1
- Run `yarn ios`
- Press Sign In or Sign Up when app has been loaded
- See error message below buttons

<img width="246" alt="image" src="https://user-images.githubusercontent.com/35310806/175395420-56358c78-3e6d-4568-b33b-05be0ba30016.png">

### Environment

- **Version of this library used: 2.13.1**
- **Which framework are you using, if applicable: React Native CLI**
- **Other modules/plugins/libraries that might be involved: see package.json**
- **Any other relevant information you think would be useful: Tested with M1 MacBook**

And yes, I tried running `pod install`...

**Comment by Widcket** [comment]
Hi @michaelbeutler, thanks for raising this.
Are you able to reproduce this using the sample app at https://github.com/auth0-samples/auth0-react-native-sample?

**Comment by Widcket** [comment]
Hi, I just tried installing the dependencies from scratch (on `master`) using both yarn and npm and was successful:

<img width="672" alt="Screen Shot 2022-06-24 at 13 53 16" src="https://user-images.githubusercontent.com/5055789/175607071-e368bc5a-0eb4-4c8e-b6ed-afa4222e85fe.png">

**Comment by Widcket** [comment]
Just installed the pods from scratch and was successful:
<img width="704" alt="Screen Shot 2022-06-24 at 14 35 21" src="https://user-images.githubusercontent.com/5055789/175613184-6e7d46a4-0520-4983-9935-7bcfdc8348e4.png">

Do you have your specs repo clone updated? Run `pod repo update` if not.

**Comment by michaelbeutler** [comment]
I did... do you use an arm64?

**Comment by Widcket** [comment]
No, I'm not using an M1.

**Comment by michaelbeutler** [comment]
Okay, it was my fault, had to simply remove `node_modules` and `yarn.lock` and install everything again. Works now, thanks for the quick support.

**Comment by michaelbeutler** [comment]
> @michaelbeutler Hi, were you able to install npm dependencies on arm64?

Yes, it worked by reinstalling all dependencies.
