### ISSUE TITLE
How get react-native-auth0 cookies when log in with auth0?

### ISSUE THREAD

**Issue by idanlevi1** [auth0/react-native-auth0#492]
I use `react native` 0.68.2v 
`react-native-auth0` 2.13.3
I can log in with auth0, is return me credentials and userInfo, 
the server-side asks me for cookies from auth0, how do I get it?

**Comment by poovamraj** [comment]
Hi @idanlevi1, Are you selecting 

In the Auth0 dashboard, can you confirm this is checked. Native applications wouldn't use cookies for authentication

>When using the Default App with a Native or Single Page Application, ensure to update the Token Endpoint Authentication Method to None and set the Application Type to either SPA or Native.

**Comment by poovamraj** [comment]
Hi @idanlevi1, we are closing this issue for now. Please feel free to reopen this if you have any more doubts
