### ISSUE TITLE
[bug] peer dependency error on React 18.0.0 upgrade. 

### ISSUE THREAD

**Issue by rajibahmed** [auth0/react-native-auth0#495]
### Describe the problem

Hi folks, I upgraded one of my react native project 0.69.3 from 0.68.2 which upgrades react to 18.0.0. 

Upgrading to React 18 causes peer dependencies mismatch and github action `npm install` to fail. 

Probably caused by this -- 
https://github.com/auth0/react-native-auth0/blob/68e91cb7710039e02eca8b33b08f578626ecffae/package.json#L27-L30

Logs 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-native-auth0@2.13.3
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!   peerOptional react@"^1[6](https://github.com/LemonEarth/Lemonade/runs/7627732968?check_suite_focus=true#step:5:7).8.0 || ^17.0.0 || ^18.0.0" from @apollo/client@3.6.9
npm ERR!   node_modules/@apollo/client
npm ERR!     @apollo/client@"^3.6.8" from the root project
npm ERR!   29 more (@gorhom/bottom-sheet, @gorhom/portal, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.11.0 || ^1[7](https://github.com/LemonEarth/Lemonade/runs/7627732968?check_suite_focus=true#step:5:8)" from react-native-auth0@2.13.3
npm ERR! node_modules/react-native-auth0
npm ERR!   react-native-auth0@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.[11](https://github.com/LemonEarth/Lemonade/runs/7627732968?check_suite_focus=true#step:5:12).0 || ^17" from react-native-auth0@2.[13](https://github.com/LemonEarth/Lemonade/runs/7627732968?check_suite_focus=true#step:5:14).3
npm ERR!   node_modules/react-native-auth0
npm ERR!     react-native-auth0@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/runner/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
```
### What was the expected behavior?

Expected behaviour is react-native-auth0 to be installed along side with React 18.

### Reproduction

N/A

### Temporary Solution

forcefully install packages

```
npm install --force
```

### Environment

- **Version of this library used:** 2.13.3
- **Which framework are you using, if applicable:** React Native 0.69.3 / React 18
- **Other modules/plugins/libraries that might be involved:** 
- **Any other relevant information you think would be useful:**

**Comment by AlekSteinmetz** [comment]
I'm having to deal with this issue as well. It would be great if the dependencies could be updated.

**Comment by poovamraj** [comment]
Hey @rajibahmed @AlekSteinmetz we have fixed this issue in this PR - https://github.com/auth0/react-native-auth0/pull/509

The version with this fix will be released soon. We will close this issue for now but please feel free to reopen if you have more doubts.

**Comment by oelerpearler** [comment]
Hi @poovamraj ! Is there already a date planned for the release?

**Comment by poovamraj** [comment]
Hi @oelerpearler  👋 We have already released a first availability with this fix which can be found [here](https://github.com/auth0/react-native-auth0/releases/tag/v2.14.0-fa.0)
