### ISSUE TITLE
Support Universal Links and App Links

### ISSUE THREAD

**Issue by chrismcleod** [auth0/react-native-auth0#496]
### Describe the problem you'd like to have solved

Apple and Google "strongly recommend" Universal Links / App Links for deep linking user credentials rather than custom url schemes.

### Describe the ideal solution

This library would allow using Universal Links and App Links for the authorization callback redirect.

## Alternatives and current work-arounds

Wrap and directly use the iOS / Android auth0 sdk's instead of this one.

**Comment by poovamraj** [comment]
@chrismcleod Can you provide more details on what is stopping you from using Universal Links and App Links in the current implementation?

**Comment by chrismcleod** [comment]
@poovamraj I'm not sure how to do it.  So a documentation example would help.  Specifically, what native code updates would I need to make for the app to accept the redirect and respond to the javascript authorize call?

**Comment by poovamraj** [comment]
@chrismcleod Got it thanks. We will try to get a documentation up but until then the procedure should be same as [Android](https://auth0.com/docs/get-started/applications/enable-android-app-links-support) or [iOS](https://auth0.com/docs/get-started/applications/enable-universal-links-support-in-apple-xcode) and our RN SDK will work as it is. Hope this helps. We are closing this issue for now but feel free to reopen it if you have any doubts

**Comment by poovamraj** [comment]
@gmonte have you tried the links mentioned in the comment above

- https://auth0.com/docs/get-started/applications/enable-android-app-links-support
- https://auth0.com/docs/get-started/applications/enable-universal-links-support-in-apple-xcode
