### ISSUE TITLE
webAuth.authorize does not return the idToken

### ISSUE THREAD

**Issue by cross19xx** [auth0/react-native-auth0#499]
### Describe the problem
We are currently using the web auth in React native.
We noticed that authentication using the same function has different responses which seem to happen after you leave the app idle for a while.

Initial login (with no prior login)

```js
const credentials = await auth0.webAuth.authorize({ scope: 'openid profile email', mode: 'login' }, { ephemeralSession: true });
console.log(credentials); 
/**
returns
{
  "accessToken": "REDACTED",
  "idToken": "REDACTED",
  "scope": "openid profile email",
  "expiresIn": 86400,
  "tokenType": "Bearer"
}
*/
```

After leaving the app idle for a while, we are faced with this response, using the same function:

```js
const credentials = await auth0.webAuth.authorize({ scope: 'openid profile email', mode: 'login' }, { ephemeralSession: true });
console.log(credentials); 
/**
returns
{
  "accessToken": "REDACTED",
  "expiresIn": 86400,
  "tokenType": "Bearer"
}
*/
```

My best guess is that we're already logged in and haven't explicitly called `auth0.webAuth.clearSession()`.

### Reproduction

```js
const credentials = await auth0.webAuth.authorize({ scope: 'openid profile email', mode: 'login' }, { ephemeralSession: true });
console.log(credentials); 
```

### Environment

- Version: `react-native-auth0@2.13.3`
- Framework used: `react-native@0.69.1`
- **Any other relevant information you think would be useful:**: the `idToken` is used to authenticate against a server

**Comment by poovamraj** [comment]
@cross19xx I see that you have set `ephemeralSession: true`. Are you able to reproduce this in iOS alone or is it on both platforms?

**Comment by cross19xx** [comment]
This was done on an iOS simulator... For Android I can get rid of this by clearing the webview app. But it happens on both platforms :)

Thanks for your reply btw

**Comment by mweel1** [comment]
Try adding the audience property in authorize

**Comment by jmz527** [comment]
Just spotted something...does the `auth0.webAuth.authorize` method accept more than one argument parameter? @poovamraj

**Comment by poovamraj** [comment]
@jmz527 yes it accepts 2 arguments (`parameters` and `options`) and the `parameter` argument has the following options 

![Screenshot 2022-08-26 at 09 10 11](https://user-images.githubusercontent.com/15910425/186843893-af8dc191-0056-4dbb-aa5d-8b1394f1cc88.png)
![Screenshot 2022-08-26 at 09 11 38](https://user-images.githubusercontent.com/15910425/186844175-039fc0ff-5a6c-4020-861f-05ed0b8b43a0.png)

**Comment by poovamraj** [comment]
@cross19xx are we sure we are passing the scope as `openid profile email`? I was able to reproduce this if `scope` is empty but not other than that.

**Comment by poovamraj** [comment]
@cross19xx I tried to reproduce this issue for some time now but couldn't. It would be better if you can provide us with a sample repository that is able to reproduce this issue. I attached a sample where I tested with the code you mentioned (with no idle time but I have tried that as well). 

https://user-images.githubusercontent.com/15910425/190459317-218cc9f3-9d48-4748-b6ab-1076d4ee93dc.mov

We will close this issue for now but please feel free to reopen it and we will be happy to help.
