### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by saadjaliawala** [auth0/react-native-auth0#502]
I want a flow where a user can reset its password within my mobile application

**Comment by poovamraj** [comment]
Hello @saadjaliawala,

Doing it with API, you can follow the docs here - https://auth0.github.io/react-native-auth0/Auth.html#.resetPassword

For Universal Login (Web Auth) - You can follow the doc [here](https://auth0.com/docs/authenticate/database-connections/password-change#universal-login-page)
