### ISSUE TITLE
User cancelled the Auth on callback

### ISSUE THREAD

**Issue by mweel1** [auth0/react-native-auth0#504]
On the call back of my android react native app I get the following error:

{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}

I've tried all the suggestions in the issue tracker with no success.  Any thoughts on how to debug this?

**Comment by dutradotdev** [comment]
same error on android, iOS works well.

**Comment by poovamraj** [comment]
@mweel1 @dutradotdev, can you provide the steps to reproduce this issue? This error is thrown only when the user explicitly cancels the login flow

**Comment by mweel1** [comment]
Here is the link coming back from Auth0

Its obvious the user is not canceling the auth process as this is the link calling back

io.xxxxxxxx.enforcement://xxxxxxx.us.auth0.com/android/ioxxxxxx.enforcement/callback?code=IYdtOeydL8OQ-HmTDvMMJNn1d4SzglYb0g4Ko_tcKWXnm&state=M5KeYkSX0L_XZJB1aCO8sYyyPcQBP-vsG2HPfo6N_Hg

 LOG  {"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}

**Comment by poovamraj** [comment]
Hi @mweel1 I agree, but we would need more information to reproduce this issue. 
- Is this happening only in specific devices/OS versions? 
- Are there any particular case in which it is not working? 
- Does the MergedManifest have RedirectActivity with the proper intent filter applied? 
- Can you see the error thrown when using Chrome Debugger when the redirection is failing?

Information on these questions will greatly help us find and fix this issue.

**Comment by dutradotdev** [comment]
hey @mweel1 

I followed this diff https://github.com/auth0-samples/auth0-react-native-sample/commit/69f79c83ceed40f44b239bbd16e79ecaa70ef70a and now it is working on Android!

**Comment by mweel1** [comment]
Is this happening only in specific devices/OS versions?

No, it happens on both IOS & Android

Are there any particular case in which it is not working?

There is really only one use case, login and it doesn't work.

Does the MergedManifest have RedirectActivity with the proper intent filter applied?

Where would lI find this?

Can you see the error thrown when using Chrome Debugger when the redirection is failing?

When I console log the error from the try/catch on authorize its:

{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}

**Comment by poovamraj** [comment]
It is interesting that it is not working in both iOS and Android. It would be better if you can share a sample app in which this issue can be reproduced for us to debug this further.

**Comment by poovamraj** [comment]
Hello @mweel1 and @dutradotdev, I tried to reproduce this issue for quite sometime with no result. We will close this issue for now but please feel free to reopen if you can provide us with more details

**Comment by davecoffin** [comment]
@mweel1 Did you resolve this? I've having the same issue. @dutradotdev  I have followed this diff as well https://github.com/auth0-samples/auth0-react-native-sample/commit/69f79c83ceed40f44b239bbd16e79ecaa70ef70a

**Comment by poovamraj** [comment]
@davecoffin 
- what version of the SDK are you using?
- Is this happening in iOS, Android or both?
- Any specific steps to reproduce this?
- Can you reproduce this in our sample app so that it will be very easy for us to reproduce?

We would love to help you with this issue just that we don't have much to go ahead with.

**Comment by dreese33** [comment]
@poovamraj I seem to be having the same issue with an app built with Expo. Specifically, this is happening when I point the app to a custom domain that is configured:
- I am using v2.17.1
- This is only happening on Android, iOS works fine
- Steps to reproduce: Configure a custom domain for your auth0 universal login. Configure an app with react-native Expo. Attempt to sign in on Android using the `webAuth.authorize()` call

Some other notes: If I call the `webAuth.authorize()` function a second time, it will authenticate my user without needing to re-enter my credentials. When the app is pointed to the tenant domain, this error does not occur, only when pointed to the custom domain. Let me know if this helps at all in resolving this

**Comment by delaneybrian** [comment]
I've been experiencing a similar issue where I get the error:

`{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}`

I'm using:

"react-native": "0.70.5",
"react-native-auth0": "^2.17.1"

Experiencing it on android (have not tried iOS) using expo dev-client.

I'm not a professional or a full time react native developer so just following on with some details of experiencing the same issue.

If I have time to reproduce in the sample app I will try.

**Comment by LucasSolares** [comment]
Hi, I'm facing this issue in a react-native-cli app, also using react native navigation, but I have to implement this bad fix, to make it work.

```
useEffect(() => {
    (async () => {
      if (error && (error as any).error === 'a0.session.user_cancelled') {
        await authorize();
      }
    })();
  }, [error, authorize]);
```

It seems that this is only happening the first time I tried to sign in and also is happening in both emulator & physical devices.

**Comment by florianrusso** [comment]
I'm facing a similar issue on my android app, I can not reproduce in the 00-Login-Hooks sample app. I have a similar code in my app compare to the sample app, which leads me to suppose something interfere with the auth-0 package

**Comment by localyte-nelson** [comment]
also seeing this issue with v2.17.1
