### ISSUE TITLE
ADFS on IOS is not working.

### ISSUE THREAD

**Issue by samsiu2014** [auth0/react-native-auth0#51]
I'm not sure if I should ask here, so if I'm wrong or I didn't follow the rules, please accept my apologize. 
I will move my question to other place.
I run the auth0-react-native-sample base on the react-native-auth0.
https://github.com/auth0-samples/auth0-react-native-sample

Everything works fine on android, however, the adfs single sign on is not working with IOS.
In IOS, after I entered the account and pressed the login button. It only shows me a loading image.
But, there will be a box popped out for me to enter the adfs account and password in android.

So, I would like to ask what can I do to solve this problem? Or any suggestions for me?
Thank You!

**Comment by hzalaz** [comment]
@samsiu2014 did you run successfully `react-native link react-native-auth0` and followed the README instructions?

Do you have a screenshot to see where it get stuck?

**Comment by samsiu2014** [comment]
@hzalaz yes, i followed everything in the README instructions. Android is fine but for IOS, it just shows me a loading picture after i clicked login button.
![loading](https://user-images.githubusercontent.com/26761164/28770660-8eae66e0-7612-11e7-8e78-e926dcd59421.png)

**Comment by madbean** [comment]
Hello same for me, can you help us ?

**Comment by cocojoe** [comment]
@madbean using sample this is what I get in iOS, please check you are using the latest versions.

![simulator screen shot 4 sep 2017 15 40 03](https://user-images.githubusercontent.com/928115/30031776-c8f58584-918a-11e7-9459-70edfb744932.png)

**Comment by madbean** [comment]
hello this ok for me now.

that was a sheme mistake...

```
<key>CFBundleURLSchemes</key>
<array>
	<string>reacthivejobs</string>
</array>
```

thx again
