### ISSUE TITLE
Need i18n support

### ISSUE THREAD

**Issue by Wxlevan** [auth0/react-native-auth0#515]
### Describe the problem you'd like to have solved
I hope to have international support.
### Describe the ideal solution

1. Add an initialization language parameter in the Auth0's Options.
2. Add language parameters to other methods.
## Alternatives and current work-arounds
When I use `passwordRealm` to login, the error message always be English.

**Comment by poovamraj** [comment]
@Wxlevan `passwordRealm` is an API based authentication and the error messages returned in this will tend to always be in English. We would suggest to do the i18n on your end.

If you want i18n support on Web Auth, you can enable it in your settings and use the following code to trigger locale based auth
`authorize({scope: 'openid profile email', "ui_locales": 'de', login_hint: 'test@test.com'});`

**Comment by poovamraj** [comment]
We will close this issue for now but please feel to reopen it if you have more doubts on this.

**Comment by alubeck** [comment]
I couldn't find this information in any documentation. In order to apply these `ui_locales`, they need to be applied within `additionalParameter` object:

```
const credentials = await authorize(
        {
          scope: 'openid profile email',
          additionalParameters: {
            ui_locales: 'de',
          },
        },
      );
```
