### ISSUE TITLE
Unable to initialize Auth0.Auth.Client class for Passwordless (2.13.3)

### ISSUE THREAD

**Issue by shottah** [auth0/react-native-auth0#517]
### Describe the problem

When implementing standard usage on iOS, calling`Auth0.auth.passwordlessWithSMS` returns the error:
`Unable to send Auth0 authorization code [TypeError: Cannot read property 'post' of undefined]`

### What was the expected behavior? 

`Auth.Client` should be initialized when `new Auth(Optionts)` is called.

### Reproduction

**Steps to reproduce:**
- Fork [zedio/rnauthstarter#core/auth](https://github.com/zed-io/rnauthstarter/tree/core/auth)
- Edit `.env.dev` file and populate the `AUTH0_DOMAIN` and `AUTH0_CLIENTID`
- Run `yarn dev:ios` to use the expo build process.

N.B. Since this is a native module package, I understand it will not work with Expo Managed Workflow (full JS, TS), however my understanding is that my project is an Expo Bare Workflow which allows importing of custom native modules.

### Environment

- **Version of this library used:**
   - "react-native-auth0": "^2.13.3",
- **Which framework are you using, if applicable:**
   - "react-native": "0.70.1",
   - "expo": "^46.0.0",
- **Other modules/plugins/libraries that might be involved:**
   - "firebase": "^9.10.0",
   - "redux-saga": "^1.2.1",
- **Any other relevant information you think would be useful:**
Reach Native 0.70.x was released on September 5th 2022.
The actual function call is done inside of a saga generator function

```ts
import { call } from 'react-redux/effects`
const auth0 = new Auth0(Options);
yield call(auth0.auth.passwordlessWithSMS({phoneNumber: phoneNumber}))
```

**Comment by Widcket** [comment]
Hi @shottah, thanks for raising this.

Are you able to reproduce this in a brand new Expo app (with bare workflow)?

**Comment by shottah** [comment]
Hi @Widcket This link i shared is a brand new Expo bare app using the following steps.

1. Use `npx react-native-init rnauthstarter`
2. Add react-navigation, react-redux, redux, redux-saga
3. Run `npx install-expo-modules@latest` and `expo`, now using Bare Workflow
4. Install `react-native-auth0@2.13.3`

If there is a concern that there are many conflicts here in the instructions above, I will continue to make the most minimal expo bare app and return to you.

1. `npx react-native-init rnauthstarter`
2. `npx install-expo-modules@latest`, `yarn add expo`
3. `yarn add react-native-auth0@2.13.3`

**Comment by Widcket** [comment]
Is it reproducible without any other dependencies, such as redux and redux-saga?

**Comment by shottah** [comment]
@Widcket, following up here. In a fresh react-native project with Expo bare workflow, the issue reported is not replicated. At the end I will also post a snipped of the redux-saga code where the function is executed in the original project that has issues.

Install Scripts
```sh
npx react-native init auth0starter
npx install-expo-modules@latest, yarn add expo expo-constants
yarn add react-native-auth0@2.13.3
```

App.tsx
```ts


  const startPhoneVerification = async (
    phoneNumber: string,
    test: boolean = true,
  ) => {
    if (!auth0) {
      return;
    }
    if (test) {
      return;
    }
    return await auth0.auth.passwordlessWithSMS({
      phoneNumber: phoneNumber,
    });
  };

  const completePhoneVerification = async (
    phoneNumber: string,
    code: string,
  ) => {
    if (!auth0) {
      return;
    }
    return await auth0.auth.loginWithSMS({
      phoneNumber: phoneNumber,
      code: code,
    });
  };

  return [auth0, startPhoneVerification, completePhoneVerification];
};
```

--- End of code for Fresh React-Native Expo Bare App ---

Redux-Saga snippet

```ts
function* initiateAuth0Text() {
  const phoneNumber = yield select(e146PhoneNumberSelector);
  if (!phoneNumber) {
    return;
  }
  const auth0 = new Auth0({
    domain: AUTH0_DOMAIN,
    clientId: AUTH0_CLIENT_ID,
  });
  if (!auth0.auth) {
    return;
  }
  console.log('Auth', auth0.auth);
  try {
    yield call(auth0.auth.passwordlessWithSMS, {phoneNumber});
  } catch (error) {
    console.error('Unable to send code', error);
  }
}
```

**Comment by poovamraj** [comment]
@shottah I tried the fork you provided and it looks like there is no issue initializing the SDK. I am not able to reproduce the issue and also looks like the SDK works good in a plain project. It would be great to have more details if you still think the issue is on the SDK side

**Comment by poovamraj** [comment]
@shottah We will close this issue for now due to inactivity and since we are not able to reproduce it. Please feel free to reopen it if you have any more doubts.
