### ISSUE TITLE
Failed Exchange

### ISSUE THREAD

**Issue by compojoom** [auth0/react-native-auth0#52]
Baby steps...

I have the following code:
```
	  auth0
		  .auth
		  .passwordRealm({username: "xxxx@yxxx", password: "123456ab", realm: "Username-Password-Authentication"})
		  .then((res) => console.log(res))
		  .catch(err => console.error(err));
```

and I get an "internal server error occurred". I had a look at my logs and I see this:
```
{
  "date": "2017-06-28T08:38:54.359Z",
  "type": "feccft",
  "description": "Unauthorized",
  "connection_id": "",
  "client_id": "xxxx",
  "client_name": null,
  "ip": "52.28.56.226",
  "user_agent": "node-superagent/2.3.0",
  "user_id": "",
  "user_name": "",
  "audience": "https://xxxx/api/v2/",
  "scope": null,
  "log_id": "xxxx"
}
```

What am I doing wrong here? I actually created the user with the library. 

 ```
auth0
		  .auth
		  .createUser({email: 'xxx@xxx', username: 'xxx@xxx', password: '123456ab',
              connection: 'Username-Password-Authentication'})
		  .then(console.log)
		  .catch(console.error);
```

So I'm not sure what the issue with the login might be?

**Comment by cocojoe** [comment]
Hi @compojoom 

I copy and pasted in your code, changing for my own username/password of course.  This worked fine.
Can you ensure you are using the latest `react-native-auth0 1.0.3` then I suggest you double check in the Auth0 Dashboard under `Users` that this user was created.
Double check you have the right password and if you are unsure you can `Change Password` in the `Users` section.

Thanks

**Comment by compojoom** [comment]
@cocojoe - yep, I'm on 1.0.3
I got it to work, but I have no clue what was wrong in the first place. 

I tested the database connection on the auth0 website - it didn't work and was complaining about the "authorization extension" - I uninstalled the extension -> same error. I installed the extension again, afterwards login magically worked...
