### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by damienherve** [auth0/react-native-auth0#525]
### Describe the problem you'd like to have solved

No Typescript support

### Describe the ideal solution

Rewrite the library in TypeScript (ideal)

## Alternatives and current work-arounds

At least, maintain @types/react-native-auth0

### Additional information, if any

Currently, the library has no Typescript support, as @types/react-native-auth0 last published version is 2.13.1.

Is it planned to add this kind of support?

**Comment by poovamraj** [comment]
Hi @damienherve we here you and we are taking note of this request. Currently the types are only provided through [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-auth0) through best effort basis. 

We would love if you can contribute to keep this up to date. We will add this request to our backlog though we are not sure when we can provide support to this.

I will leave this issue open for sometime to gather more feedback from the community. Any additional info on this will be helpful for us to make decision

**Comment by ziad-floosi** [comment]
I agree with @damienherve. If migrating the codebase to TypeScript is a hassle, I think keeping the DefinitelyTyped library up to date with this one is a very fair solution. Currently the entire hooks API has no types at all, making it a bit difficult  to use with TypeScript.

**Comment by damienherve** [comment]
Thanks for the answer, if i have time i'll try to make a PR for the types on DefinitelyTyped

**Comment by gfriedm4** [comment]
If anyone wants to work together on it, I've started a draft PR for updating the DefinitelyTyped library. I was planning to go folder by folder and have done `src/auth` and `src/credentials-manager` so far. 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62709

**Comment by poovamraj** [comment]
Thanks a lot for the effort @gfriedm4. Highly appreciate your contriubtion 🚀 🙌

**Comment by evanjmg** [comment]
types are out of date :/

**Comment by iovreche** [comment]
Not only types, but the documentation. Considering how pricey auth0 is...

**Comment by poovamraj** [comment]
@iovreche can you point out the outdated documentation so that we can try to fix it? Regarding the types, we will work with the community effort to get it fixed.

**Comment by poovamraj** [comment]
I have created a PR with the types fixed - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63584

It would be great to hear feedback from you on this and if anything needs to be improved

**Comment by poovamraj** [comment]
Hey all the PR is merged 🍾 the type support should now be available. Please feel free to reopen this thread if you have more doubts. We will close this for now
