### ISSUE TITLE
Not compatible with react-native 0.35.0

### ISSUE THREAD

**Issue by Jeammy** [auth0/react-native-auth0#53]
Hi, i'm currently haveing this configuration :
{
  "name": "testAuth3",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.35.0",
    "react-native-auth0": "^1.0.3"
  }
}

and i'm using your example : https://auth0.com/docs/quickstart/native/react-native
which states, that is React Native 0.26.0 compatible.
I didn't managed to get it working : the problem in XCode is : 
 "AppDelegate.m:14:9: 'React/RCTLinkingManager.h' file not found"

I would like to use your solution, as a API, I've already spent several days, but no success.
Using the latest version of React-Native is OK.
But i can't migrate my application right now, because of time question.
If anyone has  a solution, i'm very interested.

Thanks in advanced,

**Comment by cocojoe** [comment]
@Jeammy I do not believe this is an issue with the react-native-auth0 lib, it sounds more like an issue with the Xcode projecting not set up correctly with an older version of react-native.  As you stated there are no xcode project linking issues with the current version of react-native (0.45).

A quick google of the above provides some results worth looking at:
https://stackoverflow.com/questions/31860715/rct-linking-manager-file-not-found

**Comment by Jeammy** [comment]
@cocojoe 
Adding this line got my project working:
  $(SRCROOT)/../node_modules/react-native/Libraries/LinkingIOS

Thanks cocojoe.

**Comment by hzalaz** [comment]
@Jeammy I believe in 0.40 changed the location of headers and the default inclusion of `LinkingIOS` so your workaround is valid. (Although considering how much RN changes and update is advisable)
