### ISSUE TITLE
"authorize" from useAuth0 hook does not accept ephemeralSession properly

### ISSUE THREAD

**Issue by ebg1223** [auth0/react-native-auth0#539]
```
const auth0 = new Auth0({
  domain: 
  clientId: 
})

export default function Auth() {
  const { authorize, user, clearSession, webAuth } = useAuth0()

//WORKS CORRECTLY, DOES NOT ASK PERMISSION TO OPEN BROWSER
  const login = async () => {
    await webAuth
      .authorize(
        { scope: 'openid profile email' },
        { ephemeralSession: true } // No SSO, therefore no alert box
      )
      .then((credentials) => console.log(credentials))
      .catch((error) => console.log(error))
  }

//DOES NOT WORK AS EXPECTED. ASKS PERMISSION TO OPEN BROWSER TO auth0
   const loginViaHooks = async () => {
    await authorize(
      {scope: 'openid profile email'},
      {ephemeralSession: true,}
    )
  }
```

App is wrapped in Auth0 Provider. Login still works successfully either way, and the user object is populated. Just does not respect the ephemeralSession prop for some reason.

**Comment by moribaleta** [comment]
is there a way to track the ios alert if continue is pressed

**Comment by poovamraj** [comment]
Hi @moribaleta I am not sure what your question is. Can you please elaborate on it with a possible use case?

**Comment by poovamraj** [comment]
@ebg1223 the fix for this is currently in master. The other enhancement you provided is in review on a separate PR. We will be releasing them soon, we will keep you updated about this.

Will close this issue for now, feel free to reopen this if you have more doubts
