### ISSUE TITLE
Android clean failures since react-native 0.71.0-rc.0 tag added

### ISSUE THREAD

**Issue by bhandanyan-nomad** [auth0/react-native-auth0#544]
### Describe the problem
```
FAILURE: Build failed with an exception.

* Where:
Build file '/root/repo/node_modules/react-native-auth0/android/build.gradle' line: 95

* What went wrong:
A problem occurred configuring project ':react-native-auth0'.
> Could not resolve all files for configuration ':react-native-auth0:implementation'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-auth0
      > Cannot choose between the following variants of com.facebook.react:react-native:0.71.0-rc.0:
          - debugVariantDefaultRuntimePublication
          - releaseVariantDefaultRuntimePublication
```

### What was the expected behavior?
Not that

### Reproduction

- Try to build an app with this version installed

### Environment

- **Version of this library used:** 2.13.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:** react-native
- **Any other relevant information you think would be useful:** Related to: https://github.com/facebook/react-native/issues/35204

**Comment by poovamraj** [comment]
Hi @bhandanyan-nomad, this is an issue in React Native and has already been noted by them - https://github.com/facebook/react-native/issues/35210

![image](https://user-images.githubusercontent.com/15910425/200197860-832f9b4f-80c9-4072-8987-affa367c3fdc.png)

**Comment by poovamraj** [comment]
Hello @bhandanyan-nomad the official workaround mentioned in this thread https://github.com/facebook/react-native/issues/35210 seems to work. I have created a RN project with following versions

RN 0.65.0
react-native-auth0 2.13.0

https://github.com/poovamraj/auth0-react-native-deps-issue-sample

And it seems to work. Please try to provide a sample using the above repo if the issue is still occurring for you

**Comment by bhandanyan-nomad** [comment]
Upgrading to one of the react native patch version fixes that they released has fixed this issue for me
