### ISSUE TITLE
'ASWebAuthenticationSession' is only available in iOS 12.0 or newer Error Xcode14

### ISSUE THREAD

**Issue by shawna-donnelly** [auth0/react-native-auth0#545]
Getting an error when trying to build with XCode 14. 'ASWebAuthenticationSession' is only available in iOS 12.0 or newer. This is in the ASProvider file of the Auth0 Pod. 

Error received and build failing: 'ASWebAuthenticationSession' is only available in iOS 12.0 or newer.

- **Version of this library used:** 2.13.1

**Comment by Widcket** [comment]
Hi @shawna-donnelly, thanks for raising this.

That's correct, since this SDK is wrapping [Auth0.swift](https://github.com/auth0/Auth0.swift) for the Credentials Manager functionality, it needs at least iOS 12.0. So to use the SDK you'll need to raise the deployment target of your app to 12.0.

**Comment by shawna-donnelly** [comment]
So my deployment target is set to 12.0. It only happens in XCode 14. In 13, the app compiles properly.

**Comment by Widcket** [comment]
Can you reproduce this with the [sample app](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login)?

**Comment by poovamraj** [comment]
Hi @shawna-donnelly, any update on this?

**Comment by shawna-donnelly** [comment]
Sorry about that. I tried the sample app and it worked, so it was something in my setup. I don't remember what I did, but I think it was just making sure to clear out all lock files, remove pods, remove node_modules, and reinstall and clear cache, and I think it worked. It is working now. Thanks for your guidance!
