### ISSUE TITLE
useAuth0 / Auth0Provider types

### ISSUE THREAD

**Issue by kulak91** [auth0/react-native-auth0#553]
### Describe the problem you'd like to have solved

Hello, guys! i'm trying to use auth0 "useAuth0" hook, but @types react-native-auth0 has old typing, because it hadnt been updated for 5 months already. 
https://www.npmjs.com/package/@types/react-native-auth0

### Describe the ideal solution

Would you mind to update @types/react-native-auth0 with fresh info? Or how can i use it right now in my app?

**Comment by poovamraj** [comment]
Hi @kulak91, 

We already have a community effort on this - https://github.com/auth0/react-native-auth0/issues/525

and we would love for anyone to contribute on it.

We would like to track that issue there so closing this one. Feel free to join in the discussion in that thread.
