### ISSUE TITLE
Expo unexpected prompt with duplicate apps

### ISSUE THREAD

**Issue by jkerning-clone** [auth0/react-native-auth0#554]
### Describe the problem

I ran into an issue where after properly logging in on Android (device or emulator), I am presented with duplicate copies of my app and prompted to select which of the two copies I would like to use to open the link. One seems to work, and the other seems to return an error. Usually I am not prompted to make this selection as there should only be one "intent receiver" for my app (using quotes due to my lack of detailed understanding of how intents work on android).

Here are some similar links that shed some light on potential resolution steps:
1) #536 
2) #533 

### What was the expected behavior?

I expect to not receive a prompt after successfully entering my login code.

### Reproduction
- Step 1. Download Expo Sample App: https://auth0.com/docs/quickstart/native/react-native-expo/00-login
- Step 2. Follow Expo Sample App setup steps (i.e. configure callback & logout URLs, make sure Node.js LTS, Yarn, and Cocoapods are installed)
- Step 3. Execute the follow commands (as per expo guide): `yarn install && expo prebuild && expo run:android`
- Step 4. Login with proper credentials
- Step 5. Observe prompt to select duplicate app (see screenshot)

### Environment

- **Version of this library used:** Sample - v2.14.0 (v2.15.0 in my project)
- **Which framework are you using, if applicable:** Expo?
- **Other modules/plugins/libraries that might be involved:** See below.
- **Any other relevant information you think would be useful:** I am fairly certain the issue is coming from `./android/app/src/main/AndroidManifest.xml` 
 - Specifically, line 20's `android:launchMode="singleTask"` 
 - and lines 25-30's intent filter: ` <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="com.auth0samples"/>
      </intent-filter>` 
      
Since this file is generated during the expo prebuild step, I think this issue could potentially be resolved by having the auth0 config plugin remove these sections of code from the manifest during the prebuild phase.

If I can figure out how to edit the config plugin myself AND the library maintainers deem its worth the effort, would a PR be welcome?

**Comment by poovamraj** [comment]
Hi @jkerning-clone this issue has been fixed and discussed here - https://github.com/auth0/react-native-auth0/issues/531

Looks like we haven't updated the samples. I have created a PR for it here - https://github.com/auth0-samples/auth0-react-native-sample/pull/91

**Comment by jkerning-clone** [comment]
Hi @poovamraj 

Thanks for the reply. I am experiencing the issue on v2.15.0 on my app. I had just pointed out the sample app where I could similarly reproduce the bug was using v2.14.0.

When I run `expo prebuild --clean` with the appropriate auth0 config plugin for v2.15.0, my AndroidManifest.xml has both of these pieces of code added:
- AndroidManifest.xml:20`android:launchMode="singleTask"`
- AndroidManifest.xml:25-30`<intent-filter> <action android:name="android.intent.action.VIEW"/> <category android:name="android.intent.category.DEFAULT"/> <category android:name="android.intent.category.BROWSABLE"/> <data android:scheme="com.auth0samples"/> </intent-filter>`

Removing them solves the issue I am having. Is removing these lines still the recommended way to resolve this issue? Or will it lead to downstream issues?

Additionally, updating the sample to the latest version doesn't resolve the issue for the sample either. Not sure if additional code changes are needed.

**Comment by poovamraj** [comment]
Hi @jkerning-clone, can you run this command and see what are all the intent receivers you have for your package name - `adb shell dumpsys package r`. They can be in different locations so it would be great to comb through them or grep them

**Comment by jkerning-clone** [comment]
I ran: `grep 'my.package' androidlogs.txt` and here was the output (substituting my package name):
      `
      my.package:
        8e928f1 my.package/.MainActivity
        b9c1644 my.package/com.auth0.react.RedirectActivity
        8e928f1 my.package/.MainActivity
        ... 
       `

I had 4 others used by the background geolocation library I use, so those were replaced with `...`

**Comment by jkerning-clone** [comment]
I am not using any custom scheme. Is that required to get this working?

**Comment by jkerning-clone** [comment]
I am not using any custom scheme. Is that required to get this working? Mistakenly closed the issue.

**Comment by poovamraj** [comment]
@jkerning-clone If there is a clash between the other intent receivers then you can use a custom scheme for login. You can test it with a custom scheme to verify this and decide based on that

**Comment by jkerning-clone** [comment]
A custom scheme prevents the prompt from popping up on Android. The clash in intent receivers is being caused by a recent upgrade to another library.

Thank you @poovamraj for the help.

**Comment by AndonMitev** [comment]
Hey guys, sorry but i'm pretty new to mobile development and i'm trying to solve this issue, how to create custom scheme? Now i do have one which i take from here `<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="my-custom-scheme" xmlns:tools="http://schemas.android.com/tools">` and is used in callback urls but also can see it it here:

```
 my-custom-scheme:
        975ba9a  my-custom-scheme/.MainActivity
        a64e666  my-custom-scheme/com.auth0.react.RedirectActivity
```

**Comment by AndonMitev** [comment]
I'm having same issue with `2.15.0`. I have only this intentfilter:

```
{
              action: 'VIEW',
              data: [
                {
                  scheme: 'my-custom-scheme',
                },
              ],
              category: ['BROWSABLE', 'DEFAULT'],
            },
```

running `adb shell dumpsys package r` output this:

```
my-custom-scheme:
        975ba9a my-custom-scheme/.MainActivity
        a64e666 my-custom-scheme/com.auth0.react.RedirectActivity
```


And inside `AndroidManifest.xml` i have these `intent filters`:

```
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="scheme1"/>
        <data android:scheme="scheme2"/>
        <data android:scheme="scheme3"/>
      </intent-filter>
      <intent-filter data-generated="true">
        <action android:name="android.intent.action.VIEW"/>
        <data android:scheme="scheme2"/>
        <data android:scheme="scheme3"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>
```

**Comment by poovamraj** [comment]
@AndonMitev Looks like your scheme `my-custom-scheme` is used for `MainActivity` as well. I am not sure which intent filter is catching it as it just mentions `scheme*` instead of the `my-custom-scheme`.

**Comment by AndonMitev** [comment]
> @AndonMitev Looks like your scheme `my-custom-scheme` is used for `MainActivity` as well. I am not sure which intent filter is catching it as it just mentions `scheme*` instead of the `my-custom-scheme`.

@poovamraj , sorry for the confusion i have update it

**Comment by AndonMitev** [comment]
@poovamraj i have removed my custom intent-filter and now looks like this:

```
<activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen" android:exported="true" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="defiwallet"/>
        <data android:scheme="dev.ooo.opn.wallet"/>
        <data android:scheme="exp+defi-wallet"/>
      </intent-filter>
      <intent-filter android:autoVerify="true" data-generated="true">
        <action android:name="android.intent.action.VIEW"/>
        <data android:scheme="https" android:host="1b1.art" android:pathPrefix="/claim"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <category android:name="android.intent.category.DEFAULT"/>
      </intent-filter>
    </activity>
```

**Comment by AndonMitev** [comment]
@jkerning-clone can you share example of you `custom scheme` please

**Comment by erisvaldojunior** [comment]
@AndonMitev were you able to fix it? Same issue

**Comment by TehillahK** [comment]
@erisvaldojunior @AndonMitev did you figure out this issue?
