### ISSUE TITLE
Android `singleTask` launch mode is required for react-native deep links 

### ISSUE THREAD

**Issue by cjpete** [auth0/react-native-auth0#556]
By default react-native projects are created with a launchMode of `singleTask`, presumably so that deep links (via Linking) are supported out of the box: https://reactnative.dev/docs/linking#enabling-deep-links 

However, using a launchMode of `singleTask` prevents this package from working properly (https://github.com/auth0/react-native-auth0/pull/350) 

When using the `standard` launchMode, opening deep links to your app can result in multiple instances of your app running, which is not an acceptable user experience.

**Comment by poovamraj** [comment]
Hi, @cjpete can you provide us with more information on the issue? Following the issue template will give us the required details to work on your issue.

**Comment by poovamraj** [comment]
@cjpete, closing this issue for now. Please feel free to reopen this with more information
