### ISSUE TITLE
Change name app at alert IOS

### ISSUE THREAD

**Issue by lehuydev2203** [auth0/react-native-auth0#559]
Now, When I click login on ios device, it displays the question as shown below and I want to change the application name, where should I edit it.

<img width="651" alt="Screenshot 2022-11-17 at 15 38 20" src="https://user-images.githubusercontent.com/41155784/202397706-f6baf2a3-041d-49f9-958e-16a8c243e098.png">

**Comment by Widcket** [comment]
Hi @lehuydev2203, thanks for raising this.

The `ASWebAuthenticationSession` alert uses the app's target name, AFAIK. I'm afraid this is not something SDK-specific, but iOS specific.

**Comment by Widcket** [comment]
How to change the target name in Xcode:

<img width="705" alt="Screen Shot 2022-11-17 at 20 44 57" src="https://user-images.githubusercontent.com/5055789/202583771-a72815c3-e8ae-4324-990e-5a694008ab33.png">

Make sure to clean the build cache afterward.
