### ISSUE TITLE
[Auth0 API] React-Native@0.35.0 not compatible Auth0 API

### ISSUE THREAD

**Issue by gillesBzk** [auth0/react-native-auth0#56]
I try to use the Auth0 API, instead of the Lock (because of issues concerning the grant authorization), but it seems it’s not compatible with React-Native@0.35.0 (my case).

I would like to know, if in my configuration it is possible to use Auth0 API or not.
Upgrading react-native version, it is not a possibility right now.

Thank you in advance
Gilles

**Comment by cocojoe** [comment]
@gillesBzk can you be more specific please:

- what doesn't work exactly?
- what are you trying to achieve?
- what happens? any error logs etc?

Thanks

**Comment by cocojoe** [comment]
Closing, lack of activity.
