### ISSUE TITLE
`expo-cli doctor` warns about `@expo/config-plugins@4.1.5` being an invalid package

### ISSUE THREAD

**Issue by jferrettiboke** [auth0/react-native-auth0#563]
### Describe the problem

`expo-cli doctor` warns about an invalid package (`@expo/config-plugins@4.1.5`) when using Expo SDK 47 and `react-native-auth0` in its latest version (at this moment of writing it is v2.16.0).

### What was the expected behavior?

No warnings should pop up when executing `expo-cli doctor` and using Expo SDK 47 and latest version of `react-native-auth0`.

For that to occur, `@expo/config-plugins` dependency should be bumped from v4.x to v5.x in `react-native-auth0`.

### Reproduction

1. `npx create-expo-app my-app && cd my-app`
2. `yarn add react-native-auth0`
3. Import `react-native-auth0` somewhere (e.g. `App.js`)
4. `npm i -g expo-cli`
5. `expo-cli doctor` (You'll see the warning right after executing this command)

<img width="409" alt="Screenshot 2022-11-23 at 14 00 16" src="https://user-images.githubusercontent.com/11066224/203553064-1cbd5bcd-841a-48eb-972c-e6bcf5d2a313.png">

### Environment

- **Version of this library used:** 2.16.0
- **Which framework are you using, if applicable:** Expo SDK 47
- **Other modules/plugins/libraries that might be involved:** `@expo/config-plugins`
- **Any other relevant information you think would be useful:**

<img width="553" alt="Screenshot 2022-11-23 at 14 00 34" src="https://user-images.githubusercontent.com/11066224/203553130-a6b1466b-f35b-4111-bc48-640055041f57.png">

**Comment by robpearmain** [comment]
I came here to raise the same issue,  current version is 5.0.3

**Comment by poovamraj** [comment]
@jferrettiboke @robpearmain Thanks for raising this. I checked this out and can confirm the warning is there. But also this doesn't seem to affect the working of the SDK even in Expo 47.

The configuration recommended by Expo here - https://docs.expo.dev/guides/config-plugins/#developing-a-plugin would be a breaking change as the current SDK supports beginning from version 46.

Is there any issue being faced because of using this version of the config-plugin? I am not able to face any. 

We will be moving to Expo recommended configuration in one of the future releases but not in the current one though. If there is unavoidable breakage happening because of this, you can override the dependency like below which is supported from NPM >= 8.3

```json
  "overrides": {
    "react-native-auth0": {
      "@expo/config-plugins": "^5.0.2"
    }
  }
```

I tested this as well and it works well.

**Comment by poovamraj** [comment]
We are also tracking the update task for this internally as SDK-3885

**Comment by poovamraj** [comment]
Since this is a warning and we have are tracking this internally to fix this in the next major. We will close this issue for now. Please feel to reopen it if you have more doubts. We will update this thread once it is fixed in our future release.

**Comment by gbower30** [comment]
> @jferrettiboke @robpearmain Thanks for raising this. I checked this out and can confirm the warning is there. But also this doesn't seem to affect the working of the SDK even in Expo 47.
> 
> The configuration recommended by Expo here - https://docs.expo.dev/guides/config-plugins/#developing-a-plugin would be a breaking change as the current SDK supports beginning from version 46.
> 
> Is there any issue being faced because of using this version of the config-plugin? I am not able to face any.
> 
> We will be moving to Expo recommended configuration in one of the future releases but not in the current one though. If there is unavoidable breakage happening because of this, you can override the dependency like below which is supported from NPM >= 8.3
> 
> ```json
>   "overrides": {
>     "react-native-auth0": {
>       "@expo/config-plugins": "^5.0.2"
>     }
>   }
> ```
> 
> I tested this as well and it works well.

I am experiencing this issue as well. It is occurring when attempting an EAS build during the Run Expo Doctor phase and is causing the build to fail.
