### ISSUE TITLE
Password flow

### ISSUE THREAD

**Issue by normanzb** [auth0/react-native-auth0#566]
### Describe the problem you'd like to have solved

Username and Password login flow is not supported by `react-native-auth0`, no method on `auth` object allows login with explict username and password.

See username and password login flow details here: https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-resource-owner-password-flow
Password credential grant in oauth spec: https://www.rfc-editor.org/rfc/rfc6749#section-1.3.3

`auth.exchange()` does talk to `/oauth/token` but the type is missing username and password parameter, and it doesn't explicity saying it support username/password login

### Describe the ideal solution

add a new method to `auth` object with full support of username/password login, add it into example documention.

## Alternatives and current work-arounds

extend existing type and description of `auth.exchange` to support password and username field

**Comment by Widcket** [comment]
Hi @normanzb, thanks for raising this.

Logging in with username/password is supported: https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md#login-with-password-realm-grant

**Comment by normanzb** [comment]
> Hi @normanzb, thanks for raising this.
> 
> Logging in with username/password is supported: https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md#login-with-password-realm-grant

hi @Widcket thanks for reply but this one asks is for realm grant, while the case i raised above was for password grant. Also the API asks for `realm` parameter that I don't have for a password grant login.

**Comment by Widcket** [comment]
It is an extension grant; you just need to pass the name of the connection (e.g. `Username-Password-Authentication`) as the value of the `realm` parameter.

<img width="808" alt="Screen Shot 2022-11-29 at 17 47 25" src="https://user-images.githubusercontent.com/5055789/204644380-526e0166-19e9-4562-a378-4b1d7cd86c6d.png">


See https://auth0.com/docs/get-started/authentication-and-authorization-flow/resource-owner-password-flow#realm-support

**Comment by normanzb** [comment]
hey thanks for the help, it does work for my case as I tested it out, appreciate it! 

I wonder if it would help others if we make it more apparent by having a dedicated method or mention in the doc sites tho.
