### ISSUE TITLE
Stuck at universal login when react native app was launched from other app using startActivityForResult

### ISSUE THREAD

**Issue by mansnilssonQred** [auth0/react-native-auth0#568]
### The problem
I'm working on a mobile app where customers can manage a credit card that our company offers. We're currently integrating with the Google Wallet app (for Google Pay provisioning). 
We're having issues with one of the provisioning flows which is initiated in the Google Wallet app. The customer can select to open our mobile app so that we can identify & verify the customer (Strong Customer Authentication) in order for them to get authorized to add their card to Google Pay. Google calls this flow the ["App-to-App verification"](https://developers.google.com/pay/issuers/tsp-integration/app-to-app-idv) flow.

The issue is that the in-app browser/custom tab doesn't close after a successful login, so we're stuck at that point. 

**Short video of the problem, you can see longer videos in the table below**

https://user-images.githubusercontent.com/70260200/205515217-7c1e8afb-6eec-4bc4-98fa-8d0e32535d9d.mov

Note: If I modify our "Dummy Wallet App" and add `FLAG_ACTIVITY_NEW_TASK` to the intent that launches our app, then everything works as expected. So I wonder if the problem is that the `auth0samples` activity is added on the current "Dummy Wallet App" task, and then the `RedirectActivity` doesn't get resolved properly.. or something like that....?
I'm not really a very experienced Android developer, but I've been reading up a bit on this to try and figure out what's going wrong.

Please read further below, where I've added a link to a repo with a reproducible example, as well as videos linked.

### Expected behavior
The expected behavior is of course that the in-app browser/custom tab closes, and that the auth0samples app resumes as if I were logging in directly into the app.

### Reproduction
I've made reproduced the issue using a "Dummy Wallet App" and the "auth0samples" app (with some slight modifications for this example). I've pushed the code to a fork here: https://github.com/mansnilssonQred/auth0-react-native-sample
* Note that I've added a folder in the root: [dummy-wallet-app](https://github.com/mansnilssonQred/auth0-react-native-sample/tree/master/dummy-wallet-app). This is just a simple android app with a button that uses `startActivityForResult` with an intent to start the `com.auth0samples` app, specifically the activity with the name: `com.auth0samples.a2a` which I've added to the `auth0samples` AndroidManifest.xml.

#### Here's a table with some scenarios I've tested
Note that there are video links as well (added to Google Drive because the files were too big to attach here).
|Scenario|Video|Result|
|-|-|-|
|App to App verification - logcat logs visible|[Video Link Here](https://drive.google.com/file/d/1mD9gsUpIL_etp1r65mkv1iSOe_X0Nffs/view?usp=share_link)|Stuck at universal login|
|App to App verification - chrome devtools visible|[Video Link Here](https://drive.google.com/file/d/1Pc8DLuOd1r0VLyzxHWaeWx9iVuXXpBSk/view?usp=share_link)|Stuck at universal login|
|Login success with WalletProvider using FLAG_ACTIVITY_NEW_TASK.mov|[Video Link Here](https://drive.google.com/file/d/1WWSZYw0QEdnF3wDO6ZYYOdhNHOw17JqT/view?usp=share_link)|Success|
|Normal Login|[Video Link Here](https://drive.google.com/file/d/1H6VZ9xmYuL7htkpmz6w6Ozsv8x0W2sLd/view?usp=share_link)|Success (just wanted to show that the app isn't broken)|

Steps-to-reproduce:
1. Clone my fork: https://github.com/mansnilssonQred/auth0-react-native-sample
2. Open the "Dummy Wallet App" and install it on a AVD or real device
3. Open the "00-Login" app and install it on a AVD or real device.
4. Launch the `WalletProvider` app (i.e. "Dummy Wallet App")
5. Click the [App to App Verification Test] button.
6. Wait for the `Hello App Display Name` app (i.e "auth0samples" app)
7. Wait for the universal login to be displayed in a custom tab.
8. Login with a test user.

Result: The custom tab remains open with an infinite loading spinner

### Environment

- **Version of this library used:** 2.16.0
- **Which framework are you using, if applicable:** We're currently using `react-native: 0.68.5` and React 17.
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:** This is primarily related to Google Wallet launching our app in the current running task, as part of a Google Pay provisioning flow.

**Comment by poovamraj** [comment]
Hi @mansnilssonQred, Thanks a lot for this detailed error report. This was helpful for us to work with and we appreciate it.

So we were able to figure that the issue is because of Redirection creating a new instance of the "RedirectActivity" we use internally which has a state mismatch.

We tested this by replacing the Web Authentication code with our Auth0.Android SDK and it doesn't seem to reproduce, so I created a very temporary branch where you can provide your "domain" and "client_id" in `A0Auth0Module.java` and test your flow. If you verify the flow working, we can see the difference between our Auth0.Android and react-native-auth0 code and use it to fix it. (Note: It seems to work in the demo you provided)

Branch - https://github.com/auth0/react-native-auth0/tree/test/existing-task-redirection-issue

**Comment by mansnilssonQred** [comment]
Hi @poovamraj!

Thank you for the kind words, that means a lot to me!
Sorry for the late response here, been super busy with work lately. I will test this and get back to you as soon as possible!

I just want to add that we figured out a workaround, by having an intermediary "AppToApp" activity which acts like a "proxy activity". This activity will start our MainActivity with the flag FLAG_ACTIVITY_NEW_TASK, and we're able to finish this specific Google Pay provisioing flow successfully.
We would like to avoid this workarond though, so I'll test your change and get back to you.

**Comment by poovamraj** [comment]
Also, another workaround could be overriding the manifest file on your end to add the `FLAG_ACTIVITY_NEW_TASK` to the RedirectActivity. More details can be found [here](https://github.com/auth0/Auth0.Android/blob/main/FAQ.md#2-why-do-i-need-to-declare-manifest-placeholders-for-the-auth0-domain-and-scheme)

**Comment by SasClaudiu** [comment]
> Hi @poovamraj!
> 
> Thank you for the kind words, that means a lot to me! Sorry for the late response here, been super busy with work lately. I will test this and get back to you as soon as possible!
> 
> I just want to add that we figured out a workaround, by having an intermediary "AppToApp" activity which acts like a "proxy activity". This activity will start our MainActivity with the flag FLAG_ACTIVITY_NEW_TASK, and we're able to finish this specific Google Pay provisioing flow successfully. We would like to avoid this workarond though, so I'll test your change and get back to you.

Did you find something, having the same problem, logging in with google then it freezes here 
![image](https://user-images.githubusercontent.com/95215801/211771486-fd438ac4-88e6-456d-b7a9-6e0cdd390507.png)

**Comment by poovamraj** [comment]
Hi @SasClaudiu, were you able to try out the test branch mentioned above. Did it fix your issue?

**Comment by jbernhardt23** [comment]
@poovamraj when you mention to override the `com.auth0.android.provider.RedirectActivity` with `FLAG_ACTIVITY_NEW_TASK` do you mean that we need to add `android:launchMode="singleInstance"` to the `activity` tag of the `RedirectActivity` ?

**Comment by poovamraj** [comment]
Yes @jbernhardt23, this can be done using tools:node="replace" as mentioned in the link
