### ISSUE TITLE
Nullify user when clearSession is called

### ISSUE THREAD

**Issue by iovreche** [auth0/react-native-auth0#569]
Current behaviour keeps `user` in `useAuth0` hook after the `clearSession` utility has been called. This does not sound consistent to me.

**Comment by poovamraj** [comment]
@iovreche I just checked it in our sample repo here - https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks and it seems to work.

Can you provide a sample reproduction along with RN version and our SDK version so that we can look into more details on this

**Comment by poovamraj** [comment]
Hi @iovreche Any update on this?

**Comment by poovamraj** [comment]
Hey @iovreche, we will close this for now as it is not reproducing on our end. Please feel free to reopen it with more details. We will be happy to help.
