### ISSUE TITLE
CredentialsManager does not require Local Authentication to retrieve credentials

### ISSUE THREAD

**Issue by mingyjongo** [auth0/react-native-auth0#573]
### Describe the problem

I'm able to retrieve credentials using Credentials Manager without being prompted for local authentication (PIN, biometric, etc) even though `requireLocalAuthentication` was called when those credentials were saved.

### What was the expected behavior?

I would expect the call to `requireLocalAuthentication` to require authentication any time a user goes to retrieve those credentials with `getCredentials`. Instead, `requireLocalAuthentication` seems to need to be called manually prior to `getCredentials`.

### Reproduction

- Step 1: Invoke `auth0.credentialsManager.requireLocalAuthentication()` ✅
- Step 2: Store credentials (working as intended) ✅
- Step 3: Retrieve credentials (working as intended) ✅
- Step 4: Close and reopen app ✅
- Step 5: Retrieve credentials 🛑
  - At this point I would expect to be prompted for authentication; that specifying `requireLocalAuthentication` at the point of storing the credentials would gate those credentials by that local authentication in all future retrieval cases. Instead, I'm able to retrieve them without a prompt.

**Questions:**
1. Is this expected behavior?
2. Is there another way to mandate that authentication without a manual call to `requireLocalAuthentication`?

**Example:**
This will get and set credentials using Credentials Manager, using web authorization if there aren't currently any credentials stored. During the same session, this will prompt a user for authentication when retrieving credentials. If the app is closed and reopened, it will return credentials without prompting for authentication.

```typescript
const getCredentials = async () => {
  // Check for existing credentials
  const hasCredentials = await auth0.credentialsManager.hasValidCredentials()
  // If there are no credentials, we need to log in
  if (hasCredentials) {
    // Get credentials
    const credentials = await auth0.credentialsManager.getCredentials()
    // Return credentials
    return credentials
  } else {
    // Log in
    const credentials = await auth0.webAuth.authorize({ scope: 'offline_access openid email' })
    // Require local authentication
    await auth0.credentialsManager.requireLocalAuthentication()
    // Save credentials
    await auth0.credentialsManager.saveCredentials(credentials)
    // Return credentials
    return credentials
  }
}
```
### Environment

- **Version of this library used:** 2.15.0
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by poovamraj** [comment]
@mingyjongo `requireLocalAuthentication` is not saved between sessions. You have to enable it at the start of the app for it to work. Can you try it that way and let us know if you are still facing the issue?

**Comment by mingyjongo** [comment]
That works and prompts user for authentication, I just didn't think it was the intended behavior. This is good to know, thank you for the update.

Is there any way to require user authentication to retrieve credentials without manually calling `requireLocalAuthentication` each session?

**Comment by poovamraj** [comment]
>> without manually calling `requireLocalAuthentication`

Can you provide more details on it?

**Comment by poovamraj** [comment]
By default, we do encrypt the credentials and local authentication is used only for the purpose of whether to retrieve the credentials.

**Comment by poovamraj** [comment]
@mingyjongo hope we answered your question. We will close this issue for now but please feel free to reopen this if you have more doubts!
