### ISSUE TITLE
Invalid callback url for Huawei

### ISSUE THREAD

**Issue by AndonMitev** [auth0/react-native-auth0#575]
Currently we have perfectly working authentication for iOS and Android but when we try to log in with Huawei we get this screen 

![image](https://user-images.githubusercontent.com/32274987/207615299-439ec3f8-fa47-4a9b-bec1-ef8da081ac77.png)

Smartphone is `Huawei mate 20 pro` 

iOS:
`{IOS_BUNDLE_IDENTIFIER}://YOUR_DOMAIN/ios/{IOS_BUNDLE_IDENTIFIER}/callback`

Android:
`{ANDROID_PACKAGE}://YOUR_DOMAIN/android/{ANDROID_PACKAGE}/callback`

and it's working perfectly fine just on huawei facing this issues

**Comment by Widcket** [comment]
Hi @AndonMitev, thanks for raising this. In that error screen, if you scroll down there should be a button to see more details.

**Comment by AndonMitev** [comment]
Hey @Widcket, this is the error screen that i have:

![image](https://user-images.githubusercontent.com/32274987/207797762-99501e15-5b0d-49fa-9a8d-e4eb52caaa2a.png)

And if i click on View Log there is a this link:

https://auth0.auth0.com/u/login/identifier?state=hKFo2SB4X1pjSFFUOFVIOWI1N3VGN0RYLXUzaDh3a0Z0MW04U6Fur3VuaXZlcnNhbC1sb2dpbqN0aWTZIEl3R0NSbVZ3WV9nSTQ5cEtsZWFSQ20yWlhjTkdvMDdho2NpZNkgekVZZnBvRnpVTUV6aWxoa0hpbGNXb05rckZmSjNoQUk#/logs/

**Comment by AndonMitev** [comment]
Update, we just tested on another Huawei device, same issue

**Comment by Widcket** [comment]
Thanks for the information. @poovamraj please take a look.

**Comment by AndonMitev** [comment]
Hey @poovamraj 
1. It was chrome
2. We don't have access to the device it happens on end users
3. By redirect_uri you mean output from `adb shell dumpsys package r` or? For `Callback url` we are using this format: `{CUSTOM_SCHEME}://{YOUR_AUTH0_DOMAIN}/android/{YOUR_APP_PACKAGE_NAME}/callback`

**Comment by poovamraj** [comment]
@AndonMitev I meant that the URL opened in the browser for login has a parameter called `redirect_uri`. I wanted to confirm that this is same as the one you have configured for your Auth0 application. As this was the problem in the last issue you reported and this could be a similar scenario.

Also it would be great if you can share the HAR file and error messages on Chrome and app. As another addition you can try the same flow in Huawei's default browser

**Comment by poovamraj** [comment]
@AndonMitev without more information we couldn't proceed further on this. Please feel to reopen this issue with more information. Thank you.

**Comment by Losgaintir** [comment]
Was there a solution here? We're experiencing a similar situation with only Hauwei phones having issues with a callback
