### ISSUE TITLE
ID token is not being renewed

### ISSUE THREAD

**Issue by KMathisGit** [auth0/react-native-auth0#583]
### Describe the problem

ID token's `exp` value is less than current time and calling `getCredentials()` via `useAuth0` hook (or via `Auth0` class) is not renewing the ID token.

I do notice however that when the `expiresAt` value (at the root level of user credentials) is expired, it gets BOTH a new `accessToken` and `idToken`. 

Does the `exp` value on the ID token itself not play any role in the renewal process? Am I supposed to just ensure that the `expiresAt` value is <= than that of the `exp` on the idToken?

### What was the expected behavior?

The credentials manager should detect if the `idToken` is expired and if it is, renew it.

### Reproduction

Setup your ID token expiration time to be less than the expiration time of the access token.
1. Authorize yourself with auth0.
2. Verify that your ID token's `exp` value is less than the `expiresAt` value.
3. Wait until the ID token is expired, but access token is still good.
4. Get credentials via hook or class and notice that the ID token has not exchanged for a fresh one.

### Environment

- **Version of this library used: 2.16.0**
- **Which framework are you using, if applicable: Expo (EAS builds)**

**Comment by poovamraj** [comment]
Hey @KMathisGit 👋, this is working as expected. I'd suggest reading this [blog post](https://auth0.com/blog/id-token-access-token-what-is-the-difference/) which clearly states the differences and uses of both access token and ID token. 

We will close this issue for now but feel free to reopen it if you have more doubts.
