### ISSUE TITLE
How to delete user account? (Apple request)

### ISSUE THREAD

**Issue by idanlevi1** [auth0/react-native-auth0#590]
Apple required to add an option to delete a user account,
I tried to find the delete user function from react-native-auth0 but I didn't see it...
Does someone know how to do it?

``` Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/isracardteam/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 ```

**Comment by error-try-again** [comment]
This seems like a serious design oversight as account deletion is a required feature for all iOS applications with account based functionality and I believe android as well. Is there a reason this functionality is deliberately excluded from the SDK? 


> Hi @idanlevi1, thanks for raising this.
> 
> This SDK does not include a method for deleting users. That would require making a request to the [Auth0 Management API](https://auth0.com/docs/api/management/v2#!/Users/delete_users_by_id) from the app, but mobile apps are [public clients](https://oauth.net/2/client-types/). Auth0 only allows public clients to use a limited subset of the Management API. This does not include the ability to delete a user.
> 
> You'd need to create an endpoint in your backend that makes the request to the Auth0 Management API, and then call your endpoint from the mobile app using the access token.

**Comment by Widcket** [comment]
Hi @error-try-again, as mentioned, mobile apps are [public clients](https://oauth.net/2/client-types/). Auth0 only allows public clients to use a limited subset of the Management API. This is done for security reasons.
