### ISSUE TITLE
User object is missing Keys

### ISSUE THREAD

**Issue by Wolfleader101** [auth0/react-native-auth0#594]
### Describe the problem

My User object is missing key-value pairs, such as identities, app_metadata, etc.

(removed values to not doxx myself)
![image](https://user-images.githubusercontent.com/25214835/218251321-e24ad708-cfc8-4fbe-8d61-fda4a4fface5.png)

### Reproduction
My authorise function
```
      await authorize(
        {
          scope: "openid profile email name",
          prompt: "login",
          connection: connection,
          audience: "<URL>/api/v2/",
        },
        { ephemeralSession: true },
      );```

**Comment by poovamraj** [comment]
Hi @Wolfleader101, we just remove the claims mentioned [here](https://github.com/auth0/react-native-auth0/blob/master/src/jwt/utils.js) from our user object and do not remove any other claims. Are you sure you are receiving them in the first place?

**Comment by Wolfleader101** [comment]
Hi @poovamraj 
It is showing up on the auth0 dashboard in the raw JSON section. I am assuming it is sent with the standard scope of ‘openid profile email’

**Comment by poovamraj** [comment]
Can you share the raw JSON (hiding sensitive information) to compare it with the response you received?

**Comment by poovamraj** [comment]
@Wolfleader101 we will close this issue now. Please feel free to reopen this with more details.
