### ISSUE TITLE
iOS - Getting signin popup during logout

### ISSUE THREAD

**Issue by PareshPatel721** [auth0/react-native-auth0#595]
Hey
I've integrated Auth0 with my application and it working properly
But the issue is when I try to log out it prompts a sign-in message.

Below is the code I have used to logout from Auth0

 AuthService

          .webAuth

            .clearSession(federated: false) { result in

                switch result {

                case .success:

                    print("Session cookie cleared")

                case .failure(let error):

                    print("Failed with: \(error)")

                }

            }

![Simulator Screen Shot - iPhone 14 Plus - 2023-02-13 at 16 13 45](https://user-images.githubusercontent.com/33339336/218452075-337ed76d-1118-478a-8296-ea0d2406e357.png)

**Comment by Widcket** [comment]
Hi @PareshPatel721, thanks for raising this. That looks like Auth0.swift and not react-native-auth0, though 🤔 

This is documented in Auth0.swift's FAQ: https://github.com/auth0/Auth0.swift/blob/master/FAQ.md#2-how-can-i-disable-the-logout-alert-box

I'll go ahead and close this issue. Please feel free to comment if you'd prefer to reopen.
