### ISSUE TITLE
Updated to react-native-auth0 2.17.1 pod install is failing

### ISSUE THREAD

**Issue by emmanuelajaero** [auth0/react-native-auth0#597]
### Describe the problem
I updated my react-native-auth0 to 2.17.1 when I `cd ios` and run `pod install` I am getting error 

### What was the expected behavior?

I am getting the error bellow

[!] CocoaPods could not find compatible versions for pod "A0Auth0":
  In Podfile:
    A0Auth0 (from `../node_modules/react-native-auth0`)

Specs satisfying the `A0Auth0 (from `../node_modules/react-native-auth0`)` dependency were found, but they required a higher minimum deployment target.

### Reproduction

change version of package.json
`"react-native-auth0": "^2.17.1"`
delete the node_modules folder
run 
`npm install`
cd into ios folder and run
`cd ios`
then run 
`pod install`

### Log

pod install --repo-update
Auto-linking React Native modules for target `SubmeteringResident`: A0Auth0, RNCAsyncStorage, RNCMaskedView, RNCPicker, RNDeviceInfo, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNSentry, ReactNativeExceptionHandler, appcenter-analytics, appcenter-core, appcenter-crashes, lottie-react-native, react-native-blob-util, react-native-config, react-native-netinfo, react-native-onesignal, react-native-pdf, react-native-restart, react-native-safe-area-context, react-native-sensitive-info, react-native-splash-screen, and react-native-webview
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "A0Auth0":
  In Podfile:
    A0Auth0 (from `../node_modules/react-native-auth0`)

Specs satisfying the `A0Auth0 (from `../node_modules/react-native-auth0`)` dependency were found, but they required a higher minimum deployment target.
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "A0Auth0":
  In Podfile:
    A0Auth0 (from `../node_modules/react-native-auth0`)

Specs satisfying the `A0Auth0 (from `../node_modules/react-native-auth0`)` dependency were found, but they required a higher minimum deployment target.> - Application settings (redact/remove sensitive information)

### Environment
MacBook Pro 
Intel processor

- **"react-native-auth0": "^2.17.1"**
- **ReactNative**

**Comment by AdamBowler** [comment]
Same issue for me with 2.17.1

**Comment by poovamraj** [comment]
@Widcket can you check this?

**Comment by Widcket** [comment]
Hi @emmanuelajaero @AdamBowler, thanks for raising this.

The `react-native-auth0` SDK [requires iOS 12+](https://github.com/auth0/react-native-auth0/blob/master/A0Auth0.podspec#L12) since [v2.14.0](https://github.com/auth0/react-native-auth0/releases/tag/v2.14.0), where it as changed as part of https://github.com/auth0/react-native-auth0/pull/501. The Credentials Manager feature pulls in the [Auth0.swift](https://github.com/auth0/Auth0.swift) SDK, which in turn [requires iOS 12+](https://github.com/auth0/Auth0.swift#requirements), hence it was bumped here as well.
