### ISSUE TITLE
Provide saveCredentials method to Auth0Provider

### ISSUE THREAD

**Issue by sottar** [auth0/react-native-auth0#599]
### Describe the problem you'd like to have solved

I'm currently developing an application using auth0's embedded login.

I'm trying to save credentials information such as access token in the `Auth0Module` of react-native-auth0, but the useAuth0 hook does not provide a save credentials function, so we have to run `new Auth0()` to create an Auth0 instance and implement a function similar to Auth0Provider on my own.

Specifically:
1. Use [Passwordless Login](https://auth0.com/docs/authenticate/passwordless/implement-login/embedded-login/webapps) to obtain credentials from the backend
2. Create an Auth0 instance in the client
3. Execute `credentialsManager.saveCredentials()` to save credentials

Then if there is no particular reason, I would like to implement a method like saveCredentials to Auth0Provider.

### Describe the ideal solution

Add saveCredentials function like below in [Auth0Provider](https://github.com/auth0/react-native-auth0/blob/master/src/hooks/auth0-provider.js)

```js
const saveCredentials = useCallback(
    async (credentials: SaveCredentialsParams) => {
      const user = getIdTokenProfileClaims(credentials.idToken);
      await client.credentialsManager.saveCredentials(credentials);
      setState({ ...state, error: null, user });
    },
    [client]
  );
```

## Alternatives and current work-arounds

As mentioned above

**Comment by poovamraj** [comment]
@sottar we instead are planning to provide all our authentication methods through our hooks. You can look at this PR for that - https://github.com/auth0/react-native-auth0/pull/579. It is community contributed and still in progress.

We feel this is better way to provide the authentication API. Feel free to share your thoughts on this.

**Comment by sottar** [comment]
@poovamraj Thank you for your reply. That's good to know, and I think it’s a better solution too. I'll track the PR ;)
