### ISSUE TITLE
Android "User Cancelled Auth" Error 

### ISSUE THREAD

**Issue by kshah21** [auth0/react-native-auth0#60]
![screen shot 2017-07-11 at 12 02 19 pm](https://user-images.githubusercontent.com/12646467/28080189-ae6ba624-6630-11e7-850a-effa527e9fd9.png)

This is my onLogin command and what it does is it calls checkLogin which simply checks credentials and then navigates to new page if successful. This piece of code works perfectly on IOS and it navigates to the new page upon verifying the accessToken after pressing login and entering correct login info.

However, on Android the same code catches an error at line 54 after pressing login and entering correct login info.

![screen shot 2017-07-11 at 12 03 17 pm](https://user-images.githubusercontent.com/12646467/28080225-d05b0ea0-6630-11e7-8a9c-91e97b3e5c87.png)

My callbacks are configured correctly and all.

**Comment by lbalmaceda** [comment]
That error raises when you ask for authentication and you don't get it back, probably because the user "closed" the authentication screen. Please check that you've followed the [configuration steps](https://github.com/auth0/react-native-auth0#android) described in the readme.

**Comment by kshah21** [comment]
Oh man, silly mistake on my behalf. I had forgotten to include the line "android:launchMode="singleTask" in my manifest. Thanks for the super quick reply!
