### ISSUE TITLE
 Upgrade dependency @expo/config-plugins

### ISSUE THREAD

**Issue by devalnor** [auth0/react-native-auth0#601]
In Expo SDK 48 @expo/config-plugins@4.1.5 is deprecated.

`npx expo-doctor`
```
✖ Verifying prebuild support package versions are compatible
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@4.1.5
    (for more info, run: npm why @expo/config-plugins)
Advice:
  • Upgrade dependencies that are using the invalid package versions.
```

**Comment by poovamraj** [comment]
We have this issue in our backlog as SDK-3885 and plan to address it in the next major (work in planning). We will close this issue now but feel free to reopen it if anything more needs to be added to it. Thanks.
