### ISSUE TITLE
How to close / dismiss / hide an opened login modal for react-native-auth0 sdk? I tried "clearSession()" but it kept crashing the app for no apparent reasons...

### ISSUE THREAD

**Issue by adamchenwei** [auth0/react-native-auth0#602]
### Describe the problem

I want to be able to close an already open login modal when I attempt to load a captured deeplinking url in a webview screen. Currently, the login modal always overlap and I want to programmatically shut it off / hide it when I am on the webview screen. 

### What was the expected behavior?

I want to able to programmatically hide the login modal using clearSession without it crashes the app every time.

### Reproduction

(let me know if its mandatorily needed for my question! I can add a demo app or something but it will take me some time.

### Environment

```
"@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/blur": "^4.3.0",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.3",
    "@reduxjs/toolkit": "^1.9.2",
    "@storybook/react": "^6.5.13",
    "@storybook/react-native": "^5.3.27",
    "date-fns": "^2.29.3",
    "fetch-intercept": "^2.4.0",
    "i18next": "^22.4.6",
    "lodash.throttle": "^4.1.1",
    "react": "18.1.0",
    "react-content-loader": "^6.2.0",
    "react-dom": "18.1.0",
    "react-hook-form": "^7.43.2",
    "react-i18next": "^12.1.1",
    "react-native": "0.70.4",
    "react-native-auth0": "^2.16.0",
    "react-native-config": "^1.4.11",
    "react-native-dropdown-picker": "^5.4.4",
    "react-native-email-link": "^1.14.5",
    "react-native-exit-app": "^1.1.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-localize": "^2.2.4",
    "react-native-pager-view": "^6.1.4",
    "react-native-paper": "^4.12.5",
    "react-native-phone-call": "^1.2.0",
    "react-native-reanimated": "^2.14.4",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.8.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-vimeo-iframe": "^1.2.1",
    "react-native-web": "0.18.9",
    "react-native-webview": "^11.23.1",
```

**Comment by poovamraj** [comment]
@adamchenwei I am assuming the issue mentioned here is related to this - https://github.com/auth0/react-native-auth0/issues/582.

As you can see there for Expo application we recommend using "custom scheme". Details on how to use this can be found in this [PR](https://github.com/auth0/react-native-auth0/pull/610). Please let us know if this works for you.

**Comment by poovamraj** [comment]
Hi @adamchenwei hope the above answer helps. Please feel free to comment here if it doesn't work and we can reopen this issue.
