### ISSUE TITLE
 No credentials were found in the store

### ISSUE THREAD

**Issue by noelzappy** [auth0/react-native-auth0#604]
### Describe the problem

I have followed the instructions described in [HERE](https://auth0.com/docs/quickstart/native/react-native/00-login#integrate-auth0-in-your-application).

This is my `android/app/build.gradle`
```
....

 defaultConfig {
        applicationId "com.someapp.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [auth0Domain: "someapp.us.auth0.com", auth0Scheme: ${applicationId}"]
    }
.....
```

This is how my `AppDelegate.mm` looks like

<img width="736" alt="Screen Shot 2023-03-20 at 19 06 23" src="https://user-images.githubusercontent.com/38583057/226441077-6e584539-5111-4eb8-b8da-6ba57321bc38.png">

When trying to log in a user, the in-app browser opens and the authentication process is completed on the first time but on fails when trying again. The browser window opens and clickly closes without allowing the user to enter their credentials and this error message `[a0.credential_manager.invalid: No credentials were found in the store.]` is returned. 

### What was the expected behavior?

The user is able to login and I can then retrieve the `user` object and also the token using the `getCredentials()` method from the `useAuth0` hook.

### Reproduction

`App.tsx`
```Typescript

import { Auth0Provider } from 'react-native-auth0';
import { Config } from './config';

const App = () => {

  return (
    <Auth0Provider
      domain={Config.AUTH0_DOMAIN}
      clientId={Config.AUTH0_CLIENT_ID}
    >
       <RestOfApp/>
    </Auth0Provider>
  );
};

export default App;
```

`Login.tsx`
```Typescript

import { useAuth0 } from 'react-native-auth0';


const Login = () => {

  const { authorize, user, getCredentials, error } =
    useAuth0();

  const onLogin = async () => {
    try {
      await authorize();
      const creds = await getCredentials();

      console.log(error, creds);
    } catch (error) {
      console.log(error);
    } 
  };

  return (
  
      <View>
    
        <Button
          onPress={() => {
            onLogin();
          }}
         title="Login"
        />
    
      </View>
 
  );
};

export default Login;
```

`android/app/build.gradle`
```
....

 defaultConfig {
        applicationId "com.someapp.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [auth0Domain: "someapp.us.auth0.com", auth0Scheme: ${applicationId}"]
    }
.....
```

`ios/AppName/AppDelegate.mm`

<img width="736" alt="Screen Shot 2023-03-20 at 19 06 23" src="https://user-images.githubusercontent.com/38583057/226441077-6e584539-5111-4eb8-b8da-6ba57321bc38.png">

Just build and run the app and try to log in.

### Environment

- **Version of this library used: 2.17.1
- **Which framework are you using, if applicable: React Native (0.71.3)

**Comment by ashkand1985** [comment]
I am facing the same problem, any solutions ?

**Comment by poovamraj** [comment]
@noelzappy @ashkand1985 is this happening in iOS or Android? Is the package name all lower case?

**Comment by noelzappy** [comment]
I only tested on iOS.

**Comment by poovamraj** [comment]
@Widcket can you check this out?

**Comment by Widcket** [comment]
Hi @noelzappy, does this also happen on Android?
Are you able to reproduce this in our [sample app](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks)?

**Comment by vinchentso-ngouen** [comment]
Exactly the same issue here. Any workarounds ?

**Comment by noelzappy** [comment]
> Hi @noelzappy, does this also happen on Android?
> Are you able to reproduce this in our [sample app](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks)? 

No it does not happen with your sample app. And I've only been able to test on iOS.

**Comment by noelzappy** [comment]
Hi @Widcket, I have been able to fix the issue. The problem was, I was using the Keys from an app that does not have the "Native" type on Auth0. Creating a new app on Auth0 with the type "Native" and using it's key and domain rather have resolved the issue.

**Comment by paul-aster** [comment]
Hey, could we re-open this issue? I'm also experiencing the same ` No credentials were found in the store.` error. I've ensured the application type in the settings page is set to `Native`, and also ensured I'm using the correct client ID and domain. I'm able to log in (I can see a new entry in the users table in auth0), but I can't get the user as I need to render an email address

**Comment by paul-aster** [comment]
> Hey, could we re-open this issue? I'm also experiencing the same ` No credentials were found in the store.` error. I've ensured the application type in the settings page is set to `Native`, and also ensured I'm using the correct client ID and domain. I'm able to log in (I can see a new entry in the users table in auth0), but I can't get the user as I need to render an email address

Nevermind, I had to create an entirely new app which did the trick (even though the original app had the type set to Native), ah well 🤷🏾‍♂️

**Comment by mikolaj-adamowicz** [comment]
Well, creating an entirely new app in auth0 is not an option for us. It happens a lot in production. Is there any other known workaround?

**Comment by MxBM** [comment]
Was this ever resolved?

**Comment by noelzappy** [comment]
Yes it was. I was using the wrong app credentials


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
