### ISSUE TITLE
Android doesn't open the browser in RN 0.71.4

### ISSUE THREAD

**Issue by aleccss** [auth0/react-native-auth0#605]
### Describe the problem

Auth0 working properly for ios, but when I try to run it for android(emulator), the app crashes and closes. 
The error from logcat is: 
`{
"error": "a0.browser_not_available", 
"error_description": "No Browser application is installed."
}}`

### What was the expected behavior?

Opening the browser to login.

### Reproduction
After it didn't work on the app that I am working I tried with a fresh new app, just added react-native-auth0 package and a button for Log In to test it.

I also tried to install different browsers on the emulator, change the default browser, install the app on different emulators. No success.

### Environment

{
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-auth0": "^2.17.1"
  }

**Comment by devalnor** [comment]
No idea. Except restart from a fresh Android simulator.

**Comment by brahimmouhamou** [comment]
Nope, not working, but thanks anyways!

**Comment by brahimmouhamou** [comment]
Hey @poovamraj ,

Thank you for replying, I'm working together with @aleccss and after digging deeper we found the problem. Our stack contained the remove activity instructions, [documented here](https://github.com/auth0/react-native-auth0#skipping-the-web-authentication-setup). 🙈

Issue can be closed.

**Comment by poovamraj** [comment]
😄 No problem! Glad it worked. Closing this issue now
