### ISSUE TITLE
Error: Activity class ... does not exist

### ISSUE THREAD

**Issue by theobouwman** [auth0/react-native-auth0#61]
### Is this a bug report?

Yes

### Have you read the Bugs section of the Contributing to React Native Guide?

Yes

### Environment
1. `react-native -v`: 0.45 & 0.46.1
2. `node -v`: v6.9.1
3. `npm -v`: 3.10.8
4. `yarn --version` (if you use Yarn): 0.17.6

Then, specify:

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra

### Steps to Reproduce

- Create a new react-native project using `react-native init ExampleProject`
- Add auth0 with `yarn add react-native-auth0` and link it `react-native link react-native-auth0`
- And configure the Android project: https://github.com/auth0/react-native-auth0#configuration
- Add Redux, React Navigation and a few other JS libraries.

### Expected Behavior

App should run without any kind of errors.

### Actual Behavior

When I want to run the app with `react-native run-android` after writing some code and adding logic without touching the native Java code and with a successful build, I get this error:
```
BUILD SUCCESSFUL

Total time: 10.072 secs
Running adb -s 0259749fb8c21037 reverse tcp:8081 tcp:8081
Starting the app on 0259749fb8c21037 (adb -s 0259749fb8c21037 shell am start -n com.woodyapplication/com.woodyapplication.MainActivity)...
Starting: Intent { cmp=com.woodyapplication/.MainActivity }
Error type 3
Error: Activity class {com.woodyapplication/com.woodyapplication.MainActivity} does not exist.
```

I managed to fix this with the following hacks:
- creating a new project and copy the JS code over (which is not a solution)
- replace the package name `com.woodyapplication` with `com.woody.application` (or something else). This fixes it for a few runs but then the error message appears again.

I've tested this with RN 0.45 and RN 0.46.1 the bug appears on both versions
Could `android:launchMode="singleTask" be the cause of this bug?

**Comment by hzalaz** [comment]
the single task should affect in no way if the activity is found and tbh seems unrelated to react-native-auth0. The error states that either the app package name declared in the manifest is wrong or the java package name of the activity (folder configuration) is wrong but its hard to tell without a sample

**Comment by cocojoe** [comment]
Closing, lack of activity.

**Comment by thiagoribeir015** [comment]
Same error happened with me out of nowhere... I managed to fix by following the steps:
- open `android` folder on Android studio and
  - build > clean project
  - build > rebuild project
- back on terminal: `react-native run-android`;
