### ISSUE TITLE
Session cookie is not retrieve in universal login webview

### ISSUE THREAD

**Issue by TommyTheTribe** [auth0/react-native-auth0#612]
### Describe the problem

I login in a safari browser using universal login, with a custom domain
I call webAuth.authorize() in my react native application
Webview is opened (safari) with the good url, but the prompt ask me to login with user/password (automatic login not working)
I copy the webview link in my safari browser
I'm automatically logged in

### What was the expected behavior?

Webview should access session cookie, in order to perform automatic login 

### Reproduction
Same as above

### Environment

react-native-auth0: ^2.17.1
react-native: 0.71.0,
Iphone 14

**Comment by Widcket** [comment]
Hi @TommyTheTribe, thanks for raising this.

To have Single Sign On (SSO) between a page opened with `SFSafariViewController` and your app, your app also need to be using `SFSafariViewController` to log in. Unfortunately, this SDK does not support logging in with `SFSafariViewController`, only with `ASWebAuthenticationSession`.

**Comment by TommyTheTribe** [comment]
Thanks for response @Widcket !
