### ISSUE TITLE
Android redirection is broken

### ISSUE THREAD

**Issue by TommyTheTribe** [auth0/react-native-auth0#613]
_showUrl_ function and _onActivityResult_ returns _User cancelled the Auth_, so the _redirectURL_ value in agent _show_ method is undefined.

I don't think we need to get the _redirectURL_ from  _onActivityResult_ cause the Linking event listener already do the job, and returns a promise. I've tried to replace :

```
NativeModules.A0Auth0.showUrl(url, ...params, (error, redirectURL) => {
        if (!skipLegacyListener) {
          removeListener();
        }
        if (error) {
          reject(error);
        } else if (redirectURL) {
          resolve(redirectURL);
        } else if (closeOnLoad) {
          resolve();
        } else {
          reject(new Error('Unknown WebAuth error'));
        }
      });
```

With 

```
NativeModules.A0Auth0.showUrl(url, ...params, (error, redirectURL) => {
        if (skipLegacyListener) {
          if (error) {
            reject(error);
          } else if (redirectURL) {
            resolve(redirectURL);
          } else if (closeOnLoad) {
            resolve();
          } else {
            reject(new Error('Unknown WebAuth error'));
          }
        }
      });
```

and everything seems to be fine.

Seems to be related to [504](https://github.com/auth0/react-native-auth0/issues/504)

**Comment by KMathisGit** [comment]
I have recently been having issue myself and would just like to see how similar our issues are with these questions:

After a successful login, does webpage just sit on a blank page?
Are you using `customScheme` parameter?

I have an expo app that recently started showing an "open with" with duplicated app upon auth0 redirecting to my app after a successful login. I did research and found that many others also experienced this and we were suggested to use `customScheme` in order to solve this. Now, I have an issue where after successful login, the web page (chrome app) just sits on a blank page.

**Comment by poovamraj** [comment]
@TommyTheTribe suggested, are you using Expo? Are you using `customScheme` which we had to make as mandatory?

This issue occurs if you are using the SDK without `customScheme` in the `authorize` call.

**Comment by TommyTheTribe** [comment]
> Hi @TommyTheTribe, I have recently been having issue myself and would just like to see how similar our issues are with these questions:
> 
> After a successful login, does webpage just sit there? Are you using `customScheme` parameter?
> 
> I have an expo app that recently started showing an "open with" dialog with duplicated options of my app upon auth0 redirecting to my app after a successful login. I did research and found that many others also experienced this and we were suggested to use `customScheme` in order to solve this. Now, I have an issue where after successful login, the web page (chrome app) just sits there as if nothing happened.



> @TommyTheTribe suggested, are you using Expo? Are you using `customScheme` which we had to make as mandatory?
> 
> This issue occurs if you are using the SDK without `customScheme` in the `authorize` call.

The issue appears even if I use the customScheme parameter.

_After a successful login, does webpage just sit there?_

No, for me the webpage is closed with an error : User cancelled the Auth

It seems that something wrong happens in this part of code : 

```
@Override
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
        Callback cb = A0Auth0Module.this.callback;

        if(requestCode == LOCAL_AUTH_REQUEST_CODE) {
            secureCredentialsManager.checkAuthenticationResult(requestCode, resultCode);
            return;
        }

        if (cb == null) {
            return;
        }

        boolean hasResult = resultCode == RESULT_OK &&
                requestCode == AuthenticationActivity.AUTHENTICATION_REQUEST &&
                data.getData() != null;
        if (hasResult) {
            cb.invoke(null, data.getData().toString());
        } else {
            final WritableMap error = Arguments.createMap();
            error.putString("error", "a0.session.user_cancelled");
            error.putString("error_description", "User cancelled the Auth");
            cb.invoke(error);
        }

        A0Auth0Module.this.callback = null;
    }
```

**Comment by poovamraj** [comment]
@nullboyy 

> Do you need some gifs displaying the behavior? I can provide a minimal expo-based repository so you can reproduce the issue but it's really trivial, just run an expo project from scratch, setup the app with the library and you can see it's happening.

This would be great! Apart from that you can also use this command to see which schemes are set to open your application

`adb shell dumpsys package r`

sharing that would be helpful as well

**Comment by poovamraj** [comment]
@KMathisGit @TommyTheTribe Can you share how you call the `authorize` method? `customScheme` parameter has to be set for this to work.

**Comment by poovamraj** [comment]
Looks like this issue is not reproducible. Please feel free to comment here and we can reopen this issue if you need more help.
