### ISSUE TITLE
Going right to MFA using the users stored credentials

### ISSUE THREAD

**Issue by KristiOrium** [auth0/react-native-auth0#616]
I can login successfully using this library. 
Once the user is authenticated, and goes to a specific place in the app (e.g. change user settings), I need to show the MFA Webview without forcing the user to authenticate again (with the user credentials that are already stored in the app).

Is this possible with this library at the current state?

**Comment by poovamraj** [comment]
@KristiOrium you can authorize again using a 'prompt' as mentioned here - https://auth0.com/docs/customize/universal-login-pages/customize-login-text-prompts. This can be sent as a parameter in the `authorize` call. Hope this answers your question.

**Comment by eightyfive** [comment]
Hello,

@poovamraj 

I cannot seem to reach the `mfa-otp-challenge` screen directly, skipping the `login` screen.

In my Expo app, I would like to be able to ask/prompt the user to re-authenticate with a fresh MFA code. Without putting  email + password again.

_Note_: The user is already authenticated.

**Use case 1**

```ts
const creds = await client.webAuth.authorize({
  scope: 'openid profile email',
  audience: REACT_APP_AUTH0_AUDIENCE,
  prompt: 'mfa-otp-challenge'
})
```

It opens the Native we popup (Mobile app - Expo), loads the universal login page (or seems to), then closes it right away.

**Use case 2**

```ts
const creds = await client.webAuth.authorize({
  scope: 'openid profile email',
  audience: REACT_APP_AUTH0_AUDIENCE,
})
```

Same as use case 1.


**Use case 3**

```ts
const creds = await client.webAuth.authorize({
  scope: 'openid profile email',
  audience: REACT_APP_AUTH0_AUDIENCE,
  prompt: 'login'
})
```

It loads the universal login page correctly and ask user to re-authenticate (kinda force new login??)

_Note_: I might have clicked "Remember this device for 30 days" does it affect it? Nevertheless, sometimes I want to bypass that as well if it affects. I want to force the User to enter a fresh MFA code and get a corresponding new Access Token.

Cheers

**Comment by dominictobias-bullish** [comment]
> In my Expo app, I would like to be able to ask/prompt the user to re-authenticate with a fresh MFA code. Without putting email + password again.

I would like this too. The package doesn't work properly - passing a custom scope e.g. `prompt-mfa` which triggers `api.multifactor.enable('any', { allowRememberBrowser: false })` in an Action in Auth0 doesn't work properly, but works perfectly fine on Desktop. With this package it opens a useless page saying "Please enter your OTP", not specifying where that OTP comes from (and the OTP I already added to the account doesn't work). On Desktop I can do a WebAuthn.
