### ISSUE TITLE
iOS modal should use the displayName instead of the projectName

### ISSUE THREAD

**Issue by frArdouin** [auth0/react-native-auth0#618]
On iOS login, we get a modal to get permission to login with a certain domain. That modal is currently displaying the xCode projectName instead of the displayName.

The displayName should be used for everything related to client facing

![Capture d’écran, le 2023-04-18 à 16 03 59](https://user-images.githubusercontent.com/7546486/232896938-55e08eff-6cd9-41c1-9c8c-55dbb1beee52.png)

react-native-auth0 v2.14.1

**Comment by Widcket** [comment]
Hi @frArdouin, thanks for raising this. I'm afraid that's an `ASWebAuthenticationSession` matter, outside of our control. I'd suggest filing a bug with Apple.
