### ISSUE TITLE
Failed Exchange - type: 'feacft'

### ISSUE THREAD

**Issue by ignaciosantise** [auth0/react-native-auth0#62]
Im trying to login with an Authorized google account, but i get "Unauthorized" in the app, and this is what i see in the logs:

![fail](https://user-images.githubusercontent.com/25931366/28172047-bce8072e-67c0-11e7-921a-0f423d2fc900.png)

It returns a success and a second later it returns two Failed Exchange errors.

Here's my code:
```
auth0.webAuth
      .authorize({ scope: 'openid email', connection: 'google-oauth2' })
      .then(credentials => console.log(credentials))
      .catch(error => console.log(error));
```

and here is the Failed Exchange raw:
```
{
  "date": "2017-07-13T14:41:50.767Z",
  "type": "feacft",
  "description": "Unauthorized",
  "connection_id": "",
  "client_id": "xxxx",
  "client_name": null,
  "ip": "xxxx",
  "user_agent": "com.<appname>.<appname>/8 CFNetwork/808.2.16 Darwin/16.0.0",
  "user_id": "",
  "user_name": "",
  "auth0_client": {
    "name": "react-native-auth0",
    "version": "1.0.3"
  },
  "log_id": "xxxx"
}
```

The same account works fine when i use `react-native-lock` to login.

#### Additional info
* react-native: 0.45.0
* react-native-auth0: 1.0.3
* Platform: Android and iOS

**Comment by hzalaz** [comment]
@ignaciosantise could it be that you are using Auth0's developer keys for Google?

**Comment by ignaciosantise** [comment]
@hzalaz im really not sure, how can i check that?

**Comment by hzalaz** [comment]
@ignaciosantise in the Dashboard section for Social connections you should see a warning banner on top or just open google connection settings and if its empty you are using auth0's

**Comment by ignaciosantise** [comment]
@hzalaz the google connection is not empty. I tried reinstalling the Authorization Extension but now i get 'Authorization Extension: Invalid API Key'. Should i close this issue and open another one?

In the other hand, do you now how what is the problem now?

**Comment by hzalaz** [comment]
@ignaciosantise I personally don't have a lot of details on the inner workings of the extensions and seems a bit unrelated to the library, I'd advise contacting our support team via https://support.auth0.com since they will be better equipped to see whats wrong with you.

**Comment by ignaciosantise** [comment]
@hzalaz I solved the API Key problem, and now im getting the first error again. In the logs i see a successfull login followed by two 'Failed Exchange' errors. The curious thing is that in a previous version of my app i use `react-native-lock` and it works perfectly

**Comment by hzalaz** [comment]
@ignaciosantise its odd since I cannot reproduce that. Did you try with our samples to isolate the issue to our sdk or your app?

**Comment by ignaciosantise** [comment]
@hzalaz I just tried with auth0 sample app and i get the same error. One 'Success Login' followed by two 'Failed Exchange'

**Comment by hzalaz** [comment]
Odd, can't repro it here. Can you contact support and supply them with your tenant information so they can take a look since its not great to ask that information.

**Comment by hzalaz** [comment]
You can contact support in https://support.auth0.com

**Comment by ignaciosantise** [comment]
Thanks for your time! I finally solved the problem by changing the prop 'Client Type' to Native.
![screen shot 2017-07-14 at 11 45 21 am](https://user-images.githubusercontent.com/25931366/28217021-0f2f7f3e-688a-11e7-8367-1de28a77eb9b.png)

**Comment by karlguillotte** [comment]
Hi @hzalaz , 

I have the same issue. I kind of solve my issue by creating a new client and assigning the `Client Type`. However, I still need to use the client I initially created and that and my website is using. I am wondering if I change the `Client Type` to `Native` if the website will still be working. 

Thanks!

**Comment by nilobarp** [comment]
I was deploying apps from CLI and got this error. Solution was to change the value to something else and then back to native again.

Seems like an issue with [auth0-deploy-cli](https://github.com/auth0/auth0-deploy-cli) that it fails to set the value properly.

**Comment by paulfalgout** [comment]
So @nilobarp 's suggestion worked for me too, which is pretty concerning.  We loaded our app in via the github extension so the app was not added via manage.auth0.com.  It kept failing checking the code with `client_name` `null`.  The fix was to change the type to something else, and change it back.. then everything started working.  This seems like a sizable auth0 bug.  Though not particularly related to this library directly.

**Comment by lambdalisue** [comment]
@paulfalgout 

Thanks for your comment. Without your hint, I could not found the reason for that. In my case, `token_endpoint_auth_method` attribute was missed when the client has created through the management API. Appling that attribute through the management API solved the issue.

See 
https://community.auth0.com/t/failed-exchange-feacft-until-the-client-is-saved-through-auth0-dashboard-manually/51264 for more detail.

**Comment by radekska** [comment]
@lambdalisue thanks for bringing this up! I was losing my mind since the PKCE flow worked well for an SPA app on dev tenant, whereas it failed on prod even though the apps' configurations were almost identical.

The issue I had was that `token_endpoint_auth_method`  was set to `client_secret_basic` for the failing prod app whereas `none` for working dev app.

Switching an `Application Type` back and forth fixed the issue. 🙏
