### ISSUE TITLE
useAuth0 allow refreshToken functionality

### ISSUE THREAD

**Issue by shawna-donnelly** [auth0/react-native-auth0#625]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I am working to refresh a user's authorization scope after an invitation code is redeemed. Currently, I have to send `prompt:consent` to allow for the scope that was added on redeeming the invitation code. I haven't been able to find a way to refresh the token using `useAuth0` and do not see the `getTokenSilently` method being available, either. 

### Describe the ideal solution

I'd be able to refresh a user's scope without the user even noticing that something is happening. 

### Alternatives and current workarounds

I am using `prompt:consent` and am about to use the `Auth0` class directly to refresh my token.

**Comment by poovamraj** [comment]
@shawna-donnelly `getCredentials` method has a `scope` parameter - [Link](https://auth0.github.io/react-native-auth0/CredentialsManager.html#getCredentials). You can add the required scopes to this method and you can get back an access token with these scopes.

**Comment by poovamraj** [comment]
@shawna-donnelly hope this works. we will close this thread now. Please let us know if you have more doubts and we can reopen this.
