### ISSUE TITLE
Android doesn't redirect back after login successful

### ISSUE THREAD

**Issue by jurito** [auth0/react-native-auth0#626]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When logging in on Android from the [example app](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login) for the Auth0 class approach ( no hooks nor expo ) the login page won't redirect back to the application after the login succeeds.

### Reproduction

1. cloned the example app and installed the dependencies
2. properly filled the **manifestPlaceholders** in` /android/app/build.gradle`
3. created a fresh Auth0 application, added the correct callback URL
4. filled the credentials in the sample app with the ones from Auth0 ( domain, clientId)
5. On the built app (both on emu and real device) when tapping the login button the web form opens correctly, but after logging in it won't close anymore.
6. from the Auth0 console i can see the user logged in successfully.

### Additional context

I also tried with an arbitrary _customScheme_ in the app configuration, adding it to the `authorize` method call and accordingly to the callback URL in the Auth0 conf. Same result, login OK but no redirection.

The very same happens after upgrading an app that earlier did work perfectly with react-native-auth0 **v2.8.3** and react-native **v0.66.5**.

### react-native-auth0 version

2.16.0, 2.17.2

### React Native version

0.71.2, 0.71.4

### Expo version

none

### Platform

Android

### Platform version(s)

11, 12

**Comment by poovamraj** [comment]
Hey @jurito, Can you share the login callback URL you have in your Auth0 dashboard.

Also we would like you to run this command, search and show us the result you get for your package name `adb shell dumpsys package r`

Also a snippet (without sensitive info) on the changes you made would be great.

**Comment by jurito** [comment]
By modifying the code to remove sensitive info I could manage to make the demo work. The real world issue is instead due to [this](https://github.com/auth0/react-native-auth0/issues/421), but wasn't immediately obvious as I didn't have Auth0's admin access.
Thanks anyway and sorry for the waste of time. Have a nice day!
