### ISSUE TITLE
Sign in popup appears when you logout - Unacceptable UX so can't use auth0 in react native until fixed

### ISSUE THREAD

**Issue by anieve01** [auth0/react-native-auth0#627]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

react-native-auth0 package is currently unusable with this logout bug. 

In the same previously closed issue (https://github.com/auth0/react-native-auth0/issues/595), it was said that this is [a Auth0.swift](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md#2-how-can-i-disable-the-logout-alert-box) but I beg to differ and voice that this is effectively a react-native-auth0 issue because the problem is occurring for users of react-native-auth0; we currently can't use react-native-auth0 due to poor UX during logout!

My understanding is that the Auth0 company has brilliant engineers and amazing problem solvers. Is there some smart solution you guys can develop to address this issue? 
I'm already aware of [Matt MacAdam's thoughts ](https://community.auth0.com/t/swift-login-alert-shows-up-when-you-logout/21598/22) from 2-3 years ago on possible no-so-great alternatives; and those alternatives won't work for my team. We're using expo and we want to use auth0 for auth but with this logout issue we can't unless we find an acceptable UX for the logout flow. 

Curious enough, OpenAI just launched their own [ChatGPT app](https://apps.apple.com/us/app/chatgpt/id6448311069) on the app store and it uses Auth0 for auth and their app doesn't have this logout issue. Why?? Please perhaps provide the community with sample code using auth0 on iOS that's free of this logout issue. If an expo custom plugin for Auth0.swift is needed, then please make this available to free everyone of this pain. 

Hope someone at Auth0 takes this concern to heart and it leads to some acceptable solution soon. Thanks!

![IMG_B6F51DF2E5D8-1](https://github.com/auth0/react-native-auth0/assets/1641831/bd88208f-100f-45f5-8018-dff7e7381974)

### Reproduction

The issue is reproducible using the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample). Just login and then try to logout via the clearSession function. 

### react-native-auth0 version

2.17.2

### React Native version

0.71.8

### Expo version

48.0.15

### Platform

iOS

### Platform version(s)

iOS 16.1.1

**Comment by poovamraj** [comment]
Hi @anieve01 did you see the solution we provide in our FAQ - https://github.com/auth0/react-native-auth0/blob/master/FAQ.md#3-how-can-i-disable-the-ios-logout-alert-box ?

**Comment by BogdanRad** [comment]
Hi @anieve01, 

is working if you use this code:
`import { useAuth0 } from 'react-native-auth0';`
`const { clearSession } = useAuth0();`
`const onLogout = async () => {
    await clearSession({ federated: true }, { localStorageOnly: false })
}`

**Comment by poovamraj** [comment]
@anieve01 Hope this works for you. Please let us know if you have more doubts and we can reopen this thread. Thanks.

**Comment by zulkis** [comment]
@BogdanRad can you elaborate where did you see 'localStorageOnly' property in the ClearSessionOptions?
Latest stable 2.17.4 version does have only 'skipLegacyListener'.
