### ISSUE TITLE
Universal Login flow `invalid_request` error when calling `authorize()`

### ISSUE THREAD

**Issue by andrewflo** [auth0/react-native-auth0#630]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

A subset (~20%) of our users are seeing the following error in the in-app browser instead of Universal Login when our app calls the `authorize()` method:

> Oops!, something went wrong
>
> **invalid_request:** You may have pressed the back button, refreshed during login, opened too many login dialogs, or there is some issue with cookies, since we couldn't find your session. Try logging in again from the application and if the problem persists please contact the administrator.

This is happening in our production environment consistently for the same ~20% of users while the other users are unaffected. Our production users are exclusively using email passwordless login.

This is happening to both iOS & Android users on various OS versions including latest version (ie: iOS 16.4 & 16.5 etc.) on fresh installs of our app.

---

I've implemented the `react-native-auth0` library in our managed Expo app according to the [Auth0 Expo SDK Quickstart](https://auth0.com/docs/quickstart/native/react-native-expo/00-login) as well as the latest documentation & FAQ on this repo.

Here are some of our implementation details:

Expo **app.config.ts** config plugin settings:
```typescript
plugins: [
  [
    'react-native-auth0',
    {
      domain: '<our domain>',
      customScheme: 'com.ourcompany.auth0',
    },
  ],
  ...
]
```

**Auth0Provider**
```typescript
<Auth0Provider domain='<our domain>' clientId='<our client id>'>
  <App />
</Auth0Provider>
```

Login button:
```typescript
function App() {
  const { authorize, isLoading, user } = useAuth0();

  if (isLoading) {
    return <Loading />;
  }

  if (user) {
    return <HomeScreen />;
  }

  return (
  <View>
    // ...
    <Button title="Log in" onPress={async () => {
      try {
        await authorize(
          { scope: '<our scopes>', audience: '<our api audience>', connection: 'email' },
          { ephemeralSession: true, customScheme: 'com.ourcompany.auth0' }
        );
      } catch (error) {
        // log error
      }
    }} />
  </View>
}
```

I've also tried replacing the above code with the code from the sample app [00-Expo-Login/App.js](https://github.com/auth0-samples/auth0-react-native-sample/blob/master/00-Login-Expo/App.js) and am seeing the same results.

Application **Allowed Callback URLs** & **Allowed Logout URLs**:
```text
com.ourcompany.auth0://<our domain>/ios/<ios bundle identifier>/callback, 
com.ourcompany.auth0://<our domain>/android/<android package name>/callback
```

---

We see the following events in our logs when this error occurs:
> **Type**
> Warning During Login
> 
> **Description**
> A user has attempted to access a login page directly. This is not supported unless a "Application Login URI" is set for your application, or a "Tenant Login URI" is set for your tenant. For more information, see: https://auth0.com/docs/universal-login/default-login-url
>
> **Connection**
> N/A
> 
> **Application**
> (blank)
>
> **User**
> N/A

---

I understand the recommended solution for this error message is to implement default login routes via the _Application Login URI_ setting.

However:
1. Why does calling the `authorize()` method lead to this error in the first place? Our users are not pressing the back button or using a bookmarked or otherwise direct link to the authorize page
2.  Are there instructions on how to implement the _Application Login URI_ route to properly complete the flow back into our app authenticated with the Auth0 SDK? Setting it to a web page w/ the login flow and trying both a `redirect_uri` either back to the same web page or our app scheme doesn't result in a completion of the authentication in our app. Surely I'm missing some steps.

---

Thanks so much in advance!

### Reproduction

1. Call `authorize()` method
2. In-app browser shown w/ login flow (Universal Login screen)
3. ~20% of users instead see the error message described above

This error is consistently shown for the affected users (blocking them from logging in) whereas the users who are unaffected are consistently not seeing any error.

### react-native-auth0 version

2.17.2

### React Native version

0.71.8

### Expo version

48.0.15

### Platform

Android, iOS

### Platform version(s)

All including latest versions (iOS 16.4/16.5 etc.)

**Comment by andrewflo** [comment]
> 

@poovamraj Yes this error is shown in the in-app browser that is displayed during the login flow when our app calls `authorize()`.

iOS (left) / Android (right):

<img src="https://github.com/auth0/react-native-auth0/assets/8885443/f532f6bd-69aa-40f2-8602-fb930b828c11" width="30%" />

<img src="https://github.com/auth0/react-native-auth0/assets/8885443/8c817d04-4b4c-4573-a9d5-9cc52f45eacc" width="30.75%" />

I cloned and set up the [00-Expo-Login](https://github.com/auth0-samples/auth0-react-native-sample/blob/master/00-Login-Expo/App.js) sample app and am reproducing the issue on Android when I set my device's default browser to Firefox.

Unfortunately I can't personally reproduce the issue on Android w/ Chrome or on iOS, but we're seeing ~30-50/day of these "Warning During Login" events in our Monitoring Log and are receiving numerous customer reports of the issue in production. Most (~80%) of our users are not experiencing the issue.

Here's an example of a Warning During Login log we see when this issue occurs: 
```
{
  "date": "2023-05-30T07:34:39.284Z",
  "type": "w",
  "description": "A user has attempted to access a login page directly. This is not supported unless a \"Application Login URI\" is set for your application, or a \"Tenant Login URI\" is set for your tenant. For more information, see: https://auth0.com/docs/universal-login/default-login-url",
  "connection_id": "",
  "ip": "<USER IP ADDRESS>",
  "user_agent": "Mobile Safari 16.4.0 / iOS 16.4.1",
  "details": {
    "session_id": "j57LTvGlDByI-davIkJkQKPI1FLNcw_R"
  },
  "hostname": "<OUR AUTH0 DOMAIN>",
  "tracking_id": "b51cf878f706f674a19c",
  "user_id": "",
  "user_name": "",
  "log_id": "90020230530073440076723000000000000001223372043226158870",
  "_id": "90020230530073440076723000000000000001223372043226158870",
  "isMobile": true,
  "id": "90020230530073440076723000000000000001223372043226158870"
}
```

**Comment by poovamraj** [comment]
Hi @andrewflo thanks for the detailed response. This looks like an error in our universal login and not in our SDK. I would suggest reaching out at our [community](https://community.auth0.com/) or reach out to our support team if you are a paid customer. I will pass it along to the respective team as well. But unfortunately, the SDK couldn't be of much help here.

**Comment by andrewflo** [comment]
> Hi @andrewflo thanks for the detailed response. This looks like an error in our universal login and not in our SDK. I would suggest reaching out at our [community](https://community.auth0.com/) or reach out to our support team if you are a paid customer. I will pass it along to the respective team as well. But unfortunately, the SDK couldn't be of much help here.

@poovamraj Thanks for the insight here. I have on ongoing ticket with the support team and they've said after their internal research of the issue that they can't provide a solution.

But I can direct my troubleshoot efforts toward Universal Login to see if I get any further. Will close this issue.

Is there a way to log or otherwise debug what URL the SDK is opening via `authorize()` (before any redirects the browser makes)? That might help me with my troubleshooting.

**Comment by poovamraj** [comment]
@andrewflo best way to log it would be just directly going into the node_modules and logging the required URL. It should be built in [webauth/index.js#99](https://github.com/auth0/react-native-auth0/blob/master/src/webauth/index.js#L99)

**Comment by andrewflo** [comment]
@poovamraj Makes sense, thanks!

**Comment by MNITD** [comment]
Hey @andrewflo 

Was that issue resolved eventually? What was the reason? How did you resolve it?

I appreciate any help on that

**Comment by ribeiroantonio** [comment]
Hey! @andrewflo 

I would also appreciate any info on this matter.

We're also starting to see the same warnings and some of our users are also unable to login/seeing the same error page.

**Comment by tristanheilman-max** [comment]
Not sure if this will help anybody, but I am running into this issue today with the same small subset of users. I came across some Auth0 documentation and figured out a way to reliably reproduce the issue. This small subset of users may have cookies disabled on their default browser: [https://auth0.com/docs/authenticate/login/auth0-universal-login/configure-default-login-routes#disabled-cookies](https://auth0.com/docs/authenticate/login/auth0-universal-login/configure-default-login-routes#disabled-cookies)

You can reliably make this invalid_request error page show up by blocking all cookies through safari or chrome via Android/iOS settings app.
