### ISSUE TITLE
a0.session.user_cancelled

### ISSUE THREAD

**Issue by ymc182** [auth0/react-native-auth0#631]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Device on portrait mode
1)  Using dev server:
First click on Login calling authorize({ scope: "openid profile email offline_access" }, { customScheme: "<scheme>" }); - 
this app redirected to auth0 login panel and redirect back to the app after login
and producing`
{
  "error": "a0.session.user_cancelled",
  "error_description": "User cancelled the Auth",
}
`
checked on monitor the app logged in without exchanging token.
And when I click login again, the app now logged in and user object is now defined

2) Using EAS build on Device

Same thing happens to first login attemp, returning a0.session.user_cancelled error

however second attempt doesn't either go thru like it was on dev server

### Reproduction

1. Call authorize()

### react-native-auth0 version

^2.17.2

### React Native version

0.71.8

### Expo version

~48.0.15

### Platform

Android

### Platform version(s)

latest

**Comment by poovamraj** [comment]
@ymc182 `customScheme` cannot be a empty string like here `customScheme: "" `. Please use a string value for it and construct the callback URL in a similar way in the Auth0 Dashboard as well

**Comment by ymc182** [comment]
There are actually my custom schemes :com.abc(just eg.), I it.

And I am able to login thru dev server by logging in twice.

**Comment by poovamraj** [comment]
Can you tell the customScheme you are using and the callback URL you have in your dashboard? Even a similar sample would suffice if you are not comfortable sharing the exact customScheme

**Comment by ymc182** [comment]
`{customScheme: "com.playember.portal",}`
callback url : com.playember.portal://dev-ze6nwj8f4ouw6o3h.us.auth0.com/android/com.playember.portal/callback

**Comment by ymc182** [comment]
Thanks very much, this fixed the issue for me
