### ISSUE TITLE
Google SSO using Chrome browser on Android

### ISSUE THREAD

**Issue by alexandre-abrioux** [auth0/react-native-auth0#636]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hi! First of all, thank you for maintaining this library 🙂

As an Android user, I have another browser than Google Chrome registered as my default browser (for instance, Firefox Focus or Brave). When I log in with Google's SSO using `react-native-auth0`, I must re-enter my Google credentials in this external browser, even though my phone's operating system is already connected to this account.

### Describe the ideal solution

As an Android user, when logging in, I'm redirected to:
1. Google Chrome's application (if it is available)
2. or, the default browser application as a backup (current behavior)

In the best-case scenario (n°1), I do not need to re-enter my Google credentials.

### Additional context

This feature request is a bit similar to https://github.com/auth0/react-native-auth0/issues/116. However, in this past issue, it was suggested to use webviews as an alternative, but I've also read in https://github.com/auth0/react-native-auth0/issues/342 that this is not possible anymore (see [Google's blog article](https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html)).

Thank you for reading. Let me know what you think!

**Comment by poovamraj** [comment]
@alexandre-abrioux It won't be possible to login using your OS's Google Credentials using a browser. You need to be logged in to the Google account in the browser for this to work.

**Comment by alexandre-abrioux** [comment]
@poovamraj Thanks for your answer. Yes exactly, that is why I'm suggesting opening Google Chrome when available instead of the default browser.

**Comment by poovamraj** [comment]
I don't think even Google Chrome picks up the Google account unless the user logs into the browser (or approves to connecting the account). 

But what you seem to be looking for is a feature called BrowserPicker which we have in Android - https://javadoc.io/static/com.auth0.android/auth0/2.9.3/com/auth0/android/provider/BrowserPicker.html. This allows the developer to choose the browser they want but again this is not a preferred approach as it could lead to unwanted intentions.

**Comment by alexandre-abrioux** [comment]
> I don't think even Google Chrome picks up the Google account unless the user logs into the browser (or approves to connecting the account).

Chrome is deeply linked to Google services on Android. Chrome even [used to be Android's webview provider](https://www.xda-developers.com/google-chrome-no-longer-webview-provider-android-10/) at some point. [Google's documentation](https://support.google.com/chrome/answer/2364824?co=GENIE.Platform%3DAndroid&hl=en-GB&oco=0) specifies that you cannot use multiple profiles on Chrome on Android without adding the user account to the device. As far as I understand, Chrome being installed on the device means that:
- the user does not run a Google-free version of Android
- the user is logged in with their Google account on Chrome

> what you seem to be looking for is a feature called BrowserPicker [...] we can bring it to React Native as it uses our Auth0.Android SDK underneath

That would be awesome! Thanks🙂

**Comment by poovamraj** [comment]
@alexandre-abrioux we have taken note of this feature request. Since this is the first time we are seeing this request, we will check if the community is more interested in this feature before going ahead with the implementation. Until then we will close this issue. Please feel free to comment here and we can reopen this issue if required.
