### ISSUE TITLE
Logout?

### ISSUE THREAD

**Issue by kahitarich** [auth0/react-native-auth0#64]
Is there a logout function corresponding to webAuth.authorize? There is an logout function for the webAuth library in auth0.js for web based clients. How does a react-native user logout with react-native-auth0?

Currently, even though I can logout the user out of the app by destroying local state, the user remain logged in at the social provider and so is not prompted for credentials when they try to log in again.

**Comment by kahitarich** [comment]
See [https://community.auth0.com/questions/5796/how-do-i-completely-logout-a-user-from-a-react-nat](https://community.auth0.com/questions/5796/how-do-i-completely-logout-a-user-from-a-react-nat) for the current status ...

Status below:
_When using the method you describe the user should be performing the authentication through the system browser (which is the recommended approach for security reasons). The consequence is that if the identity provider establishes a session and you really need to terminate that session then the federated logout also needs to be performed through the system browser (since that's where the session was established).

At this time the SDK in question does not have an utility method that could be used to clear the session at the identity provider, however, I can inform you that this has been discussed and should be included. However, I cannot provide you with a definitive timeline for its availability.

Meanwhile, if you are already building the URL to the logout endpoint you may want to try to use Linking.openURL to open that URL (according to the documentation this may allow you to open the URL through the system browser)._

**Comment by lukecwilliams** [comment]
We just clear all credentials from memory and LocalStorage, and use react-native-restart to reboot the app (works for our scenario with Relay).

Of course it won't be possible to log the user out of Facebook or Google.
