### ISSUE TITLE
[EXPO][iOS]: compiling for iOS 12.0, but module 'Auth0' has a minimum deployment target of iOS 13.0

### ISSUE THREAD

**Issue by nickrugge** [auth0/react-native-auth0#646]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

expo: 48
react-native: 0.71.8
react-native-auth0: 2.17.2 to 2.17.4
platform: ios

The fastlane build phase produces the following error:

```
❌  (node_modules/react-native-auth0/ios/CredentialsManagerBridge.swift:8:8)

   6 | //
   7 | 
>  8 | import Auth0
     |        ^ compiling for iOS 12.0, but module 'Auth0' has a minimum deployment target of iOS 13.0: /Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/Auth0/Auth0.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
   9 | import Foundation
  10 | import LocalAuthentication
  11 | 
  ```

We have also tried installing `expo-build-properties` package and configure the deploymentTarget to iOS 13 for the project

```
plugins: [
   [
      'expo-build-properties',
      {
       ios: {
          deploymentTarget: '13.0',
       },
    },
  ],
]
```

but it didn't work even if the project deployment target was set to 13.0.

The build stopped working since yesterday under the exactly same conditions as before when it worked, looking at the build output logs the pods installed are changed.

```
Installing A0Auth0 (2.17.2)
Installing Auth0 (2.3.2)
```
to
```
Installing A0Auth0 (2.17.2)
Installing Auth0 (2.4.0)
```

### Reproduction

- install and configure react-native-auth0 on expo48
- run an ios build

### react-native-auth0 version

2.17.2 - 2.17.4

### React Native version

0.71.8

### Expo version

48

### Platform

iOS

### Platform version(s)

All

**Comment by poovamraj** [comment]
Hello @nickrugge, Thanks a lot for reporting this issue.

This SDK uses Auth0.Swift as one of its dependencies and it recently dropped support for iOS 12 in version 2.4. Since we used dynamic versioning to resolve the dependency we are facing this issue.

To fix this we have released a new version that points to 2.3.2 which still supports iOS 12. You can find the release here - https://github.com/auth0/react-native-auth0/releases/tag/v2.17.3

**Comment by Widcket** [comment]
As an alternative, you should be able to set a lower deployment target for Auth0.swift like in https://stackoverflow.com/a/37289688 –note that you'd have to add a conditional that checks for Auth0.swift so it doesn't set it for all pods needlessly.

You should also be able to add Auth0.swift to the Podfile, as if you were installing it on a native iOS project, but using a fixed version number: `pod 'Auth0', '2.3.2`.

**Comment by nickrugge** [comment]
Hi @poovamraj, thank you a lot for you instant support, the problem reported seems to be fixed with 2.17.3 but now a similar (and i think related) problem affects the build. 
This is the error reported during fastlane build

```
❌  (ios/Pods/Auth0/Auth0/ClaimValidators.swift:3:8)

  1 | #if WEB_AUTH_PLATFORM
  2 | import Foundation
> 3 | import JWTDecode
    |        ^ compiling for iOS 12.0, but module 'JWTDecode' has a minimum deployment target of iOS 13.0: /Users/expo/workingdir/build/ios/build/Build/Products/Debug-iphonesimulator/JWTDecode/JWTDecode.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
  4 | 
  5 | protocol IDTokenClaimsValidatorContext {
  6 |     var issuer: String { get }
```

Should i open another issue for that or is it ok staying here?


@Widcket can this be done in expo managed workflow?

**Comment by Widcket** [comment]
@nickrugge There seems to be an API for that: https://docs.expo.dev/config-plugins/development-and-debugging/#modify-ios-podfile

**Comment by Widcket** [comment]
Example usage: https://github.com/expo/config-plugins/blob/main/packages/ffmpeg-kit-react-native/src/withCocoaPodsImport.ts#L14

**Comment by AlexanderEggers** [comment]
A similar issue is also present in non-expo projects when using the latest version of RN Auth0, JWTDecode and SimpleKeychain.

For example:
`error: compiling for iOS 12.0, but module 'JWTDecode' has a minimum deployment target of iOS 13.0`

Workaround is to update the podfile using:

```ruby
installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
```

**Comment by poovamraj** [comment]
Hey All 👋 Looks like we didn't consider the tranisitive dependencies resolving dynamic versions. We have released another version that should fix this - https://github.com/auth0/react-native-auth0/releases/tag/v2.17.4. Do check it out and let us know

**Comment by nickrugge** [comment]
Thank you @poovamraj, v2.17.4 fixes build problems!! 🎉
saved my day
