### ISSUE TITLE
The error raised "No credentials were found in the store" in sample app

### ISSUE THREAD

**Issue by januswel** [auth0/react-native-auth0#660]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I got the error "No credentials were found in the store" when I'm trying out Auth0 with React Native

<img width="240" alt="image" src="https://github.com/auth0/react-native-auth0/assets/43239/1191e7d1-785c-45ea-bb9a-ddc56ac19889">

I've tried `Hooks` app

https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks

### Reproduction

1. git clone git@github.com:auth0-samples/auth0-react-native-sample.git
2. cd auth0-react-native-sample
3. yarn
4. cd ios
5. pod install
6. cd ..
7. ([make some changes to build](https://github.com/auth0-samples/auth0-react-native-sample/issues/119))
8. yarn run ios
9. tap `Log in`

### react-native-auth0 version

2.17.4

### React Native version

0.69.2

### Platform

iOS

### Platform version(s)

16.4

**Comment by januswel** [comment]
I've tried with a whole new React Native app and following instructions, my app worked well!!

https://auth0.com/docs/quickstart/native/react-native/00-login

I think there's something wrong with the sample app
I will report the issue in the sample repo, thank you!!

**Comment by Kaur-Pushpinder** [comment]
I am getting the same issue on the production native app

Auth0 version 2.7.2
