### ISSUE TITLE
react-native-auth0 uses a deprecated version of @expo/config-plugins 

### ISSUE THREAD

**Issue by WrRaThY** [auth0/react-native-auth0#670]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

react-native-auth0 uses a deprecated version of @expo/config-plugins 

### Reproduction

1. use `react-native-auth0` in your app
2. run `npx expo-doctor` - you'll see that it uses an invalid version (`@expo/config-plugins@4.1.5`)
3. Expected package `@expo/config-plugins@~6.0.0`

as expo-doctor explains this: 
```
Advice: Upgrade dependencies that are using the invalid package versions.
```

### react-native-auth0 version

2.17.4

### React Native version

0.71.8

### Expo version

~48.0.18

### Platform

Android, iOS

### Platform version(s)

any

**Comment by poovamraj** [comment]
Hello @WrRaThY, Can you try out the latest version of our SDK which is still in Beta - https://github.com/auth0/react-native-auth0/releases/tag/v3.0.0-beta.2

This should fix the issue you mentioned
