### ISSUE TITLE
[3.0.0-beta.2] Missing type exports 

### ISSUE THREAD

**Issue by gfriedm4** [auth0/react-native-auth0#675]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi there - I was previously using the `@types/react-native-auth0` library to provide types for my auth0 client and have tried to remove the dependency now that this repo has been converted into TS. 

I am missing one type that I need to be able to import directly from the library (as opposed to just using the implicit types). 

`import type { Credentials } from "react-native-auth0";`

### Reproduction

`import type { Credentials } from "react-native-auth0";`

> error TS2614: Module '"react-native-auth0"' has no exported member 'Credentials'. Did you mean to use 'import Credentials from "react-native-auth0"' instead?

### react-native-auth0 version

3.0.0-beta.2

### React Native version

0.72.1

### Expo version

49

### Platform

Android, iOS

### Platform version(s)

*

**Comment by gfriedm4** [comment]
Note: I am not confident this should be categorized as a bug, but it is a missing feature in order to have parity with the removal of `@types/react-native-auth0`.

**Comment by poovamraj** [comment]
Hey @gfriedm4 we have fixed this one in the release here - https://github.com/auth0/react-native-auth0/releases/tag/v3.0.0-beta.3

Thanks a lot for your feedback! We would really appreciate more feedback and thoughts on the SDK.
