### ISSUE TITLE
User cancelled the Auth in Android on Google login feature

### ISSUE THREAD

**Issue by Amberevol** [auth0/react-native-auth0#678]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I was implementing google login in react-native CLI which authenticates the user using gmail but after entering gmail and password it redirects to my app giving error user cancelled the Auth
{"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"}
although it's working perfectly on ios.
below are my code and AndroidManifest.xml files
![Screenshot 2023-07-17 at 4 03 33 PM](https://github.com/auth0/react-native-auth0/assets/117064129/ad699e5d-4243-4e5c-8b96-5483ce1debc1)
![Screenshot 2023-07-17 at 4 04 50 PM](https://github.com/auth0/react-native-auth0/assets/117064129/9f307229-fc83-4e82-bc14-fe68b7d197a2)

### Reproduction

1.react-native auth0
2.implement google login in react-native CLI  0.71 in android

### react-native-auth0 version

2.17.4

### React Native version

71

### Platform

Android

### Platform version(s)

sdk 33

**Comment by poovamraj** [comment]
@Amberevol Can you try this in our [latest release](https://github.com/auth0/react-native-auth0/releases/tag/v3.0.0-beta.2) and see if it reproduces.

**Comment by Amberevol** [comment]
No i can't do that it has too many breaking changes and callback URLs can't be changed don't have access to auth0 dashboard

**Comment by poovamraj** [comment]
Can you let me know the callback URL you are using? Also can you run the command `adb shell dumpsys package r` to show what intents your app has registered to receive?

**Comment by Amberevol** [comment]
There can't be any mistake in callback url cause it's working in ios  
`com.interscripts.adaptcare.dev` is my package name which is correctly included in callback URL because username and password login is working smoothly.

**Comment by Amberevol** [comment]
> Can you let me know the callback URL you are using? Also can you run the command `adb shell dumpsys package r` to show what intents your app has registered to receive?

can you please check my AndroidManifest.xml code provided above is it correct?

**Comment by poovamraj** [comment]
You seem to have multiple intent filters that can clash with the one we use in Android. Can you let us know what is the callback URL that you use for login?

Also as mentioned earlier `adb shell dumpsys package r` running this command will help you isolate all the intents you use for your application

**Comment by abhisheksaxenaa** [comment]
com.org.appname.dev://auth.auth0-custom-domain.com/ios/com.org.appname.dev/callback

@poovamraj 

Out of the above intent filters which one do you think can clash with it?

**Comment by poovamraj** [comment]
@abhisheksaxenaa @Amberevol we will close this now as it looks more like application's issue than the SDK's. Please feel free to comment here with a reproduceable sample and we can reopen this issue
