### ISSUE TITLE
auth0.auth.passwordRealm always return 401 access_denied (missing client secret)

### ISSUE THREAD

**Issue by FredericRuaudel** [auth0/react-native-auth0#68]
I spent two days trying to make the passwordRealm() function to work without any success. 

I configured my client to have the correct grant type password with realm support by patching my client as explained in https://auth0.com/docs/api-auth/tutorials/password-grant#realm-support

And when sniffing the api calls, the Auth0 module produce this HTTP request that always return 401 access_denied:

```http
POST /oauth/token HTTP/1.1
Host: MY_TENANT.eu.auth0.com
Content-Type: application/json
Connection: keep-alive
Accept: application/json
auth0-client: XXXX=
Accept-Language: en-us
Content-Length: 209
Accept-Encoding: gzip, deflate
User-Agent: Test/1 CFNetwork/811.4.18 Darwin/16.6.0

{
	"username": "test98765@example.net",
	"password": "mypassword",
	"realm": "Username-Password-Authentication",
	"client_id": "XXXXXXX",
	"grant_type": "http://auth0.com/oauth/grant-type/password-realm"
}
```

And after looking closely to the above link, I found that the client_secret was missing from the request. So I tried hacking a little bit the current module with this code:

```javascript
function password(parameters = {}) {
    const payload = apply({
        parameters: {
            username: { required: true },
            password: { required: true },
            audience: { required: false },
            scope: { required: false }
        }
    }, parameters);
    return this.client
        .post('/oauth/token', {
            ...payload,
            client_id: this.clientId,
            grant_type: 'http://auth0.com/oauth/grant-type/password-realm',
            realm: 'Username-Password-Authentication',
            client_secret: 'XXXXX'    //<-----  ADD THE CLIENT SECRET HERE !!!
        })
}

const auth0 = new Auth0({
    domain: 'MY_DOMAIN',
    clientId: 'MY_CLIENT_ID',
})

const authWithPassword = password.bind(auth0.auth)

authWithPassword({ username: 'test98765@exemple.net', password: 'XXXX', scope: 'openid' }).then(json => {
    console.log({
        success: true,
        json
    })
}).catch(error => {
    console.log({
        errorMsg: 'error',
        error
    })
})
``` 

And I finally managed to have my token back. 

Unfortunately, it seems that there is no way to setup the client secret in the current API interface. Would it be possible to add it to the Auth0 constructor options ??

Thanks in advance!

**Comment by hzalaz** [comment]
@FredericRuaudel please make sure your client has the type `Native`. You can check this in your Auth0 Dashboard

**Comment by FredericRuaudel** [comment]
Thanks it works!!!

I think you should maybe add a link in this module's readme to the official doc that explain this. 

As I said, I spent two days digging all yours docs, forum posts, github tickets, github code, scanning all options in the dashboard, trying to patch my client with the good grant types. Sniffing connections, trying to figure out what do you mean with all your complex vocabulary: strategies, grant type, realm, connections, domain, tenant, audience, scope, etc, etc. 
The purpose of your product is really great and I know that the underlying subject is even more complex, but it's still quite hard to figure out how all of this works despite all the docs you have. 

Anyway, thanks again and have a nice day!
