### ISSUE TITLE
'expiresIn' in iOS has an incorrect value

### ISSUE THREAD

**Issue by jess-hwang** [auth0/react-native-auth0#685]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

"authorize" returns "expiresIn" in Unix timestamp format, but in iOS, when using "saveCredentials," the value is mistakenly assigned using "timeIntervalSinceNow," leading to incorrect values for "expiresIn."
I think it should be  "timeIntervalSince1970."
"expiresIn" contains strange dates like "2077-03-03 22:24:35 +0000."

### Reproduction

I tested it in version 3.0.0-beta.3.

### react-native-auth0 version

3.0.0-beta.3

### React Native version

0.68.2

### Platform

iOS

### Platform version(s)

16.4

**Comment by brushton-ces** [comment]
I'm seeing something similar.  

After a normal authorise, I was seeing getCredentials return 
"expiresIn": 3381989740,
but the accessToken returned was decoding to "exp": 1691038070,

And then after calling getCredentials with force refresh I got
"expiresIn": 1691195705,
and the accessToken returned was decoding to "exp": 1691195705,
Which seems to properly match.

So it seems the expiresIn value from the initial login was not correct? The authorise method uses the saveCredentials method - https://github.com/auth0/react-native-auth0/blob/71a5e9206b19b824aa4dea28674b05d9cff95827/src/hooks/auth0-provider.js#L83

This error leads to hasValidCredentials returning true when the accessToken returned has expired...

**Comment by poovamraj** [comment]
@Widcket Can you check this one out?

**Comment by Widcket** [comment]
Hi @jess-hwan, thanks for raising this.

I just reproduced this issue. Indeed, the `expiresIn` value returned to the JS layer after login is a Unix timestamp, but it's being added to the current time inside `saveCredentials()`:

<img width="681" alt="Screenshot 2023-08-04 at 9 13 43 PM" src="https://github.com/auth0/react-native-auth0/assets/5055789/aaef3cf6-f5a8-499f-82d3-c4847e7711c9">

<img width="986" alt="Screenshot 2023-08-04 at 9 15 14 PM" src="https://github.com/auth0/react-native-auth0/assets/5055789/fd14c36a-4c39-49b9-975c-6c1dca8322e6">

The solution would be to use the [Date(timeIntervalSince1970:)](https://developer.apple.com/documentation/foundation/nsdate/1416453-init) initializer instead.

**Comment by poovamraj** [comment]
Hi @jess-hwang and @brushton-ces thanks for raising this. We have fixed this in the PR here - https://github.com/auth0/react-native-auth0/pull/686.

Please test it and let us know. We will close this issue and the conversation can be continued there.
