### ISSUE TITLE
Call back to App on Logout URL

### ISSUE THREAD

**Issue by minhchienwikipedia** [auth0/react-native-auth0#69]
How to i can back to app on click logout (URL)

**Comment by cocojoe** [comment]
How exactly are you logging out?

**Comment by minhchienwikipedia** [comment]
I'm logout when i click open my URL 'https://minhchien.au.auth0.com/v2/logout' in browser, so i want auto call back to my app when logout success  ( Web return 'OK'). This look like when i login my facebook or my google, this is auto call back my app when login success.

**Comment by cocojoe** [comment]
There is a PR #65 that gives you a convenient way to clear the session (logout). This will make it much easier for you to achieve. Thx

**Comment by cocojoe** [comment]
Merged
