### ISSUE TITLE
The `prompt: 'login'` parameter to the `authorize` function is not available in v3.0.0

### ISSUE THREAD

**Issue by evrimfeyyaz** [auth0/react-native-auth0#697]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

As the title says, the `prompt: 'login'` parameter to the `authorize` function is not available in v3.0.0. Is this intentional? If so, is there a way to achieve the same effect using another method?

### Reproduction

1. Login using `authorize`.
2. Log out using the `clearCredentials` function, this way the session cookie is not cleared.
3. Try logging in through `authorize` again.
4. Even if we pass the `prompt: 'login'` parameter to `authorize`, it automatically logs the user with the saved session in instead of showing a login prompt.

### Additional context

The documentation still shows it as available (see: https://github.com/auth0/react-native-auth0/blob/master/FAQ.md#3-how-can-i-disable-the-ios-logout-alert-box).

### react-native-auth0 version

3.0.0

### React Native version

0.72.3

### Platform

iOS

### Platform version(s)

16.4

**Comment by poovamraj** [comment]
@evrimfeyyaz this can now be sent under `additionalParameters`. I can see that the documents are not updated for v3. We will do it rightaway

**Comment by poovamraj** [comment]
@evrimfeyyaz thanks again for raising this! we have created a PR to fix this - https://github.com/auth0/react-native-auth0/pull/702

**Comment by evrimfeyyaz** [comment]
You got it! Thanks for the quick response, @poovamraj :)

**Comment by KajalSharma011** [comment]
additionalParameter prompt :'none' navigating to browser . How can i use it in react-native for silent authorization without navigating to browser
