### ISSUE TITLE
the `A0Auth0 (from `../node_modules/react-native-auth0`)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by PhoenixAssutech** [auth0/react-native-auth0#698]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

[!] CocoaPods could not find compatible versions for pod "A0Auth0":
  In Podfile:
    A0Auth0 (from `../node_modules/react-native-auth0`)

Specs satisfying the `A0Auth0 (from `../node_modules/react-native-auth0`)` dependency were found, but they required a higher minimum deployment target.

### Reproduction

run  pod install    
you will get the issue                                                                            

### react-native-auth0 version

3.0.0

### React Native version

71.10

### Platform

iOS

### Platform version(s)

16+

**Comment by daidoo-mtn-gh** [comment]
go into your podfile and update to this
platform :ios, '13'

**Comment by poovamraj** [comment]
@daidoo-mtn-gh is right, our SDK now supports only from min iOS version 13. This has to be updated on the podfile.

**Comment by poovamraj** [comment]
This will mean we have to update the minimum supported React Native version. We will check this before closing this issue.

**Comment by poovamraj** [comment]
We have created a PR for this here - https://github.com/auth0/react-native-auth0/pull/703. Please let us know your feedback
