### ISSUE TITLE
Incorrect parameters to `authorize` in docs

### ISSUE THREAD

**Issue by objectiveSee** [auth0/react-native-auth0#700]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In README, the example you have provided for using `authorize()` is not correct. There are two required parameters which cannot be omited in Typescript.

https://github.com/auth0/react-native-auth0/blob/master/README.md?plain=1#L280

The correct usage would be:
```
authorize({},{})
```

Empty objects must be passed because `parameters` and `options` are not optional. 

Solution: Update docs. Or, update `authorize` to take a single object with optional parameters such as:

Change this:
```
  authorize: (
    parameters: WebAuthorizeParameters,
    options: WebAuthorizeOptions
  ) => Promise<Credentials | undefined>;
```

to this:
```
  authorize: ({
        parameters?: WebAuthorizeParameters,
        options?: WebAuthorizeOptions
    }
  ) => Promise<Credentials | undefined>;
```

### Reproduction

See README

### react-native-auth0 version

3.0.0

### React Native version

72.3

### Expo version

49

### Platform

Android, iOS

### Platform version(s)

any

**Comment by objectiveSee** [comment]
`clearSession` has the same bug in docs: https://github.com/auth0/react-native-auth0#expo

**Comment by poovamraj** [comment]
@objectiveSee thanks a lot for raising this. We will make the API cleaner to use.

**Comment by poovamraj** [comment]
@felipem292 can you create a seperate issue with more details?

**Comment by poovamraj** [comment]
@objectiveSee thanks for reporting this. We have fixed this in this PR - https://github.com/auth0/react-native-auth0/pull/701

Please check it out and let us know your feedback. We will close this issue to continue the conversation in the PR.

**Comment by ysheep-js** [comment]
> 

Same issue here, is there any feedback?

**Comment by poovamraj** [comment]
@ysheep-js we would require more details. Can you create a seperate Github issue with more details asked in the issues template.

**Comment by poovamraj** [comment]
@ysheep-js @felipem292 Did you follow the [migration guide](https://github.com/auth0/react-native-auth0/blob/master/MIGRATION_GUIDE.md) on updating the callback URL?

**Comment by ysheep-js** [comment]
> @ysheep-js @felipem292 Did you follow the [migration guide](https://github.com/auth0/react-native-auth0/blob/master/MIGRATION_GUIDE.md) on updating the callback URL?

Yes, I have added `.auth0` suffix

**Comment by poovamraj** [comment]
@ysheep-js It would be helpful if you can share the code snippet, a screen recording, whether this issue is happening only in version 3.0.0 and more details we would be happy to help. Please create a seperate GH issue to make it easier to track

**Comment by felipem292** [comment]
i'm using  "react-native-auth0": "^2.17.4"
