### ISSUE TITLE
RedirectActivity is removed in v3?

### ISSUE THREAD

**Issue by xanderdeseyn** [auth0/react-native-auth0#707]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

So we used the intent filter to support multiple domains (as stated in the docs).
This seems to be completely broken in v3 and when I look at the AndroidManifest.xml, the activities that were defined there have all been completely removed? **How can we use multiple domains in v3?**

Old AndroidManifest: https://github.com/auth0/react-native-auth0/blob/eb61245abbb491192d10acf1d6ba6999666756f1/android/src/main/AndroidManifest.xml

### Reproduction

N/A

### react-native-auth0 version

3.0.1

### React Native version

0.72.3

### Platform

Android, iOS

### Platform version(s)

All

**Comment by poovamraj** [comment]
@xanderdeseyn can you point us to the documentation so that we can update it? This should not be broken as the RedirectActivity still exists but inside the Auth0.Android library as `com.auth0.android.provider.RedirectActivity`

Can you share the snippet you use to override this? This can be done through your android folder itself.

**Comment by xanderdeseyn** [comment]
Thanks for the quick reply @poovamraj , it worked with the new path. Code snippet:

`<activity android:name="com.auth0.android.provider.RedirectActivity"
          tools:node="replace">
    <intent-filter android:autoVerify="true"
                   tools:targetApi="m">
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data android:host="domain1.auth0.com"
              android:pathPrefix="/android/${applicationId}/callback"
              android:scheme="${auth0Scheme}" />
        <data android:host="domain2.auth0.com"
              android:pathPrefix="/android/${applicationId}/callback"
              android:scheme="${auth0Scheme}" />
    </intent-filter>
</activity>`

I tried to locate the docs about this again, but I can't seem to find them anymore...

**Comment by frederikprijck** [comment]
It was in the FAQ, I opened a PR to fix it.
