### ISSUE TITLE
Android : Build failed in react-native@0.47.1

### ISSUE THREAD

**Issue by tastelessgreentea** [auth0/react-native-auth0#71]
During android build on version 0.47.1 of react native, I'm getting an error on the following line in A0Auth0Package.java: 

```    
@Override
public List<Class<? extends JavaScriptModule>> createJSModules() { 
```

I believe this might be related to a react-native patch: https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8, which removed `createJSModule` from the ReactPackage interface

**Comment by diegobfernandez** [comment]
@tastelessgreentea I'm having the same problem. Can you submit your changes as a PR?
I'll submit my app to stores in 2 weeks and I need to be on 0.47.1 :(
