### ISSUE TITLE
`hasValidCredentials` requires a `minTtl` argument using the hook, but not the class

### ISSUE THREAD

**Issue by JosefBud** [auth0/react-native-auth0#711]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the `useAuth0` hook, the returned function `hasValidCredentials` requires the user to input a `minTtl` argument. If using the method of the same name on the `CredentialsManager` class, the `minTtl` argument is optional with a default value of `0`.

### Reproduction

1. Create a component or hook
2. Add `const { hasValidCredentials } = useAuth0();`
3. Observe that `hasValidCredentials` requires an argument
4. Add `const auth0 = new Auth0({ clientId: '', domain: '' })`
5. Observe that `auth0.credentialsManager.hasValidCredentials()` does not require an argument

### react-native-auth0 version

3.0.1

### React Native version

0.70.12

### Expo version

47.0.14

### Platform

Android, iOS

### Platform version(s)

N/A

**Comment by poovamraj** [comment]
Hi @JosefBud, thanks for raising this. We will fix this one soon and update you.

**Comment by poovamraj** [comment]
Hi @JosefBud we have created a [PR](https://github.com/auth0/react-native-auth0/pull/717) to fix this issue. Feel free to check it out.

We will close this issue and continue any conversation there. Thanks
