### ISSUE TITLE
requireLocalAuthentication causing react-native application to crash when running on a real iOS device

### ISSUE THREAD

**Issue by doyeka** [auth0/react-native-auth0#714]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Whenever I call the import functions from the `useAuth0()` hook, and call `requireLocalAuthentication()`, I expect to be able to access Face ID/Touch ID on iOS whenever I call `authorize()` (also from the `useAuth0()` hook.

However, once I await my call to `requireLocalAuthentication()` the sample app crashes when the Promise resolves.

I have to re-open the app to see that I'm logged in.

I'm testing this on a real device, an iPhone 14 Pro Max running on iOS 16.6.

### Reproduction

1. Replace the code before `onLogin()` in 00-Login-Hooks/App.tsx with the following:
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React, {useEffect} from 'react';
import {Alert, Button, StyleSheet, Text, View} from 'react-native';
import {useAuth0, Auth0Provider} from 'react-native-auth0';
import config from './auth0-configuration';

const Home = () => {
  const {
    authorize,
    clearSession,
    user,
    getCredentials,
    error,
    isLoading,
    requireLocalAuthentication,
  } = useAuth0();

  useEffect(() => {
    const biometricAuth = async () => {
      await requireLocalAuthentication();
      console.log('HERE!');
    };
    biometricAuth();
  });`
  
  2. Login to your tenant with valid credentials.
  3. The app will crash after you successfully login.
  4. After you re-open the app post crash, you will have the post login component displayed, showing that it is the promise resolution post-login that triggers this crash.

### Additional context

Full reproduction of issue here: https://github.com/doyeka/auth0-sample

### react-native-auth0 version

3.0.0

### React Native version

0.72.1

### Platform

iOS

### Platform version(s)

16.6

**Comment by poovamraj** [comment]
@doyeka can you provide the crash report here for us to dig in deeper?

**Comment by poovamraj** [comment]
We will close this issue now. But feel free to comment here with more details and we can reopen this issue.
