### ISSUE TITLE
Refresh token rotation

### ISSUE THREAD

**Issue by mbyio** [auth0/react-native-auth0#715]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Reopening https://github.com/auth0/react-native-auth0/issues/328

### Describe the ideal solution

I would like this library to support refresh token rotation for increased security.

**Comment by poovamraj** [comment]
@mbyio we already support this using our [Credentials Manager](https://github.com/auth0/react-native-auth0#credentials-manager). You can store the credentials here and the rotation logic is handled internally for you. 

Please comment here if you have more doubts and we can reopen this issue if required.

**Comment by mbyio** [comment]
Oh okay, great. Maybe update the docs to clarify it is supported? Eg. https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation#sdk-support or the credentials manager docs.
