### ISSUE TITLE
hasValidCredentials returns true when refreshToken is not valid.

### ISSUE THREAD

**Issue by fragilehm** [auth0/react-native-auth0#716]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

`hasValidCredentials` returns `true` even when the session is not valid (the refresh token is not valid and access token failed to refresh).

### Reproduction

1. After the auth flow store the credentials using `credentialsManager.saveCredentials(credentials)`
2. Revoke the `refreshToken` using auth0 api `{doamin}/oauth/revoke`
3. Use `credentialsManager.hasValidCredentials()` to check for a valid credentials.

### react-native-auth0 version

3.0.1

### React Native version

0.67.4

### Platform

iOS, Android

### Platform version(s)

Any

**Comment by doyeka** [comment]
I also saw this issue when using `hasValidCredentials()` returned from the `useAuth0()` hook last week.

**Comment by poovamraj** [comment]
@fragilehm @doyeka this is the accepted behaviour for `hasValidCredentials`. This method checks for the validity of the access token and not the refresh token. Since the access token is still valid, it will return true.

We can update the docs to make this clear. Hope this helps. I will close this issue now. Feel free to comment here if you have more doubts and I can reopen this thread.

**Comment by hwride** [comment]
As far as I can tell, this also returns true even if the access token is expired, as long as you have a valid refresh token? It seems to say as long as you can refresh, credentials are valid. I tried putting a massive `minTTL` much higher than access token lifetime, and still got true back.
