### ISSUE TITLE
Lock screen customisation

### ISSUE THREAD

**Issue by doodlemoonch** [auth0/react-native-auth0#73]
Is lock screen customisation currently possible?

I followed examples linked to from https://github.com/auth0/react-native-auth0/issues/10 but with no luck, is this library using Lock V2?

**Comment by cocojoe** [comment]
@doodlemoonch this library does not use Lock, the Lock screen as you see it is the [Hosted Login Page](https://auth0.com/docs/hosted-pages/login) which you can customize from the [Auth0 Dashboard](https://manage.auth0.com/#/login_page).
