### ISSUE TITLE
isLoading not working on 3.0

### ISSUE THREAD

**Issue by guhcostan-tw** [auth0/react-native-auth0#735]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I updated the lib in my app and isLoading stopped working. When I call the authorize function, it doesn't set it to true.

### Reproduction

- Add a console.log with isLoading
- Call authorize
- See that isLoading does not change

### react-native-auth0 version

3.0.1

### React Native version

0.71.11

### Platform

Android, iOS

### Platform version(s)

15

**Comment by poovamraj** [comment]
@guhcostan-tw the `isLoading` property is set to true once the authentication state of the user is known to the SDK. This can be the `user` value or `null`. Once this is known, the `isLoading` property will be at false. This is not to notify whether the authentication flow is in progress.

**Comment by guhcostan-tw** [comment]
> @guhcostan-tw the `isLoading` property is set to true once the authentication state of the user is known to the SDK. This can be the `user` value or `null`. Once this is known, the `isLoading` property will be at false. This is not to notify whether the authentication flow is in progress.

Hmmmmm, could you confirm this statement, because for me isLoading is never changing. In the old version it changed at the beginning of the authentication flow, but now it doesn't change anymore.

**Comment by poovamraj** [comment]
@guhcostan-tw Yes it seems to work, If the SDK is initialized (i.e `isLoading` is set to false) and `error` or `user` state is filled then it is working as intended. The time take to load the SDK can be very small and that is why you might feel like this is an issue. You can try to have this state in a `useEffect` to see it change.

**Comment by guhcostan-tw** [comment]
Ahhhh yes, now that I understand. isLoading is about loading the SDK, is there a way to add some loading to load user data in the authentication flow?

I'm just asking this because in the old version this isLoading referred to loading user data after starting the login flow.

**Comment by poovamraj** [comment]
The old version also was used for the same purpose of loading the SDK. What I can suggest is to maintain a state before `authorize` is called that can be cleared after the method is returned. Hope this answers your query.

**Comment by guhcostan-tw** [comment]
Yes yes, I implemented this solution. It worked, but I believe it would be good to have an authLoading to store if it is loading, for applications that use it globally. I'll close it for now, thank you very much.
