### ISSUE TITLE
Auth0-webAuth

### ISSUE THREAD

**Issue by Majky336** [auth0/react-native-auth0#74]
Hello,

just wanted to ask, if the webAuth always needs to open browser? Can't this be done directly in App with some widget? The official Auth0 documentation is a bit confusing on this.

**Comment by hzalaz** [comment]
Using webAuth will always open a browser, for some methods like username/pass can be achieved with custom UI and calling some api endpoints, this page will bring more info comparing browsers vs native forms https://auth0.com/docs/tutorials/browser-based-vs-native-experience-on-mobile. There is no guide for RN though
