### ISSUE TITLE
UnauthorizedError doesn't provide error message for android.

### ISSUE THREAD

**Issue by lazzystep** [auth0/react-native-auth0#749]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm using WebAuth to signup using email and password to get verification link and then be able to access the app. I get different error messages on iOS and Android. 
At web dashboard I see error message: `Please verify your email before trying to log in.` error which is correct, but on android I receive `An error occurred when trying to authenticate with the server` error. On iOS it seems correct `An unexpected error occurred. CAUSE: Please verify your email before trying to log in.`

After a bit of debugging I found that error contains correct `description`, but not correct `detailMessage`. `isVerificationRequired` is also set to false.

So right now error gets to line: `promise.reject("a0.response.invalid", error.getMessage(), error);` and gets reject without necessary details. Can you add extra handler for it or provide some advices how to handle it so I can open a pr for it?

<img width="991" alt="Screenshot 2023-10-03 at 16 43 12" src="https://github.com/auth0/react-native-auth0/assets/25006856/d8515795-897f-47f7-9573-bf59e1eb5b63">

### Reproduction

sign up using email and password

### react-native-auth0 version

3.0.1

### React Native version

0.66.1

### Platform

Android

### Platform version(s)

all

**Comment by poovamraj** [comment]
@lazzystep This PR should address your issue - https://github.com/auth0/react-native-auth0/pull/720

We are planning to release this soon. You can verify it as well and let us know your feedback.

**Comment by lazzystep** [comment]
@poovamraj thank you, I tried it but it didn't help me.
I'll try to test it out again later today and provide feedback.

**Comment by lazzystep** [comment]
@poovamraj I double checked It and it seems that passing error doesn't allow developer to get value from description field which I think is important. 
For example: in your manual testing results iOS contains it (`Transaction failed, integrity_token not provided`), but android is not. How developer can create condition if description field is missing?

<img width="998" alt="Screenshot 2023-10-04 at 17 56 01" src="https://github.com/auth0/react-native-auth0/assets/25006856/3367d849-9088-4c74-bf64-d205101f2133">

**Comment by poovamraj** [comment]
@lazzystep Can you check out this PR - https://github.com/auth0/react-native-auth0/pull/751

This was added now.

**Comment by lazzystep** [comment]
@poovamraj awesome, thank you!

It solves my problem so I will close this issue. Will be waiting for this functionality in the future versions
