### ISSUE TITLE
iOS does not retain login User when ios app gets restarted

### ISSUE THREAD

**Issue by archiegq21** [auth0/react-native-auth0#753]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Why does iOS not retain logged in state when app is closed and re-opened?

Meanwhile for the android app, the app retains the Logged In State

for iOS, `const { user } = useAuth0()`, the `user` will always be `null` on app start. Docs and samples does not mention any additional steps to keep the `user` state. How do we keep the user state even when the app gets restarted?

### Reproduction

1. Setup Auth0
2. Login a User through Universal Login
3. User now in Logged In state
4. Close the App
5. Re-open the App

Expected:
App is in Logged In State

Actual:
App starts at Login Page

### react-native-auth0 version

3.0.1

### React Native version

0.72.4

### Platform

iOS

### Platform version(s)

17

**Comment by poovamraj** [comment]
@archiegq21 are you waiting for the SDK to load

```
  if (isLoading) {
    return (
      <View>
        <Text>SDK is Loading</Text>
      </View>
    );
  }
```

**Comment by archiegq21** [comment]
@poovamraj No. The user object returns null on app startup after loading finish. Do you have any idea what's causing the issue?

**Comment by archiegq21** [comment]
@poovamraj When I call authorize, I am able to get the credentials by call `getCredentials()` on success of `authorize` call. But after that, if I try to retrieve credentials again by again calling `getCredentials()` it just returns undefined. This all happens in iOS. For android it am able to retrieve credentials with not issue.

**Comment by archiegq21** [comment]
I found the cause of the issue. We are using [EncrytedStorage](https://www.npmjs.com/package/react-native-encrypted-storage) on our project and looks like its conflicting with how Auth0's Crendential Manager store its credentials. We simply remove EncrytedStorage for now.

**Comment by AsurNikul** [comment]
I am facing same issue can you please respond i am also using EncrytedStorage.
