### ISSUE TITLE
CreateUserOptions metadata property type mismatch on v3

### ISSUE THREAD

**Issue by andreyleonardo** [auth0/react-native-auth0#758]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,

While upgrading from v2 to v3 I noticed that Typescript started to complain about my `metadata` in a `createUser` call being an object when this is expected [to be a string](https://auth0.github.io/react-native-auth0/interfaces/CreateUserOptions.html#metadata).

When stringifying the object, the calls to Auth0 started to fail because [Auth0 API](https://auth0.com/docs/api/authentication#signup) expects an object.

The following error is returned from the Auth0 call:
```
{
  name:a0.response.invalid,
  message:unknown error,
  error:invalid user_metadata type (expected object),
  status:400
}
```

I think this is just a type mismatch for the `metadata` property in the `CreateUserOptions` because keeping it as an object (and suppressing the TS error) works as expected. 

### Reproduction

1. Use the `createUser` method to call Auth0 signup
2. Pass an object to the `metadata` property in that call
3. TS will complain that the type for `metadata` is expected to be `string | undefined`
4. Try to use `JSON.stringify` in your object to match the type
5. Request to Auth0 will fail because it expects an object and not a string

### react-native-auth0 version

3.0.1

### React Native version

0.68.7

### Platform

Android, iOS

### Platform version(s)

N/A

**Comment by poovamraj** [comment]
Thanks for reporting this @andreyleonardo. We have created a PR to fix this - https://github.com/auth0/react-native-auth0/pull/789.

Please let us know your feedback. We will continue the conversation in the PR and close this issue.
