### ISSUE TITLE
Logout when using passwordRealm?

### ISSUE THREAD

**Issue by sampurcell93** [auth0/react-native-auth0#77]
Hi, my login code looks like this:

```
auth0.auth.passwordRealm({
    username, password,
    realm: AUTH0_REALM,
});
```

I have tried doing this for logout, which returns 200:

```
fetch('https://MYDOMAIN.auth0.com/v2/logout');
```

But a call to `auth0.auth.userInfo` with the same access token still returns my user's data. What would be the best way to log out? I see that I can revoke refreshToken but that would still leave the accessToken vulnerable, no?

Thanks,
Sam

**Comment by hzalaz** [comment]
The logout won't revoke the AT since it only removes the Web Session nothing more. Having token with short expiration might help you reduce the amount of time a token is vulnerable. Please for better support contact us via https://support.auth0.com unless its a library issue
