### ISSUE TITLE
Custom template for Universal Login not showing up for mobile

### ISSUE THREAD

**Issue by cross19xx** [auth0/react-native-auth0#780]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I recently upgraded from the classical login to the new universal login. With two applications (a mobile and a web view), I implemented a custom template using the Auth0 CLI. However, the template doesn't appear on the mobile view, only the web view.

### Reproduction

1. Create a tenant and turn on universal login
2. Create a mobile application

### react-native-auth0 version

3.0.2

### React Native version

0.69.1

### Platform

Android

### Platform version(s)

Android 13

**Comment by poovamraj** [comment]
@cross19xx Not sure if this is an issue in the SDK. We open the authorize URL link that we generate for the domain. 

You mention that it is working in web view. I want to confirm that your app is also using web authentication and it is that particular view that has not been updated?

Any chance you can provide us a screenshot of difference between both?

**Comment by cross19xx** [comment]
Thank you for reaching out @poovamraj. To answer:
- The tenant has two applications, one mobile and one web. The web works fine without any issues. However mobile has been having challenges authenticating. Currently we get an error "Unable to process redirect callback"

Please see the screenshots between mobile and web, and notice the difference between the fonts. For security, I've blurred out the company's logo. Also, please note that the logo was inserted dynamically in the Universal Login template, and not using the dashboard.

![mobile_version](https://github.com/auth0/react-native-auth0/assets/59402430/e8abaf3e-9feb-453b-b2cd-a4de0f3fcd13)
![web_version](https://github.com/auth0/react-native-auth0/assets/59402430/29366a70-3e44-41eb-a30a-631259c3f5c9)

**Comment by cross19xx** [comment]
For anyone interested in this, you need to confirm if the domain matches the one you pass to the `react-native-auth0`. In my case, the domain, even though was listed on the Application's dashboard, it wasn't the same domain the universal login pushed to.
