### ISSUE TITLE
Expose RedirectUri in the authorize hook

### ISSUE THREAD

**Issue by aHochstein** [auth0/react-native-auth0#781]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Given a setup of multiple auth0 tenants and a common custom domain to handle the redirect you can not interact with the redirect uri through the authorize hook.
The redirect uri will be automatically derived from the provider settings.

### Describe the ideal solution

Ability to set the redirect uri explicitly when using the authorize hook.

**Comment by felixcolaci** [comment]
+1

**Comment by poovamraj** [comment]
Hey @aHochstein @felixcolaci, we have added support for this feature here - https://github.com/auth0/react-native-auth0/pull/813/files

Can you check this out and let us know your feedback

**Comment by aHochstein** [comment]
@poovamraj looks like this is just what we were looking for. Thanks!
