### ISSUE TITLE
How to configure the SDK and setup the callback URLs if my applicationId has capital letters - com.example.exampleApp seems to break the redirect back from browser.

### ISSUE THREAD

**Issue by BozhidarKabzamalovMM** [auth0/react-native-auth0#782]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have a React Native Android application with an applicationId of com.example.exampleApp and it seems that the camel case letters are somehow messing up the redirect URL callback invocation, which results in me not being logged in or redirected to the Android application.

I read that applicationId that contains capital letters messes up the redirect, but I can't quite figure out what exactly am I supposed to do in order to solve this issue.

The application was created using the React Native CLI and my namespace and defaultConfig look like this:

    namespace "com.example.exampleApp"
    defaultConfig {
        applicationId "com.example.exampleApp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        multiDexEnabled true
        versionCode buildCode()
        versionName "1.0.0"
        manifestPlaceholders = [auth0Domain: "my-domain", auth0Scheme: "${applicationId}.auth0"]
    }

### Reproduction

1. Create a React Native application with an applicationId that contains camel case, e.g com.example.exampleApp
2. Add the callback and logout URLs - com.example.exampleApp.auth0://your-domain/android/com.example.exampleApp/callback
3. Confirm that you won't be redirected back from login page back into the Android application

### react-native-auth0 version

3.0.1

### React Native version

0.72.3

### Platform

Android

### Platform version(s)

33

**Comment by poovamraj** [comment]
@BozhidarKabzamalovMM You can use Custom Scheme as mentioned here - https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md#using-custom-scheme-for-web-authentication-redirection to overcome this issue.

**Comment by poovamraj** [comment]
Hope the above solution helped. We will close this issue for now. Feel free to reopen this issue if you have more doubts.

**Comment by cx5168** [comment]
@BozhidarKabzamalovMM 
How to solve it？
