### ISSUE TITLE
newArchEnabled: Cannot specify link libraries for target "react_codegen_RNAuth0Spec" which is not built by this project.

### ISSUE THREAD

**Issue by elroyshilling** [auth0/react-native-auth0#804]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have enabled **newArchEnabled** and builds are failing for Android. 

**Debugging**: I can build the app successfully by removing react-native-auth0.
**Version**: 3.0.2
**Issue**: react_codegen_RNAuth0Spec
**Logs**:

CMake Error /node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:124 (target_link_libraries):
    Cannot specify link libraries for target "react_codegen_RNAuth0Spec" which
    is not built by this project.
  Call Stack (most recent call first):

---------------------------

> Task :app:configureCMakeDebug[arm64-v8a] FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

---------------------------

### Reproduction

1.  Enable newArchEnabled

> Build fails

3. Disable newArchEnabled

> Build successfully 

4. Remove react-native-auth0 & Enable  newArchEnabled

> Build successfully 

### react-native-auth0 version

3.0.2

### React Native version

0.72.7

### Platform

Android

### Platform version(s)

0.72.7

**Comment by cj-hnadeem** [comment]
Same issue

**Comment by cj-hnadeem** [comment]
@elroyshilling are you able to find any solution?

**Comment by poovamraj** [comment]
@elroyshilling @cj-hnadeem Is this happening only for the Android platform? I am wondering this because many errors mentioned here seem to be iOS specific.

**Comment by elroyshilling** [comment]
> @elroyshilling @cj-hnadeem Is this happening only for the Android platform? I am wondering this because many errors mentioned here seem to be iOS specific.

@poovamraj Android only, iOS working fine. I have detailed the steps on reproduction.

**Comment by cj-hnadeem** [comment]
@poovamraj any update on this issue?

**Comment by poovamraj** [comment]
@cj-hnadeem We have started looking into this issue. We will provide the update in this thread.

**Comment by poovamraj** [comment]
We will close this issue due to inactivity and the fact that new arch is still in Beta. The SDK has to be prepared for the new architecture in the upcoming versions.

**Comment by TheHighriser** [comment]
Not sure if too late, but I had the same issue when doing the conversion for our library. In the end it turned out that the new architecture is not able to handle space in the path. I removed them => successful build.

**Comment by teberl** [comment]
> Not sure if too late, but I had the same issue when doing the conversion for our library. In the end it turned out that the new architecture is not able to handle space in the path. I removed them => successful build.

Hey @TheHighriser, could you please explain which path you adjusted?
I'm facing the same issue and would be great if i can patch it until it gets resolved from auth0.

@poovamraj, we would be highly appreciating if this bug could take this into consideration for an upcoming release? The newArchitecture is going in big steps and my projects already relays on the new TurboModules feature. Therefore i would be super happy, if auth0 can stay our auth provider of choice.

Thanks in advance for the great work!

**Comment by TheHighriser** [comment]
So I did a lot of things, as I was desperate to resolve this. I had the opinion in the end that removing a space in the path structure resolved my issue. That means I was testing my library in a project which had a space. Like "C:\Workspace\My Test Project\". When I removed the space and completely cleaned the project it was suddenly passing the error ("Cannot specify link libraries for target "react_codegen_XXX"").

**Comment by teberl** [comment]
@TheHighriser thanks for you feedback, sadly i am not able to build the project in the current RNT version (0.73.1). Both builds fail (ios/android) when i enable the newArchitecture flag.

**Comment by elroyshilling** [comment]
> > Not sure if too late, but I had the same issue when doing the conversion for our library. In the end it turned out that the new architecture is not able to handle space in the path. I removed them => successful build.
> 
> Hey @TheHighriser, could you please explain which path you adjusted? I'm facing the same issue and would be great if i can patch it until it gets resolved from auth0.
> 
> @poovamraj, we would highly appreciate if this bug could be taken take into consideration for an upcoming release? The newArchitecture is going forward in big steps and my projects already relies on the new TurboModules available in newArchitecture. For me the build is failing on both environments, iOS and android when i try to integrate `react-native-auth0` into my application. Without both platforms build
> 
> Thanks in advance for the great work!

Seems there is no urgency to resolve the issue. It's better to start a new project with the new arch, so the "new arch is still in beta" argument doesn't make sense.

**Comment by teberl** [comment]
@poovamraj && @elroyshilling i simply think it is a good investment to make the package support the new Architecture earlier then later. I know it is still in beta but i also dont think, that the changes would be very fundamental to make it compatible.

For example expo modules are all supported already with new architecture and it is quite sad, that auth0 is atm the only depdency blocking us from using C++TurboModules from the new Archtitecture.

Sorry @TheHighriser that i need to ask again, but with some configurations you where able to run this package in a RNT project where newArchitecture is enabled. This is correct?
I already spent quite some time but without success to make it work.

**Comment by TheHighriser** [comment]
@teberl No. 

I am developing a React Native library for a company and I had the exact same issue as stated here. That's why I actually ended up here over a Google search. 

I know it is not a lot but I wanted to state that It was resolved for me after removing the space. But not sure if this is the whole thing. I did so many different things because I was desperate to resolve this.

**Comment by elroyshilling** [comment]
> @poovamraj && @elroyshilling i simply think it is a good investment to make the package support the new Architecture earlier then later. I know it is still in beta but i also dont think, that the changes would be very fundamental to make it compatible.
> 
> For example expo modules are all supported (SDK49) in the new architecture and it is quite sad, that auth0 is atm the only depdency blocking us from using C++TurboModules from the new Archtitecture. Also you could find links where they tell you to turn it off for now but i would highly suggest to search why to turn it on and migrate your package. [why-invest-in-migrating-to-the-new-architecture](https://docs.expo.dev/guides/new-architecture/#why-invest-in-migrating-to-the-new-architecture)
> 
> Sorry @TheHighriser that i need to ask again, but with some configurations you where able to run this package in a RNT project where newArchitecture is enabled. This is correct? I already spent quite some time but without success to make it work.

@teberl I agree with you and I have been vocal about it.

**Comment by kibiz0r** [comment]
@TheHighriser My project path does not have any spaces in it. No spaces in any of the paths that the Gradle output complains about, either. It must have been something else that you tried along the way.

@elroyshilling Can you reopen this issue so we can keep an eye on its status? I just went through and fixed a ton of significant issues on our project related to the new architecture, and I think this is the last one, so this issue's status is pretty much the "go" signal for us.

**Comment by teberl** [comment]
Same issue #778 but when uses with expo.

@poovamraj I don't want to bother you with this but what is the correct approach here?
Should we create a new feature request to support the new architecture or can we reopen this issue?

Anyway I'm really hoping to get some feedback from auth0 on this topic.

Don't get me wrong, if you tell me this is not planed for the near future (3-6 month) it is okay for me and I move on or think about different solutions. 
But as for now, our next release should have  the new architecture enabled which will require us to drop this package.

**Comment by kibiz0r** [comment]
@poovamraj Just realized I tagged the wrong person earlier.

I meant to ask you this:

Can you reopen this issue so we can keep an eye on its status? I just went through and fixed a ton of significant issues on our project related to the new architecture, and I think this is the last one, so this issue's status is pretty much the "go" signal for us.

**Comment by Under-Warz** [comment]
Hi, please reopen the issue. The problem is still present and prevent to enable new arch on Android :(

**Comment by SaraChicaD** [comment]
For context, I _just_ created a `react-native` project through the CLI, `0.76.1` and it fails unless I change `newArchEnabled=false` in `gradle.properties`. The only thing this app has in it is `react-navigation` -- and the app worked fine iOS/Android -- but when I added this package, _only_ iOS worked and I get a unbuildable app for Android. 

```
> Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Error at /Users/sinescalderon/Desktop/navtest/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:10 (add_subdirectory undefined):
C/C++:   add_subdirectory given source
C/C++:   "/Users/sinescalderon/Desktop/navtest/node_modules/react-native-auth0/android/build/generated/source/codegen/jni/"
C/C++:   which is not an existing directory.
C/C++: Call Stack (most recent call first):
C/C++:   /Users/sinescalderon/Desktop/navtest/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:86 (include)
C/C++:   CMakeLists.txt:31 (include)
C/C++: CMake Error at /Users/sinescalderon/Desktop/navtest/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:89 (target_link_libraries undefined):
C/C++:   Cannot specify link libraries for target "react_codegen_RNAuth0Spec" which
C/C++:   is not built by this project.
```

**Comment by tontonrally** [comment]
Same here on an existing project that I migrated on `0.76.2`, that uses `react-navigation` as well.

**Comment by luca-tomasetti** [comment]
same here

**Comment by roy-law** [comment]
same here

**Comment by akosiakevych** [comment]
Why the issue just closed? It's blocker for all who using auth with new arch for a more than year, please fix

**Comment by kristian-nst** [comment]
Same here. Android only, iOS working fine.
New Arctitechure is now the DEFAULT in both RN and Expo
Hello? Re-open please.

**Comment by Manikandan-saminathan** [comment]
@poovamraj  Any update on this issue 
<img width="1797" alt="image" src="https://github.com/user-attachments/assets/1527305d-db12-45ba-9823-dce9ecc8bb7e" />

**Comment by Melchy** [comment]
same here

**Comment by MatheusMoura17** [comment]
Same here

```
> Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Error at C:/Users/mathe/Workspace/hgs/zero-box-hub/android/app/build/generated/autolinking/src/main/jni/Android-autolinking.cmake:9 (add_subdirectory):
C/C++:   add_subdirectory given source
C/C++:   "C:/Users/mathe/Workspace/hgs/zero-box-hub/node_modules/react-native-auth0/android/build/generated/source/codegen/jni/"
C/C++:   which is not an existing directory.
C/C++: Call Stack (most recent call first):
C/C++:   C:/Users/mathe/Workspace/hgs/zero-box-hub/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:85 (include)
C/C++:   CMakeLists.txt:31 (include)
C/C++: CMake Error at C:/Users/mathe/Workspace/hgs/zero-box-hub/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:88 (target_link_libraries):
C/C++:   Cannot specify link libraries for target "react_codegen_RNAuth0Spec" which
C/C++:   is not built by this project.
C/C++: Call Stack (most recent call first):
C/C++:   CMakeLists.txt:31 (include)
```

changing `newArchEnabled` to `false` in `android/gradle.properties` works fine.

**Comment by CaptainJeff** [comment]
I think you have to run two extra commands for android now for this to work

`./gradlew generateCodegenArtifactsFromSchema` to generate the codegen properly and when you are building for release pass the `-PnewArchEnabled=true` flag IE `./gradlew assembleRelease -PnewArchEnabled=true`

This seemed to fix the issue for me

**Comment by noumantahir** [comment]
This resolved the issue for me in dev mode, yet to test with a release build

**Comment by kristian-nst** [comment]
Running some extra special command shouldn't be the solutions. Devs are expecting their apps to work with `react-native run ios` / `expo run ios` etc, and their respective build commands, not to mention ci/cd runners that expect the same to work by default.

**Comment by CaptainJeff** [comment]
@kristian-nst look at the RN documentation https://reactnative.dev/docs/the-new-architecture/using-codegen#android

**Comment by kristian-nst** [comment]
So all projects that uses this package and newArch has to configure android codegen in their package json? Where in this repo's docs is this?

**Comment by poovamraj** [comment]
@subhankarmaiti Can we check this one and update the documentation as required?

**Comment by jvegax** [comment]
Same here. Upgraded to expo 52 and new arch, then auth0 fails to compile on android

**Comment by jvegax** [comment]
Why is this closed?

**Comment by subhankarmaiti** [comment]
We are investigating this issue and will share updates in this thread.

**Comment by kristian-nst** [comment]
I ran `./gradlew generateCodegenArtifactsFromSchema`

Can't build now
```
  CMake Error at /Users/frexuz/www/xorro-mobile/node_modules/react-native/ReactAndroid/cmake-utils/ReactNative-application.cmake:88 (target_link_libraries):
    Cannot specify link libraries for target "react_codegen_RNAuth0Spec" which
    is not built by this project.
  Call Stack (most recent call first):
    CMakeLists.txt:31 (include) : com.android.ide.common.process.ProcessException: -- The C compiler identification is Clang 17.0.2
```

**Comment by loijwdev** [comment]
any update?
