### ISSUE TITLE
Pre-populate email id

### ISSUE THREAD

**Issue by andresmithnewyork** [auth0/react-native-auth0#805]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I want to pre-populate the email id on Auth0 Sign-in Page also for social connection. A user will enter the email id on page displayed in react-native application and based on some business logic we want to use the Auth0 authentication some of our users. 

I see some link for similar implementation using API and PHP but not able to impelment this with react-native-auth0.

https://auth0.com/docs/authenticate/identity-providers/pass-parameters-to-idps
https://community.auth0.com/t/php-prefill-an-email-address/41070

### Describe the ideal solution

 When the user will view the Auth0 page, we want the email id to be pre-populated whether user is  using Auth0 DB connection or social connection.

**Comment by poovamraj** [comment]
@andresmithnewyork This is already supported. You can try this

```
await authorize({additionalParameters: {login_hint: 'test@test.com'}});
```
