### ISSUE TITLE
App rejected by Apple due to 'Sign in with Apple' opening in the browser

### ISSUE THREAD

**Issue by baptiste0928** [auth0/react-native-auth0#818]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Our app was just rejected by Apple because the 'Sign in with Apple' button, which we enabled in our Universal Login page, is show in the integrated web browser instead of using [their native APIs](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple) to provide the button.

> Regarding 4.0, we were redirected to safari when we used “Sign in with Apple” as login option.
> 
> To resolve this issue, it would be appropriate to revise your app to enable users to sign in or register for an account in the app.
> 
> We look forward to reviewing your resubmitted app.
> 
> Best regards,
> 
> App Store Review

I searched both the issues on this repository and the Auth0 forum and found nothing about integrating 'Sign in with Apple' and Auth0 on React Native using Apple's APIs. This looks like it might be a new requirement from Apple. 

### Describe the ideal solution

`react-native-auth0` should provide a way to integrate with Apple's native APIs to implement the 'Sign in with Apple' button, or at least some indication on how to do so if a third-party library is required.

### Alternatives and current workarounds

I only found [an example from the `react-native-apple-authentication` library](https://github.com/invertase/react-native-apple-authentication/blob/main/docs/Auth0.md) on how to integrate it with Auth0, but there doesn't seem to be a way to integrate directly it with `react-native-auth0`.

**Comment by poovamraj** [comment]
@baptiste0928 I consulted regarding this with our iOS expert @Widcket 

It looks like they are mentioning 

> we were redirected to safari when we used “Sign in with Apple” as login option.

But our SDK doesn't support SFSafariViewController yet. Are you sure you are using ASWebAuthenticationSession? Can you share the code you use for login (without sensitive information)

ASWebAuthenticationSession should be considered as "In the app" and we are wondering how this was rejected. This is the first time we have had this reported where as SIWA requirement has existed for sometime now.

**Comment by Widcket** [comment]
👋🏼 @baptiste0928,

I've looked at the response from App Review you posted, and they say (1) the app is redirecting to Safari, and (2) they should provide a way to sign up and login inside the app.

Either `ASWebAuthenticationSession` or `SFSafariViewController` are "inside the app". Only the Safari app would not, as it's literally a separate app.

<img width="837" alt="Screenshot 2023-12-05 at 11 21 33" src="https://github.com/auth0/react-native-auth0/assets/5055789/9881696e-3ebe-4deb-bcb5-ce0d9f2b6e55">

This SDK only uses `ASWebAuthenticationSession` to perform web-based authentication (`SFSafariViewController` support is not released yet). Are you using the SDK to open the in-app browser (`ASWebAuthenticationSession`) or are you opening the login URL in the Safari app?

**Comment by baptiste0928** [comment]
Thanks for your answers! After discussing it further with our team and reaching out to Apple for more details, it turns out the issue comes from a page we sometimes show after authentication that had a button opening Safari. It's not an issue with the Auth0 SDK, everything is working fine on this side.

Sorry for wasting your time with this, the explanations Apple initially gave us were really ambiguous :sweat_smile:
