### ISSUE TITLE
Error: the specified item could not be found in the keychain

### ISSUE THREAD

**Issue by PatrickHeneise** [auth0/react-native-auth0#834]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have several auth0 keychain items for different projects. When I start the react-native-app, I get prompted with the login box and if I want to re-use the item from the keychain.

I already tried removing the password from the keychain and entered it manually, resulting in the same error.

```
      const credentials = await auth0.webAuth.authorize({
        scope: 'openid offline_access profile email',
        audience: AUTH0_AUDIENCE,
      });

      await SecureStore.setItemAsync('accessToken', credentials.accessToken);
      await SecureStore.setItemAsync('refreshToken', credentials.refreshToken);
```

This throws and results in the logout. I suppose this is more related to the `SecureStore`?

What am I doing wrong?

### Reproduction

1. Login
2. "App" wants to use "auth0.com" to Sign In
3. Continue
4. Error: the specified item could not be found in the keychain

If I clear the session etc. it's slightly different:

1. Login
2. "App" wants to use "auth0.com" to Sign In
3. Continue
4. Web Auth view: Log in to App, email, password etc.
5. Use password from keychain
6. Log in
7. "App" wants to use "auth0.com" to Sign In
8. Continue
9. Error: the specified item could not be found in the keychain

### Additional context

1. Successful login
2. Authorization Code for Access Token
3. User successfully logged out

Auth0 logs show successful login, but a logout straight after

### react-native-auth0 version

2.17.4

### React Native version

0.71.14

### Expo version

48.0.21

### Platform

iOS

### Platform version(s)

17.2

**Comment by poovamraj** [comment]
@PatrickHeneise this looks more related to `SecureStore` as you mentioned that the auth0 SDK. Have you checked out the `credentialsManager` we provide in our SDK to store and retrieve the credentials? If you use Hooks, we handle the storage automatically.

**Comment by PatrickHeneise** [comment]
I'll try that, thank you!

**Comment by poovamraj** [comment]
We will close this issue now but feel free to comment here and we can reopen it if required.
