### ISSUE TITLE
Logout from multiple Tenants

### ISSUE THREAD

**Issue by consuelo-sanna** [auth0/react-native-auth0#835]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Howdy, I've looked through the issues, examples and documentation but I can't find an answer to this question:
How should I logout the user from multiple Tenants?

Security is the top priority for the application, and we also have a fairly complex system with multiple Tenants on Auth0 managed by us. The mobile application uses the webAuth, and the webAuth.clearSession does NOT logs the user out from the parent Tenant, we can clearly seeing it by looking at the logs in Auth0

The only thing that seem to be working is using an ad-hoc URL that chains the returnTo, and on v2.17.x we could leverage .webAuth.agent.show(), but that has been removed on v3

we would like to upgrade to v3, so I'd like to understand if there's a better way to log the user out in this scenario, or if an option could be add to open a specific URL like with the show method

Every suggestion is welcomed, Cheers

### Reproduction

pre-requisite:
Having Tenant Parent and Tenant Child, those have an OIDC Enterprise connection 

1) login
2) logout using the clearSession

-> by checking the logs, we can see that the logout action is present on the Child Tenant, but not on the Parent Tenant

3). open the following link: https://parent-tenant.com/v2/logout?returnTo=https://child-tenant.com/v2/logout?returnTo=com.my.app://child-tenant.com/ios/com.my.app/callback

-> by checking the logs after point 3, we can see that the logout action is present on BOTH the Child Tenant and the Parent Tenant

### react-native-auth0 version

3.1.0

### React Native version

0.71.11

### Expo version

none, Bare workflow

### Platform

Android, iOS

### Platform version(s)

iOS>13

**Comment by poovamraj** [comment]
@consuelo-sanna `webAuth.agent.show()` was never a public API so we removed it in V3. Since the latest release provides options to construct the return URL, did you try that approach out?

**Comment by consuelo-sanna** [comment]
Hi, yes I tried with the returnUrl but I was not configuring it right on auth0, I was able to fix that and it works now
Thank you, all good now :)
