### ISSUE TITLE
WebAuth never opens safari on iOS

### ISSUE THREAD

**Issue by sebirdman** [auth0/react-native-auth0#84]
During testing I saw this issue on debug builds and thought nothing of it (worked in release, so all seems good right?) However, I now have one of my testers reporting the same issue on a release build:

Here is the warning i see in xcode: 

Warning: Attempt to present <SFSafariViewController: 0x102363bc0>  on <UIViewController: 0x10241ea00> which is already presenting <RCTModalHostViewController: 0x102337990>

Interestingly, if I avoid using SFSafariViewControler and instead do:

https://github.com/sebirdman/react-native-auth0/commit/b439e1f3cb12a35a409453071a3f08da2902d398

then the page opens and login works as expected. 

I'm very new to iOS development, maybe there's an easier fix for the above warning or a particular reason SFSafariViewController was chosen over just openURL?

**Comment by sebirdman** [comment]
Ah, i've found another bit.

During login, we display a Modal that shows "logging in" if i disable that modal (RCTModalHostViewController) then the page opens as expected every time without any code changes.

very strange.

**Comment by cocojoe** [comment]
Sounds like you already have the solution, dismiss your modal before calling WebAuth.

**Comment by stefanedberg** [comment]
I'm having a similar issue. In my use case I have a tabbed application (with react-native-navigation) and when the user isn't authenticated (the first time they launch the app or when the JWT is not valid anymore) I'd like to show the login in a modal. We have a multi-tenant solution that requires them to first enter their account name and then logging in with Auth0. When I try to authenticate with Auth0 the webauth doesn't open and I get this Warning: Attempt to present SFSafariViewController on RCCTabBarController whose view is not in the window hierarchy @cocojoe

**Comment by cocojoe** [comment]
OK have made PR to ensure the SFSafariViewController is presented from the topmost view controller.  @stefanedberg @sebirdman please can you try #89 and report back.  Thanks

**Comment by stefanedberg** [comment]
Solved my use case. Works as expected, thanks @cocojoe.
