### ISSUE TITLE
Method authorize returning undefined

### ISSUE THREAD

**Issue by colaquecez** [auth0/react-native-auth0#857]
### Checklist

- [X] The issue can be reproduced in the [react-native-auth0 sample app](https://github.com/auth0-samples/auth0-react-native-sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I've implemented the react-native-auth0 sample app, however, I'm getting a blank screen only for Android, sometimes I can see the custom login screen but after pressing `continue` nothing happens, so I close the modal, open it again, then the blank screen appears.

### Reproduction

There are all the steps in this video:

### react-native-auth0 version

^3.0.0

### React Native version

0.71.14

### Expo version

~48.0.21

### Platform

Android

### Platform version(s)
Android 13

**Comment by colaquecez** [comment]
![Screenshot 2024-01-29 at 4 19 08 PM](https://github.com/auth0/react-native-auth0/assets/38195454/148c1c1d-f3cb-42c3-b519-52536a23a99f)
![Screenshot 2024-01-29 at 4 19 15 PM](https://github.com/auth0/react-native-auth0/assets/38195454/5d91ee0c-8c34-40d1-95b1-2915d40c322f)
I've made these changes following this PR: https://github.com/auth0/react-native-auth0/pull/610/files

It didn't work, still getting the same error

**Comment by colaquecez** [comment]
I needed to setup the customScheme

**Comment by devDoubleH** [comment]
could share the source the please ?

**Comment by Shivampurbia** [comment]
It open the login page but authrize() returns undefined.

**Comment by KajalSharma011** [comment]
Any update on this . I am also facing same issue. iOS is working fine but it return undefined in authorize callback after successful authorization in Android.
