### ISSUE TITLE
Question: Silent Authentication

### ISSUE THREAD

**Issue by nickcobbett** [auth0/react-native-auth0#86]
I don't want the lock screen to appear every time I open my app, so I'm trying to implement [Silent Authentication](https://auth0.com/docs/api-auth/tutorials/silent-authentication#initiate-a-silent-authentication-request) per the auth0 docs. Using WebAuth, I can't figure out how to add a `prompt=none` parameter to my authorization url. Do I have to use the Auth class instead? If so, does the authorizationUrl method take extra parameters? 

Initially I was trying to implement this using the refreshToken, but I read that storing tokens in AsyncStorage was not advised. If I'm mistaken on this, or if there is a different solution please let me know! Thanks!

**Comment by cocojoe** [comment]
@nickcobbett You are correct that you should be using the `refreshToken` as it stands I don't believe `AsyncStorage` offers any kind of encryption. This post contains more of the internal details and is worth a quick read.
https://stackoverflow.com/questions/39028755/save-sensitive-data-in-react-native

You could take a look at https://github.com/oblador/react-native-keychain
