### ISSUE TITLE
Browser tabs not closed upon webauth success/failure

### ISSUE THREAD

**Issue by mleduque** [auth0/react-native-auth0#87]
Each time I login, the WebAuth opens in a new browser tab.
After some roundtrip, I end up with a dozen login tabs in the browser.
How do I close the login tab in the browser ?

**Comment by mleduque** [comment]
I this project dead ?

**Comment by cocojoe** [comment]
If you need help then please provide sufficient information, what steps are required to recreate this issue starting with 
https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login

What platform/device are you testing with, what browser (presume this is Android) etc Let's see some screenshots or ideally a video.  

Thanks

**Comment by cocojoe** [comment]
I've been testing and have noticed that browser tabs are not closed.  Thanks

**Comment by lbalmaceda** [comment]
Adding the `Intent.FLAG_ACTIVITY_NO_HISTORY` to the intent might help, although it doesn't guarantee that the tab is going to be closed later.

**Comment by mleduque** [comment]
@cocojoe I'll add more information soon, thanks.
@lbalmaceda I will try, thanks.

**Comment by cocojoe** [comment]
@mleduque You can try PR #90 and feedback.

**Comment by mleduque** [comment]
After Updating the dependency to 1.2.0, I can confirm it doesn't happen anymore.
