### ISSUE TITLE
Add Apple Privacy file

### ISSUE THREAD

**Issue by eppisapiafsl** [auth0/react-native-auth0#870]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/react-native-auth0#readme), [Examples](https://github.com/auth0/react-native-auth0/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/react-native-auth0/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/react-native-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/react-native-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Starting in April 2024, Apple will request a privacy file. [Apple - Privacy manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) to be able to deploy to the stores, and this file must contain the code not just from the App but any third-party library we install in our app. 

Any app that installs the Auth0 SDK (Switft), needs to declare which data the SDK is collecting (if any).

It will be beneficial if the teams add the Privacy Manifest file in the repo or documentation 🙏 

### Describe the ideal solution

If the App Privacy File is declared and maintained in the repo, it will automatically added to the final Privacy file that Apple reviews.

With Xcode 15+, create the new App Privacy File. -> [Create your app privacy report](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4239187)

### Alternatives and current workarounds

Documentation around what data is collected/store from the user

**Comment by SasClaudiuCristian** [comment]
any updates on this?

**Comment by brth31** [comment]
@eppisapiafsl @SasClaudiuCristian Privacy manifest has been added to Auth0.Swift as a part of [this PR](https://github.com/auth0/Auth0.swift/pull/841). I believe that it should be available on our latest version of React Native SDK- `v3.2.1`. Could you confirm if this issue is resolved?

**Comment by eppisapiafsl** [comment]
@brth31 Yes, I see the Pods have the permission added 👍
