### ISSUE TITLE
What is needed for `resetPassword()` to fail?

### ISSUE THREAD

**Issue by sampurcell93** [auth0/react-native-auth0#88]
Hi, my testing of the `resetPassword` function shows that it never seems to fail. I'm looking for a way to know when a user inputs an email that doesn't exist in our user db. Is there a way to find this out so we can display errors (I'm not sold that we should even be displaying errors for this, but anyway...)

Thanks for all the hard work!
Sam

**Comment by lbalmaceda** [comment]
The server will never give you an error response. Every request, even for non registered emails will succeed. This is to prevent email enumeration, a.k.a. guessing if an email is a registered user.

**Comment by sampurcell93** [comment]
Thanks, I'll pass that back to my team - my thoughts on the matter exactly :)

Sam
