### ISSUE TITLE
Unhandled JS Exception: Missing required parameters: [  "token" ]

### ISSUE THREAD

**Issue by kevinlu1211** [auth0/react-native-auth0#94]
When I use the code snippet for getting user data I'm getting this error:
Unhandled JS Exception: Missing required parameters: [  "token" ]

```
auth0.auth
      .userInfo({ token: this.state.accessToken })
      .then((token) => {
        console.log(token);
      })
      .catch(console.error);
```

What am I doing wrong?

**Comment by cocojoe** [comment]
Have you checked that `this.state.accessToken` has  a value?

**Comment by kevinlu1211** [comment]
You're right silly mistake on my part!
