### ISSUE TITLE
Popover on iPad instead of push

### ISSUE THREAD

**Issue by Swatto** [auth0/react-native-auth0#97]
Instead of presenting the `SFSafariViewController` by using push, it could be great as user experience point of view, to present it in a popover window.

**Comment by cocojoe** [comment]
Thanks @Swatto for the suggestion. You have any screenshots ? 😄 
Also please feel free to create a PR.

**Comment by Swatto** [comment]
TBH, I don't the knowledge and the time at work to do it.
